webstudio-is/webstudio

app/shared/tree-utils/create-instance.test.ts

Just added few tests for create instance to be consistent with other tests . 
@kof  Let me know if there are any issues with pr

add create instance tests

---

.eslintrc.json
.github/workflows/main.yml
app/shared/design-system/components/verified-badge.tsx

Add GH aactions for:
- test
- lint
- typecsheck
We just need to not allow merges from non passing pipelines on the settings now cc @kof 
closes https://github.com/webstudio-is/webstudio-designer/pull/48

Add Github actions

---

app/designer/features/sidebar-left/index.tsx
app/designer/features/sidebar-left/panels/components/component-thumb.tsx
app/designer/features/sidebar-left/panels/components/components.tsx
app/designer/features/sidebar-left/panels/components/custom-drag-layer.tsx
app/designer/features/sidebar-left/panels/components/index.ts
app/shared/icons/index.ts
app/shared/icons/types.ts

This is fixed by not showing the native thumbnail, but instead showing one rendered manually
Fixes https://github.com/webstudio-is/webstudio-designer/issues/30

Fixes bouncing back animation from native thumbnail on drop

---

app/env.server.ts
app/routes/dashboard.tsx
app/shared/documents/canvas.tsx
app/shared/documents/designer.tsx
app/shared/env/env-getter.ts
app/shared/env/env.tsx
app/shared/env/index.ts
app/shared/env/namespace.ts
app/shared/sentry.ts
package.json
prisma/schema.prisma
yarn.lock

This is needed for sentry.
Essentially Remix should have its native way of doing it, so this is a temp solution for us
https://github.com/remix-run/remix/discussions/2769

Env config inlined for the UI before any other script runs

---

apps/designer/app/designer/features/props-panel/props-panel.tsx

Closes #151
Closes #152
Closes #153

Fix follow up issues from CSF branch

---

apps/designer/env-check.js

fix env check

---

apps/designer/app/designer/features/style-panel/lib/use-style-data.ts

Hey, I just wrote this function, I didn't test it and it needs to be passed down to the components like setProperty, the idea is this:
```ts
const batch = createBatchUpdate()
const setDisplayValue = batch.setProperty('display')
setDisplayValue('block')
const setSomeOtherValue = batch.setProperty('something')
setSomeOtherValue('somevalue')
batch.publish()
```

Added createBatchUpdate to apply multiple properties updates at once

---

packages/design-system/.storybook/main.js
packages/design-system/.storybook/preview.js
packages/design-system/package.json

Add storybook support to design-system

---

apps/designer/app/dashboard/components/card.tsx
apps/designer/app/dashboard/dashboard.tsx
apps/designer/app/routes/dashboard/index.tsx

refactor: update type for designer path config option

---

apps/designer/app/shared/documents/designer.tsx
packages/design-system/src/components/toast.tsx

related: https://github.com/webstudio-is/webstudio-designer/issues/210

Toast redesign

---

apps/designer/app/designer/designer.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/thumbnail.tsx
apps/designer/app/designer/features/sidebar-left/sidebar-left.tsx
apps/designer/app/routes/designer/$id.tsx
apps/designer/app/shared/db/project.server.ts
packages/prisma-client/prisma/schema.prisma
packages/prisma-client/src/types.ts

fix project connectiuon

---

packages/prisma-client/package.json

fix: prisma client command

---

apps/designer/docs/test-cases.md
packages/design-system/src/components/primitives/dnd/README.md
packages/design-system/src/components/primitives/dnd/__snapshots__/geometry-utils.test.ts.snap
packages/design-system/src/components/primitives/dnd/geometry-utils.test.ts
packages/design-system/src/components/primitives/dnd/geometry-utils.ts
packages/design-system/src/components/primitives/dnd/index.ts
packages/design-system/src/components/primitives/dnd/use-auto-scroll.test.ts
packages/design-system/src/components/primitives/dnd/use-auto-scroll.ts
packages/design-system/src/components/primitives/dnd/use-drag.ts
packages/design-system/src/components/primitives/dnd/use-drop.ts
packages/design-system/src/components/primitives/dnd/use-hold.ts
packages/design-system/src/components/text.tsx
packages/design-system/src/components/tree/tree.tsx

Drag&drop improvements & some minor fixes

---

.github/actions/publish/action.yaml
.github/workflows/asset-uploader.yml
.github/workflows/design-system.yml
.github/workflows/eslint-config-custom.yml
.github/workflows/http-client.yml
.github/workflows/icons.yml
.github/workflows/jest-config.yml
.github/workflows/react-sdk.yml
packages/asset-uploader/package.json
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/icons/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/react-sdk/package.json
packages/tsconfig/package.json

GitHub Actions had a problem, in that not all files were presented in the published package. That was because of our monorepo setup.
Now it is fixed.
If this PR is approved, I will bump all package versions, so the latest will be updated.

fix: GitHub actions

---

.github/workflows/asset-uploader.yml
.github/workflows/design-system.yml
.github/workflows/eslint-config-custom.yml
.github/workflows/http-client.yml
.github/workflows/icons.yml
.github/workflows/jest-config.yml
.github/workflows/react-sdk.yml
.github/workflows/tsconfig.yml

Made small typos. Just the trigger of GH packages changed.

fix: typos

---

apps/designer/app/designer/designer.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/add-an-asset-form.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-info.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-manager.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-thumbnail.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-tooltip.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/types.ts
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/utils.ts
packages/asset-uploader/src/delete.ts
packages/asset-uploader/src/schema.ts
packages/asset-uploader/src/targets/s3/client.ts
packages/asset-uploader/src/targets/s3/handler.ts
packages/asset-uploader/src/types.ts
packages/asset-uploader/src/upload.ts
packages/asset-uploader/src/utils/format-asset.ts
packages/asset-uploader/src/utils/get-asset-path.ts
packages/asset-uploader/src/utils/image-fs-path.ts
packages/prisma-client/prisma/schema.prisma
packages/prisma-client/src/types.ts

These were drive-by changes  I made in https://github.com/webstudio-is/webstudio-designer/pull/255 and extracted to this separate PR to be merged faster, because the rest will be a WIP for a bit longer, because it is waiting for data migration thing we build

Asset manager types improvements

---

apps/designer/app/designer/designer.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/add-an-asset-form.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-info.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-manager.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-thumbnail.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/asset-tooltip.tsx
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/types.ts
apps/designer/app/designer/features/sidebar-left/panels/asset-manager/utils.ts
packages/asset-uploader/src/delete.ts
packages/asset-uploader/src/schema.ts
packages/asset-uploader/src/targets/s3/client.ts
packages/asset-uploader/src/targets/s3/handler.ts
packages/asset-uploader/src/types.ts
packages/asset-uploader/src/upload.ts
packages/asset-uploader/src/utils/format-asset.ts
packages/asset-uploader/src/utils/get-asset-path.ts
packages/asset-uploader/src/utils/image-fs-path.ts
packages/prisma-client/prisma/schema.prisma
packages/prisma-client/src/types.ts

Migrate Asset to meta, clean up types in asset manager

---

apps/designer/package.json
packages/asset-uploader/package.json
packages/css-vars/package.json
packages/css-vars/src/index.ts
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/icons/package.json
packages/jest-config/package.json
packages/react-sdk/package.json
yarn.lock

Upgrade to TS 4.8 is currently blocked by https://github.com/stitchesjs/stitches/issues/1078

Upgrade to TS 4.7

---

packages/http-client/package.json

Make http-client public and publish to npm

---

apps/designer/app/routes/canvas/$projectId.tsx
apps/designer/app/routes/index.tsx
apps/designer/app/routes/preview/$projectId.tsx
packages/react-sdk/package.json
packages/react-sdk/src/canvas/canvas.tsx
packages/react-sdk/src/canvas/index.ts
packages/react-sdk/src/index.ts
packages/react-sdk/src/tree/root.ts

Move canvasDocument to react-sdk

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/canvas/shared/instance.ts
apps/designer/app/canvas/shared/nano-states.ts
apps/designer/app/canvas/shared/use-track-hovered-element.ts
apps/designer/app/designer/features/sidebar-left/lib/navigator/navigator.tsx
packages/design-system/src/components/tree/tree-node.tsx
packages/design-system/src/components/tree/tree.tsx

Outline on canvas item that's hovered in navigator

---

packages/design-system/src/components/text-field.tsx

Omit conflicting props

---

packages/http-client/package.json
packages/http-client/src/fetch-polyfill.ts
packages/http-client/src/index.ts
yarn.lock

fix: use isomorphic fetch for worker, node & browser

---

apps/designer/app/services/auth.server.ts
apps/designer/app/shared/db/user.server.ts

Auth logic was using _json which looks like an unofficial part of the data
https://github.com/webstudio-is/webstudio-designer/issues/307

Fix github login

---

apps/designer/app/canvas/features/wrapper-component/text-editor/plugins/plugin-on-change.tsx

When we quit text editing mode, we need to safe again otherwise it can happen before debounce calls.
https://github.com/webstudio-is/webstudio-designer/issues/288

Fix saving text change when quickly pressing esc after editing

---

packages/react-sdk/src/components/image.props.json
packages/react-sdk/src/components/image.stories.tsx
packages/react-sdk/src/components/image.tsx
packages/react-sdk/src/components/image.ws.tsx
packages/react-sdk/src/components/index.ts
packages/react-sdk/src/components/meta.ts

This PR renders an Image component on the canvas. Selecting src visually is not yet possible, but I want to merge it as-is.
https://github.com/webstudio-is/webstudio-designer/issues/196

Image component

---

.github/workflows/main.yml
package.json

Remove node 14 support

---

apps/designer/app/routes/rest/publish.ts

Related PR for [SaaS](https://github.com/webstudio-is/webstudio-saas/pull/3).

fix: send origin url to publisher

---

packages/prisma-client/prisma/migrations/20220915144008_breakpoints-build_data/migration.ts

Fix migration

---

packages/asset-uploader/package.json
packages/css-vars/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/prisma-client/package.json
packages/project/package.json
packages/react-sdk/package.json

Fixed the `build` script

---

packages/react-sdk/package.json

Increment react-sdk version

---

.github/workflows/fonts.yml
.github/workflows/package-tests.yml
.github/workflows/prisma-client.yml

New packages: prisma-client & fonts

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/canvas/shared/sync/use-sync.ts
apps/designer/app/entry.client.tsx
packages/react-sdk/src/tree/create-elements-tree.tsx
packages/react-sdk/src/tree/session-storage-polyfill.tsx

Fix a crash in canvas when "Block third-party cookies" is enabled in Chrome

---

packages/react-sdk/src/stitches/stitches.ts

Just some minor changes to the structure of this module. No functional changes or anything but this way it will stay a little bit closer to the intention.

Tweak the Stitches module

---

apps/designer/docker-compose.yaml

[admin] Add docker-compose with postgres

---

apps/designer/app/designer/features/props-panel/use-props-logic.ts
packages/react-sdk/src/arg-types/utils.ts
packages/react-sdk/src/components/body.props.json
packages/react-sdk/src/components/bold.props.json
packages/react-sdk/src/components/box.props.json
packages/react-sdk/src/components/button.props.json
packages/react-sdk/src/components/form.props.json
packages/react-sdk/src/components/heading.props.json
packages/react-sdk/src/components/image.props.json
packages/react-sdk/src/components/input.props.json
packages/react-sdk/src/components/italic.props.json
packages/react-sdk/src/components/link.props.json
packages/react-sdk/src/components/paragraph.props.json
packages/react-sdk/src/components/text-block.props.json

Cherry-picked from #378
fixes broken attributes in storybook for default values

Fix defaultValue to work with storybook

---

apps/designer/app/canvas/features/wrapper-component/text-editor/editor.tsx
apps/designer/app/canvas/features/wrapper-component/text-editor/lexical.ts
apps/designer/app/canvas/features/wrapper-component/text-editor/plugins/plugin-instance.tsx
apps/designer/package.json
yarn.lock

See https://github.com/facebook/lexical/releases/tag/v0.4.0 https://github.com/facebook/lexical/releases/tag/v0.5.0 https://github.com/facebook/lexical/releases/tag/v0.6.0
Added ErrorBoundary and fixed types.

Upgrade to lexical v0.6

---

apps/designer/app/designer/features/sidebar-left/panels/pages/settings.tsx
apps/designer/app/designer/features/style-panel/shared/property-name.tsx
packages/design-system/src/components/label.tsx

Don't use __DEPRECATED__Text in Label

---

apps/designer/app/designer/features/style-panel/style-settings.tsx

fix style panel search error

---

packages/http-client/package.json
packages/http-client/src/index.d.ts
packages/http-client/src/index.test.ts
packages/http-client/src/index.ts

Able to query pages in loadProject

---

.github/workflows/package-tests.yml
.github/workflows/project.yml

Publish project package

---

apps/designer/app/designer/features/sidebar-left/panels/pages/pages.tsx
apps/designer/app/designer/features/sidebar-left/panels/pages/settings-panel.tsx
packages/design-system/src/stitches.config.ts

Page settings animation

---

apps/designer/app/designer/designer.tsx
apps/designer/app/designer/features/sidebar-left/sidebar-left.tsx
apps/designer/app/designer/features/style-panel/shared/value-picker-popover.tsx
apps/designer/app/designer/shared/constants/index.ts

Remove PANEL_WIDTH constant, use token

---

apps/designer/.gitignore
apps/designer/app/routes/rest/pages.$projectId.ts
packages/asset-uploader/src/constants.ts
packages/asset-uploader/src/utils/get-asset-path.test.ts
packages/project/src/db/types.ts

Restrict some prefixes for page paths

---

apps/designer/app/designer/features/style-panel/shared/css-value-input/unit-select.tsx
packages/design-system/src/components/text-field.tsx
packages/design-system/src/components/text.tsx

After I removed all: initial it broke unit in other ways

Fix unit font

---

apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx

Flex Section - the left icon isn't supposed to have greyish background

[release-fix] Flex gap icon is not button

---

.github/workflows/css-data.yml
.github/workflows/css-engine.yml
.github/workflows/package-tests.yml

Straightforward. Publish new packages to NPM.

Publish `css-data` & `css-engine` to NPM

---

apps/designer/app/canvas/shared/use-track-hovered-element.ts
apps/designer/app/designer/features/breakpoints/breakpoints-editor.tsx

https://user-images.githubusercontent.com/52824/202865326-2d8f1c4c-8843-40c9-837d-fd678dbacdaa.mp4
https://user-images.githubusercontent.com/52824/202865322-3ff488c8-eb36-4d4a-9c6f-591a84332ebc.mp4

Stop flicker when hovering instances

---

packages/prisma-client/package.json
yarn.lock

Had to add concurrently to run two watch commands in parallel

Fix dev in prisma-client

---

.github/workflows/vis-reg-tests.yml
packages/design-system/package.json
yarn.lock

Bump lost-pixel

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/routes/$.tsx
apps/designer/app/routes/rest/project.$projectId.tsx
apps/designer/app/shared/db/canvas.server.ts
packages/http-client/package.json
packages/http-client/src/index.test.ts
packages/http-client/src/index.ts
packages/http-client/tsconfig.json
packages/project/package.json
packages/project/src/db/types.ts

fix: type CanvasData

---

packages/asset-uploader/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/fonts/package.json
packages/icons/package.json
packages/prisma-client/package.json
packages/project/package.json
packages/react-sdk/package.json

We need to bump all saas deps to get esm support
and treeshake bundled code.

Bump saas deps

---

.github/workflows/publish.yml
bin/publish-to-npm.sh

Let's see if it will fix the issue

Fix npm publish token

---

apps/designer/app/designer/features/props-panel/control.tsx
apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
apps/designer/app/designer/features/props-panel/props-panel.tsx
apps/designer/app/designer/features/props-panel/use-props-logic.ts
packages/react-sdk/src/components/meta.ts

[release-fix] Fix adding new prop

---

packages/asset-uploader/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/design-system/package.json
packages/design-tokens/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project/package.json
packages/react-sdk/package.json

Bump packages versions

---

apps/designer/app/shared/router-utils/build-params.ts

I'm using a remote development server and accessing it with an IP address. This minor fix allows me to use it.

Able to use remote dev environments with IP address

---

apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx

Fix menu not closed on blur

---

packages/asset-uploader/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/design-system/package.json
packages/design-tokens/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project/package.json
packages/react-sdk/package.json

For easier version change next time, now all has same version.

Bump versions

---

apps/designer/app/designer/shared/assets/use-assets.ts

Fixes https://github.com/webstudio-is/webstudio-designer/issues/593
1. upload a custom font
2. use the font on any text element
3. see font apply immediately without reload
4. see that switching fonts between custom and defaults works

Asset status can be undefined if image was not just recently uploaded

---

packages/design-system/src/components/text-field.tsx

Closes https://github.com/webstudio-is/webstudio-designer/issues/592
Before

Don't let an input/button grow beyond the layout constraint

---

apps/designer/app/designer/features/style-panel/shared/color-picker.tsx

Absence of exact types, stupid bugs.

Fix alpha didn't changed

---

apps/designer/app/designer/features/props-panel/props-panel.tsx
apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
apps/designer/app/designer/features/props-panel/use-props-logic.ts
packages/design-system/src/components/switch.tsx
packages/react-sdk/src/components/component-type.ts
packages/react-sdk/src/components/image.ws.tsx

Add initial props

---

apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx

Ref https://github.com/webstudio-is/webstudio-designer/issues/261 https://github.com/webstudio-is/webstudio-designer/issues/603
- filtered to show only important values
- always show display as select instead of combobox for non-flex values

Show only important values in "display" select

---

apps/designer/app/designer/shared/assets/use-assets.ts

Refresh assets after deletion

---

apps/designer/app/canvas/features/text-editor/interop.ts
apps/designer/app/canvas/features/text-editor/text-editor.stories.tsx
apps/designer/app/canvas/features/text-editor/text-editor.tsx
apps/designer/app/canvas/features/text-editor/toolbar-connector.tsx
apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx

Ref https://github.com/webstudio-is/webstudio-designer/issues/588

Auto select span after toggling

---

packages/project/src/shared/tree-utils/populate.ts
packages/react-sdk/src/components/body.ws.tsx
packages/react-sdk/src/components/box.ws.ts
packages/react-sdk/src/components/component-type.ts
packages/react-sdk/src/components/form.ws.tsx
packages/react-sdk/src/components/image.ws.tsx
packages/react-sdk/src/components/italic.ws.tsx
packages/react-sdk/src/components/link.ws.tsx
packages/react-sdk/src/components/text-block.ws.tsx

Rename defaultStyle  to presetStyle

---

apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
apps/designer/app/canvas/shared/nano-states.ts
apps/designer/app/canvas/shared/use-track-selected-element.ts

Looks like no longer used. All related logic movied to selected instance connector.

Drop selected element container

---

apps/designer/app/designer/features/props-panel/props-panel.tsx
apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
packages/design-system/src/components/combobox.stories.tsx
packages/design-system/src/components/combobox.tsx

Check mark in Combo Boxes can be lost or be incorrect in case of input changes

---

.github/pull_request_template.md

The changes to PR template are made to make the process of reviewing more intentional.

Better pull request template

---

apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx

Extracted this from #550 as @istarkov needs this too: https://github.com/webstudio-is/webstudio-designer/pull/550#discussion_r1053432597

Add `reason` argument to onChangeComplete

---

apps/designer/.gitignore
apps/designer/app/routes/$.tsx
apps/designer/app/routes/auth/dev.tsx
apps/designer/app/routes/auth/github.tsx
apps/designer/app/routes/auth/github/callback.tsx
apps/designer/app/routes/auth/google.tsx
apps/designer/app/routes/auth/google/callback.tsx
apps/designer/app/routes/dashboard.tsx
apps/designer/app/routes/dashboard/index.tsx
apps/designer/app/routes/designer.tsx
apps/designer/app/routes/designer/$projectId.tsx
apps/designer/app/routes/index.tsx
apps/designer/app/routes/login.tsx
apps/designer/app/routes/login/index.tsx
apps/designer/app/routes/logout.tsx
apps/designer/app/routes/rest/assets.$projectId.tsx
apps/designer/app/routes/rest/breakpoints.$projectId.ts
apps/designer/app/routes/rest/pages.$projectId.ts
apps/designer/app/routes/rest/patch.ts
apps/designer/app/routes/rest/project.$projectId.tsx
apps/designer/app/routes/rest/project/clone.$domain.ts
apps/designer/app/routes/rest/props.$projectId.ts
apps/designer/app/routes/rest/publish.ts
apps/designer/app/routes/rest/theme.$setting.ts
apps/designer/app/routes/rest/tree.$projectId.ts
apps/designer/app/routes/s/css.ts

Ref https://github.com/remix-run/remix/releases/tag/remix%401.6.5
Now loader and action data can be inferred

Switch from LoaderFunction to LoaderArgs

---

apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
apps/designer/app/designer/features/style-panel/controls/select/select-control.tsx
apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
apps/designer/app/designer/features/style-panel/sections/flex-child/flex-child.tsx
apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
apps/designer/app/designer/features/style-panel/sections/typography/typography.tsx
apps/designer/app/designer/features/style-panel/style-panel.tsx
apps/designer/app/designer/features/style-panel/style-sections.tsx
apps/designer/app/designer/features/style-panel/style-settings.tsx

It's just an additional and confusing "style" term. Also spread is often not safe to use so better explicitly pass all needed props.

Drop section style

---

packages/react-sdk/src/css/categories.ts

Somehow we forgot to add object-position
2. go to sizes section in style panel

Add object position property

---

package.json
packages/asset-uploader/src/utils/get-asset-path.test.ts
packages/prisma-client/migrations-cli/README.md
packages/prisma-client/package.json
packages/prisma-client/prisma/migrations/20221227220622_assets-status/migration.sql
packages/prisma-client/prisma/schema.prisma

I need this filed in the following PR, to count assets before upload. And restrict the total number of assets per project.

Add status field to assets table

---

packages/asset-uploader/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/design-system/package.json
packages/design-tokens/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project/package.json
packages/react-sdk/package.json

Bump packages

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
apps/designer/app/canvas/shared/breakpoints.ts
apps/designer/app/canvas/shared/immerhin.ts
apps/designer/app/canvas/shared/styles.ts
apps/designer/app/routes/rest/patch.ts
apps/designer/app/shared/array-utils.test.ts
apps/designer/app/shared/array-utils.ts
apps/designer/app/shared/nano-states/nano-states.ts
packages/project/src/db/index.ts
packages/project/src/db/styles.ts
packages/project/src/db/tree.ts
packages/react-sdk/src/db/style.ts

Migrated updating and rendering to normalized styles. There are still a few cases to migrate so left legacy root instance updates.
Styles are updated with immerhin consistently with whole project.
Can be tested changing styles and deleting breakpoints.

Update normalized styles directly

---

apps/designer/app/designer/features/style-panel/style-source-input/style-source-input.stories.tsx
apps/designer/app/designer/features/style-panel/style-source-input/style-source-input.tsx
apps/designer/app/designer/features/style-panel/style-source-input/style-source.tsx

1. Now we can pass currentIndex and user can click on an item to make it current.
1. open style source UI in stories
2. click item to make it current

Current item in style source UI

---

.github/workflows/re-create-figma-tokens-branch.yml

See https://discord.com/channels/955905230107738152/1063389035705401386
I've tested it in a tmp repo. Here is an example of it running: https://github.com/rpominov/test/actions/runs/3911119209/jobs/6684132390

Add action that re-creates `figma-tokens` branch when it gets deleted

---

packages/project/src/db/styles.ts
packages/project/src/db/tree.ts

Forgot to move uploads logic to normalized styles

Fix styles uploads

---

apps/designer/app/auth/login-button.tsx
apps/designer/app/auth/login.tsx

Login looks terrible, we need a proper design, so I just removed unnecessary elements and made the buttons neutral
1.  open login

Login visual fixes

---

apps/designer/app/designer/features/props-panel/control.tsx
apps/designer/app/designer/features/sidebar-left/panels/pages/settings.tsx
apps/designer/app/designer/features/style-panel/shared/property-name.tsx
apps/designer/app/designer/features/topbar/publish.tsx
apps/designer/app/designer/shared/design-tokens-manager/token-editor.tsx
packages/design-system/src/components/__DEPRECATED__/label.tsx
packages/design-system/src/index.ts

Gonna start over to align with design system.

Deprecate label component

---

packages/design-system/bin/transform-figma-tokens.ts

Closes https://github.com/webstudio-is/webstudio-designer/issues/838
Just need an approval to merge

fix fontWeight parsing in transform-figma-tokens

---

apps/designer/app/dashboard/header.tsx
apps/designer/app/dashboard/panel.tsx
apps/designer/app/dashboard/projects.tsx
packages/design-system/src/components/avatar.tsx

Styling tweaks
1. open /dashboard

Dashboard styling

---

apps/designer/app/dashboard/header.tsx
apps/designer/app/dashboard/project-card.tsx
apps/designer/app/designer/features/breakpoints/breakpoints.tsx
apps/designer/app/designer/features/breakpoints/preview.tsx
apps/designer/app/designer/features/topbar/menu/menu.tsx
packages/design-system/src/components/dropdown-menu.tsx
packages/design-system/src/components/menu.stories.tsx

1. Fixed #851 
2. Cleaned up Menu usage in some other places
Need a review to merge

Minor menu fixes

---

apps/designer/app/shared/share-project/share-project.tsx
apps/designer/package.json
pnpm-lock.yaml

Share list uses Collapsible instead of Framer motion
Click Share button, see expand of list items

Remove framer-motion for a link list add collapsible

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/canvas/shared/use-shortcuts.ts
apps/designer/app/designer/features/topbar/menu/menu.tsx
apps/designer/app/designer/features/topbar/preview.tsx
apps/designer/app/designer/features/topbar/topbar.tsx
apps/designer/app/shared/nano-states/nano-states.ts
apps/designer/app/shared/sync/sync-stores.ts

Sync preview mode through sync-stores

---

apps/designer/app/dashboard/projects/thumbnail-link.tsx

Fix font in project card

---

apps/designer/app/routes/rest/project.$projectId.tsx

Fix production publish

---

packages/project/src/db/build.ts

Fix build create

---

apps/designer/app/routes/rest/project.$projectId.tsx
apps/designer/app/shared/db/canvas.server.ts
packages/http-client/src/index.ts

Unify and simplify fetch and errors for endpoints and packages used in SaaS
ref #928
2. expect xyz

Unify and simplify fetch and errors for endpoints and packages used in SaaS

---

apps/designer/app/canvas/canvas.tsx
apps/designer/app/canvas/shared/styles.ts
apps/designer/app/designer/designer.tsx
apps/designer/app/designer/shared/assets/use-assets.tsx
apps/designer/app/shared/nano-states/nano-states.ts
apps/designer/app/shared/sync/sync-stores.ts
packages/project/src/db/styles.ts

Before assets were synchronized with pubsub between canvas and designer. Here I switched to synchronized store.

Use synchronized store for assets

---

apps/designer/app/dashboard/projects/project-card.tsx
apps/designer/app/dashboard/projects/project-dialogs.tsx

1. optimistic delete
https://user-images.githubusercontent.com/52824/216601949-743ee55b-2f4b-42bd-9c4f-b94f4b76bce8.mp4
1. delete project without waiting for response

Optimistic project deletetion

---

.gitignore
apps/designer/app/designer/designer.tsx
apps/designer/app/routes/designer/$projectId.tsx
apps/designer/app/shared/nano-states/nano-states.ts
packages/trpc-interface/src/authorize/project.server.ts
packages/trpc-interface/src/shared/authorization-router.ts

Show preview initially for view only users
ref #548
2. expect xyz

Show preview initially for view only users

---

apps/designer/app/designer/designer.tsx
apps/designer/app/designer/shared/assets/use-assets.tsx
apps/designer/app/routes/$.tsx
apps/designer/app/routes/rest/assets.$projectId.tsx
apps/designer/app/routes/rest/project.$projectId.tsx
apps/designer/app/shared/css-utils/generate-css-text.ts
apps/designer/app/shared/db/canvas.server.ts
apps/designer/app/shared/db/misc.server.ts
apps/designer/app/shared/router-utils/path-utils.ts
packages/asset-uploader/package.json
packages/asset-uploader/src/db/create.ts
packages/asset-uploader/src/db/delete.ts
packages/asset-uploader/src/db/load.ts
packages/asset-uploader/src/delete.ts
packages/asset-uploader/src/targets/fs/upload.ts
packages/asset-uploader/src/targets/s3/upload.ts
packages/asset-uploader/src/upload.ts
packages/project/src/db/build.ts
packages/project/src/db/project.ts
packages/project/src/db/props.ts
packages/project/src/db/tree.ts
pnpm-lock.yaml

Add assets permissions checks serverside.
Mostly adding context 
2. expect xyz

Add assets permissions checks

---

apps/designer/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Update npm packages
2. expect xyz

Update npm packages

---

apps/designer/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json
pnpm-lock.yaml

Update ver 0.26.0

---

apps/designer/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Update ussets and project

---

packages/design-system/src/components/tree/tree.tsx

Fix drag & drop

---

apps/designer/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Update npm versions

---

packages/react-sdk/src/app/custom-components/shared/remix-link.tsx

https://github.com/webstudio-is/webstudio-designer/issues/997
2. expect xyz

Don't crash on href=//

---

apps/builder/app/routes/rest/project/clone.$domain.ts
packages/prisma-client/prisma/migrations/20230213220858_is-deleted-uniq/migration.sql
packages/prisma-client/prisma/schema.prisma
packages/project/src/db/project.ts

closes  #989
closes #988
Initially I wanted to make this with permission system, but as of now we don't support deleting all permissions from the project, and that probably can break some future undo operation
2. expect xyz

Do not select deleted projects, make clone predictable

---

apps/builder/app/shared/share-project/share-project-container.tsx
apps/builder/app/shared/share-project/share-project.tsx
packages/design-system/src/index.ts

1. Close second popover after editing link label on enter
2. migrate deprecated popover

Share UI improvements

---

apps/builder/package.json
package.json
packages/design-system/src/__generated__/figma-design-tokens.json

More renames

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Make @webstudio-is/generate-arg-types public, update versions

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Add lib to files section of package.json of generate-arg-types

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.ts
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/router-utils/path-utils.ts

Fix build permission not work on page change inside builder

---

apps/builder/app/canvas/features/wrapper-component/wrapper-component.tsx
apps/builder/app/shared/db/canvas.server.ts

ref #1065
`+` fixed useLayoutEffect server warning

Filter font assets for published apps

---

apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
apps/builder/app/routes/rest/pages.$projectId.ts
apps/builder/app/shared/pages/types.ts

Fixes #1061 .
- Try to rename page title or page name
- It should not revert back in few seconds

Fix page settings

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.ts
apps/builder/app/builder/shared/nano-states/index.ts
apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/collapsed.ts
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/canvas/shared/styles.ts
apps/builder/app/routes/s/css.ts

Fix collapse

---

apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Update npm packages to version 0.36

---

.github/workflows/vis-reg-tests.yml
packages/design-system/lostpixel.config.ts

Migrating lost-pixel to their new method

---

apps/builder/app/root.tsx

Fix sentry error

---

apps/builder/app/routes/$.tsx
apps/builder/app/routes/rest/project.$projectId.tsx
apps/builder/app/routes/s/css.ts
apps/builder/app/shared/db/canvas.server.ts
packages/project/src/shared/schema.ts

Fix publish

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Release new versions

---

packages/design-system/src/components/tree/tree-node.tsx

Don't react to isDragging/isDropTarget

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json
pnpm-lock.yaml
scripts/release.sh

Release 0.42.0

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Release 0.43.0

---

packages/design-system/src/components/position-grid.stories.tsx
packages/design-system/src/components/position-grid.tsx
packages/design-system/src/index.ts

First part of https://github.com/webstudio-is/webstudio-builder/issues/1138
Implements position grid ui with keyboard accessibility.
https://user-images.githubusercontent.com/52824/222828649-2caa8140-3723-447e-9db1-c02f6e1add71.mp4
1. https://638245578b47d4399fba191a-qpucehpzyq.chromatic.com/?path=/story/library-position-grid--position-grid
2. click or hit enter on a focused/hovered item
3. use arrow keys to focus items with keyboard

Position grid component

---

apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
apps/builder/app/builder/features/topbar/menu/menu.tsx
apps/builder/app/shared/copy-paste/plugin-instance.ts
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/shortcuts/shortcuts.ts
packages/project-build/src/db/build.ts

Need to cleanup all page related data to prevent bloating project with garbage data. Delete already prevent reloading so its safe to clear data on client.

Delete page data on client

---

packages/react-sdk/src/tree/root.ts

RootInstance dont need all the data we pass
2. expect xyz

Right types for the RootInstance

---

apps/builder/app/shared/router-utils/path-utils.ts

closes #1159
with hight probablity closes #1183
2. expect xyz

Fix wrong or absense of canvas css on production, probably fix collapse

---

apps/builder/app/canvas/canvas.tsx
apps/builder/app/shared/dom-hooks/use-window-resize.ts

Fix collapse on size change

---

apps/builder/package.json
package.json
packages/react-sdk/package.json
pnpm-lock.yaml

Storybook don't understand ts satisfies. Until we move onto new storybook this adds that support
2. expect xyz

ts satisfies keyword support for storybook

---

.github/workflows/chromatic.yml
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
package.json
packages/design-system/src/components/list.tsx
pnpm-lock.yaml

I don't know why it started to detect this error. But here we are.
2. expect xyz

Fix ts error

---

.storybook/main.js

I tested locally that it fixes the problem, let's see what CI has to say about that

Use webpack5 builder in the root Storybook

---

apps/builder/app/canvas/custom-components/index.ts
packages/react-sdk/src/app/custom-components/index.ts
packages/react-sdk/src/app/custom-components/link-block.tsx

Link block wasn't using remix link

Use remix link for link block

---

apps/builder/app/builder/features/style-panel/shared/color-picker.tsx

Select non transparent color if default color was transparent
2. expect xyz

Fix color picker

---

apps/builder/app/builder/features/footer/breadcrumbs.tsx
apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.ts
apps/builder/app/builder/features/style-panel/style-settings.tsx
apps/builder/app/builder/features/style-panel/style-source-section.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
apps/builder/app/builder/features/workspace/workspace.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/canvas/instance-selection.ts
apps/builder/app/canvas/shared/styles.ts
apps/builder/app/canvas/shared/use-shortcuts.ts
apps/builder/app/canvas/shared/use-track-selected-element.ts
apps/builder/app/shared/copy-paste/plugin-instance.ts
apps/builder/app/shared/copy-paste/plugin-markdown.ts
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/sync/sync-stores.ts
apps/builder/app/shared/tree-utils.test.ts
apps/builder/app/shared/tree-utils.ts

Selector makes more sense and allows to not introduce "instance element" term.

Rename instance address to instance selector

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.test.ts
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/use-sortable.tsx
packages/design-system/src/components/css-value-list-item.stories.tsx
packages/design-system/src/components/css-value-list-item.tsx

ref #877
Add few background layers, drag'n'drop them

Drag drop background layers

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Update version 0.49.0 to publish npm
2. expect xyz

Update version 0.49.0

---

packages/design-system/src/components/icon-button.tsx

Fix toggle button styles

---

apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
apps/builder/app/routes/rest/pages.$projectId.ts
apps/builder/app/shared/pages/types.ts
packages/project-build/src/db/build.ts

Ref https://github.com/webstudio-is/webstudio-builder/issues/1084 https://github.com/webstudio-is/webstudio-builder/issues/1286
Currently only create page patches propagate to canvas. Here migrated update to immerhin too.

Update pages with store

---

apps/builder/app/builder/shared/navigator-tree.tsx
packages/design-system/src/components/tree/tree.stories.tsx
packages/design-system/src/components/tree/tree.tsx

Drag end is called conditionally and I forgot to handle cancel event.

Cancel tree drag

---

apps/builder/app/builder/features/style-panel/sections/size/size.tsx

Object position doesn't fit the grid layout like other elements have in size section

Fix object position layout

---

apps/builder/app/builder/builder.tsx
apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/shared/styles.ts
apps/builder/app/routes/$.tsx
apps/builder/app/routes/builder/$projectId.tsx
apps/builder/app/routes/index.tsx
apps/builder/app/shared/context.server.ts
apps/builder/app/shared/router-utils/path-utils.ts
packages/trpc-interface/src/authorize/project.server.ts
packages/trpc-interface/src/context/context.server.ts

Ref https://github.com/webstudio-is/webstudio-builder/issues/1044 https://github.com/webstudio-is/webstudio-builder/issues/360
Canvas no longer need to load any data. No longer need pages. No longer need auth token. No longer need static css.
Here I cleaned all unnecessary logic to load canvas. It may load much faster now.

Optimize canvas loading

---

apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
apps/builder/app/builder/shared/nano-states/index.ts
apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
apps/builder/app/canvas/features/text-editor/toolbar-connector.tsx
apps/builder/app/shared/nano-states/canvas.ts
apps/builder/app/shared/sync/sync-stores.ts

- refactored with synchronized client store
- recompute toolbar position on scroll end

Refactor text toolbar state

---

.github/workflows/chromatic.yml
.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/vis-reg-tests.yml
package.json
packages/sdk-size-test/package.json
pnpm-lock.yaml
turbo.json

Rebased https://github.com/webstudio-is/webstudio-builder/pull/1111. Took all changes which  already work. Will try to enable caching in separate PR.

Upgrade turbo

---

.npmrc
package.json

Ref https://github.com/pnpm/pnpm/releases/tag/v8.0.0
The new version got a lot of stuff enabled by default including the one I didn't enabled before "dedupe-peer-dependents" which will make packages upgrade so much easier.

Upgrade to pnpm 8

---

apps/builder/app/shared/copy-paste/plugin-instance.ts
apps/builder/app/shared/tree-utils.test.ts
apps/builder/app/shared/tree-utils.ts
packages/css-engine/src/core/equal-media.test.ts
packages/css-engine/src/core/equal-media.ts
packages/css-engine/src/core/index.ts

Here added utility to merge pasted breakpoints into existing ones or add new one if breakpoint does not match any.

Support cross-project breakpoints copy paste

---

apps/builder/app/builder/features/style-panel/style-source-section.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
apps/builder/app/shared/nano-states/nano-states.ts

Added "delete" item to style source menu and select last style source by default in input.

Support style source deletion

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
packages/design-system/src/components/css-value-list-item.stories.tsx
packages/design-system/src/components/css-value-list-item.tsx
packages/design-system/src/components/primitives/arrow-focus.tsx
packages/design-system/src/components/primitives/dnd/use-drop.ts

closes #877
added `focusManagerOptions` to ArrowFocus handleKeyDown
what allows us to create nested focus navigation.
Create a few background layers and use arrows to navigate.

Background list focus management

---

apps/builder/app/builder/features/style-panel/style-panel.tsx
apps/builder/app/canvas/canvas.tsx
packages/react-sdk/src/pubsub/create.ts
packages/react-sdk/src/pubsub/raf-queue.ts

Reduce renders from 5 to 1

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

packages update 0.52.0

---

packages/eslint-config-custom/package.json
packages/tsconfig/package.json

Update ts and eslint configs

---

packages/project-build/src/schema/styles.ts

2. expect xyz
not "what")
5de6)
cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md)
document
and the `builder/env-check.js` if mandatory
2. expect xyz

Fix Expression produces a union type that is too complex to represent.

---

apps/builder/app/builder/features/style-panel/style-panel.tsx

fixes perf on breakpoint scrub change
Still some issues on breakpoint change, but we know why this happens. Would be fixed in next iterations.
2. expect xyz

Fix perf on scrub

---

packages/design-system/src/components/scroll-area.tsx

This aligns scrollbars with new design
1. scroll add components panel
2. window needs to be small

Align scrollbars with new design

---

apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts

This is the fast-fix.
Better to rewrite as here https://github.com/webstudio-is/webstudio-builder/issues/1431
2. expect xyz

Fix inital canvas size and breakpoints

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/props-panel/props-panel.tsx
apps/builder/app/builder/features/settings-panel/settings-panel.tsx
apps/builder/app/builder/features/style-panel/style-panel.tsx
apps/builder/app/builder/shared/assets/assets-shell.tsx
packages/design-system/src/components/list.tsx
packages/design-system/src/components/panel-title.tsx
packages/design-system/src/components/scroll-area.tsx
packages/design-system/src/components/tree/tree.tsx

Replacing scrollbar in all panels on the right
Closes https://github.com/webstudio-is/webstudio-builder/issues/1417
2. expect xyz

Use scroll area in style right panels

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Npm packages release 0.55.0
2. expect xyz

Npm packages release 0.55.0

---

apps/builder/app/builder/features/style-panel/style-panel.tsx

No longer needed, as impossible to set width less than allowed
2. expect xyz

Remove useless warning

---

apps/builder/app/builder/features/topbar/topbar.tsx

Prevent topbar from jumping when loading

---

apps/builder/app/builder/shared/collapsible-section.tsx

Fix display-table

---

apps/builder/app/builder/features/breakpoints/breakpoints-selector-container.tsx
apps/builder/app/builder/features/breakpoints/breakpoints-selector.stories.tsx
apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
apps/builder/app/builder/features/breakpoints/cascade-indicator.tsx
apps/builder/app/builder/features/breakpoints/index.ts
apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
apps/builder/app/builder/features/topbar/topbar.tsx

Closes https://github.com/webstudio-is/webstudio-builder/issues/1460
2. expect xyz

Add border radius and other fixes to cascade indicator

---

apps/builder/app/shared/remix/root.tsx

This fixed crossdomain development mode used in SaaS 
2. expect xyz

Fix cross domain livereload in dev mode

---

packages/prisma-client/src/prisma.ts
packages/project-build/src/db/breakpoints.ts
packages/project-build/src/db/build.ts
packages/project-build/src/db/instances.ts
packages/project-build/src/db/props.ts
packages/project-build/src/db/style-source-selections.ts
packages/project-build/src/db/style-sources.ts
packages/project-build/src/db/styles.ts
packages/trpc-interface/src/authorize/project.server.ts
turbo.json

On the server for web-studio landing it shows from 230 to 600ms for loading now.
parseBuild time on the server varies from 18ms to 100+ms 
locally sometimes I see

Skip validation

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json
packages/tsconfig/package.json

Release 0.57.0

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/prisma-client/src/prisma.ts
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json
packages/tsconfig/package.json

Merge after #1487 
2. expect xyz

Release 0.58

---

packages/design-system/src/components/primitives/dnd/use-drag.ts
packages/design-system/src/components/primitives/dnd/use-drop.ts
packages/design-system/src/components/tree/tree.tsx

Fix navigator drag flickering

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Npm Release 0.59.0
2. expect xyz

Release 0.59.0

---

apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
apps/builder/app/builder/shared/assets/assets-shell.tsx
apps/builder/app/builder/shared/fonts-manager/fonts-manager.tsx
apps/builder/app/builder/shared/image-manager/image-manager.tsx
packages/design-system/src/components/list.tsx
packages/design-system/src/components/scroll-area.tsx
packages/design-system/src/components/tree/tree-node.tsx

Closes #1458
1. Fixed paddings
2. Fixed color of scrollbar
3. Fixed color of the options button of the selected page item

Paddings to make space for scroll bar

---

apps/builder/app/shared/sync/sync-stores.ts

Fix data not synchronized if you reopen the projects from the dashboard
2. expect xyz

Fix data not synchronized if you reopen the projects from the dashboard

---

apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
packages/feature-flags/src/flags.ts

remove white spaces to check diff
Select link component, add style source, select current page. 
Should be Current Page and not the "Aria Current Page"

Fix style source input

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Npm update 0.60.0
2. expect xyz

npm release 0.60.0

---

apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/tree-utils.ts
packages/react-sdk/src/embed-template.test.ts
packages/react-sdk/src/embed-template.ts

Ref https://github.com/webstudio-is/webstudio-builder/pull/1516
This will allow further customization of react components through meta

Add props support in embed template instances

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-size-test/tsconfig.json
packages/trpc-interface/package.json
packages/tsconfig/package.json

Release 0.61.0
Npm packages update
2. expect xyz

Release 0.61.0

---

apps/builder/app/builder/features/breakpoints/breakpoints-editor.tsx
apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
apps/builder/app/builder/features/breakpoints/confirmation-dialog.tsx
apps/builder/app/canvas/shared/styles.ts
apps/builder/app/shared/breakpoints/group-breakpoints.ts
packages/css-engine/src/core/compare-media.test.ts
packages/css-engine/src/core/compare-media.ts
packages/css-engine/src/core/css-engine.test.ts
packages/css-engine/src/core/css-engine.ts
packages/css-engine/src/core/find-applicable-media.ts
packages/design-system/src/components/select.tsx
packages/feature-flags/src/flags.ts
packages/icons/icons/minus.svg
packages/icons/src/__generated__/index.ts
packages/icons/src/__generated__/minus.tsx
packages/project-build/src/schema/breakpoints.ts

https://user-images.githubusercontent.com/52824/235469260-2a212e73-0815-4a4b-a02d-d98cf56c7a88.mp4
Closes https://github.com/webstudio-is/webstudio-builder/issues/1407
1. click edit breakpoints
2. test all possible inputs

Breakpoints editor

---

apps/builder/app/builder/features/props-panel/props-panel.stories.tsx

https://discord.com/channels/955905230107738152/1102879882960175164
2. expect xyz

Fix lostpixel

---

apps/builder/app/builder/features/style-panel/shared/style-info.ts

Fix preset styles

---

apps/builder/app/builder/shared/assets/use-assets.tsx
packages/asset-uploader/src/clients/fs/upload.ts
packages/asset-uploader/src/clients/s3/upload.ts
packages/asset-uploader/src/schema.ts
packages/asset-uploader/src/utils/get-asset-data.ts

Removed all no longer used fields. Stopped passing id with form data.

Simplify asset data

---

packages/asset-uploader/src/clients/s3/upload.ts

Ref https://github.com/webstudio-is/webstudio-builder/issues/1572

Add cache control

---

apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/807 https://github.com/webstudio-is/webstudio-builder/issues/1108
- more consistent input spacing
- more visible text editing
- consistent border around input instead of shadow
- toggle selected state

Align style source along with design

---

apps/builder/app/builder/features/inspector/inspector.tsx

Fixed conditional rendering of tree preview.

Fix dragging when navigator is docked

---

apps/builder/app/builder/features/style-panel/shared/property-name.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.ts
packages/css-data/src/html.ts
packages/react-sdk/src/components/link.ws.tsx
packages/react-sdk/src/css/normalize.ts
packages/react-sdk/src/css/presets.ts

Here made added browser defaults for link and set color as preset.

Fix link default and preset styles

---

apps/builder/app/routes/rest.patch.ts
packages/prisma-client/src/prisma.ts

170ms -> 5ms reduction on validation 
2. expect xyz

Path performance, validate only changed styles

---

apps/builder/env-check.js
apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Release-0.63.0

---

apps/builder/app/builder/features/inspector/inspector.tsx
apps/builder/app/shared/nano-states/nano-states.ts

Do not rerender Instance on drag
2. expect xyz

Improve drag performance if style panel is open

---

packages/react-sdk/src/app/custom-components/form.ws.tsx
packages/react-sdk/src/components/button.ws.tsx
packages/react-sdk/src/components/checkbox-field.ws.tsx
packages/react-sdk/src/components/checkbox.ws.tsx
packages/react-sdk/src/components/form.ws.tsx
packages/react-sdk/src/components/input.ws.tsx
packages/react-sdk/src/components/radio-button-field.ws.tsx
packages/react-sdk/src/components/radio-button.ws.tsx
packages/react-sdk/src/embed-template.ts

Closes #84 
1. Fixed a bug in form template (`email=email` instead of `name=email`)
2. Changed labels of components
3. Moved Button back to Forms category

Forms fixes

---

apps/builder/app/auth/login.tsx
apps/builder/app/builder/builder.css
apps/builder/app/builder/builder.tsx
apps/builder/app/dashboard/dashboard.tsx
apps/builder/app/entry.client.tsx
apps/builder/app/entry.server.tsx
apps/builder/app/routes/dashboard._index.tsx
apps/builder/app/routes/login._index.tsx
apps/builder/app/shared/app.css
apps/builder/app/shared/remix/handle-request.server.tsx
apps/builder/app/shared/remix/root.tsx
apps/builder/package.json
pnpm-lock.yaml

closes #1557
Install https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj plugin
See our website doesn't work but current PR is

Fix hydration

---

apps/builder/app/routes/$.tsx
apps/builder/app/routes/login.tsx
apps/builder/app/routes/vercel-deploy-workaround.tsx
apps/builder/app/shared/remix/handle-request.server.tsx

1. Add 404 instead of redirect
2. Fix vercel/remix upload
2. expect xyz

Fix assets vercel uploading 

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/shared/assets/use-assets.tsx
apps/builder/app/builder/shared/nano-states/index.ts
apps/builder/app/shared/array-utils.ts
apps/builder/app/shared/copy-paste/plugin-instance.ts
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/pages/use-switch-page.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/asset-uploader/src/patch.ts

1. Closes #1325
2. Assets used in styles are copied
3. Assets used in props are copied

Assets copy-paste

---

apps/builder/app/builder/features/style-panel/style-panel.tsx
apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/sync/sync-stores.ts

Fixes review comment: https://github.com/webstudio-is/webstudio-builder/pull/1632#discussion_r1196082482

selectedInstanceIsRendered -> selectedInstanceRenderState

---

packages/design-system/src/components/button.stories.tsx
packages/design-system/src/components/button.tsx

Add neutral-destructive button

---

packages/design-system/src/components/section-title.tsx

Change section title color

---

packages/prisma-client/prisma/migrations/20230520112258_drop_breakpoints/migration.sql
packages/prisma-client/prisma/schema.prisma
packages/prisma-client/src/types.ts

Breakpoints are moved into Build.breakpoints column. Separate table is no longer necessary.

Drop breakpoints table

---

apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.tsx
apps/builder/app/builder/features/style-panel/sections/space/space.tsx
apps/builder/app/builder/features/style-panel/sections/space/value-text.stories.tsx
apps/builder/app/builder/features/style-panel/sections/space/value-text.tsx
apps/builder/app/builder/features/style-panel/shared/collapsible-section.tsx
apps/builder/app/builder/features/style-panel/shared/property-name.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.ts
packages/design-system/src/components/css-value-list-item.stories.tsx
packages/design-system/src/components/icon-button-with-menu.tsx
packages/design-system/src/components/icon-button.stories.tsx
packages/design-system/src/components/icon-button.tsx
packages/design-system/src/components/label.stories.tsx
packages/design-system/src/components/label.tsx
packages/design-system/src/components/nested-icon-label.tsx
packages/design-system/src/components/section-title.tsx
packages/design-system/src/components/toggle-button.stories.tsx
packages/design-system/src/components/toggle-button.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/1658
Updated following components in design system
- css value list item
- icon button
- label
- nested icon label
- section title
- toggle button
Updated following UI in builder
- toggle control
- flex grid
- space UI
- collapsible section
- property name

Add overwritten values support

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Release 0.66.0

---

apps/builder/app/routes/asset.image.$name.ts

We need to forward existing request with headers.
Secure by restricting origin.

Forward request in image proxy

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/trpc-interface/package.json

Release 0.67.0

---

apps/builder/app/builder/features/inspector/inspector.tsx
apps/builder/app/builder/features/props-panel/props-panel.stories.tsx
apps/builder/app/builder/features/props-panel/props-panel.tsx
apps/builder/app/builder/features/settings-panel/settings-panel.tsx
apps/builder/app/builder/features/style-panel/style-panel.tsx
apps/builder/app/builder/features/style-panel/style-source-section.tsx
packages/design-system/src/components/combobox.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/1644
- added instance info to all panels
- fixed style sources design

Update inspector panels design

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/trpc-interface/package.json

Npm:
"version": "0.69.0"
2. expect xyz

Release 0.69.0

---

apps/builder/app/builder/shared/sync/sync-server.ts

Ref https://github.com/webstudio-is/webstudio-builder/issues/1704
Module scope is preserved across projects and does not invalidate last version. Moved to ref to fix.

Store last version in ref

---

packages/project/src/db/project-domain.ts

Reserve static-assets name

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.71.0

---

apps/builder/app/builder/builder.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/1704
Here select body when switch or create pages or create projects.

Select body when switch pages

---

apps/builder/app/builder/features/style-panel/style-source-section.tsx

Remaining code review change requests from https://github.com/webstudio-is/webstudio-builder/pull/1695

Token Deletion Code Review 

---

packages/project/src/db/project.ts

forgotten `await` caused race condition issues
2. expect xyz

Fix you don't have access on project create

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.72.0

---

apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx

Added tooltips to breakpoints similar to webflow.

Add breakpoints descriptions

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.73.0

---

apps/builder/app/builder/features/sidebar-left/navigator/css-preview.tsx

Fix css preview

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.74.0

---

packages/design-system/src/components/search-field.tsx

- center search icon vertically
- get rid of native search button
- fix width jumping when type into search field

Fix font search field

---

apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
packages/react-sdk/src/components/component-meta.ts
packages/sdk-components-react/src/slot.ws.ts

Components like Slot need explanation, so I added a new field - description.
1. hover Slot component in add componens tab

Add first component description for slot

---

packages/react-sdk/src/css/global-rules.ts
packages/sdk-components-react/src/body.ws.tsx

closes #1781
Also makes body/html layout more modern fixing additional bugs
More details https://twitter.com/ChallengesCss/status/1471128244720181258
2. expect xyz

Fix body layout

---

apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx

1. Prevents the breakpoint to be deselected #1764
1. Go to the builder screen
2. Change the breakpoint
3. Click on the changed breakpoint again

Clicking the current breakpoint should not deselect the breakpoint.

---

apps/builder/app/builder/features/style-panel/style-source/style-source.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/1790

Show style source menu button when menu is open

---

apps/builder/app/canvas/features/text-editor/text-editor.tsx

Fix height jumping when editing text

---

packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/feature-flags/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json

Ref https://github.com/webstudio-is/webstudio-builder/pull/1708#discussion_r1229878400

Move types above import/require conditions

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.75.0

---

packages/css-data/bin/prompts/declarations.prompt.md
packages/css-data/bin/prompts/properties.prompt.md
packages/css-data/bin/property-value-descriptions.ts
packages/css-data/src/__generated__/property-value-descriptions.ts

Fixes #1793
I tweaked the prompt and generated new descriptions. 
@kof @taylornowotny The results are still not ideal but please take a look and decide whether we should merge these changes or not (probably still better than the previous generation).
PS: I tweaked the script a bit so now it creates: `propertiesOverrides` and `propertiesGenerated` (same for property:value descriptions). This way we can add overrides to `propertiesOverrides`

Tweak prompt and regenerate properties descriptions

---

apps/builder/app/routes/rest.build.$buildId.tsx

Just typo in the error description, no functional change

Error description typo

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/props-panel/props-panel.tsx
apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/react-sdk/src/context.tsx
packages/react-sdk/src/index.ts
packages/react-sdk/src/props.ts
packages/react-sdk/src/tree/create-elements-tree.tsx
packages/react-sdk/src/tree/root.ts
packages/sdk-size-test/package.json

Added data source values store which can be updated from both components and props panel.
```js
const { setState } = useContext(ReactSdkContext)
const instanceId = getInstanceIdFromComponentProps(props)
setState(instanceId, propName, value)
```
- test nothing is broken in props panel on preview

Support updating data source values

---

apps/builder/app/builder/features/props-panel/props-panel.tsx

Fix props not saved

---

apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
apps/builder/app/builder/features/style-panel/sections/size/size.tsx
apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
apps/builder/app/builder/features/style-panel/shared/property-name.tsx

Closes  https://github.com/webstudio-is/webstudio-builder/issues/1844
1. see issue
- QC

Reset properties with option-click

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/topbar/preview.tsx
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/pages/use-switch-page.ts
apps/builder/app/shared/router-utils/path-utils.ts

Fix preview mode toggle and sync

---

packages/css-data/bin/mdn-data.ts
packages/generate-arg-types/src/cli.ts
packages/prisma-client/migrations-cli/args.ts
packages/prisma-client/migrations-cli/cli.ts
packages/prisma-client/migrations-cli/commands.ts
packages/prisma-client/package.json
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio-builder/issues/1191

Replace minimist with parseArgs

---

packages/css-data/bin/property-value-descriptions.ts
packages/css-data/package.json
packages/http-client/package.json
packages/http-client/src/index.ts
packages/trpc-interface/package.json
packages/trpc-interface/src/shared/client.ts
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio-builder/issues/1191
- dropped undici (installed one)
- dropped isomorphic-fetch
- dropped node-fetch

Use native node fetch

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.76.0

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Upate version

---

apps/builder/package.json
apps/builder/remix.config.js
packages/trpc-interface/src/shared/client.ts
pnpm-lock.yaml

Use node-fetch for trpc-interface to fix vercel/remix override

---

.npmrc
apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Update version 0.78.0

---

packages/design-system/src/components/button.tsx

Change pending button icon loading size

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Update versions 0.79.0

---

apps/builder/app/builder/features/style-panel/shared/property-name.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
apps/builder/app/builder/features/style-panel/shared/style-info.ts

Ref https://github.com/webstudio-is/webstudio-builder/issues/1895

Show badges on inherited styles

---

apps/builder/app/builder/builder.tsx
apps/builder/app/dashboard/projects/project-card.tsx
apps/builder/app/dashboard/projects/project-dialogs.tsx

Fix create project useEffect not working.
Fix double redirect.
Fix card hover
2. expect xyz

Fix project creation race condition

---

apps/builder/app/dashboard/projects/project-dialogs.tsx

Race comment

---

apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
packages/sdk-components-react/src/html-embed.ws.ts

Fixes https://discord.com/channels/955905230107738152/955907841070346300/1130407072522059896
- replaced blocking error with console.error
- removed id from html embed initial props

Fix initial props

---

apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
packages/generate-arg-types/src/types.ts
packages/image/src/image.tsx
packages/sdk-components-react/src/__generated__/image.props.ts
packages/sdk-components-react/src/image.tsx

Fixes https://discord.com/channels/955905230107738152/955907841070346300/1130819857403887616 and https://discord.com/channels/955905230107738152/955907841070346300/1131197538112905348
- specified default in image wrapper to let our props generator find it
- fix added with ui props
- prevent setting defaults when no default value is available

Fix props bugs

---

packages/design-system/src/components/tree/tree-node.tsx

Closes https://github.com/webstudio-is/webstudio-builder/issues/1951
1. just font weight in navigator

Fix font weight in the navigator

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Update version 0.82.0

---

apps/builder/package.json
package.json
packages/design-system/package.json
packages/image/package.json
packages/scripts/package.json
packages/sdk-components-react/package.json
packages/storybook-config/package.json
pnpm-lock.yaml

Here bumped, storybook and esbuild and deduped all dependencies (mostly babel packages)
- https://github.com/storybookjs/storybook/releases/tag/v7.1.0
- https://github.com/evanw/esbuild/releases/tag/v0.18.0
```diff
Packages:
- 2203
+ 1902
```

Bump storybook

---

apps/builder/app/canvas/canvas.tsx
packages/project-build/src/schema/props.ts
packages/react-sdk/src/context.tsx
packages/react-sdk/src/embed-template.test.ts
packages/react-sdk/src/embed-template.ts
packages/react-sdk/src/expression.test.ts
packages/react-sdk/src/expression.ts
packages/react-sdk/src/props.ts
packages/react-sdk/src/tree/create-elements-tree.tsx

Here added support for expression arguments to utilize callback based state management. So for example Form component can expose onStateChange action with "newState" value and update any variable with it. So all state management inside form becomes prop and callback.
You can test it by pasting
<details>
<summary>You can test by pasting this template and clicking on +</summary>
```ison
{
"@webstudio/template": [
{
"type": "instance",
"component": "Box",
"props": [
{
"type": "number",
"name": "data-count",
"value": 0,
"dataSourceRef": {
"type": "variable",
"name": "count"
}
}
],
"styles": [
{
"property": "display",
"value": { "type": "keyword", "value": "flex" }
}
],
"children": [
{
"type": "instance",
"component": "Button",
"props": [
{
"type": "action",
"name": "onClick",
"value": [
{ …
```

Support effectful expression arguments

---

packages/design-system/src/__generated__/figma-design-tokens.json
packages/design-system/src/__generated__/figma-design-tokens.ts

space section unit text changed from semi-bold to medium
noticed some brand text changes as well

text token updates

---

apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx

Closes https://github.com/webstudio-is/webstudio-builder/issues/1921

Rename "Add"  panel to "Components"

---

packages/sdk-components-react/LICENSE-3RD-PARTY
packages/sdk-components-react/package.json
packages/sdk-components-react/src/radix-tooltip.ws.tsx
packages/sdk-components-react/src/theme/radix-common-types.ts
packages/sdk-components-react/src/theme/radix-variables.ts
packages/sdk-components-react/src/theme/tailwind-classes.ts
packages/sdk-components-react/src/theme/tailwind-colors.ts
packages/sdk-components-react/src/theme/tailwind-theme.ts
pnpm-lock.yaml

Local styles from https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/tooltip.tsx
Add NEW tooltip, see styles

Radix tooltip local styles

---

apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
apps/builder/app/builder/features/settings-panel/controls/color.tsx
apps/builder/app/builder/features/settings-panel/controls/number.tsx
apps/builder/app/builder/features/settings-panel/controls/text.tsx
apps/builder/app/builder/features/settings-panel/shared.tsx

Fix layout

---

apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
packages/sdk-components-react/package.json
packages/sdk-components-react/src/__generated__/radix-popover.props.ts
packages/sdk-components-react/src/components.ts
packages/sdk-components-react/src/metas.ts
packages/sdk-components-react/src/props.ts
packages/sdk-components-react/src/radix-popover.tsx
packages/sdk-components-react/src/radix-popover.ws.tsx
packages/sdk-components-react/src/theme/tailwind-classes.ts
pnpm-lock.yaml

Add radix popover

---

apps/builder/package.json
package.json
packages/asset-uploader/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/design-system/package.json
packages/eslint-config-custom/package.json
packages/fonts/package.json
packages/http-client/package.json
packages/image/package.json
packages/jest-config/package.json
packages/project-build/package.json
packages/react-sdk/package.json
packages/sdk-size-test/package.json
pnpm-lock.yaml

- jest
- simple-git-hooks
- eslint
- size-limit

Bump checks packages

---

apps/builder/app/builder/features/topbar/entri.tsx

Removing mentioning Entri, there is no value in it, nobody knows them

Publishing wording

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Update NPM 0.83.0

---

apps/builder/package.json
package.json
packages/design-system/package.json
packages/image/package.json
packages/jest-config/package.json
packages/scripts/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react/package.json
packages/storybook-config/package.json
pnpm-lock.yaml

- https://github.com/storybookjs/storybook/releases/tag/v7.2.0
- https://storybook.js.org/blog/july-2023-update/

Bump to storybook 7.2

---

apps/builder/app/builder/features/settings-panel/controls/url.tsx
apps/builder/app/builder/features/settings-panel/shared.tsx

Add https to url 
https://discord.com/channels/955905230107738152/1138821247791284244
https://discord.com/channels/955905230107738152/1137045793069600888
2. expect xyz

Add automatic https to url

---

apps/builder/app/builder/features/topbar/sync-status.tsx
apps/builder/app/builder/shared/sync/command-queue.ts
apps/builder/app/builder/shared/sync/sync-server.ts
apps/builder/app/routes/rest.patch.ts
packages/design-system/src/components/toast.tsx

-  Fixes sync bugs https://discord.com/channels/955905230107738152/1138073603036954664
- There is no sense to retry `fatal` errors, we can stop sync.
- Fatal errors state, show fatal error message.
- If user cancel confirmation goto fatal state too, as sync will never be fixed.
- Intercept error if project is loaded during synchronisation.
- Errors logged, as during investigation there were no way to get why `patch` requests are in failed state. 
- rest.patch are now wrapped with try/catch so we can distinguish api errors.
- toasts added too (and made infinite in case of fatal errors)
- exponential backoff + jitter added
- improved connectivity messages
Use for review:
2. expect xyz …

Synchronisations fixes

---

apps/builder/package.json
apps/cli/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/eslint-config-custom/package.json
packages/feature-flags/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json
packages/tsconfig/package.json

npm packages update
2. expect xyz

release-0.84.0

---

packages/design-system/src/components/tooltip.tsx

Fix tooltip

---

apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx

Here fixing the issue with props not bypassed from parent component in canvas mode. This is important for radix triggers with asChild which bypass props to child button.

Improve props bypassing in canvas

---

packages/asset-uploader/package.json
packages/asset-uploader/src/clients/s3/s3.ts
packages/asset-uploader/src/clients/s3/upload.ts
packages/asset-uploader/src/utils/sanitize-s3-key.test.ts
packages/asset-uploader/src/utils/sanitize-s3-key.ts
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio-builder/issues/2091 https://github.com/webstudio-is/webstudio-builder/issues/2049
Here fixed uploading of files by sanitizing a few more characters which require special treatment in signature v4.

Improve s3 keys sanitizer

---

apps/builder/app/builder/features/style-panel/sections/effects/effects.tsx
packages/react-sdk/src/component-renderer.tsx
packages/sdk-components-react-radix/.storybook/preview-body.html
packages/sdk-components-react-radix/src/__generated__/button.props.ts
packages/sdk-components-react-radix/src/button.stories.ts
packages/sdk-components-react-radix/src/button.tsx
packages/sdk-components-react-radix/src/button.ws.ts
packages/sdk-components-react-radix/src/components.ts
packages/sdk-components-react-radix/src/metas.ts
packages/sdk-components-react-radix/src/props.ts
packages/sdk-components-react-radix/src/theme/tailwind-classes.ts
packages/sdk-components-react-radix/src/theme/tailwind-colors.ts

Add radix button.
2. expect xyz

Radix Button

---

packages/sdk-components-react-radix/package.json
packages/sdk-components-react-radix/src/__generated__/input.props.ts
packages/sdk-components-react-radix/src/__generated__/label.props.ts
packages/sdk-components-react-radix/src/__generated__/textarea.props.ts
packages/sdk-components-react-radix/src/components.ts
packages/sdk-components-react-radix/src/input.stories.ts
packages/sdk-components-react-radix/src/input.tsx
packages/sdk-components-react-radix/src/input.ws.ts
packages/sdk-components-react-radix/src/label.stories.ts
packages/sdk-components-react-radix/src/label.tsx
packages/sdk-components-react-radix/src/label.ws.ts
packages/sdk-components-react-radix/src/metas.ts
packages/sdk-components-react-radix/src/props.ts
packages/sdk-components-react-radix/src/textarea.stories.ts
packages/sdk-components-react-radix/src/textarea.tsx
packages/sdk-components-react-radix/src/textarea.ws.ts
packages/sdk-components-react-radix/src/theme/tailwind-classes.ts
pnpm-lock.yaml

Input + Textarea + Label components

---

packages/sdk-components-react-radix/package.json
packages/sdk-components-react-radix/src/__generated__/accordion.props.ts
packages/sdk-components-react-radix/src/accordion.stories.tsx
packages/sdk-components-react-radix/src/accordion.tsx
packages/sdk-components-react-radix/src/accordion.ws.ts
packages/sdk-components-react-radix/src/components.ts
packages/sdk-components-react-radix/src/hooks.ts
packages/sdk-components-react-radix/src/metas.ts
packages/sdk-components-react-radix/src/props.ts
packages/sdk-components-react-radix/src/tabs.ws.ts
packages/sdk-components-react-radix/src/theme/tailwind-classes.ts
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio-builder/issues/2096
- https://ui.shadcn.com/docs/components/accordion
- https://www.radix-ui.com/primitives/docs/components/accordion

Add radix accordion

---

apps/builder/app/canvas/instance-selected-react.ts
apps/builder/app/canvas/instance-selected.ts

https://discord.com/channels/955905230107738152/1140198766364860416
2. expect xyz

Fix hidden elements not selected sometimes

---

packages/sdk-components-react/src/html-embed.tsx
packages/sdk-components-react/src/html-embed.ws.ts

- renamed "Execute script on canvas" to "Run script on canvas" (https://github.com/webstudio-is/webstudio-builder/issues/2104)
- execute in preview (https://github.com/webstudio-is/webstudio-builder/issues/2107)

Fix html embed

---

apps/builder/package.json
apps/cli/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.87.0

---

apps/builder/app/builder/shared/assets/use-assets.tsx

Ref https://github.com/webstudio-is/webstudio-builder/pull/2115
- sort uploading assets first
- sort newest uploaded first

Sort assets

---

packages/sdk-components-react-radix/src/dialog.ws.tsx

Small fix to allow dialog to be scrollable in case of content overflow

Add overflow scroll to dialog element

---

packages/sdk-components-react-radix/src/accordion.ws.ts
packages/sdk-components-react-radix/src/button.ws.ts
packages/sdk-components-react-radix/src/collapsible.ws.ts
packages/sdk-components-react-radix/src/dialog.ws.tsx
packages/sdk-components-react-radix/src/input.ws.ts
packages/sdk-components-react-radix/src/label.ws.ts
packages/sdk-components-react-radix/src/popover.ws.tsx
packages/sdk-components-react-radix/src/sheet.ws.tsx
packages/sdk-components-react-radix/src/tabs.ws.ts
packages/sdk-components-react-radix/src/textarea.ws.ts
packages/sdk-components-react-radix/src/tooltip.ws.tsx

Ref https://github.com/webstudio-is/webstudio-builder/issues/2140

Reorder radix components

---

apps/builder/app/dashboard/dashboard.stories.tsx
apps/builder/app/dashboard/dashboard.tsx
apps/builder/app/dashboard/projects/panel.tsx
apps/builder/app/dashboard/projects/project-card.tsx
apps/builder/app/dashboard/projects/project-dialogs.tsx
apps/builder/app/dashboard/projects/projects.tsx
apps/builder/app/dashboard/projects/thumbnail-link.tsx
apps/builder/app/env/env.server.ts
apps/builder/app/routes/dashboard._index.tsx
apps/builder/app/shared/context.server.ts
packages/dashboard/src/db/projects.ts
packages/dashboard/src/trpc/project-router.ts
packages/project/src/db/project.ts
packages/project/src/trpc/project-router.ts
packages/trpc-interface/src/authorize/project.server.ts
packages/trpc-interface/src/context/context.server.ts

closes #2134
On card click
Also fixed resize
Made it
2. expect xyz

Add project templates

---

apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
apps/builder/app/builder/features/settings-panel/controls/color.tsx
apps/builder/app/builder/features/settings-panel/controls/number.tsx
apps/builder/app/builder/features/settings-panel/controls/text.tsx
apps/builder/app/builder/features/settings-panel/props-section/props-section.stories.tsx
apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
apps/builder/app/builder/features/settings-panel/shared.tsx

- https://github.com/webstudio-is/webstudio-builder/issues/2104
- https://github.com/webstudio-is/webstudio-builder/issues/2047
- https://github.com/webstudio-is/webstudio-builder/issues/2131
- https://github.com/webstudio-is/webstudio-builder/issues/2129
Improved switch control layout and made all inputs change to vertical layout when label is more than 8 chars.

Fix prop labels

---

apps/builder/remix.config.js
packages/css-vars/src/index.ts

This speedups my remix dev rebuilds from 42s to 1s
The issue was that chokidar watched my whole fs and seems like something on my machine makes it very slow.
Also enabled `v2_dev: true,` doesn't affect perf, just to be modern
2. expect xyz

Speedup remix dev 40x on my machine

---

packages/sdk-components-react-radix/src/navigation-menu.ws.ts

Ref https://discord.com/channels/955905230107738152/1143794425290555452/1143794425290555452
Items need to allow duplicate and reorder

Make nav menu items detachable

---

packages/sdk-components-react-radix/src/accordion.ws.ts
packages/sdk-components-react-radix/src/dialog.ws.tsx
packages/sdk-components-react-radix/src/navigation-menu.ws.ts
packages/sdk-components-react-radix/src/sheet.ws.tsx
packages/sdk-components-react-radix/src/tabs.ws.ts

Rename radix template labels

---

packages/sdk-components-react-radix/package.json
packages/sdk-components-react-radix/src/__generated__/checkbox.props.ts
packages/sdk-components-react-radix/src/checkbox.stories.ts
packages/sdk-components-react-radix/src/checkbox.tsx
packages/sdk-components-react-radix/src/checkbox.ws.ts
packages/sdk-components-react-radix/src/components.ts
packages/sdk-components-react-radix/src/metas.ts
packages/sdk-components-react-radix/src/props.ts
packages/sdk-components-react/src/checkbox.ws.tsx
pnpm-lock.yaml

- https://www.radix-ui.com/primitives/docs/components/checkbox
- https://ui.shadcn.com/docs/components/checkbox

Add radix checkbox

---

apps/builder/package.json
apps/cli/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

NPM Release 0.88.0

---

packages/sdk-components-react-radix/src/checkbox.ws.ts
packages/sdk-components-react-radix/src/radio-group.ws.ts
packages/sdk-components-react-radix/src/switch.ws.ts
packages/sdk-components-react/src/code-text.ws.tsx
packages/sdk-components-react/src/heading.ws.tsx
packages/sdk-components-react/src/label.ws.tsx
packages/sdk-components-react/src/link.ws.tsx
packages/sdk-components-react/src/paragraph.ws.tsx

Marked more components as non-detachable and non-self-nestable

Add more constraints to components

---

apps/builder/package.json
apps/cli/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/css-vars/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/trpc-interface/package.json

Release 0.89.0

---

apps/builder/app/builder/features/footer/breadcrumbs.tsx
apps/builder/app/builder/features/footer/footer.tsx

1. Chevron icon changed, color not set
1. open footer
2. see color of cheveron is white

Fix footer chevron color

---

.github/pull_request_template.md
README.md
apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
apps/builder/app/builder/features/style-panel/sections/position/position.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
apps/builder/app/builder/features/topbar/domains.tsx
apps/builder/app/builder/features/topbar/menu/menu.tsx
apps/builder/app/builder/shared/navigator-tree.tsx
apps/builder/app/canvas/canvas.tsx
packages/cli/src/prebuild.ts
packages/design-system/src/components/label.tsx
packages/image/src/image-dev.stories.tsx
packages/react-sdk/src/props.test.ts
packages/react-sdk/src/props.ts
packages/sdk-components-react-radix/src/navigation-menu.ws.ts
packages/trpc-interface/src/authorize/project.server.ts

We renamed webstudio-builder to webstudio

Update main webstudio repo links

---

README.md

webstudio -> webstudio-community
webstudio-builder -> webstudio

Fix community links

---

packages/cli/LICENSE
packages/cli/package.json

- We decided to use `npx webstudio` for simplicity and new package name is nicer
- Added the license

New package name for CLI

---

apps/builder/app/canvas/instance-selected.ts

calulated -> calculated
2. expect xyz

Fix comment in instance-selected.ts

---

apps/builder/app/shared/share-project/share-project-container.tsx
apps/builder/app/shared/share-project/share-project.stories.tsx
apps/builder/app/shared/share-project/share-project.tsx

closes #2225
Add/delete/update/load links see button has pending state

Use pending state on button in Share panel

---

apps/builder/app/builder/features/topbar/share.tsx
apps/builder/app/shared/share-project/share-project.tsx
packages/design-system/src/components/popover.tsx

ref #2226
Everything except Button aligned to the design, we don't have Button with Menu Item style
2. expect xyz

Update permission level tooltips to reflect recent changes

---

packages/cli/src/prebuild.ts

Missing piece to make accordion and tabs components work on published sites.

Fix radix tabs and accordion on published sites

---

packages/cli/src/commands/init-flow.ts

This PR updates the text from the cli's init flow. The changes are request from the #2263

Update text inside cli init flow

---

packages/cli/src/commands/init-flow.ts

Better wording in CLI

---

fixtures/webstudio-remix-vercel/remix.config.js
packages/cli/src/__generated__/templates.ts
packages/cli/templates/defaults/remix.config.js

Fix remix dev warnings

---

package.json

Do not run dev inside `./fixtures` folder
2. expect xyz

Fixes dev mode

---

fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/index.css
fixtures/webstudio-remix-vercel/app/__generated__/radix._index.tsx
fixtures/webstudio-remix-vercel/app/routes/radix._index.tsx
packages/cli/src/prebuild.ts

Used wrong import name.
Added accordion fixture to see issues in the future

Fix radix imports generation

---

apps/builder/app/canvas/canvas.tsx
apps/builder/app/routes/$.tsx
fixtures/webstudio-remix-vercel/app/constants.ts
fixtures/webstudio-remix-vercel/app/routes/[blog].[page].[deep-nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[blog].[page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[blog]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/package.json
fixtures/webstudio-remix-vercel/vercel.json
packages/cli/src/__generated__/router.ts
packages/cli/src/__generated__/templates.ts
packages/cli/templates/defaults/app/constants.ts
packages/cli/templates/defaults/package.json
packages/cli/templates/defaults/vercel.json
packages/cli/templates/route-template.tsx
packages/react-sdk/package.json
packages/react-sdk/src/component-renderer.tsx
packages/react-sdk/src/context.tsx
packages/react-sdk/src/tree/create-elements-tree.tsx
packages/react-sdk/src/tree/root.ts
packages/sdk-components-react/src/image.tsx
pnpm-lock.yaml

CLI support of vercel image optimisation
2. expect xyz

Vercel image optimisation support

---

packages/cli/README.md

Add video to the readme

---

apps/builder/app/canvas/canvas.tsx
apps/builder/app/shared/nano-states/nano-states.ts
fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
packages/cli/__generated__/index.ts
packages/cli/src/prebuild.ts
packages/react-sdk/src/component-renderer.tsx
packages/react-sdk/src/context.tsx
packages/react-sdk/src/expression.test.ts
packages/react-sdk/src/expression.ts
packages/react-sdk/src/generator.test.ts
packages/react-sdk/src/generator.ts
packages/react-sdk/src/index.ts
packages/react-sdk/src/props.ts
packages/react-sdk/src/tree/create-elements-tree.tsx
packages/react-sdk/src/tree/root.ts

Scope utility give us a way to generate more readable data sources and actions. Here variables, expressions and actions are output into the same map.
In the future same utility can be used to produce framework specific stores like React.useState.
See fixtures for example.

Generate human readable data sources and actions

---

fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/route-template.tsx

Forms have special behavior so here added fixture to test what is generated for them.
Found default forms would fail on submit.
2. expect xyz

Add form fixture

---

apps/builder/app/dashboard/dashboard.tsx

Fix Dashboard Failure Due to Tooltip

---

.github/workflows/lint-pull-request.yaml

Change title of this PR to be non semantic see comment.

ci:  Semantic pull request titles

---

packages/generate-arg-types/src/arg-types.ts
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-radix/src/__generated__/accordion.props.ts
packages/sdk-components-react-radix/src/__generated__/tabs.props.ts
packages/sdk-components-react-remix/src/form.tsx
packages/sdk-components-react/src/__generated__/html-embed.props.ts

- fixed incorrect jsdoc parsing in accordion collapsible
- fixed form default props by inlining destructuring

fix: fix props meta generation

---

apps/builder/app/dashboard/projects/project-dialogs.tsx

style: Change label at delete project dialog

---

apps/builder/app/services/auth.server.ts

This PR addresses an issue where inconsistencies between the database and session were causing crashes on every page of the application.
2. expect xyz

fix: Resolve inconsistencies between database and session

---

apps/builder/app/builder/features/topbar/publish.tsx
apps/builder/app/builder/shared/nano-states/index.ts

fixes #2372 
Updates the export dialog with the new deployment target changes.

refactor: Update export dialog for deployments

---

apps/builder/app/builder/features/topbar/publish.tsx
apps/builder/package.json
apps/builder/remix.config.js
packages/cli/src/commands/init-flow.ts
packages/cli/src/config.ts
pnpm-lock.yaml

Adds the `netlify` deployment commands sequence. Tested one by one, seems to be the best flow i can come by. Would like to validate on someone else too.

chore: Add netlify deploy command list in cli and in export tab

---

apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
packages/feature-flags/src/flags.ts

Removes feature flag for radix elements in the editor.

chore: remove radix components flag

---

package.json

Last few versions bring many fixes and performance improvements and might solve some issues when add or upgrade packages.

build: upgrade to pnpm 8.8

---

.github/workflows/cli-test.yml

Run link sequentially, this fixes cli link test
2. expect xyz

fix: Сli tests, run cli link command sequentially

---

apps/builder/app/builder/shared/sync/sync-server.ts
apps/builder/app/shared/commands-emitter.ts
apps/builder/app/shared/sync/sync-stores.ts

Commands meta store introduced in latest changes polutted immerhin history. Here created separate store for client only synchronization.

fix: fix undo/redo

---

.gitignore
apps/builder/.gitignore
apps/builder/middleware.js
apps/builder/package.json
apps/builder/tsconfig.json
package.json
packages/form-handlers-mailchannels-test/package.json
patches/@cloudflare__workers-types@3.19.0.patch
patches/@cloudflare__workers-types@4.20230922.0.patch
pnpm-lock.yaml

This PR integrates a rate-limiting mechanism into the app using Vercel's edge-layer middleware in combination with the Hono framework. This middleware is written in JS with full JSDoc TypeScript typings.
Vercel Middleware: Serves as the front-line defense, running at the edge for optimal performance.
Hono Framework: For granular control, we utilize Hono middlewares for applying or skipping rate limits.
Additionally, non-expensive routes benefit from an ephemeral cache to further optimize performance
Due to a dependency on CommonJS, we cannot use TypeScript fully. Consequently, session configurations are not yet shared across multiple files. All utility functions are present in a single file for the time being.
- Assets: Rate limiting skipped.
- Service Calls: Rate limiting skipped.
- …

feat: Implement Rate Limiting 

---

packages/css-data/src/tailwind-parser/shorthand.test.ts
packages/css-data/src/tailwind-parser/shorthand.ts

fix: Resolve longhand-to-shorthand expansion in Tailwind conversion

---

packages/css-data/src/tailwind-parser/parse.test.ts
packages/css-data/src/tailwind-parser/parse.ts
packages/css-data/src/tailwind-parser/shorthand.ts

fix no-underline
2. expect xyz

fix: supports no-underline in Tailwind conversion

---

apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
apps/builder/app/canvas/features/text-editor/interop.ts
apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
apps/builder/app/canvas/features/text-editor/text-editor.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
packages/sdk-components-react/src/text.tsx

- add missing placeholder to Text component
- fix wrapping buttons and links with span
- preserve node content when entering editing mode if instance has no children
- hide "link" button in text toolbar when edit link component to prevent nested links

fix: fix various text editor bugs

---

apps/builder/app/builder/features/ai/hooks/effect-event.ts
apps/builder/app/builder/features/ai/hooks/long-press-toggle.ts
apps/builder/app/builder/features/ai/hooks/media-recorder.stories.tsx
apps/builder/app/builder/features/ai/hooks/media-recorder.ts

Media recorder hook and useLongPressToggle hook.
https://6382151c8b47d4399fb9fc69-gumktzhrtx.chromatic.com/?path=/story/library-media-recorder--media-recorder
See storybook for usage.

feat: Add Media Recorder

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/ai/ai-command-bar.tsx
apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
apps/builder/app/builder/shared/commands.ts
apps/builder/app/shared/nano-states/nano-states.ts

Just UI of command bar. It does nothing. 
2. expect xyz

feat: Add AI command bar

---

apps/builder/app/builder/features/ai/ai-command-bar.tsx
apps/builder/app/builder/features/ai/hooks/media-recorder.ts
apps/builder/app/routes/rest.ai.audio.transcriptions.ts
packages/design-system/src/components/ai-command-bar/autogrow-text-area.tsx

Audio transcribe UI, and fast implementation of rest endpoint. No validation etc.
NEXT PRs:
1. Send data to AI endpoint
2. Move transcription logic to AI package.
3. Implement prompt history
Start record anything in Command bar, see results

feat: Audio transcribe

---

.github/workflows/cli-test.yml
apps/builder/app/builder/features/topbar/publish.tsx
fixtures/webstudio-custom-template/README.md
fixtures/webstudio-custom-template/package.json
fixtures/webstudio-remix-netlify-edge-functions/README.md
fixtures/webstudio-remix-netlify-edge-functions/package.json
fixtures/webstudio-remix-netlify-functions/README.md
fixtures/webstudio-remix-netlify-functions/package.json
fixtures/webstudio-remix-vercel/package.json
packages/cli/README.md
packages/cli/package.json
packages/cli/src/cli.ts
packages/cli/src/commands/sync.ts
packages/cli/src/prebuild.ts
pnpm-lock.yaml

feat: Rename webstudio-cli to webstudio as we got the shorter namespace

---

apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/selected-instance-outline.tsx

Just better colors for collaborative outline
https://share.descript.com/view/X2nGgJUZaC2

style: Better colors for the outline

---

apps/builder/app/builder/features/ai/ai-command-bar.tsx
apps/builder/app/builder/features/ai/ai-fetch-result.ts
apps/builder/app/builder/features/ai/ai-fetch-transcription.ts

No Error processing.
No Cancel wroking.
2. expect xyz

feat: new AI command bar

---

apps/builder/middleware.js

Increasing AI rate limit per user per 5 minute

chore: Increase AI rate limit

---

apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/design-system/src/components/primitives/dnd/placement-indicator.tsx

- allow dragging control and embed components
- fix placement indicator for style sources and backgrounds
- synchronize drag and drop state between builder and canvas

fix: fix drag&drop issues

---

apps/builder/app/builder/features/ai/ai-fetch-result.ts
apps/builder/app/builder/features/ai/commands-bar.tsx
apps/builder/app/routes/rest.ai._index.ts

1. Route now is not layout or like `_index`  postfix
2. export const config instead of export const maxDuration
3. expect xyz

fix: AI route maxDuration 

---

apps/builder/app/builder/features/ai/ai-fetch-result.ts

Fixes few errors:
1. In some cases previous algorithm failed on every text instance provided except last.
2. Previous algorithm was able to skip nodes.
3. expect xyz

fix: AI completion streaming algorithm

---

apps/builder/app/shared/instance-utils.test.ts
apps/builder/app/shared/instance-utils.ts

Moved root detection logic into "deleteInstance" utility and covered with test.

fix: prevent deleting Body

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/ai/ai-command-bar.tsx
packages/design-system/src/components/ai-command-bar/command-bar.tsx

fix: AI Command Bar improvements

---

apps/builder/app/builder/features/ai/ai-command-bar.tsx
apps/builder/app/builder/features/ai/ai-fetch-result.ts
apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/collaborative-instance-outline.tsx
apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/collaborative-instance-react.ts
apps/builder/app/canvas/collaborative-instance.ts
apps/builder/app/shared/nano-states/canvas.ts

Implement collaborative highlight for AI-modified elements
2. expect xyz

feat: Implement collaborative highlight for AI-modified elements

---

fixtures/webstudio-custom-template/remix.config.js
fixtures/webstudio-remix-netlify-edge-functions/remix.config.js
fixtures/webstudio-remix-netlify-functions/remix.config.js
fixtures/webstudio-remix-vercel/remix.config.js
packages/cli/templates/defaults/remix.config.js
packages/cli/templates/netlify-edge-functions/remix.config.js
packages/cli/templates/netlify-functions/remix.config.js

Fixes https://github.com/webstudio-is/webstudio-community/discussions/62

fix: bundle esm dependencies in templates

---

apps/builder/app/builder/features/ai/ai-command-bar.tsx

1. click on a prompt
2. run ai

feat: Add some initial prompts to ai bar

---

packages/ai/src/chains/command-detect/chain.ts

feat: Add anonymous logger of prompts

---

apps/builder/app/builder/features/ai/ai-command-bar.tsx

fix: Remove todos

---

apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
apps/builder/app/builder/features/style-panel/style-layers-list.tsx

Extract layer-list component and use it inside box-shadow component.

refactor: extract layer-list component and use it inside box-shadown

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
packages/feature-flags/src/flags.ts

With this we are enabling AI for everyone @itsNintu let's spread the news on X.

feat: Enable AI for everyone

---

apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
apps/builder/app/shared/breakpoints/select-breakpoint-by-order.ts

Fixes https://github.com/webstudio-is/webstudio/issues/2520

fix: resize canvas with breakpoints hotkeys

---

apps/builder/app/builder/features/sidebar-left/panels/pages/search-preview.stories.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/search-preview.test.ts
apps/builder/app/builder/features/sidebar-left/panels/pages/search-preview.tsx

feat: Google Search Preview block

---

apps/builder/app/dashboard/header.tsx

This PR fixes the alignment of drop down menu under user avatar 
Issue Number- #2075 
Here is the video of the fix-
https://github.com/webstudio-is/webstudio/assets/88244542/3b233676-5928-4b94-a88a-d4c00eb9d073

fix: Alignment of drop down menu under user avatar fixed

---

apps/builder/app/builder/shared/floating-panel/floating-panel.tsx

fix: Wrong zIndex on favicon upload

---

apps/builder/app/builder/features/sidebar-left/panels/pages/social-preview.tsx

No image is stretched
2. expect xyz

fix: No image at page settings

---

apps/builder/app/builder/features/settings-panel/variables.stories.tsx
apps/builder/app/builder/features/settings-panel/variables.tsx
packages/design-system/src/components/css-value-list-item.tsx
packages/design-system/src/components/floating-panel-popover.tsx

Here added popover panel to maintain variables. For now only create/edit/delete. Will add bindings support in another PR.
Can be tested in storybook "Variables" component.
<br />

feat: add variables panel

---

apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/route-template.tsx
packages/sdk/src/schema/pages.ts

Custom metadata pages support
ref #2544
2. expect xyz

feat: Add custom metadata to page settings form

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Bump package versions to 0.112.0

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx

All code is autogenerated
Update fixtures to proceed with vercel rewriter
2. expect xyz

build: Update fixtures (autogenerated)

---

apps/builder/app/routes/rest.patch.ts
packages/prisma-client/prisma/migrations/20231105075338_add-last-transaction-id/migration.sql
packages/prisma-client/prisma/schema.prisma

Fixes some issues with disconnects and wrong version mismatch error
2. expect xyz

fix: Resolve version mismatch error for post-transaction issues

---

fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/routes/[sitemap.xml].tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-netlify-edge-functions/app/routes/[sitemap.xml].tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-netlify-functions/app/routes/[sitemap.xml].tsx
fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-vercel/app/routes/[sitemap.xml].tsx
packages/cli/src/prebuild.ts
packages/cli/templates/defaults/app/__generated__/[sitemap.xml].ts
packages/cli/templates/defaults/app/routes/[sitemap.xml].tsx
packages/http-client/src/index.ts
packages/project-build/package.json
packages/project-build/src/db/build.ts
packages/project-build/src/types.ts
pnpm-lock.yaml

Need to merge, before proceed with sitemap generation. Will ruin all fixtures tests after merge
2. expect xyz

feat: Sitemap endpoint support

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/settings.stories.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
apps/builder/app/env/env.public.server.ts
apps/builder/app/env/env.server.ts
apps/builder/app/routes/builder.$projectId.tsx
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/router-utils/path-utils.ts
packages/domain/src/db/index.ts

https://discord.com/channels/955905230107738152/1170434939318182020
2. expect xyz

fix: Page Setting URL Misformatted

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Npm release 0.113.0

---

apps/builder/middleware.js
fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts

fix: Wrong path in rate limiting

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Npm release 0.114.0

---

fixtures/webstudio-custom-template/app/extension.ts
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/extension.ts
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/extension.ts
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/app/extension.ts
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/defaults/app/extension.ts
packages/cli/templates/route-template.tsx

fix: Fix cli types

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: NPM release 0.115.0

---

packages/prisma-client/prisma/migrations/20231108172804_prop_expression/migration.ts

build: Increase transaction timeout

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: NPM release 0.116.0

---

fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
packages/prisma-client/prisma/migrations/20231108172804_prop_expression/migration.ts

speedup migration 1000x
2. expect xyz

build: Make migration fast

---

apps/builder/package.json
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: NPM Release 0.117.0

---

apps/builder/app/routes/rest.current.products.ts
packages/prisma-client/prisma/migrations/20231116173417_product/migration.sql
packages/prisma-client/prisma/migrations/20231116174151_transaction/migration.sql
packages/prisma-client/prisma/schema.prisma

With high probability tables will be changed.
rest endpoint created for debugging purposes.
Product intent - synchonized from 3rd parties product (stripe) 
TransactionLog - product, user, status, date + debug and idempotency params
Response example:
```json
{
"id": "0d970e5f-3344-4658-bf5d-b58c33629e4e",
"username": "admin",
"checkout": [
{
"eventId": "evt_1OD7CmBvryG8KJjl9t37DsdG",
"sessionId": "cs_test_b19O6wCvKi0MIADIs9QFZ5OB9lsC2G8HqzxyqMJO2NvnH2Bn43lyMN30V9",
"createdAt": "2023-11-16T15:47:06.706Z",
"product": {
"id": "prod_P0NaZnTWpJJ2Ay",
"name": "Webstudio Agency LTD Test",
"description": null,
"features": ["Admin permission sharing", "1000000 vews per month"],
"meta": { "hello": "world", "kototto": "kototo" },
"images": [ …
```

feat: Product and Transaction Log tables

---

apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx

All the PR's related to transitions are merged now. 
#2581 
#2572
#2538
#2511

chore: remove feature flag check for transitions

---

apps/builder/app/builder/features/style-panel/style-source/style-source.tsx

Fixes https://github.com/webstudio-is/webstudio/issues/2610

fix: use main color for local style source

---

apps/builder/app/shared/context.server.ts
apps/builder/app/shared/db/user-plan-features.server.ts
packages/prisma-client/prisma/migrations/20231121125755_token-uniq/migration.sql
packages/prisma-client/prisma/schema.prisma

Apply project owner's plan features to the projects shared via link
Need to be merged to test (see migrations)
After merge:
Create project shared link.
Open in incognito.

fix: Apply project owner's plan features to the via link shared projects

---

apps/builder/app/shared/db/user-plan-features.server.ts
packages/prisma-client/prisma/migrations/20231120172840_add-event-type/migration.sql
packages/prisma-client/prisma/schema.prisma

SaaS has new n8n schema "Stripe Customer Subscription Deleted" 
Other schemas updated accordingly
Now unsubscribe is handled by our system
2. expect xyz

feat: Support mutiple events in transaction log table

---

packages/prisma-client/prisma/migrations/20231108172804_prop_expression/migration.ts

Fixes https://github.com/webstudio-is/webstudio/issues/2632

build: fix running migrations on empty database

---

.github/workflows/add-status.yml

fix: "Add status to commit" fails on forked repos

---

apps/builder/app/shared/commands-emitter.ts

Fixes https://discord.com/channels/955905230107738152/1184660413326053426/1184660413326053426
Primitives exposed by react-hotkeys-hook are quite useless and buggy for us. Here added own simple implementation which should fit our needs.

fix: implement own hotkeys

---

fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.server.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
packages/cli/src/prebuild.ts
packages/react-sdk/src/component-generator.test.ts
packages/react-sdk/src/component-generator.ts
packages/react-sdk/src/resources-generator.test.ts
packages/react-sdk/src/resources-generator.ts

Here added resources fixture and fixed a few issues with it
- add optional chaining to collection?.map to safely skip iterating missing data
- added any to resource responses to access remote data without type errors
- always generate empty headers array
- skip empty body in generated resources

fix: improve generating resources

---

apps/builder/app/builder/features/blocking-alerts/blocking-alerts.tsx

In the last PR I forgot to uncomment the check
2. expect xyz

fix: blocking alerts accidentally got enabled for everyone

---

apps/builder/app/builder/features/seo/project-settings.tsx
packages/sdk/src/schema/pages.ts

Open Project, See Project Settings

feat: Add Publish Settings section to Project settings

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Release 0.124.0

---

README.md

Add thanks to Lost Pixel section

Update README.md with lost pixel

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Release 0.125.0

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/settings-panel/variable-popover.tsx
apps/builder/app/builder/shared/nano-states/index.ts
apps/builder/app/dashboard/dashboard.stories.tsx
apps/builder/app/dashboard/header.tsx
apps/builder/app/shared/db/user-plan-features.server.ts
packages/design-system/src/components/pro-badge.tsx
packages/design-system/src/index.ts
packages/trpc-interface/src/context/context.server.ts

feat: hide resource variables as paid feature

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-layer.tsx
packages/design-system/src/components/css-value-list-item.stories.tsx
packages/design-system/src/components/css-value-list-item.tsx

fix: remove drag handle from variables and bindings

---

apps/builder/app/builder/shared/expression-editor.tsx

fix: support mouse select in expression autocomplete

---

apps/builder/app/shared/instance-utils.test.ts
apps/builder/app/shared/instance-utils.ts

Extended existing tests and logic to support expressions in instance children beside prop expressions.

feat: support copy pasting text content bindings

---

apps/builder/app/shared/instance-utils.test.ts
apps/builder/app/shared/instance-utils.ts

Closes https://github.com/webstudio-is/webstudio/issues/2532
Last one

feat: support copy pasting resources

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

Npm 0.126.0 Release
2. expect xyz

build: Release 0.126.0

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Release 0.127.0

---

apps/builder/app/shared/commands-emitter.ts

Here fixed the issue with builder commands stopped being available to canvas because initialized only once when app starts.
Here changed initialization to each time builder is open.

fix: reinitialize commands when builder is reopen

---

packages/prisma-client/prisma/migrations/20240125182656_calc-domains/migration.sql

fix: Remove deleted projects from domain count calc

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-layer.tsx
apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx

Closes https://github.com/webstudio-is/webstudio/issues/1889
Small  styling fixes 
2. expect xyz

fix: Remaining styling fixes for box shadow and backgrounds

---

apps/builder/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/css-engine/package.json
packages/dashboard/package.json
packages/design-system/package.json
packages/domain/package.json
packages/error-utils/package.json
packages/fonts/package.json
packages/form-handlers/package.json
packages/generate-arg-types/package.json
packages/html-data/package.json
packages/http-client/package.json
packages/icons/package.json
packages/image/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-remix/package.json
packages/sdk-components-react/package.json
packages/sdk/package.json
packages/trpc-interface/package.json

build: Npm release 0.128.0

---

apps/builder/app/shared/instance-utils.test.ts
apps/builder/app/shared/instance-utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/2732 https://discord.com/channels/955905230107738152/1192842837583212655

fix: prevent editing body

---

apps/builder/app/builder/features/settings-panel/variable-popover.tsx
apps/builder/app/shared/nano-states/props.ts

Fixes https://github.com/webstudio-is/webstudio/issues/2797

feat: allow refreshing resources

---

apps/builder/app/dashboard/projects/empty-state.tsx
apps/builder/app/dashboard/projects/projects.tsx

feat: Cleaner dashboard look and an intro video

---

packages/project/src/db/project.ts

Closes https://github.com/webstudio-is/webstudio/issues/2841
Previews Dashboard preview image pr broke creation and duplicatin of projects
1. create a new project
2. duplicate a project

fix: Fix create and duplicate project

---

apps/builder/app/builder/features/topbar/menu/menu.tsx
apps/builder/app/dashboard/header.tsx

feat:  Update the menu according to figma

---

apps/builder/app/builder/features/sidebar-left/help-popover.tsx
apps/builder/app/dashboard/card.tsx
apps/builder/app/dashboard/dashboard.tsx
apps/builder/app/dashboard/panel.tsx
apps/builder/app/dashboard/projects/empty-state.tsx
apps/builder/app/dashboard/projects/project-card.tsx
apps/builder/app/dashboard/projects/projects.tsx
apps/builder/app/dashboard/resources.tsx
packages/design-system/src/components/card.tsx
packages/design-system/src/components/text.ts
packages/design-system/src/index.ts
packages/design-system/src/stitches.config.ts
packages/icons/src/types.ts

This is supposed to help with the onboarding: people generally miss all the content we have.
https://github.com/webstudio-is/webstudio/assets/52824/8e79e3a2-0dd2-452e-b852-a2c59454f817
1. open dashboard
2. see new Resources section
3. check accessibility

feat: Big learning resources panel for dashboard

---

apps/builder/app/dashboard/resources/resources.tsx
apps/builder/app/dashboard/shared/card.tsx
apps/builder/app/dashboard/shared/spinner/spinner.tsx

- improved dashboard resource items
- fixed react warnings

chore: More dashboard improvements

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-functions/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts

Here updated fixtures after migrating page meta to expressions.

build: resync fixtures

---

apps/builder/app/builder/features/footer/breadcrumbs.tsx
apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
apps/builder/app/builder/features/style-panel/style-source-section.test.ts
apps/builder/app/builder/features/style-panel/style-source-section.tsx
apps/builder/app/builder/features/workspace/workspace.tsx
apps/builder/app/builder/shared/commands.ts
apps/builder/app/builder/shared/navigator-tree.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/canvas/instance-selection.ts
apps/builder/app/canvas/shared/commands.ts
apps/builder/app/canvas/shared/styles.ts
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/sync/sync-stores.ts

Fixes https://github.com/webstudio-is/webstudio/issues/2575

feat: preserve last selected style source on instances

---

apps/builder/app/shared/share-project/share-project.tsx

Description was outdated
2. expect xyz

chore: Update wording on the view permission

---

apps/builder/app/builder/features/sidebar-left/panels/pages/address-bar.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx

- moved copy url to address bar
- support copy with keyboard
- persist copied state for 2 seconds

refactor: improve copy page url

---

apps/builder/app/shared/share-project/share-project-container.tsx

When deleting a link, blur event from link name triggers an update, which executes after link has been deleted
1. create a link
2. delete it
3. should not crash

fix: Fix shared link deletion crash

---

apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
apps/builder/app/canvas/shared/styles.ts

fix: Dialog focus issues

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx

experimental: disable status and redirect for hobby users

---

apps/builder/app/builder/features/settings-panel/controls/text.tsx
apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
apps/builder/app/builder/features/settings-panel/shared.tsx
packages/design-system/src/components/combobox.tsx

Closes https://github.com/webstudio-is/webstudio/issues/1012
I decided to just use the same control to add a custom property/attribute, it works same way as adding style sources.

feat: Custom attributes / properties

---

apps/builder/app/shared/share-project/share-project.tsx

- more decent copy to clipboard button with tooltip expaining the state
2. expect xyz

chore: Improve copy to clipboard experience

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/__generated__/[world]._index.server.tsx
fixtures/webstudio-custom-template/app/__generated__/[world]._index.tsx
fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-custom-template/app/routes/[hello]._index.ts
fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/defaults/__templates__/route-template.tsx

Issues found on saas
2. expect xyz

fix: Fix link preloads

---

apps/builder/app/builder/features/sidebar-left/panels/marketplace/about.tsx
apps/builder/app/builder/features/sidebar-left/panels/marketplace/overview.tsx
apps/builder/app/builder/features/sidebar-left/panels/marketplace/section-templates.tsx
packages/asset-uploader/src/db/load.ts

- skip assets permission check for marketplace, assets had a separate check which is not needed for a marketplace item
- sort template categories alphabetically
- improve about layou
2. expect xyz

experimental: marketplace improvements

---

apps/builder/app/shared/marketplace/db.server.ts

Previous pr didn't add the flag to skip the check
2. expect xyz

experimental: skip permissions check in assets for marketplace

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/__generated__/[world]._index.tsx

build: update fixtures

---

apps/builder/app/builder/features/project-settings/project-settings.tsx

More space is needed
2. expect xyz

fix: larger project settings dialog

---

apps/builder/app/shared/nano-states/props.ts

Here improved perf of computing expressions in props and pages. Instead of serializing all variables here added getters from variables map. So there is less bottleneck when variable value is a huge object and serialized with JSON.stringify and evaluated with new Function after it.

perf: compute expressions without serializing values

---

apps/builder/app/builder/features/project-settings/project-settings.stories.tsx
apps/builder/app/builder/features/project-settings/project-settings.tsx
apps/builder/app/builder/features/project-settings/section-redirects.tsx
packages/design-system/src/utilities.ts

Closes https://github.com/webstudio-is/webstudio/issues/2975
2. expect xyz

refactor: Redirects improvements

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts

Here fixed the issue with displaying selected page variables in page settings instead of currently editing one.

experimental: show page variables for editing page

---

apps/builder/package.json
packages/ai/package.json
packages/asset-uploader/package.json
packages/authorization-token/package.json
packages/cli/package.json
packages/css-data/package.json
packages/dashboard/package.json
packages/domain/package.json
packages/fonts/package.json
packages/generate-arg-types/package.json
packages/jsx-utils/package.json
packages/prisma-client/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/trpc-interface/package.json
pnpm-lock.yaml

fixes email validation hangs
https://github.com/colinhacks/zod/issues/2580
2. expect xyz

fix: Update zod

---

.github/workflows/vis-reg-tests.yml

Here bumped lost-pixel to see if it solves bugs.

build: upgrade to lost-pixel 3.15.1

---

apps/builder/app/shared/marketplace/router.ts
packages/authorization-token/src/trpc/authorization-tokens-router.ts
packages/dashboard/src/trpc/project-router.ts
packages/domain/src/trpc/domain.ts
packages/project/src/trpc/index.ts
packages/project/src/trpc/project-router.ts
packages/project/src/trpc/trpc.ts
packages/trpc-interface/src/context/router.server.ts
packages/trpc-interface/src/index.server.ts
packages/trpc-interface/src/shared/trpc.ts

Preparation on using std trpc protocol for everything
2. expect xyz

fix: Switch on single router

---

packages/prisma-client/prisma/migrations/20240309212641_page_system_variable/migration.ts

fix: Use direct url

---

apps/builder/app/builder/shared/binding-popover.tsx
packages/react-sdk/src/expression.test.ts
packages/react-sdk/src/expression.ts

Here added new lintExpression utility to provide diagnostics when parsing error happens or not supported language feature is used.
Additionally it no longer forbids template literals and ternary operators. Btw still need to get rid from legacy implementation to make them work.

refactor: switch to acorn for expression linting

---

apps/builder/app/builder/features/style-panel/shared/style-info.ts
apps/builder/app/shared/style-object-model.test.ts
apps/builder/app/shared/style-object-model.ts

Here added style object model basic functionality with inheritance and a few keywords like "initial", "inherit" and "unset".
The algorithm is following css spec and will get more features in next PRs.

experimental: setup style object model

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts

fix: Disallow home page inside folder

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/defaults/__templates__/route-template.tsx

fix:  Meta hydration errors on published sites

---

.github/workflows/vis-reg-tests.yml

This PR fixes monorepo mode in lost-pixel

fix: add finalise job to lost pixel

---

package.json
packages/cli/package.json
packages/css-data/package.json
packages/design-system/package.json
packages/generate-arg-types/package.json
packages/icons/package.json
packages/jest-config/package.json
packages/prisma-client/package.json
packages/scripts/package.json
pnpm-lock.yaml

Need to bump storybook to use vite in remix.

build: upgrade esbuild

---

fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
fixtures/webstudio-custom-template/app/__generated__/_index.server.tsx
fixtures/webstudio-custom-template/app/__generated__/_index.tsx

build: Add social image to fixture

---

apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
apps/builder/app/canvas/features/text-editor/text-editor.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx

Broke rich text, what to do is written in reopened issue.
https://github.com/webstudio-is/webstudio/issues/3021
2. expect xyz

fix: Broken rich text panel

---

apps/builder/app/entry.client.tsx
apps/builder/app/env/env.public.server.ts
apps/builder/package.json
pnpm-lock.yaml

I think nobody used this utility for a while
and we do not really need to support it in our code.

refactor: drop debug

---

apps/builder/app/builder/features/settings-panel/resource-panel.tsx
apps/builder/app/shared/nano-states/props.ts

Ref https://github.com/webstudio-is/webstudio/pull/3068

experimental: show system variable in resource

---

apps/builder/app/shared/remix/root.tsx
apps/builder/package.json
pnpm-lock.yaml

Here bumped package with minor change to support layouts we don't use. Added comment with reference to the PR and repro.

refactor: upgrade remix-island

---

apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx

UI will be more consistent and also its the latest standard to use lower case
2. expect xyz

fix: make currentcolor lower case

---

apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx

Better interface, simpler
2. expect xyz

refactor: simplify toggle control

---

apps/builder/app/builder/features/settings-panel/controls/text.tsx
packages/sdk-components-react/src/html-embed.ws.ts

Text is using responsive layout and doesn't need vertical one
2. expect xyz

refactor: Vertical layout hasn't been actually used

---

apps/builder/app/builder/features/project-settings/project-settings.tsx
apps/builder/app/builder/features/sidebar-left/panels/index.ts
apps/builder/app/builder/features/sidebar-left/panels/marketplace/overview.tsx
packages/feature-flags/src/flags.ts

These feature flags are not needed any more
2. expect xyz

chore: Remove old feature flags

---

devops/cli/Dockerfile
fixtures/webstudio-cloudlfare-template/package.json
packages/cli/src/prebuild.ts
packages/cli/templates/cloudflare/package.json
pnpm-lock.yaml

build: Stage publish

---

fixtures/webstudio-cloudlfare-template/package.json
packages/cli/templates/cloudflare/package.json
packages/cli/templates/saas-helpers/package.json
pnpm-lock.yaml

To avoid (for now) install step on saas publish
2. expect xyz

build: Saas helpers

---

.github/workflows/cli-docker.yaml
devops/cli/Dockerfile
fixtures/webstudio-cloudlfare-template/package.json
packages/cli/templates/cloudflare/package.json
pnpm-lock.yaml

build: Mini.staging

---

packages/css-data/bin/mdn-data.ts
packages/css-data/bin/prompts/declarations.prompt.md
packages/css-data/src/__generated__/property-value-descriptions.ts

Bringing the changes from https://github.com/webstudio-is/webstudio/pull/3166 as a separate PR 
2. expect xyz

chore: Improved descriptions prompt and descriptions

---

.github/workflows/cli-test.yml
.npmrc
devops/cli/Dockerfile
fixtures/webstudio-cloudlfare-template/package.json
fixtures/webstudio-custom-template/package.json
fixtures/webstudio-remix-netlify-edge-functions/package.json
fixtures/webstudio-remix-netlify-functions/package.json
fixtures/webstudio-remix-vercel/package.json
package.json

Ref https://github.com/pnpm/pnpm/releases/tag/v9.0.0
This release trims like 100MB from our node_modules
```diff
- 771_432
+ 872_444
```

build: upgrade to pnpm v9

---

apps/builder/app/builder/shared/fonts-manager/fonts-manager.tsx
packages/design-system/src/components/combobox.tsx

chore: fix React key warning

---

apps/builder/app/builder/features/style-panel/sections/advanced/advanced.stories.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
apps/builder/app/builder/features/style-panel/sections/borders/borders.stories.tsx
apps/builder/app/builder/features/style-panel/sections/position/position-control.stories.tsx
apps/builder/app/builder/features/style-panel/sections/position/position-layout.stories.tsx
apps/builder/app/builder/features/style-panel/sections/sections.ts

Visual regression tests for advanced section
Note: didn't add any mocking to make it functional in all states

chore: Visual regression tests for advanced section

---

packages/prisma-client/migrations-cli/prisma-migrations.ts

Fixed the command in migrations cli

build: fix prisma migrations

---

packages/asset-uploader/src/db/clone.ts
packages/project-build/src/db/build.ts
packages/project/src/db/project.ts

- reduces amount of queries inside transaction from 26 to 7
- removed read of assets and build from db to api
3. expect xyz

fix: Clone timeouts

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx

Closes https://github.com/webstudio-is/webstudio/issues/3322
Users want to test in prod before including in sitemap
2. expect xyz

feat: Exclude the page from search by default

---

package.json

Vite uses `webstudio` exports see resolve.conditions
2. expect xyz

build: Improve dev perf a little bit removing all (except prisma) esbuilds.

---

package.json

fix: dev command

---

apps/builder/app/routes/trpc.$.ts

We should not check user auth on trpc, 
context security is enough
Open in Incognito
https://trpc-auth.staging.webstudio.is/builder/95821bd9-040a-4294-aa7f-edf26d7f1ebe?authToken=137726f9-7914-4807-8d62-091eea59296b&mode=edit
Click publish

fix: Do not check user authenticated on trpc

---

apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx

feat: Show xml category for xml, hide in other cases

---

apps/builder/app/builder/features/breakpoints/breakpoints-editor.tsx

fix: Fix breakpoints editor layout

---

apps/builder/app/dashboard/header.tsx

Closes https://github.com/webstudio-is/webstudio/issues/3277
As a user I want to be able to see what email my login is using
2. expect xyz

feat: add email to the dashboard menu

---

apps/builder/app/builder/features/settings-panel/resource-panel.tsx

Here switched resource headers to native validation. Now it finally blocks closing variable popover and shows errors. Works even for multiple headers with the same input.name.
Had to workaround InputField cases like ref -> inputRef and event.currentTarget -> inputRef.current.

refactor: use native validation for resource headers

---

apps/builder/app/builder/features/settings-panel/resource-panel.tsx
apps/builder/app/builder/features/settings-panel/variable-popover.tsx

Here refactored name field with native validation
and accessed it with form data in on submit.
Basic zod validation will wllow to avoid issues with missings fields.
Note: review with hidden whitespaces

refactor: switch variable name to native validation

---

apps/builder/app/shared/nano-states/props.ts

Looks like we default system was not in loading resources and showed empty page.

fix: use default system in resources

---

packages/cli/.npmignore

fix: Include .npmrc in cli package

---

apps/builder/app/builder/features/style-panel/shared/color-picker.tsx

Fixes https://github.com/webstudio-is/webstudio/issues/3408
Here fixed the issue with auto converting hex while user typing and improved performance while typing or dragging color.

fix: avoid interfering with user input in color picker

---

apps/builder/app/builder/features/sidebar-left/panels/marketplace/marketplace.tsx
apps/builder/app/builder/features/sidebar-left/panels/marketplace/templates.tsx
apps/builder/app/builder/features/sidebar-left/panels/marketplace/utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3397
Here instead of inserting page content into body I improved bahvior to insert complete page with whole meta and navigate into it.

feat: insert marketplace pages

---

apps/builder/app/shared/page-utils.test.ts
apps/builder/app/shared/page-utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3431
Here improved page name logic to check conflicts in target folder.

fix: append iterator to page when inserting from marketplace

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx

Fixes https://github.com/webstudio-is/webstudio/issues/3432

fix: switch to home page when deleted currently selected page

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx

Form is very big, forgot to add to save.

fix: save "Include in marketplace" switch

---

packages/cli/package.json
packages/cli/src/commands/link.ts
pnpm-lock.yaml

Switched from readline to @clack/prompts package
with more rich ui docorations and better validation.
It should improve UX and @clack/prompts actually can replace both prompts and ora packages, in fact it is smaller than each of these and has builtin types.
https://github.com/webstudio-is/webstudio/assets/5635476/b03174f5-33ef-47a5-90b8-90ad0697c442

feat: improve CLI link command

---

apps/builder/app/shared/copy-paste/plugin-webflow.test.ts
apps/builder/app/shared/copy-paste/plugin-webflow.ts

Added support for Link Block
2. expect xyz

experimental: Paste from webflow 2

---

apps/builder/app/shared/copy-paste/plugin-webflow.test.ts
apps/builder/app/shared/copy-paste/plugin-webflow.ts

More components: Richt Text, Supescript, Subscript, Emphasized, Strong, Section, Container, Quick Stack, VStack, HStack
2. expect xyz

experimental: Paste from Webflow 3

---

apps/builder/app/builder/features/settings-panel/variables-section.tsx

Ref https://github.com/webstudio-is/webstudio/issues/3080
Now user can see how many usages left. It can give some hint where to look. We will explore in the future how to show the list of usages.
Also fixed usage detection on pages.

feat: show usage count when delete variable

---

apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx

fix: Create a new page and mark it as home in the same step

---

apps/builder/app/shared/instance-utils.test.ts
apps/builder/app/shared/instance-utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3468

fix: allow deleting unknown instance without meta

---

apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx

Fixes https://github.com/webstudio-is/webstudio/issues/3481 https://github.com/webstudio-is/webstudio/issues/3473

fix: show error on canvas when collection data is invalid

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/workspace/canvas-iframe.tsx
apps/builder/app/builder/features/workspace/workspace.tsx

This fixes glitches from time to time when
canvas stay blank without loaded data.

fix: render canvas only when data is loaded

---

apps/builder/app/shared/builder-data.ts

Broken since refactoring to loading builder data client side.

fix: pass auth token to data loader

---

packages/react-sdk/src/component-generator.test.ts
packages/react-sdk/src/component-generator.ts

Fixes https://github.com/webstudio-is/webstudio-community/discussions/151
Here fixed the issue with generating conditional collection code for published sites. Added fragment around collection when rendered inside of condition.

fix: generate conditional collection

---

apps/builder/app/builder/builder.tsx

fix: fixes stacking context between style panel and collapsible in pages

---

packages/trpc-interface/src/authorize/project.server.ts

fix: Template clone error

---

apps/builder/app/builder/features/workspace/canvas-iframe.tsx
apps/builder/app/builder/shared/assets/asset-upload.tsx
apps/builder/app/builder/shared/assets/assets-shell.tsx
apps/builder/app/builder/shared/assets/use-assets.tsx
apps/builder/app/canvas/canvas.tsx
apps/builder/app/shared/canvas-api.ts
apps/builder/app/shared/nano-states/canvas.ts
apps/builder/app/shared/sync/sync-stores.ts
apps/builder/package.json
packages/feature-flags/src/flags.ts
pnpm-lock.yaml

This is 1st PR In a series of PR's
Next: Image URL Links upload support.
Image Manager now support files drag/drop
(Images, Fonts etc)
Drag files on image manager see it works.

feat: Image Manager drag/drop suport

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/topbar/topbar.tsx
apps/builder/app/builder/features/workspace/canvas-iframe.tsx
apps/builder/app/builder/features/workspace/workspace.tsx
apps/builder/app/shared/hook-utils/use-interval.ts
packages/design-system/src/components/progress.tsx
packages/design-system/src/index.ts

Closes https://github.com/webstudio-is/webstudio/issues/3520
Before: 
https://github.com/webstudio-is/webstudio/assets/52824/4ba347e6-8994-45c6-bdee-cdd0738539fa
After:
https://github.com/webstudio-is/webstudio/assets/52824/416b4614-cf8d-4b2e-bf34-439fb65d3195
1. reload builder with large amount of data
2. click from dashboard to a project

feat: Builder loading delight

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/shared/assets/asset-upload.tsx
apps/builder/app/builder/shared/assets/assets-shell.tsx
apps/builder/app/builder/shared/assets/use-assets.tsx
apps/builder/app/shared/nano-states/builder.ts

fix: Development mode refersh fix.

---

apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.ts
apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
packages/css-data/src/parse-css.test.ts
packages/css-data/src/parse-css.ts

1. add rendering states e.g. :hover
2. keep the original rules order
3. remove overwritten properties
4. code embed component
2. expect xyz

experimental: Paste from webflow 6

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

- flex -> flex-grow, flex-shrink, flex-basis
- flex-flow -> flex-direction, flex-wrap
Also slightly flatten shorthand extractors
to make it more straightforward.

experimental: support flex shorthands

---

apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
package.json
packages/eslint-config-custom/package.json
pnpm-lock.yaml

Upgraded eslint minor version, plugins and prettier.

build: uprgade eslint and prettier

---

packages/react-sdk/src/core-components.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3473
Somehow lost this fix from other PR

fix: treat collection box as container

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

Added support for the following shorthands
- columns
- column-rule
- list-style

experimental: support columns and list-style shorthands

---

apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.ts
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
packages/css-data/src/parse-css.test.ts
packages/css-data/src/parse-css.ts
packages/css-data/src/property-parsers/background.ts

- show a toast when skipping unsupported elements
- handle shorthands
- RichText test and link inside rich text fixes
2. expect xyz

experimental: Paste from webflow 7

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

experimental: support animation shorthand

---

packages/css-data/src/index.ts
packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

Ref https://github.com/webstudio-is/webstudio/issues/3567

experimental: support transition shorthand

---

apps/builder/app/builder/shared/assets/asset-utils.ts
apps/builder/app/builder/shared/assets/assets-shell.tsx
apps/builder/app/builder/shared/assets/use-assets.tsx
apps/builder/app/routes/rest.assets.$name.tsx
apps/builder/app/shared/builder-api.ts
apps/builder/app/shared/copy-paste/asset-upload.test.tsx
apps/builder/app/shared/copy-paste/asset-upload.ts
apps/builder/app/shared/copy-paste/plugin-markdown.ts
apps/builder/app/shared/nano-states/props.ts
apps/builder/jest.config.js

Markdown paste with images
Take MD from 
https://github.com/webstudio-is/webstudio/pull/3569#issuecomment-2171213517
Paste, see images are uploaded
2. expect xyz

feat: Upload images on copy-paste

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

experimental: support mask and mask-border shorthands

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

- grid-area
- grid-row
- grid-column

experimental: expand grid-area shorthands

---

apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts

Add Webflow image paste support
Copy node with images from webflow
Paste

experimental: Add Webflow image paste support

---

apps/builder/app/routes/builder.$projectId.tsx

fix: After cloning a shared template, buttons are still disabled

---

apps/builder/app/builder/features/topbar/publish.tsx

fix: Domain name and the link is not updated after renaming in publish dialog

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

- offset
- scroll-timeline
- scroll-padding
- scroll-padding-inline
- scroll-padding-block
- scroll-margin
- scroll-margin-inline
- scroll-margin-block

experimental: expand scroll and offset shorthands

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

experimental: support grid and grid-template shorthands

---

apps/builder/app/shared/nano-states/components.ts
apps/builder/app/shared/nano-states/nano-states.ts
apps/builder/app/shared/nano-states/props.ts
apps/builder/app/shared/shim.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/react-sdk/src/hook.ts
packages/sdk-components-react-radix/src/accordion.tsx
packages/sdk-components-react-radix/src/accordion.ws.ts
packages/sdk-components-react-radix/src/collapsible.tsx
packages/sdk-components-react-radix/src/collapsible.ws.ts
packages/sdk-components-react-radix/src/dialog.tsx
packages/sdk-components-react-radix/src/dialog.ws.ts
packages/sdk-components-react-radix/src/navigation-menu.tsx
packages/sdk-components-react-radix/src/navigation-menu.ws.ts
packages/sdk-components-react-radix/src/popover.tsx
packages/sdk-components-react-radix/src/popover.ws.ts
packages/sdk-components-react-radix/src/select.tsx
packages/sdk-components-react-radix/src/select.ws.ts
packages/sdk-components-react-radix/src/sheet.tsx
packages/sdk-components-react-radix/src/sheet.ws.ts
packages/sdk-components-react-radix/src/tabs.tsx
packages/sdk-components-react-radix/src/tabs.ws.ts
packages/sdk-components-react-radix/src/tooltip.tsx
packages/sdk-components-react-radix/src/tooltip.ws.ts

https://discord.com/channels/955905230107738152/1251593079161491637/1251593079161491637
https://dialog-col.staging.webstudio.is/builder/be551fca-b3bc-4750-961a-c0bdc0557506?authToken=3d9f5902-0ecc-4645-ba12-9f7af2f81e09&mode=edit
https://dialog-saas-a7f4v.wstd.work/

fix: Dialog within collection issues

---

packages/generate-arg-types/src/arg-types.ts
packages/sdk-components-react/src/__generated__/image.props.ts
packages/sdk-components-react/src/image.tsx
packages/sdk-components-react/src/image.ws.ts

feat: Add ‘optimize’ property to Image component

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3608

experimental: correctly match unordered shorthands values

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

- container
- contain-intrinsic-size

experimental: expand container shorthands

---

apps/builder/app/builder/features/settings-panel/controls/combined.tsx

fix: Unsupported property type error

---

apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
packages/design-system/src/components/toast.tsx
packages/sdk-components-react/src/html-embed.tsx
packages/sdk-components-react/src/html-embed.ws.ts

1. allow styles on html embed, still display contents by default
2. allow clicking away toasts immediately
3. expect xyz

experimental: Paste from webflow 10

---

apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts

Add assets support
2. expect xyz

chore: Enhance webflow clipboard parsing to support assets

---

packages/css-data/src/shorthands.ts

Here slightly simplified parsing repeated shorthands like transition or background with iterator utility. Now parsers are less error prone.

refactor: simplify parsing repeated shorthands

---

apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts

- support visibility setting
2. expect xyz

experimental: Paste from webflow 13

---

apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

- animation-range
- view-timeline
- caret
- position-try
- overscroll-behavior

experimental: support last shorthands

---

packages/sdk-components-react/src/html-embed.tsx

chore: Fix HTML-Embed test errors

---

packages/sdk-components-react/src/html-embed.test.tsx

fix: HTML-Embed test errors

---

apps/builder/app/builder/features/style-panel/style-layer-utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3675
Already on production
2. expect xyz

fix: Fix transition

---

packages/sdk-components-react/package.json
packages/sdk-components-react/src/html-embed.test.tsx
pnpm-lock.yaml

Looks like we don't really need jest-jsdom for our tests all checks here are just null checks.

build: drop jest-jsdom

---

apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts

Source order specificity in webflow is completely unpredictable. I am just trying to do a wild guess based on testing with relume what would be the right order.
2. expect xyz

experimental: More comboclass fixes

---

fixtures/webstudio-cloudflare-template/package.json
packages/cli/package.json
packages/cli/templates/cloudflare/package.json
pnpm-lock.yaml

build: Update wrangler

---

apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts

Fixed the issue with pasting components with local styles for exmaple quick stack.

experimental: fix local styles when copy from webflow

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx

Ref https://discord.com/channels/955905230107738152/1115982879651016814/1262152122774851675

fix: ignore transparent color when paste gradient

---

packages/css-data/src/parse-css-value.test.ts
packages/css-data/src/parse-css-value.ts

Fixes the issue with pasting images from webflow.

refactor: parse complex aspect ratio as unparsed value

---

apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts

https://discord.com/channels/955905230107738152/1262723546669645865/1262723682032287838
2. expect xyz

fix: Image paste from webflow

---

apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts

Now can be pasted
https://www.relume.io/components/gallery-7
2. expect xyz

fix: Lightbox paste partial support

---

packages/asset-uploader/src/delete.ts

Dashboard thumbnail disappears on asset deletion
Delete any asset see dashboard thumb is still exist

fix: Dashboard thumbnail disappears on asset deletion

---

fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/defaults/app/route-templates/html.tsx

Write environment flag to page meta in load instead of exposing to client.

refactor: merge exclude from search flags

---

apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
apps/builder/app/builder/shared/tree/index.tsx
packages/design-system/src/components/tree/tree-node.tsx

Closes https://github.com/webstudio-is/webstudio/issues/237
Now you can show/hide directly from navigator
1. focus/hover any navigator item
2. show/hide item works as expected
3. in sync with show/hide in settings

feat: Show/hide toggle in navigator

---

fixtures/webstudio-cloudflare-template/.webstudio/data.json
fixtures/webstudio-cloudflare-template/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-cloudflare-template/app/__generated__/[another-page]._index.server.tsx
fixtures/webstudio-cloudflare-template/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-cloudflare-template/app/__generated__/_index.tsx
fixtures/webstudio-cloudflare-template/app/__generated__/index.css
fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[another-page]._index.server.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-functions/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-remix-netlify-functions/app/__generated__/[another-page]._index.server.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
fixtures/webstudio-remix-vercel/.webstudio/data.json

We need at least to test page links in basic fixtures.

refactor: add page link to basic fixture

---

apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx

Previous pr introduced a bug
2. expect xyz

fix: fix validation for selected attributes/properties

---

apps/builder/app/routes/rest.patch.ts
apps/builder/app/shared/context.server.ts
packages/prisma-client/src/prisma.ts

chore: Improve prisma and api debugability

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yml
.devcontainer/library-scripts/docker-in-docker-debian.sh
packages/postgrest/README.md

chore: Add Docker-in-Docker Support for Utilities like Supabase CLI

---

packages/cli/package.json
packages/cli/src/commands/build.ts
packages/cli/src/commands/init-flow.ts
packages/cli/src/config.ts
pnpm-lock.yaml

Closes https://github.com/webstudio-is/webstudio/issues/3763
Added ssg to the list of templates.

feat: support static site generation in cli

---

apps/builder/app/dashboard/projects/project-dialogs.tsx

Here fixed deleting projects with space in the end. Also trimmed spaces in titles when create new projects.

fix: delete projects with space in the end

---

apps/builder/app/builder/shared/sync/sync-server.ts
apps/builder/app/env/env.static.ts
apps/builder/app/routes/rest.patch.ts
apps/builder/app/shared/router-utils/path-utils.ts
packages/jest-config/esbuild-jest.js

Reload if server and client versions do not match on patch
2. expect xyz

feat: Compare server and client versions and prompt for reload.

---

apps/builder/app/builder/features/topbar/publish.tsx
packages/cli/package.json
packages/cli/src/config.ts
packages/cli/src/config.ts-expect.ts
packages/domain/package.json
packages/domain/src/trpc/domain.ts
packages/sdk/src/schema/deployment.ts
pnpm-lock.yaml

Only support without any UI
Corresponding saas
https://github.com/webstudio-is/webstudio-saas/pull/312
2. expect xyz

experimental: Templates support

---

apps/builder/app/routes/rest.assets.$name.tsx
packages/asset-uploader/package.json
packages/asset-uploader/src/db/load.ts
packages/asset-uploader/src/delete.ts
packages/asset-uploader/src/patch.ts
packages/asset-uploader/src/upload.ts
packages/asset-uploader/src/utils/format-asset.ts
packages/postgrest/jest.config.js
packages/postgrest/package.json
pnpm-lock.yaml

Got some experience with using postgrest api.
Tested locally.

refactor: migrate asset uploader to postgrest

---

packages/asset-uploader/src/db/load.ts

This fixes the issue with random fails in fixtures. Need to fix first then submit another PR with fixtures updates.

refactor: sort assets by id

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx

Ref https://discord.com/channels/955905230107738152/1268162090934206494/1268162090934206494
This regressed while refactoring with new parser.

fix: allow to paste multiple gradients at pnce

---

packages/css-data/src/parse-css-value.test.ts
packages/css-data/src/parse-css-value.ts

Added font-family parser to css value parser

refactor: support parsing font-family

---

apps/builder/app/builder/features/topbar/publish.tsx

Can be broken as saas has other non rebased staging PRs
Additionally:

experimental: Download ssg

---

packages/prisma-client/prisma/migrations/20240731170412_create_production_build/migration.sql

Fixed only in local db and forgot to backport this to migration.

refactor: fix create production build migration

---

apps/builder/app/routes/rest.build.$buildId.tsx

https://github.com/webstudio-is/webstudio-saas/pull/315
Fixtures needs to be regenearate in the next PR
2. expect xyz

experimental: Support beautiful file name

---

fixtures/ssg/.webstudio/data.json
fixtures/webstudio-cloudflare-template/.webstudio/data.json
fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
fixtures/webstudio-remix-vercel/.webstudio/data.json

chore: Resync fixtures

---

fixtures/ssg/package.json

fix: Do not fail on prettier Errors during SSG build

---

packages/sdk-components-react/src/image.tsx

Log was only needed temporarily
2. expect xyz

chore: delete info log

---

apps/builder/app/shared/copy-paste/init-copy-paste.ts

Fixes https://github.com/webstudio-is/webstudio/issues/3880
Also cutting  or inserting instances without copy permissions should be not allowed.
Problem was in detecting cut content editable:
```
if (selection?.type === "Range" || selection?.type === "Caret") {
```
1. create multiline text inside paragraph
2. select some lines, cmd/ctrl+x to cut
3. expected: should only cut the text
4. currently: cuts the instnace

fix: when cutting in text editing mode, it should not cut the instance

---

.github/workflows/fixtures-test.yaml

Need to merge into main to play with.
2. expect xyz

chore: Use workflow_run completed event for fixtures

---

fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
fixtures/webstudio-custom-template/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/routes/_index.tsx
packages/cli/templates/defaults/app/route-templates/html.tsx

Looks like I overlooked n8n automatically adds
content-type: application/json to requests.

fix: automatically add json content-type to webhook forms

---

apps/builder/app/builder/features/settings-panel/resource-panel.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
apps/builder/app/builder/features/style-panel/sections/position/position-control.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
apps/builder/app/builder/features/style-panel/shared/style-info.ts
apps/builder/app/builder/features/topbar/publish.tsx
apps/builder/app/routes/$.tsx
apps/builder/app/routes/builder.$projectId.tsx
fixtures/ssg/package.json
package.json
packages/css-data/src/parse-css-value.ts
packages/design-system/src/components/section-title.tsx
pnpm-lock.yaml

New prettier version wraps nullish coalescing with parens when used inside of ternaries.

build: upgrade prettier

---

packages/design-system/src/components/tree/tree-node.tsx

fix: Tree node edit

---

apps/builder/app/builder/features/topbar/share.tsx
apps/builder/app/dashboard/projects/project-dialogs.tsx
apps/builder/app/shared/share-project/share-project-container.tsx
apps/builder/package.json
packages/ai/package.json
packages/css-data/package.json
packages/dashboard/package.json
packages/dashboard/src/db/projects.ts
packages/jsx-utils/package.json
packages/project-build/package.json
packages/project/package.json
packages/react-sdk/package.json
packages/sdk/package.json
pnpm-lock.yaml

Bumped type-fest everywhere to cast DashboardProject view

refactor: migrate dashboard to postgrest

---

apps/builder/app/builder/builder.tsx

chore: make initial value of the logo brightness always at least 30

---

packages/prisma-client/prisma/migrations/20240809220753_tz/migration.sql
packages/prisma-client/prisma/schema.prisma

chore: Add timezone

---

apps/builder/app/builder/builder.tsx

1. optimized for showing continuous progress
2. removed darkening of the logo (user feedback)
3. made side panels same color as canvas to show less busy screen
4. expect xyz

chore: Rewrite loading animation

---

packages/project-build/src/db/build.ts

chore: Fix marketplace loading issue

---

apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx

feat: added ability to search / filter out components

---

apps/builder/app/shared/style-object-model.test.tsx
apps/builder/app/shared/style-object-model.ts

Here reduced the work in every cascade value computation by storing all data in normalized way.
These normalized maps can be created incrementally later.

refactor: store indexed data in style object model

---

apps/builder/package.json
apps/builder/vite.config.ts
pnpm-lock.yaml

In case of hsts errors type `thisisunsafe` in chrome.
Or add never used domains to `/etc/hosts`
2. expect xyz

chore: Enable ssl for local development

---

apps/builder/app/shared/style-object-model.ts

Ref https://github.com/webstudio-is/webstudio/issues/3399 https://github.com/webstudio-is/webstudio/issues/1536
Even less work needed now to compute style.
Turns out since we check each possible style declaration the order of keys is determenistic and already can provide the right order.
Here removed computing specificity and ordering by it. Instead rearranged style declarations lookup.

refactor: drop sorting by specificity

---

apps/builder/app/shared/style-object-model.test.tsx
apps/builder/app/shared/style-object-model.ts

Ref https://github.com/webstudio-is/webstudio/issues/3399 https://github.com/webstudio-is/webstudio/issues/1536
Here added support for selecting specific style source and state when computing styles. Matching states are now treated as less specific.

experimental: support selecting style source and state

---

packages/project/src/db/project.ts

closes #3960
The issue that in prisma we had multi key relation
`project   Project @relation(fields: [projectId, domain], references: [id, domain])`
but in postgrest seems lile this is not working (invetigating)
2. expect xyz

fix: Sometimes publishing status indicator doesn't correspond actual publishing

---

apps/builder/app/builder/shared/commands.ts
apps/builder/app/builder/shared/nano-states/index.ts

Previous pr broke pages switcher in preview
1. switch to preview
2. open pages

chore: fix pages switcher in preview

---

apps/builder/app/builder/features/topbar/menu/menu.tsx

For users to easier discover all the shortcuts, I linked it directly from the menu
2. expect xyz

feat: add keyboard shortcuts link to the menu

---

apps/builder/app/shared/nano-states/props.ts

fix: Collection binding with JSON Variable not working

---

apps/builder/app/builder/features/topbar/domains.tsx
packages/domain/src/db/domain.ts
packages/domain/src/trpc/domain.ts

Here exposed domain id and used it for remove and verify operations to avoid additional roundtrips to db.

refactor: remove and verify domain by id

---

apps/builder/app/routes/rest.ai._index.ts
apps/builder/app/shared/db/canvas.server.ts
fixtures/ssg/.webstudio/data.json
fixtures/webstudio-cloudflare-template/.webstudio/data.json
fixtures/webstudio-custom-template/.webstudio/data.json
fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
packages/project-build/package.json
packages/project-build/src/db/build.ts
pnpm-lock.yaml

Migrated ai to compact format and moved conversion to build endpoint for cli (will be migrated later).

refactor: remove legacy build format from project build

---

apps/builder/app/shared/style-object-model.test.tsx
apps/builder/app/shared/style-object-model.ts

Here added "source" property to computed style decl. It represents a color of property labels.
Improved selected state and style source logic.

experimental: provide style value source in computed style

---

.github/workflows/delete-github-deployments.yml

Tired of deployment messages
https://github.com/orgs/community/discussions/36919
2. expect xyz

chore: Add deployments cleanup workflow

---

apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
apps/builder/app/builder/features/style-panel/sections/list-item.tsx
apps/builder/app/builder/features/style-panel/sections/position/position.tsx
apps/builder/app/builder/features/style-panel/sections/size/size.tsx
apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
apps/builder/app/builder/features/style-panel/shared/use-style-data.ts

No visual or functional changes, just changed the source of computed value.

refactor: migrate select control to style object model

---

apps/builder/app/routes/_ui.(builder).tsx
apps/builder/app/routes/_ui.dashboard.tsx
apps/builder/app/routes/_ui.error.tsx
apps/builder/app/routes/_ui.login._index.tsx
apps/builder/app/routes/_ui.logout.tsx

Page titles were lost
2. expect xyz

fix: Show page titles

---

packages/sdk-components-react/src/time.test.ts
packages/sdk-components-react/src/time.tsx

Date can be in various forms, lets support them all:
1698377386 - A valid 10-digit Unix timestamp (October 26, 2023).
2147483647 - The maximum 32-bit signed integer timestamp (January 19, 2038).
1698377386000 - A valid 13-digit Unix timestamp (October 26, 2023).
9999999999999 - A far future date (November 20, 2286).
2024.10
2. expect xyz

feat: Support multiple types of timestamps in the Time Component

---

apps/builder/app/routes/_ui.(builder).tsx

Cookie Overwriting in Canvas:
Scripts running inside the canvas can add any cookie client-side. There is no way on the server to distinguish whether a cookie was created on the server or client-side. A bad actor can even write a signed cookie by copying it from their own session, making it difficult to identify the source of the cookie.
To protect against cookie overwrites, we set a null session cookie if a user is using an authToken.
This ensures that any existing HttpOnly, secure session cookies cannot be overwritten by client-side scripts
See Storage model https://datatracker.ietf.org/doc/html/rfc6265#section-5.3
If the cookie store contains a cookie with the same name,
domain, and path as the newly created cookie:
...
If the newly created cookie was received from a "non-HTTP"
API and …

chore: Protect session cookies

---

.devcontainer/postinstall.sh

Can't leave without this commands
2. expect xyz

chore: Add gitclean and gitrebase to devcontainer

---

apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
apps/builder/app/builder/features/style-panel/sections/position/position.tsx
apps/builder/app/builder/features/style-panel/sections/size/size.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transform-backface-visibility.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transform-perspective.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx

Straightforward switch in all cases.
Size section can be tested.

experimental: migrate text control to style object model

---

apps/builder/app/routes/builder.$projectId.tsx

Regression with old share link urls
2. expect xyz

fix: fix old share link support

---

apps/builder/app/shared/$resources/sitemap.xml.server.ts

fix: Sitemap resource loading issue

---

apps/builder/app/routes/_ui.login._index.tsx
apps/builder/public/robots.txt

chore: Add SEO support

---

apps/builder/app/dashboard/projects/project-card.tsx
apps/builder/app/dashboard/projects/thumbnail.tsx
apps/builder/app/routes/_ui.dashboard.tsx
apps/builder/package.json
apps/builder/tsconfig.json
pnpm-lock.yaml

chore: Add prefetch dns, add loading indicator to dashboard

---

fixtures/ssg-netlify-by-project-id/.npmrc
fixtures/ssg-netlify-by-project-id/.webstudio/config.json
fixtures/ssg-netlify-by-project-id/.webstudio/data.json
fixtures/ssg-netlify-by-project-id/app/__generated__/$resources.sitemap.xml.ts
fixtures/ssg-netlify-by-project-id/app/__generated__/_index.server.tsx
fixtures/ssg-netlify-by-project-id/app/__generated__/_index.tsx
fixtures/ssg-netlify-by-project-id/app/__generated__/index.css
fixtures/ssg-netlify-by-project-id/app/constants.mjs
fixtures/ssg-netlify-by-project-id/package.json
fixtures/ssg-netlify-by-project-id/pages/+config.ts
fixtures/ssg-netlify-by-project-id/pages/index/+Head.tsx
fixtures/ssg-netlify-by-project-id/pages/index/+Page.tsx
fixtures/ssg-netlify-by-project-id/pages/index/+data.ts
fixtures/ssg-netlify-by-project-id/renderer/+onRenderClient.tsx
fixtures/ssg-netlify-by-project-id/renderer/+onRenderHtml.tsx
fixtures/ssg-netlify-by-project-id/tsconfig.json
fixtures/ssg-netlify-by-project-id/vike.d.ts
fixtures/ssg-netlify-by-project-id/vite.config.ts
packages/http-client/src/index.ts
pnpm-lock.yaml

**✅🔍 Review per commit!!! ✅🔍**
We missed this bug because our CLI has two different sync methods:
1. Sync by buildId - This one works fine.
2. Sync by projectId - broken
This PR contains:
1. Fix
2. Fixture with sync by projectId  
4. expect xyz

fix: CLI, CORS does not allow synchronization in certain scenarios

---

packages/sdk-components-react-radix/src/select.tsx

chore: add unused ref to fix the warning

---

apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.stories.tsx
apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.tsx

- test display flex and inline-flex showing flex controls
- test wrap showing align content

experimental: migrate layout section to style object model

---

apps/builder/app/routes/oauth.ws.authorize.tsx

It was possible to use any builder subdomain for redirect_uri. What can cause auth `code` leak.
Not a big deal having pkce but better to avoid as additional security measure.
2. expect xyz

chore: Additional checks for the redirect_uri to avoid authorization code leakage

---

apps/builder/app/builder/features/style-panel/controls/toggle-group/toggle-group-control.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx

Ref https://github.com/webstudio-is/webstudio/issues/4087

fix: delay showing tooltip in toggle group

---

apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
apps/builder/app/builder/features/style-panel/controls/font-weight/font-weight-control.tsx
apps/builder/app/builder/features/style-panel/controls/toggle-group/toggle-group-control.tsx
apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx

Smooth migration, slightly tweaked advanced typography layout.

experimental: migrate typography section to style object model

---

fixtures/ssg/app/constants.mjs
packages/cli/templates/ssg-netlify/app/constants.mjs
packages/cli/templates/ssg-vercel/app/constants.mjs
packages/cli/templates/ssg/app/constants.mjs
packages/image/src/image-loaders.ts
packages/image/src/image-optimize.test.ts
packages/image/src/image-optimize.ts

fix: Disabling image optimize breaks image path

---

packages/project-build/src/shared/marketplace.ts

We want to differentiate page templates and cms templates
2. expect xyz

feat: add integrations section in the marketplace

---

apps/builder/app/builder/features/sidebar-left/panels/marketplace/templates.tsx

Previous change broke insertion of integration templates
2. expect xyz

fix: fix integration templates insertion

---

apps/builder/app/routes/rest.patch.ts
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/project-build/src/db/build.ts
packages/project-build/src/index.ts
packages/project-build/src/shared/graph-utils.test.ts
packages/project-build/src/shared/graph-utils.ts

closes #4111
https://github.com/user-attachments/assets/8bb6ffdc-2e78-45eb-b98b-e697daee822a
Now seems like impossible to save broken project. Tested locally on broken project.

fix: Inserting Slots within Slots from the Marketplace causes infinite loop and crash

---

apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx

main checks are  broken. 
2. expect xyz

chore: Fix prettier check

---

apps/builder/app/builder/features/workspace/workspace.tsx
packages/design-system/src/components/scroll-area.tsx

Closes https://github.com/webstudio-is/webstudio/issues/4128
should fix both: style panel and canvas scrolling
2. expect xyz

fix: Fix scrolling for some users on Windows 10 + Chrome 129

---

apps/builder/app/canvas/collapsed.ts
apps/builder/app/canvas/instance-selected.ts

fix: Collapsed recalculate loop during load

---

packages/react-sdk/src/component-generator.test.tsx
packages/react-sdk/src/component-generator.ts

Here fixed rendering body with bound show prop.

fix: generate hidden body correctly

---

fixtures/ssg-netlify-by-project-id/app/__generated__/_index.tsx
fixtures/ssg/app/__generated__/[another-page]._index.tsx
fixtures/ssg/app/__generated__/_index.tsx
fixtures/webstudio-cloudflare-template/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-cloudflare-template/app/__generated__/_index.tsx
fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml]._index.tsx
fixtures/webstudio-custom-template/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/[another-page]._index.tsx
fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[class-names]._index.server.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[class-names]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[expressions]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/index.css
fixtures/webstudio-remix-vercel/app/routes/[class-names]._index.tsx
fixtures/webstudio-remix-vercel/package.json
packages/cli/src/html-to-jsx.ts
packages/react-sdk/src/component-generator.test.tsx
packages/react-sdk/src/component-generator.ts

fix: User defined class name is not being escaped

---

packages/postgrest/package.json
pnpm-lock.yaml

chore: Upgrade postgrest

---

packages/design-system/src/components/tooltip.stories.tsx
packages/design-system/src/components/tooltip.tsx

fix: Unexpectedly losing focus while editing input fields.

---

apps/builder/app/shared/instance-utils.test.tsx
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/page-utils.ts
packages/css-data/src/parse-css.test.ts
packages/css-data/src/parse-css.ts
packages/sdk/src/instances-utils.test.tsx
packages/sdk/src/instances-utils.ts

Now we have a way to deliver custom properties to user projects.

experimental: support copying root styles from marketplace

---

apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
packages/design-system/src/components/input-field.tsx

Now users can tinker colors in css variables

experimental: show color picker in advanced panel

---

apps/builder/app/canvas/shared/font-weight-support.ts

Using willReadFrequently option makes it 3-5 times faster
2. expect xyz

chore: faster font weight detection

---

packages/react-sdk/src/component-generator.test.tsx
packages/sdk/package.json
packages/sdk/src/scope.ts
pnpm-lock.yaml

fix: Identifier names must not be reserved words

---

@types/content.d.ts
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/shared/client-supports.ts

chore: Advanced properties performance (chrome only)

---

apps/builder/package.json
pnpm-lock.yaml

closes https://github.com/webstudio-is/webstudio-community/pull/191
2. expect xyz

build: Fix migrations

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts

Fixes https://github.com/webstudio-is/webstudio/issues/4196 https://github.com/webstudio-is/webstudio/issues/4237
- fixed z-index scrubbing by rounding integrer number
- fixed background size by fallback to non layers value

fix: some scrub bugs

---

apps/builder/app/builder/features/sidebar-left/panels/pages/social-utils.ts

fix: Some symbols in the page’s ‘Dynamic path’ input cause the builder to crash.

---

apps/builder/app/builder/features/settings-panel/variables-section.tsx

This should clarify the distinction between data variables and css variables for newcomers.

refactor: rename variables to data variables

---

fixtures/webstudio-remix-vercel/.webstudio/data.json
fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-remix-vercel/app/__generated__/[class-names]._index.tsx
fixtures/webstudio-remix-vercel/app/__generated__/index.css
fixtures/webstudio-remix-vercel/package.json
packages/react-sdk/src/component-generator.test.tsx
packages/react-sdk/src/component-generator.ts

closes #3683
Tests and fixtures

fix: Variable bindings on Class don't show on live site

---

packages/sdk-cli/src/generate-stories.ts
packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
packages/sdk-components-react-radix/src/__generated__/label.stories.tsx
packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx

refactor: regenerate radix stories

---

packages/sdk-components-react-remix/src/shared/remix-link.tsx

fix: Incorrect Current Page link state on dynamic pages

---

apps/builder/app/builder/features/style-panel/property-label.tsx

One of the worst thing with our internal theme is I don't know what actual values used for example in theme.spacing[5] without going into theme file.
Here added info about computed value in property tooltip. It computes initial, inherit, unset, currentColor and css variables.

experimental: show computes values in tooltip when alt is pressed

---

apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
apps/builder/app/shared/event-utils.ts
packages/design-system/src/components/combobox.stories.tsx

fix: Style panel style value combobox doesn't close on ESC

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
apps/builder/app/builder/features/style-panel/sections/text-shadows/text-shadows.tsx
apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx
apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx

experimental: support css variables in shadows

---

packages/design-system/src/components/primitives/numeric-gesture-control.ts

Seems like 
closes #4236
For me bug on windows looks a little bit different like a huge scrubbing jumps. But anyway seems like fixed everything described in corresponding issue. 
2. expect xyz

fix: Movement jumps on windows

---

apps/builder/app/shared/instance-utils.test.tsx
apps/builder/app/shared/instance-utils.ts

Fixes https://github.com/webstudio-is/webstudio/issues/4294

fix: allow inserting into textual collection items

---

apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx

closes #4301
closes #4308
2. expect xyz

fix: Hovering over autocomplete ignores actual input value

---

packages/design-system/src/components/primitives/numeric-gesture-control.ts

https://discord.com/channels/955905230107738152/1297002444647170129/1297002444647170129
2. expect xyz

fix: Canvas resize on Linux

---

apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx

Just inifinite loop fix
2. expect xyz

fix: Infininite loop in backgrounds

---

packages/css-data/src/shorthands.test.ts
packages/css-data/src/shorthands.ts

fix: expand border-bottom-left-radius from shorthand

---

apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
apps/builder/app/builder/shared/floating-panel.tsx

Slightly change floating panel "open" state to make it controlled from outside. This is important with form validations.

refactor: control floating panel open state

---

apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
apps/builder/app/builder/features/style-panel/property-label.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx
apps/builder/app/shared/style-object-model.test.tsx
packages/css-data/src/parse-css.test.ts
packages/css-data/src/parse-css.ts
packages/feature-flags/src/flags.ts

Css variables are landed. No need for conditional rendering.

refactor: remove css variables feature flag

---

apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx

Here fixed closing space popover before selecting value from autocomplete with mouse.

fix: select "space" autocomplete with mouse

---

apps/builder/app/builder/features/style-panel/sections/position/inset-control.tsx
apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
apps/builder/app/builder/features/style-panel/sections/space/space.tsx

Here made space and inset controls to remember active properties when open side input.
Test inset and space controls with alt and shift pressed.
https://github.com/user-attachments/assets/c6718245-9426-49ed-91a5-05f83c3ccb88

feat: support editing sides in space and inset controls

---

apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx

Fixes https://github.com/webstudio-is/webstudio/issues/4357

fix: complete css variable properly in code inputs

---

apps/builder/app/builder/features/pages/folder-settings.tsx
apps/builder/app/builder/features/pages/page-settings.tsx
apps/builder/app/builder/features/pages/page-utils.test.ts
apps/builder/app/builder/features/pages/page-utils.ts
apps/builder/app/builder/features/pages/pages.tsx
apps/builder/package.json

Closes https://github.com/webstudio-is/webstudio/issues/403
Now pages and folders can be maintained with drag and drop.
https://github.com/user-attachments/assets/108230ea-95fa-40ac-bbcb-5d0785c5554f

feat: allow drag and drop in pages

---

apps/builder/app/builder/features/footer/breadcrumbs.tsx
apps/builder/app/builder/features/marketplace/templates.tsx
apps/builder/app/builder/features/navigator/navigator-tree.tsx
apps/builder/app/builder/features/pages/page-settings.tsx
apps/builder/app/builder/features/pages/page-utils.ts
apps/builder/app/builder/features/pages/pages.tsx
apps/builder/app/builder/features/settings-panel/variables-section.stories.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.stories.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
apps/builder/app/builder/features/style-panel/sections/position/inset-control.stories.tsx
apps/builder/app/builder/features/style-panel/sections/transitions/transitions.stories.tsx
apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
apps/builder/app/builder/features/style-panel/style-source-section.test.ts
apps/builder/app/builder/features/workspace/workspace.tsx
apps/builder/app/builder/shared/commands.test.ts
apps/builder/app/builder/shared/commands.ts
apps/builder/app/canvas/features/text-editor/text-editor.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/canvas/instance-selection.ts
apps/builder/app/canvas/interceptor.ts
apps/builder/app/canvas/shared/commands.ts
apps/builder/app/shared/awareness.ts
apps/builder/app/shared/copy-paste/plugin-instance.test.ts
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/pages/use-switch-page.ts

For now sync awareness with selected instance selector. Added selectPage and selectInstance utilities to update awareness properly.

refactor: store selected instance in awareness state

---

apps/builder/app/builder/features/command-panel/command-panel.tsx
apps/builder/package.json
packages/design-system/package.json
packages/design-system/src/components/command.tsx
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio/issues/1696
Switch to match sorter for more control over results. Now it will try to match best token in the list of each option.

experimental: fuzzy search tokens

---

apps/builder/package.json
pnpm-lock.yaml

cookie package now has builtin types

refactor: bump cookie

---

.github/pull_request_template.md
apps/builder/app/services/auth.server.ts

chore: Make dev password more escure!

---

packages/trpc-interface/src/authorize/project.server.ts

Adding new template to the dashboard. Getting this queued up and will coordinate with someone to add to .env, though it's okay if this goes out first.
SaaS Landing
5b33acf4-53cf-4f03-8973-d5679772edee
2. expect xyz

chore: Add SaaS template to trpc

---

packages/trpc-interface/src/authorize/project.server.ts

Pet Grooming (Local Services)
909a139b-1f2d-415a-ac90-382fa19fa7d8
2. expect xyz

chore: Add pet grooming template to trpc

---

apps/builder/app/builder/features/topbar/publish.tsx

Cherry pick from release
2. expect xyz

fix: Inifinite pending state for the "Build and download static site" button

---

apps/builder/app/shared/sync-client.test.ts
apps/builder/app/shared/sync-client.ts

Cleaned up api a little and added more tests for nanostores sync object.

refactor: add more tests for nanostores sync object

---

apps/builder/app/builder/features/topbar/builder-mode.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/shared/nano-states/misc.ts

feat: Reorder items in the build menu

---

apps/builder/app/builder/features/navigator/navigator-tree.tsx
apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/editable-block-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
apps/builder/app/builder/shared/commands.ts
apps/builder/app/canvas/features/build-mode/block-template.tsx
apps/builder/app/canvas/features/build-mode/block.tsx
apps/builder/app/canvas/features/text-editor/text-editor.tsx
apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
apps/builder/app/canvas/instance-hovering.ts
apps/builder/app/shared/nano-states/canvas.ts
apps/builder/app/shared/sync/sync-stores.ts
packages/react-sdk/src/core-components.ts

chore: Rename editable block component

---

apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
apps/builder/app/builder/features/style-panel/shared/use-style-data.ts

closes https://github.com/webstudio-is/webstudio/issues/4481
2. expect xyz

feat: Reset any css value when user deletes the input and hits enter

---

apps/builder/app/builder/builder.tsx
apps/builder/app/builder/features/marketplace/marketplace.tsx
apps/builder/app/builder/features/pages/pages.tsx
apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
apps/builder/app/builder/features/workspace/workspace.tsx
apps/builder/app/builder/shared/extended-sidebar-panel.tsx
apps/builder/app/shared/nano-states/misc.ts
packages/design-system/src/components/toast.tsx

fix: Show extended panels

---

apps/builder/app/builder/features/pages/page-settings.tsx
apps/builder/app/builder/features/pages/pages.tsx
apps/builder/app/builder/sidebar-left/sidebar-left.tsx

ref #3994
https://discord.com/channels/955905230107738152/1313579337940996096/1313591871926308914
2. expect xyz

feat: Disable AI and Page Settings editing in Content Mode

---

apps/builder/app/canvas/features/text-editor/interop.test.ts
apps/builder/app/canvas/features/text-editor/interop.ts
apps/builder/app/canvas/features/text-editor/text-editor.tsx
apps/builder/app/shared/awareness.ts
apps/builder/app/shared/sync/sync-stores.ts

Same as #4505 but supports just created links too
ref #3994
2. expect xyz

feat: Support new link selection in the text editor

---

apps/builder/app/builder/features/components/components.tsx
apps/builder/app/builder/features/topbar/builder-mode.tsx

cherry pick from release
2. expect xyz

fix: Hide content mode and component  under feature flag

---

apps/builder/app/builder/features/pages/page-settings.tsx
apps/builder/app/builder/features/project-settings/project-settings.tsx
apps/builder/app/builder/shared/code-editor-base.tsx

ref #3994
+ disable edit project settings
2. expect xyz

feat: Allow page clone in Content Edit mode

---

apps/builder/app/builder/features/topbar/builder-mode.tsx
apps/builder/app/shared/nano-states/misc.ts
packages/design-system/src/components/focus-ring.ts
packages/design-system/src/components/toolbar.stories.tsx
packages/design-system/src/components/toolbar.tsx

feat: Add new button mode switch button

---

apps/builder/app/canvas/instance-selected.ts
apps/builder/app/shared/debug-track.ts

fix: Reduce amount of draw on resize 

---

apps/builder/app/builder/features/navigator/navigator-tree.tsx
apps/builder/package.json
packages/design-system/package.json
pnpm-lock.yaml

Ref https://github.com/webstudio-is/webstudio/issues/3994
- upgraded pragmatic-drag-and-drop
- fixed extra level in collections and slots
- render placeholder properly in content mode

experimental: support navigator dnd in content mode

---

apps/builder/app/canvas/instance-selected.ts

Removes display etc fast switching changes on instance change. 
2. expect xyz

fix: Fast switch between selected instances

---

apps/builder/app/builder/features/navigator/navigator-tree.tsx
apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/matcher.test.tsx
apps/builder/app/shared/matcher.ts
packages/react-sdk/src/core-components.ts

- fixed dropping into non-container instances (like image)
- fixed dropping instances from another block

fix: navigator dnd bugs

---

apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
packages/design-system/src/components/combobox.tsx

I'm afraid that fix can introduce new bugs.
Must be very carefully tested.
Also fixed jumps
https://github.com/user-attachments/assets/33af39d4-7ac1-4eb7-8c49-c474f6a9aae7
2. expect xyz

fix: Combo mouse select is not working

---

apps/builder/app/builder/features/workspace/canvas-iframe.tsx
apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/apply-scale.ts
apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/collaborative-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.stories.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
apps/builder/app/builder/shared/nano-states/index.ts
apps/builder/app/canvas/canvas.tsx
apps/builder/app/canvas/scrollbar-width.ts
apps/builder/app/shared/sync/sync-stores.ts

Playground
https://p-183a0702-0620-49ac-84b6-066dbce1d300-dot-fix-outline.development.webstudio.is/
todo:
2. expect xyz

fix: Ensure outline stays within canvas bounds

---

packages/design-system/src/components/primitives/dnd/use-drag.ts

fix: Pressing Escape during component dragging makes the canvas unselectable.

---

packages/design-system/src/components/ai-command-bar/command-bar-button.tsx

AI Button  in the AI toolbar got into elliptic shape by accident
2. expect xyz

fix: fix ai button aspect ratio

---

apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx

https://discord.com/channels/955905230107738152/1115982879651016814/1316758494191419393
2. expect xyz

fix: CSS Select menu jumping

---

apps/builder/app/builder/features/style-panel/style-source-section.test.ts
apps/builder/app/builder/features/style-panel/style-source-section.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-badge.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-control.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
packages/react-sdk/package.json
packages/react-sdk/src/components/component-meta.ts
packages/react-sdk/src/embed-template.test.tsx
packages/react-sdk/src/embed-template.ts
pnpm-lock.yaml

We stopped using them long time ago. Better remove now.

refactor: drop preset tokens

---

packages/react-sdk/src/core-components.ts

Forgot we have markdown embed. Now everything should work well.

fix: descendants constraint

---

apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx

fix: Instance outline is rendered above style panel

---

apps/builder/app/canvas/features/text-editor/text-editor.tsx

experimental: Pressing Enter within an empty list item deletes the empty item

---

packages/react-sdk/src/components/component-meta.ts
packages/react-sdk/src/core-components.ts
packages/sdk-components-react/src/blockquote.ws.ts
packages/sdk-components-react/src/heading.ws.ts
packages/sdk-components-react/src/list-item.ws.ts
packages/sdk-components-react/src/list.ws.ts
packages/sdk-components-react/src/paragraph.ws.ts
packages/sdk-components-react/src/text.ws.ts
packages/sdk-components-react/src/time.ws.ts

1. Rename Text category to Typography
2. Move Content Block to typography
3. move Time to a standalone new "Localization" category
4. move Media section next after Typography
2. expect xyz

chore: Improved components list organization

---

apps/builder/app/canvas/canvas.tsx
packages/sdk-components-react-radix/package.json
packages/sdk-components-react-radix/src/label.template.tsx
packages/sdk-components-react-radix/src/label.ws.ts
packages/sdk-components-react-radix/src/shared/proxy.ts
packages/sdk-components-react-radix/src/shared/theme.ts
packages/sdk-components-react-radix/src/templates.ts
packages/template/src/css.test.ts
packages/template/src/css.ts
pnpm-lock.yaml

- added radix templates to components panel
- support interpolations in css tagged template
- added theme with static values

refactor: rewrite radix label template with jsx

---

packages/sdk-components-react-radix/src/dialog.template.tsx
packages/sdk-components-react-radix/src/dialog.ws.ts
packages/sdk-components-react-radix/src/popover.template.tsx
packages/sdk-components-react-radix/src/popover.ws.ts
packages/sdk-components-react-radix/src/templates.ts
packages/sdk-components-react-radix/src/tooltip.template.tsx
packages/sdk-components-react-radix/src/tooltip.ws.ts

refactor: rewrite popover and tooltip templates with jsx

---

apps/builder/app/builder/features/topbar/domains.tsx
apps/builder/app/builder/features/topbar/publish.tsx

closes https://github.com/webstudio-is/webstudio/issues/4562
2. expect xyz

fix: fix check icon size in publish dialog

---

apps/builder/app/canvas/shared/styles.ts

probably somehow related to #4448
define --color variable at :root and on current element.
See background or color preview on the current element. 

fix: Fix preview on css variables defined on the current element

---

.github/workflows/fixtures-test.yml

build: Fix build

---

apps/builder/app/canvas/interceptor.ts

Fixes https://github.com/webstudio-is/webstudio/issues/4096

fix: submit forms from a page inside of folder

---

packages/react-sdk/src/css/css.test.tsx
packages/react-sdk/src/css/css.ts
packages/sdk-cli/package.json
packages/sdk-cli/src/generate-stories.ts
packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
packages/sdk-components-react-radix/src/__generated__/label.stories.tsx
packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
packages/sdk-components-react-radix/src/accordion.template.tsx
packages/sdk-components-react-radix/src/checkbox.tsx
pnpm-lock.yaml

Reimplemented generate-stories command in sdk-cli
to not rely on sdk components and load metas
and templates dynamically according to files convention.

refactor: generate radix stories from templates

---

packages/sdk-components-react/src/youtube.template.tsx

fix: Fix typos in the YouTube component

---

apps/builder/app/builder/features/topbar/builder-mode.tsx

closes https://github.com/webstudio-is/webstudio/issues/4647
2. expect xyz

fix: hide pages when switching to preview mode via topbar button

---

apps/builder/app/builder/shared/commands.test.tsx
apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
apps/builder/app/shared/copy-paste.test.tsx
apps/builder/app/shared/copy-paste/asset-upload.test.tsx
apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
apps/builder/app/shared/instance-utils.test.tsx
apps/builder/app/shared/matcher.test.tsx
apps/builder/app/shared/style-object-model.test.tsx
packages/sdk/src/instances-utils.test.tsx
packages/sdk/src/resources-generator.test.tsx
packages/template/src/jsx.ts

Here replaced renderJsx with renderData everywhere and refreshed copy paste tests so they not break CI occasionally. Will help with writing tests for global variables.

refactor: refresh copy paste tests

---

apps/builder/app/shared/instance-utils.test.tsx
apps/builder/app/shared/matcher.test.tsx
packages/react-sdk/src/component-generator.test.tsx
packages/template/src/jsx.test.tsx
packages/template/src/jsx.ts

Added full resource configuration in templates.
Will be useful for testing.

refactor: support resources in jsx templates

---

packages/design-system/src/components/scroll-area.tsx

Navigator will get horizontal scrollbars when necessary.
2. expect xyz

fix: fix horizontal scrolling in navigator

---

apps/builder/app/builder/features/style-panel/style-source-section.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx

[Discussion](https://discord.com/channels/955905230107738152/1334251272127119430/1335002117961678948) 
Difference between delete and remove is too subtle. Detach is clearer
2. expect xyz

feat: Rename "remove" to "detach" in token menu

---

apps/builder/app/builder/features/inspector/inspector.tsx
apps/builder/app/builder/features/settings-panel/variables-section.tsx
apps/builder/app/builder/features/style-panel/property-label.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
apps/builder/app/builder/features/style-panel/shared/style-section.tsx
apps/builder/app/builder/features/style-panel/style-panel.tsx
apps/builder/app/builder/features/topbar/topbar.tsx
apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
apps/builder/app/builder/shared/client-settings/settings.ts
apps/builder/app/builder/shared/collapsible-section.tsx
apps/builder/app/builder/shared/commands.ts
packages/design-system/src/components/kbd.tsx
packages/design-system/src/components/menu.tsx

- implements accordion pattern
- adds a dropdown switch
2. expect xyz

experimental: Style panel focus mode

---

apps/builder/app/builder/features/settings-panel/curl.ts
apps/builder/package.json
pnpm-lock.yaml

The project migrated to the new name.
No changes.

refactor: replace ultraflag with @bomb.sh/args

---

fixtures/webstudio-features/.webstudio/data.json
fixtures/webstudio-features/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-features/app/__generated__/[expressions]._index.tsx
fixtures/webstudio-features/package.json
packages/cli/src/prebuild.ts

Another placed missed global variables support.

fix: generate global variables for published sites

---

apps/builder/app/builder/features/style-panel/style-source/style-source-control.tsx

Select the state, see it stays selected
2. expect xyz

fix: Fix token state selector

---

apps/builder/app/builder/features/style-panel/style-source/style-source-control.tsx

fix: Refix bigger clickable surface for local style source

---

packages/cli/src/prebuild.ts

XML body did not have any children and the logic had runtime error.

fix: handle empty xml

---

apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
apps/builder/app/builder/features/style-panel/sections/filter/filter.tsx
apps/builder/app/builder/features/style-panel/sections/list-item.tsx
apps/builder/app/builder/features/style-panel/sections/sections.ts
apps/builder/app/builder/features/style-panel/sections/transforms/transform-and-perspective-origin.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
apps/builder/app/builder/features/style-panel/shared/style-section.tsx

Migrated to hyphenated properties all left sections
- filter
- list item
- transforms
- typography

refactor: hyphenate all sections

---

apps/builder/app/builder/features/topbar/domains.tsx
apps/builder/app/builder/features/topbar/publish.tsx

fix: format publishing tooltip properly

---

apps/builder/app/builder/features/navigator/css-preview.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
apps/builder/app/builder/features/style-panel/shared/model.tsx
apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
apps/builder/app/builder/shared/collapsible-section.tsx
apps/builder/app/builder/shared/css-editor/css-editor-context-menu.tsx
apps/builder/app/builder/shared/css-editor/css-editor.stories.tsx
apps/builder/app/builder/shared/css-editor/css-editor.tsx
apps/builder/app/shared/style-object-model.ts
packages/design-system/src/components/grid.tsx
packages/sdk/src/schema/animation-schema.ts

experimental:  Use css editor in keyframes

---

apps/builder/app/builder/features/inspector/inspector.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animations-select.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/subject-select.tsx
apps/builder/app/builder/features/settings-panel/props-section/props-section.stories.tsx
apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
apps/builder/app/builder/features/settings-panel/settings-panel.tsx
apps/builder/app/shared/form-utils/use-ids.ts
packages/sdk/src/schema/styles.ts

experimental: Live animation setting update

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx

fix: Shrinking animation panel when new keyframes are added

---

apps/builder/app/builder/features/components/components.tsx
apps/builder/app/builder/features/topbar/publish.tsx

Now user will see error when try to publish project with pro features.

refactor: forbid publishing pro features

---

apps/builder/app/builder/features/topbar/publish.tsx

fix: fix wording in the toast

---

apps/builder/app/builder/features/pages/page-settings.tsx
apps/builder/app/builder/features/project-settings/section-general.tsx
apps/builder/app/builder/features/settings-panel/variable-popover.tsx
apps/builder/app/builder/features/topbar/publish.tsx
packages/sdk/src/expression.test.ts
packages/sdk/src/expression.ts

We decided to not block testing of pro features in builder and block only publishing projects with these features.

feat: allow using pro features in builder for free users

---

apps/builder/app/shared/instance-utils.ts
apps/builder/app/shared/matcher.test.tsx
apps/builder/app/shared/matcher.ts
packages/sdk-components-animation/src/animate-children.ws.ts
packages/sdk-components-animation/src/animate-text.ws.ts
packages/sdk/src/schema/instances.ts

experimental: Add banner to Animate components

---

.github/workflows/main.yml
@types/navigator.d.ts
packages/sdk-components-animation/tsconfig.json

https://issues.chromium.org/issues/403708813
Type in Debug Console 
`ScrollTimeline`
for Chrome  134.0.6998.164  >= version  >= 134.0.6998.0 
This would be non native code

experimental: Fix chrome 134 regression bug

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/new-view-animations.ts

experimental: Animation descriptions

---

README.md

Fixes https://github.com/webstudio-is/webstudio/issues/5090

docs: fix discord link in readme

---

apps/builder/app/routes/rest.patch.ts

tested 
```
select "createdAt", "updatedAt" from "Build" where "projectId" = '2d1d1e10-c20b-4061-a02a-ee570179c60c';
```
Result
```
2025-03-10 18:06:45.848+00 | 2025-04-05 10:55:58.263+00
```
2. expect xyz

fix: Update Build updatedAt on patch

---

apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
packages/react-sdk/src/component-generator.ts
packages/react-sdk/src/props.ts
packages/react-sdk/src/runtime.ts
packages/sdk-components-react-radix/src/accordion.tsx
packages/sdk-components-react-radix/src/navigation-menu.tsx
packages/sdk-components-react-radix/src/tabs.tsx
packages/sdk-components-react/src/box.tsx
packages/sdk-components-react/src/heading.tsx
packages/sdk-components-react/src/text.tsx
packages/sdk/src/runtime.ts

Slowly moving stuff out of react-sdk

refactor: move index property to sdk

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx
packages/sdk/src/index.ts
packages/sdk/src/schema/animation-schema.ts
packages/tsconfig/base.json

experimental: Animations. Entry animations support

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx

experimental: Fix inset reset (onAbort is called on blur)

---

packages/sdk-components-animation/tsconfig.json

experimental: Reload animations on custom properties change

---

.github/workflows/main.yml

experimental: Animations, disable BFCache in Chrome 134 and FF

---

packages/sdk-components-react/src/youtube.tsx

fix: Youtube mute and other options

---

.github/workflows/main.yml
fixtures/webstudio-features/.webstudio/data.json
fixtures/webstudio-features/app/__generated__/$resources.sitemap.xml.ts
fixtures/webstudio-features/app/__generated__/[_route_with_symbols_]._index.tsx
fixtures/webstudio-features/app/__generated__/[animations]._index.tsx
fixtures/webstudio-features/app/__generated__/[class-names]._index.tsx
fixtures/webstudio-features/app/__generated__/[content-block]._index.tsx
fixtures/webstudio-features/app/__generated__/[duration]._index.server.tsx
fixtures/webstudio-features/app/__generated__/[duration]._index.tsx
fixtures/webstudio-features/app/__generated__/[expressions]._index.tsx
fixtures/webstudio-features/app/__generated__/[form]._index.tsx
fixtures/webstudio-features/app/__generated__/[head-tag]._index.tsx
fixtures/webstudio-features/app/__generated__/[heading-with-id]._index.tsx
fixtures/webstudio-features/app/__generated__/[nested].[nested-page]._index.tsx
fixtures/webstudio-features/app/__generated__/[radix]._index.tsx
fixtures/webstudio-features/app/__generated__/[resources]._index.tsx
fixtures/webstudio-features/app/__generated__/[sitemap.xml]._index.tsx
fixtures/webstudio-features/app/__generated__/[text-duration]._index.server.tsx
fixtures/webstudio-features/app/__generated__/[text-duration]._index.tsx
fixtures/webstudio-features/app/__generated__/_index.tsx
fixtures/webstudio-features/app/__generated__/index.css
fixtures/webstudio-features/app/routes/[duration]._index.tsx
fixtures/webstudio-features/app/routes/[text-duration]._index.tsx
fixtures/webstudio-features/package.json

experimental: Various Animation fixes

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
apps/builder/app/builder/features/settings-panel/props-section/animation/animation-transforms.tsx
apps/builder/app/builder/shared/transforms.tsx

Here added UI for transform and opacity properties to keyframe configuration.

experimental: add keyframe transforms

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx

experimental: fix typo

---

fixtures/webstudio-features/app/__generated__/[animations]._index.tsx
fixtures/webstudio-features/app/__generated__/[text-duration]._index.tsx
fixtures/webstudio-features/app/__generated__/index.css
packages/sdk-components-animation/src/animate-text.tsx
packages/sdk-components-animation/src/animate-text.ws.ts
packages/sdk-components-animation/src/stagger-animation.tsx
packages/sdk-components-animation/src/stagger-animation.ws.ts

experimental: Allow styling staggering and text animations

---

packages/react-sdk/src/context.tsx

fix: Context onError type fix

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx

experimental: Animation Panel Label Tolltips

---

packages/sdk-components-animation/src/animate-children.ws.ts
packages/sdk-components-animation/src/animate-text.ws.ts
packages/sdk-components-animation/src/stagger-animation.ws.ts
packages/sdk-components-animation/src/video-animation.ws.ts

experimental: Icon and order for video animation

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx

experimental: Use ordinary range UI for scroll animations

---

apps/builder/app/builder/shared/assets/asset-upload.tsx
apps/builder/app/builder/shared/image-manager/image-manager.tsx

Now Video elelment shows only video files. 
2. expect xyz

experimental: Video uploads fixes accept support

---

packages/sdk-components-animation/src/video-animation.ws.ts

experimental: Fix Video Animation Styles

---

apps/builder/app/shared/data-variables.test.tsx
apps/builder/app/shared/data-variables.ts

Before parent collection item on nested collection was rebind with nested collection item which lead to broken state
```
<Collection id="parent" data={[]} item="collectionItem">
<Collection id="nested" data={collectionItem} item="collectionItem">
</Collection
</Collection
```
```
collection.map(collectionItem =>
// oops
collectionItem2.map(collectionItem2 => {
})
})
```

fix: rebind nested collection item properly

---

packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
packages/sdk-components-react-radix/src/accordion.template.tsx

Mistyped when refactored with new templates

fix: generate proper rotate variable for accordion

---

apps/builder/app/builder/features/breakpoints/confirmation-dialog.tsx

feat: Use destructive button when deleting breakpoints

---

apps/builder/app/builder/features/style-panel/sections/size/size.tsx
packages/css-data/src/__generated__/property-value-descriptions.ts

Rewrite overflow clip and hidden description and move it to css-data
2. expect xyz

fix: Rewrite overflow clip and hidden description 

---

packages/sdk/src/core-templates.tsx

So we can know how well this is working
2. expect xyz

chore: Add add via=badge parameter to made with webstudio

---

packages/domain/src/trpc/domain.ts

We detect cname flattening by registrar though when nameservers are rerouted legal registar stays the same.
So instead we check if nameservers are cloudflare and can use cname flattening.

fix: detect registrar by nameservers

---

apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx

Ref https://discord.com/channels/955905230107738152/1401100781989531718/1401100781989531718
https://github.com/user-attachments/assets/7d6c0a6e-5e92-4d90-84e2-460824675d99

fix: let user type "auto" into duration input

---

README.md

Add proprietary license for animations engine
2. expect xyz

chore: Add the note for animation engine license

---

apps/builder/app/builder/shared/assets/asset-upload.tsx
apps/builder/app/builder/shared/assets/assets-shell.tsx
apps/builder/package.json
packages/design-system/package.json
pnpm-lock.yaml

Fixes https://github.com/webstudio-is/webstudio/issues/5326

fix: show proper error when dropping a too big file

---

apps/builder/app/dashboard/dashboard.tsx

feat: Add Inception link to the dashboard
