- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-vercel/.webstudio/data.json
Reverting back to the logic that during duplication uses '/test' to '/copy-1/test' because it also supports '/test/*' and '/test/name*'
2. expect xyz
> fix: support wildcards when duplicating pages

- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/builder/shared/html-editor.tsx
Ref https://github.com/webstudio-is/webstudio/issues/2956
Here fixed the issue with scrolling code editor
by setting height on editor instead of content.
> fix: fix code editor scrolling

- apps/builder/app/shared/instance-utils.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
- packages/css-engine/src/schema.ts
This PR adds a new `FunctionValue` type to the `css-engine`. This helps in defining `blur(5px)`, `drop-shadow(10px 10px 10px red)` and `translate3d(42px, -62px, -135px)` type of functions more clearly. There is a flag in the `FunctionValue` with the name `seperator` which defined that type of separator to be used  while passing the function arguments. 
In `css-tree` they use a `Operator` node. But we don't have something similar to that in the schema. So, using a new flag to define it.
> feat: Add `FunctionValue` to the css-engine to describe css functions effeciently.

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- apps/builder/app/shared/error/toast-error.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/share-project/share-project-container.tsx
- apps/builder/app/shared/share-project/share-project.stories.tsx
- apps/builder/app/shared/share-project/share-project.tsx
- apps/builder/app/shared/sync/sync-stores.ts
- packages/authorization-token/src/db/authorization-token.ts
- packages/authorization-token/src/index.server.ts
- packages/authorization-token/src/index.ts
- packages/authorization-token/src/trpc/authorization-tokens-router.ts
- packages/prisma-client/prisma/migrations/20240308131249_add-token-rights/migration.sql
- packages/prisma-client/prisma/schema.prisma
Pro users can add additional permissions to auth tokens
In case of cloning is disabled user will see
In case of copying
2. expect xyz
> feat: Add ability to disable clone and copy for view links

- apps/builder/app/shared/share-project/share-project.tsx
> fix: Set disabled labels on permission checkboxes

- packages/image/src/image-optimize.test.ts
- packages/image/src/image-optimize.ts
- packages/image/src/image.tsx
https://discord.com/channels/955905230107738152/1217108594735190066
Images should either have an alt text or be decorative. By adding an empty alt by default, they are becoming decorative by default which seems logical, because if you can't explain what's in the picture to assistive tools, then they should be ignoring that picture
https://www.w3.org/WAI/tutorials/images/decorative/
1. by default see alt is empty (<img alt> is the same as. <img alt="">)
2. when set by the user its applied
> fix: Use empty alt attribute by default

- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
When uploading wrong proportions they should still render okay
2. expect xyz
> fix: Fix marketplace form thumb rendering for wrong proportions

- packages/design-system/src/components/tooltip.stories.tsx
- packages/design-system/src/components/tooltip.tsx
> fix: detect scroll collision for form error tooltips

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-vercel/.webstudio/data.json
Here replaced Path Params variable with system variable in builder. Now system always prefilled with `{ params: {}, search: {} }` to let user always see the structure and not get confused with undefined.
> experimental: switch to system variable for params in builder

- apps/builder/app/routes/trpc.$.ts
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/marketplace/router.server.ts
- packages/trpc-interface/src/context/context.server.ts
- packages/trpc-interface/src/context/router.server.ts
- packages/trpc-interface/src/index.server.ts
trpc procedures can be cached if wrapped with
```js
const cacheMiddleware = createCacheMiddleware(60 * 3); // 60 * 3 = 3 minutes cache
const cachedProcedure = procedure.use(cacheMiddleware);
```
Implementation supports trpc batching.
1.  If any of calls inside trpc batch is not cacheable - nothing will be cached.
2. If all trpc batch calls can be cached then the least max age among all calls is selected for caching
Open marketplace, see trpc request has cache headers, see trpc request has cache HIT from vercel or cloudflare
> feat: TRPC caching support

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/shared/url-pattern.ts
- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/shared/nano-states/nano-states.ts
Here added support for navigating to dynamic paths in preview mode by using URLPattern matcher. Matched params are filled into address bar to simplify accessing dynamic pages without manually entering params.
> experimental: switch matched dynamic paths

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/shared/nano-states/props.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/resources-generator.test.ts
- pnpm-lock.yaml
Our code generation with jsep has a big problem of not preserving parenthesis entered by user. And jsep is not able to provide the information.
As a solution I suggest to switch parser to acorn. It is 10 times bigger than jsep but provides more strict parsing with location info for every node. Here I use it to transpile simply with string manipulation which does not touch spaces or parenthesis entered by user.
> refactor: transpile expression without code generation

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/shared/instance-utils.ts
- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/index.css
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
Here switched the rest of usages to acorn based expressions. Added getExpressionIdentifiers utility to extract used variables names to avoid using transpiler replaceVariable callback for this.
> refactor: switch to acorn expressions everywhere

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/features/project-settings/section-redirects.tsx
- apps/builder/app/builder/features/project-settings/utils.ts
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/overview.tsx
- packages/design-system/src/components/select.stories.tsx
- packages/design-system/src/components/select.tsx
- packages/project-build/src/shared/marketplace.ts
1. added description to show property (People are often confused why breakpoints have no impact on this)
2. added descriptions to right sidebar tabs
3. added descriptions to marketplace tabs
4. show marketplace category descriptions in select box
5. added ability to select component to render the hint/description
> feat:  add more descriptions

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/__templates__/route-template.tsx
- packages/sdk/src/page-utils.test.ts
- packages/sdk/src/page-utils.ts
Here added support for search params in builder and compiler.
system.search contains an object computed from url.
In generated website loaders compute search params which allows to access them in resources.
In builder links with search params populate system.search.
<br>
<br>
> experimental: support search params in expressions

- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/stores.ts
Closes https://github.com/webstudio-is/webstudio/issues/2988
When a token value is modified, the change will be immediately visible across all N instances using the same token
Create token, use it on 2 instances, change token styles, local styles etc to see it work
> fix: Style updates on all instances upon change

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/inspector-edits.ts
- apps/builder/app/canvas/shared/inert.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
closes #2998
Also fixes name edits etc.
The same issue with radix as we had in the past, focus lock on any mutation inside dialog aquires focus. 
And we have no good way to prevent programmatic focus inside iframe.
2. expect xyz
> fix: HTML Embed Code editor inside Dialog Content looses focus

- apps/builder/app/builder/features/style-panel/sections/shared/value-text.tsx
- packages/design-system/src/components/label.tsx
Many don't realize that properties in style panel are hoverable, clickable and even have alt+click for reset function
https://github.com/webstudio-is/webstudio/assets/52824/5080c9ec-5f78-4fef-b498-b4fc577536ad
> feat: Make unset property in style panel visibly interactive

- packages/design-system/src/components/label.tsx
In the previous PR I forgot to stop using default variant when label has no specified variant, because hover effect is only meant for those button labels.
1. open share dialog
2. see the items have no hover effect
> fix: initially label shouldn't have a hover effect

- apps/builder/app/shared/style-object-model.test.ts
- apps/builder/app/shared/style-object-model.ts
Here added currentcolor keyword support. It is case insensitive and resolved as a new "used value", while "computed value" still contains currentcolor.
> experimental: support currentcolor in style object model

- apps/builder/app/shared/style-object-model.test.ts
- apps/builder/app/shared/style-object-model.ts
Here slightly changed how color: currentcolor is treated. Before on color property inherited value was used. Though this didn't handle the case when inherited value is also currentcolor. Here found note in another spec which says color: currentcolor should be interpreted same as inherit keyword.
> experimental: improve color: currentcolor behavior

- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/style-object-model.test.ts
- apps/builder/app/shared/style-object-model.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
- packages/css-engine/src/schema.ts
Here added support for css custom properties in style object model. Added guaranteed-invalid value to schema to represent initial value of custom properties.
> experimental: support custom properties

- apps/builder/app/shared/style-object-model.test.ts
- apps/builder/app/shared/style-object-model.ts
Here improved sorting declared values and computing cascade value. Added support for breakpoints and states. Introduced specificity rules to sort by State-Breakpoint-StyleSource without complicated logic.
> experimental: support breakpoints and states in style object model

- apps/builder/app/shared/style-object-model.test.ts
- apps/builder/app/shared/style-object-model.ts
Here added new "layer" option to specificity
which isolate browser and preset styles into own layeys similar to cascade layers feature from css.
> experimental: support browser and preset styles in style object model

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-layer.tsx
Update: this PR is not fixing it fully, there is still an issue when cleaning up field and pressing arrow down it goes into keywords mode.
@JayaKrishnaNamburu will fix it with the next PR
- Remove keyword values for `transition-delay` and `transition-duration`. Keywords are valid if they are directly applied as individual properties. But when they are used under `transition` shorthand. The `keyword` values actually make the property invalid. For more reference (https://www.w3.org/TR/css-transitions-1/#propdef-transition-duration)
-  Add `draggable` for the  `CSSValueListItem` to show the drag indicator for individual layers.
- Set intermediate values only when the layer is changed.
- test it on …
> fix: Remove keywords for transition delay and duration, enable sorting layers

- fixtures/webstudio-custom-template/package.json
- fixtures/webstudio-remix-netlify-edge-functions/package.json
- fixtures/webstudio-remix-netlify-functions/package.json
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/prebuild.ts
- packages/cli/templates/internal/package.json
Here improved CLI build command to upgrade dependencies in user package.json whenever we change them in template.
For our own dependencies added "internal" template with `workspace:*`
> fix: update package.json dependencies with cli

- apps/builder/app/builder/features/sidebar-left/panels/pages/folder-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
Fixes. https://discord.com/channels/955905230107738152/1223709963025907854
Empty slug is not a slug, it's an absence of one, so there can be any amount of folders with empty slug
1. add 2 folders with empty slug
2. expect no error
> fix: Allow multiple folders to have an empty slug

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- packages/feature-flags/src/flags.ts
- packages/sdk-components-react-remix/src/server-form.ws.ts
Here added new "filters" flag which hides new form component form components panel and renamed server form back to just form until we agree on name.
> experimental: hide new form component behind flag

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- packages/design-system/src/components/select.tsx
This should clarify that Resource is a safe for using private keys inside them.
1. create a variable
2. hover over type options
> feat: add Resource type descriptions to the select box

- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
We were only show matching 5 tokens for no reason at all, why not show user more options as they narrow down the search?
https://discord.com/channels/955905230107738152/1225627427972055112
1. when you see a lit of tokens now you will see up to 50 and it will be scrollable
> feat: Show 50 tokens in style source search

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/project-settings/section-redirects.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/dashboard/dashboard.tsx
- apps/builder/app/dashboard/projects/project-card.tsx
- apps/builder/app/dashboard/projects/projects.tsx
- apps/builder/app/env/env.public.server.ts
- apps/builder/app/env/env.server.ts
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/dashboard._index.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/env-check.js
Here refactored ours envs.
- deleted BUILDER_HOST as unused
- moved PUBLISHER_HOST into loader and shared in UI with atom
> refactor: move publisher host into loader

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.stories.tsx
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/card.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/search-preview.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/social-preview.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/dashboard/dashboard.tsx
- apps/builder/app/dashboard/projects/project-card.tsx
- apps/builder/app/dashboard/projects/projects.tsx
- apps/builder/app/dashboard/projects/thumbnail.tsx
- apps/builder/app/env/env.public.server.ts
- apps/builder/app/routes/$.tsx
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/dashboard._index.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
Here moved IMAGE_BASE_URL and ASSET_BASE_URL env variables into loader. Builder now can access image loader with atom.
> refactor: move image base url into loader

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/folder-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/image-manager/uploading-animation.tsx
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/hook-utils/use-mount.ts
- apps/builder/package.json
- pnpm-lock.yaml
Here replaced react-use utilities with own solutions because could not bundle it with vite. It also had a lot of transitive deps which bloated our bundle and node_modules. Win-win.
> refactor: drop react-use

- apps/builder/env.d.ts
- apps/builder/tsconfig.json
- fixtures/webstudio-custom-template/env.d.ts
- fixtures/webstudio-custom-template/tsconfig.json
- fixtures/webstudio-remix-netlify-edge-functions/env.d.ts
- fixtures/webstudio-remix-netlify-edge-functions/tsconfig.json
- fixtures/webstudio-remix-netlify-functions/env.d.ts
- fixtures/webstudio-remix-netlify-functions/tsconfig.json
- fixtures/webstudio-remix-vercel/env.d.ts
- fixtures/webstudio-remix-vercel/tsconfig.json
- packages/cli/templates/defaults/env.d.ts
- packages/cli/templates/defaults/tsconfig.json
- packages/cli/tsconfig.json
Latest remix template stopped generating additional file for types.
> refactor: replace env.d.ts with tsconfig types

- apps/builder/package.json
- packages/ai/package.json
- packages/ai/src/models/gpt.ts
- packages/trpc-interface/src/shared/client.ts
- pnpm-lock.yaml
Remix Vite no longer polyfills streams and fetch.
Should be safe to drop them.
Stream polyfills broke ai, fetch broke trpc.
> refactor: drop fetch polyfills

- apps/builder/app/builder/features/workspace/canvas-tools/resize-handles.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
closes https://github.com/webstudio-is/webstudio/issues/3117
Now threshold is 3 px, so if you click and move under 3 px, there won't be scrub registered
https://web.descript.com/66aafa2f-3e4c-4e96-b739-171dc7b09e84/afc85
1. scrub any field in style panel 
2. try to move mouse under 3 px and let it go
3. expect no change
> fix: introduce distance threshold before scrub begins to avoid accidental scrub when user clicks

- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.tsx
Closes https://github.com/webstudio-is/webstudio/issues/3132
Only show navigator helper lines on hover
1. open navigator
2. expect helper lines to be only showed when hovering navigator
> feat: Only show navigator helper lines on hover

- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
Close https://github.com/webstudio-is/webstudio/issues/3140
1. open any tab on the left side
2. switch to preview mode
3. expect all tabs to be closed
4. try opening and closing pages from top bar button
> fix: Hide active sidebar tab when switching to preview mode

- packages/design-system/src/components/component-card.tsx
Closes https://github.com/webstudio-is/webstudio/issues/2184
This is quite important - allows user to go over to the next item without being stuck on the tooltip if they happen to hover it
2. expect xyz
> fix: disable hoverable content for tooltips in add components

- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/label.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
Closes https://github.com/webstudio-is/webstudio/issues/3152
1. Slots are different and need a different outline color
2. Use a blue color from design system
3. expect xyz
> feat: Use a green outline color for Slot instances

- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/html-editor.tsx
closes https://github.com/webstudio-is/webstudio/issues/3116
Original reason was to identify syntax errors as user has already been hit by this, I don't think our current syntax highlighter does a good job for css there though,  case study:
```html
<style>
.class {
)
.class1 {
}
</style>
```
> feat: Use html editor for custom code in the project settings

- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
To match the css flex order: flex-basis, grow, shrink
2. expect xyz
> fix: Fix flex child inputs order

- packages/design-system/src/components/tree/tree-node.tsx
Closes https://github.com/webstudio-is/webstudio/issues/3169
Auto scroll navigation item doesn't work when item is hidden 
1. create lots of items in navigator, each with a nested item, see scrollbar
2. click the last item from canvas, the inner one, so its not visible in navigator
3. see navigator didn't scroll item into viewport because it was not open
Navigator needs to open the item it wants to scroll to before scrolling
> fix: Fix scroll into view for the navigator

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- packages/sdk/src/schema/pages.ts
Closes https://github.com/webstudio-is/webstudio/issues/3025
Allow having the same page path if the full path is different through folder slug
Case 1
1. create a folder with slug /1 and another with slug /2
2. create page with path /p in folder 1
3. create page with path /p in folder 2
4. see that this is allowed
Case 2
1. create a foder 1 with empty slug and folder 2 with empty slug
2. create page with path /p in folder 1
3. create page with path /p in folder 2
4. see that this is not allowed
> fix: Allow same page path in different folders if those have a slug

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
Page settings path shows upgrade tooltip to a pro account
2. expect xyz
> fix: Fix upgrade tooltip

- packages/design-system/src/components/section-title.tsx
We have been hestitating adding those because they pollute the screen but on hover only seems like a reasonable compromise
https://github.com/webstudio-is/webstudio/assets/52824/0772d724-358e-44ec-910f-348c96fd1b93
2. expect xyz
> feat: Show chevron on hover in all section titles

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
Here added "Eye" button to inspect variable values in big editor. Useful to preview resource and parameter variables which are not specified by user.
> feat: inspect variable value

- apps/builder/app/builder/features/workspace/canvas-tools/outline/label.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- packages/design-system/src/components/tree/tree-node.tsx
Trying to align the colors with the design system
2. expect xyz
> chore: use navigator colors from ds

- apps/builder/app/builder/shared/code-editor.tsx
Was broken while implementing "inspect variable" feature. asChild pattern used by radix is not very type safe.
> fix: expand code editor when click on maximize button

- apps/builder/app/builder/shared/binding-popover.tsx
- packages/design-system/src/components/primitives/small-button.tsx
Made the bleed option for binding button 
2. expect xyz
> fix: Fix binding button covering too much of the control

- packages/design-system/src/components/select.tsx
Menu is still upper case by default and Select is based on menu styles, but needs to have the right text variant
2. expect xyz
> fix: Don't modify the text case in select boxes

- apps/builder/app/routes/rest.patch.ts
Here enabled patches, map and set in immer which were broken after moving canvas and builder to client side.
> fix: avoid error while running any patch

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/project-settings/project-settings.stories.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/url-pattern.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/src/props.test.ts
- packages/sdk/src/page-meta-generator.test.ts
- packages/sdk/src/schema/pages.ts
Use sdk type for system variable and make it required in pages since it was added to all pages with migration.
> refactor: cleanup system variable

- apps/builder/app/canvas/interceptor.ts
- packages/sdk-components-react-remix/src/remix-form.tsx
Here added support for sending get requests to pages and update search params in preview.
The logic is same we use for links but instead of href search params system is updated with form fields.
This is essential filters feature to support testing without publishing.
Also modified form component to fallback to native form when absolute action is used
to avoid casting it to relative path.
1. create form
2. set current page url
3. add select
4. add button
5. go to preview
6. click the button
7. go to canvas
8. select body
9. inspect system variable
> experimental: support GET forms in preview

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
Closes https://github.com/webstudio-is/webstudio/issues/3203
If DOM parser is available, let it do the parsing and don't rely on csstree if possible for validation
2. expect xyz
> fix: Suppoort min() and other functions in advanced section

- apps/builder/app/shared/share-project/share-project.stories.tsx
- apps/builder/package.json
- packages/authorization-token/package.json
- packages/authorization-token/src/db/authorization-token.ts
- packages/domain/package.json
- packages/domain/src/db/cname-from-user-id.ts
- packages/domain/src/db/domain.ts
- packages/prisma-client/prisma/migrations/20220909124542_builds-data/migration.ts
- packages/project/package.json
- packages/project/src/db/project.ts
- packages/trpc-interface/package.json
- pnpm-lock.yaml
crypto.randomUUID() is globally available in node and browser environments. Uuid package is no longer necessary for our cases.
> refactor: replace uuid with crypto.randomUUID()

- packages/eslint-config-custom/index.js
We should never keep console.log, but use console.info and console.error if we need logging in prod/cli
2. expect xyz
> chore: disable console.log

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
Wrong color was used on the active item 
2. expect xyz
> fix: Fix page settings icon button color

- apps/builder/app/builder/features/breakpoints/width-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
- packages/design-system/src/components/primitives/use-scrub.ts
I just noticed that using scrub on any other things but inputs became less responsive because of the threshold and its not needed anywhere but in the inputs in 2 places
2. expect xyz
> refactor: Only use scrub distanceThreshold on inputs

- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/core/to-property.ts
Seems like unprefixed background-clip: text is supported in all browsers including chrome (since december 2023) and no longer need to have workarounds with var().
Though still left prefix in css engine to have better support for published sites.
> refactor: drop background-clip workarounds

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/shared/nano-states/props.ts
Here fixed the issue with resources not refreshed while editing and clicking on refresh button. Also fixed cached value not restored after closing resource panel.
> fix: save resources on reload

- .github/actions/ci-setup/action.yml
- .github/workflows/build-figma-tokens.yml
- .github/workflows/chromatic.yml
- .github/workflows/cli-r2.yaml
- .github/workflows/cli-test.yml
- .github/workflows/main.yml
- .github/workflows/publish-beta.yml
- .github/workflows/publish.yml
- .github/workflows/re-create-figma-tokens-branch.yml
- .github/workflows/vercel-deploy-staging.yml
- .github/workflows/vis-reg-tests.yml
preview-worker-deployment
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, pnpm/action-setup@v2.2.4, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
2. expect xyz
> build: Update action versions

- apps/builder/app/builder/features/project-settings/section-redirects.tsx
- packages/sdk/src/schema/pages.ts
fixes #3224 
Allow users to set `/` in new-path. So, from any old-path users can redirect to the home page.
1. Go to Project Settings -> redirects.
2. Enter a `old-path` and set the `/` in the new path.
3. Deploy the project
4. And when we use the `old-path` in the URL, the project should take the route to the home page.
> fix: Allow users to redirect to home page in redirects

- packages/design-system/src/components/css-value-list-item.tsx
For some reason the box shadow border of the right panel can not render on top specifically that button when it has a background color defined, inherit solves the issue nicely but WTF.
2. expect xyz
> fix: fix style panel list item covering the border of the panel

- apps/builder/app/builder/shared/expression-editor.tsx
> chore: used wrong component, showed dialog inside dialog

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/project-settings/section-redirects.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/dashboard/projects/project-card.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-cloudflare-template/tsconfig.json
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[sitemap-html]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/routes/template.tsx
- packages/cli/templates/defaults/tsconfig.json
- packages/cli/templates/internal/tsconfig.json
- packages/cli/templates/saas-helpers/tsconfig.json
- packages/sdk-components-react/src/xml-node.tsx
- packages/sdk/src/schema/pages.ts
review per commit.
- Add system.url.origin to the props, rename publishedUrl -> publishedOrigin
- Add system.url.origin to the published sites
Example on published site
https://saas-sitemapxml-x1g2n.wstd.work/
Example on builder
We use because as of now system is not available on canvas
2. expect xyz
> feat: Add system.origin

- packages/sdk-components-react/src/code-text.tsx
Initially we allowed using any component inside code text and now we need to keep backwards compatibility because its not easy to migrate that to pure text.
1. would need to find any old instance with code text that has other instances inside
2. see that it still works
3. override it with new code property
> fix: add backwards compatibility for children in code text

- apps/builder/app/shared/share-project/share-project.tsx
1. You couldn't type space at the end of the shared link name 
2. When clicking outside it would save the value
3. expect xyz
> fix: Fix share dialog saving behavior

- apps/builder/app/canvas/interceptor.ts
When a path leads to a nested page inside folders, we were not building a full path with folders
1. create a link to a subpage from a folder
2. open preview mode
3. click on a link - expect it to switch
4. works when link is to a page from the root
> fix: Canvas link click is not working for nested paths

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/core/index.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
- packages/css-engine/src/core/style-sheet-regular.ts
- packages/css-engine/src/core/style-sheet.ts
Here got rid of top level stylesheet caching in favor of managing caching by each rule. So nesting rule, font face and style rule based on their inputs and methods manage own cached css string.
In stylesheet all the work left is building media queries and concatenating all rules. This prevents hard to debug cached css after updates.
> refactor: simplify stylesheet caching

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/stores.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/shim.test.ts
- apps/builder/app/shared/shim.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet.ts
- packages/css-engine/src/schema.ts
Here refactored canvas styles with nesting rules which allow to update each declaration incrementally and closer to our data format.
Things to test
- initial rendering
- updating values
- ephemeral values
- selecting state, rendered as separate stylesheet
Added shim.ts to contain simplified polyfills for future methods like Set.prototype.difference which I use here to find added and deleted styles.
Removed warning from parseCssValue which pollutes log with outdated messages.
Additionally fixed old bugs
- support ephemeral styles with selector state, for example hover was not updated on on canvas while updating ephemeral styles
- remove ephemeral custom property from body (bug appeared when added support ephemeral styles in tokens)
> refactor: reimplement canvas style renderer

- packages/design-system/src/components/tree/tree.tsx
closes https://github.com/webstudio-is/webstudio/issues/3285
when editing navigator item name, don't allow dragging, because it prevents text selection
2. expect xyz
> fix: when navigator item is being edited, it can't be draggable

- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-content.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-layer.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/style-layer-utils.ts
Fixes the issue with transitions that is leaving a `tuple` default value on reset. 
Please refer to #3302  for the steps to reproduce.
> fix: default values of transitions is tuple which needs to be reset

- packages/sdk-components-react/src/xml-node.tsx
Example xmlns attribute in sitemap
2. expect xyz
> feat: Add support for Xml Node attributes

- apps/builder/app/routes/cgi.image.$name.ts
- packages/prisma-client/migrations-cli/prisma-migrations.ts
- Remove vite overlay Error about image not exists in dev mode (replacing 500 on 
404)
- Add prisma package directory as cwd to all prisma commands
2. expect xyz
> build: Simplify development by fixing dev mode image behavior, fix migrate cli

- packages/cli/templates/defaults/.npmrc
Closes https://github.com/webstudio-is/webstudio/pull/3300 https://github.com/webstudio-is/webstudio/issues/3284
Here's another fix. Instead of just passing --force flag to npm install command I added .npmrc with force=true which will affect not only webstudio init command but also subsequent npm install calls by user.
> fix: prevent failing npm install on peer mismatch

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- packages/design-system/src/components/select.tsx
- packages/sdk/src/schema/pages.ts
ref: #3308 
Use for review:
In case of xml is selected
- No way to make xml as home page
- Editing of social/etc is disabled
2. expect xyz
> feat: Add doctype to new/edit page

- packages/css-engine/package.json
- packages/error-utils/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react/package.json
- packages/sdk/package.json
This hack was used to support classic remix compiler and no longer necessary.
> refactor: drop require export condition

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/cli/src/prebuild.ts
- packages/css-engine/src/core/atomic.test.ts
- packages/css-engine/src/core/atomic.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
- packages/css-engine/src/core/style-sheet.ts
- packages/feature-flags/src/flags.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/core-components.ts
- packages/react-sdk/src/css/css.test.ts
- packages/react-sdk/src/css/css.ts
- packages/sdk-cli/src/generate-stories.ts
Here added support for new `<ws:descendent />` component. It allows to style any children or descendents of components. Primary usage is for embed content which renders html and need to style tags.
Descendent component accepts "selector" prop which can be suffix like ` img`, ` .image` or `::first-child` pseudo-element.
Potentially it could be used as tag styling for any element.
Can be tested in any element by dropping "Descendent" component from "internal" category.
> experimental: add descendent component

- packages/design-system/src/components/button.stories.tsx
- packages/design-system/src/components/button.tsx
See storybook, buttons inside disabled fieldset should be disabled. As of now buttons didn't support native disabled style
See pixel comparison
2. expect xyz
> fix: Buttons native disabled support

- apps/builder/app/builder/shared/binding-popover.tsx
Do not show bind button inside `<fieldset disabled`
That will mean that button itself is disabled and don't need to be shown
2. expect xyz
> fix: Do not show bind button if it disabled

- packages/sdk-components-react-remix/src/remix-form.tsx
Form action in case of undefined should use Remix Form to avoid page reload
2. expect xyz
> fix: Form action in case of undefined should use Remix Form to avoid reload

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/filter/filter.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
- apps/builder/app/builder/features/style-panel/shared/collapsible-section.tsx
- packages/css-data/src/parse-css-value.ts
fixes #3294 
This PR does two things,
- When users add complex values like `box-shadow`, `filter`, `transition`, `text-shadow`. They are parsed and added to the data layer accordingly. This will help the sections to properly handle them using the style-panel. 
- For projects that already have `unparsed` complex values in them. They are just showing a blue label as local state in the `ProeprtyName` component. We need to display default style, because even though the property is unparsed and valid. The sections can't take advantage of it to help it edit with UI.
1. Add a property like `filter`, `box-shadow` in the advanced tab.
2. Now, start editing the value in the style-panel.
> feat: parse complex values with available parsers for sections

- packages/sdk-components-react-radix/src/dialog.tsx
Close the dialog when a navigable link within it is clicked
Fixes the issue when we have anchor links inside Sheet
https://href.staging.webstudio.is/builder/95821bd9-040a-4294-aa7f-edf26d7f1ebe
https://link-inside-sheet-saas-sk7pk.wstd.work/
Open sheet
Click links, links should work
> feat: Close the dialog when a navigable link within it is clicked

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- packages/eslint-config-custom/index.js
- packages/eslint-config-custom/package.json
- packages/sdk-components-react-radix/src/accordion.tsx
- packages/sdk-components-react-radix/src/checkbox.tsx
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/label.tsx
- packages/sdk-components-react-radix/src/navigation-menu.tsx
- packages/sdk-components-react-radix/src/popover.tsx
- packages/sdk-components-react-radix/src/select.tsx
- packages/sdk-components-react-radix/src/sheet.tsx
- packages/sdk-components-react-radix/src/tabs.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
- pnpm-lock.yaml
Most rules protect from legacy and class component apis.
Many rules are checked by typescript.
A few rules just do not bring much value.
The package brings too many dependencies.
> build: drop eslint-plugin-react

- apps/builder/app/builder/features/inspector/inspector.tsx
Do not show styles at all on non html page
Open any page with document type xml, see no style panel is present
> feat: Hide style settings on non html pages

- packages/sdk-components-react/src/content-embed.ws.ts
I forgot to add a link in the first revision. Will an href with "#" work?
2. expect xyz
> fix: add sample link to content embed component

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/routes/rest.resources-loader.ts
- packages/sdk/src/schema/resources.ts
ref #3308
Add Variable, System Resource, open Select, check texts
> feat: Add System Resource instead of $resources url

- packages/sdk-components-react-remix/src/shared/remix-link.tsx
- packages/sdk-components-react/src/image.tsx
Ref https://github.com/webstudio-is/webstudio/issues/2798
Here fixed failing whole canvas when object is passed to image src or link href. Both src and href are casted to string same way html does with its props. It does not solve the issue universally but at least covers most popular ones.
> fix: avoid canvas failure when image/link props invalid

- packages/asset-uploader/package.json
- packages/asset-uploader/src/utils/font-data.ts
- packages/fonts/src/constants.ts
- packages/fonts/src/schema.ts
- pnpm-lock.yaml
fontkit types added missing pieces. Figured otf is interpreted as ttf so no need to have it as separate type.
Testing
- upload font
- upload image
> refactor: bump asset uploader dependencies

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/shared/nano-states/components.ts
- apps/builder/app/shared/nano-states/index.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/nano-states/variables.ts
Here added support for autocompleting inferred path params where their values are not specified by user.
> experimental: autocomplete path params

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
Handle layout changes for individual shadow properties.
> chore: change layout for shadow UI

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
JSON.parse is not safe to parse expressions. Better execute it with try/catch.
> fix: settings panel breaks when resource url is an expression

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/property-parsers/filter.test.ts
- packages/css-data/src/property-parsers/filter.ts
- packages/css-data/src/property-parsers/shadows.ts
fixes #3355 
Allows filter parser to parse `rgba` and `hex` values when copy pasted. I added some tests for filters too, we added initiall before as the css filters parser returns false positives. But now, i added all the valid tests, so at least we can catch things like this in future.
- Use the following filter values to test them.
```
drop-shadow(10px 10px 25px blue)
drop-shadow(10px 10px 25px rgba(0, 0, 255, 1))
drop-shadow(10px 10px 25px  #0000FF)
```
> fix: allow users to use hex and rgba values in css-filters

- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/n8n.ts
- packages/form-handlers/src/shared.ts
- packages/sdk-components-react-remix/src/webhook-form.tsx
Add simple protection against non js and jsdom bots
Idea is to add hidden js generated field on submit, and check that matchMedia is working.
Go here
https://saas-form-rdlrc.wstd.work/
then check via curl
```bash
curl 'https://saas-form-rdlrc.wstd.work/?index=&_data=routes%2F_index' \
-H 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
-H 'referer: https://saas-form-rdlrc.wstd.work/' \
--data-raw 'ws--form-id=2TIgyB2vQViDMitiYiGSK&name=wewe&email=wewe&ws--form-bot=18f72a6'
curl 'https://saas-form-rdlrc.wstd.work/?index=&_data=routes%2F_index' \
-H 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
-H 'referer: https://saas-form-rdlrc.wstd.work/' \
--data-raw 'ws--form-id=2TIgyB2vQViDMitiYiGSK&name=wewe&email=wewe'
curl …
```
> feat: Simple bot protection that should elimiminate most of the spam on our forms

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- packages/sdk/src/schema/resources.ts
Here simplified detecting system resource control with explicit resource field. Without it ui falls back to http ui.
Will be useful for graphql ui later.
Also disabled system resource option for non-paid users
- create sitemap resource
- close variable popover
- open again and see system control instead of default http control
> refactor: define resource control explicitly

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
ref #3343
Overlay or hidden support for headers etc to make it look more disabled
Create/Edit Page, change type on XML
> fix: Style non-XML sections as disabled on page edit/create

- apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3295
User may be accidentally on a zoom and this will result in unpredictable media query application.
We show warning only when user has non 1 zoom level
2. expect xyz
> feat: Warn user when they use browser zoom on canvas

- packages/sdk/src/expression.test.ts
- packages/sdk/src/expression.ts
Here added utilities to update expressions partially for example in graphql json body we need to update separately query and variables expressions but store as single body expression.
> refactor: add object expression utilities

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
- packages/design-system/src/components/text-area.stories.tsx
- packages/design-system/src/components/text-area.tsx
Here replaced state=invalid with color=error in textarea to align with input field and fixed focused input with error style.
> refactor: align text area error with input field

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.stories.tsx
- apps/builder/app/shared/form-utils/form-utils.ts
Here integrated native fields validation into our form utilities. It will let us have more isolated validation complexity within each field.
The trick was to detect if any error are not shown. Solved by iterating form.elements and checking its input.validity.valid and data-color=error attribute.
> refactor: use native validation for resource url

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
Here added new "GraphQL" option into variable "type" select. It allows to switch to special resource subset with "query" and "variables" fields instead of single json body.
> experimental: add graphql resource control

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
Here's 2 major changes
- switched to native body validation without json auto-formatting while editing
- automatially add Content-Type: application/json header when object is set from binding expression
This refactoring opens room for more improvements.
> feat: improve resource body

- apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
1. Zoom detector that warns user next to breakpoints selector had bugs
2. expect xyz
> fix: fix zoom detector

- apps/builder/app/builder/features/settings-panel/curl.test.ts
- apps/builder/app/builder/features/settings-panel/curl.ts
Fixes https://github.com/webstudio-is/webstudio/issues/3375
The arguments parser we use missed a case with explicit backslashes and I missed it in our tests. Here removed it with regex.
> fix: strip backslashes from curl when paste

- apps/builder/app/builder/features/address-bar.stories.tsx
- apps/builder/app/builder/features/address-bar.tsx
- packages/sdk/src/schema/pages.ts
Address bar need to fill every time user want to test the page. Here added history suggestions which let users reuse peviously entered params.
Had to implement own combobox-like behavior to support syggestions universally on all inputs.
> experimental: support history in address bar

- apps/builder/app/builder/shared/url-pattern.ts
- packages/sdk/src/index.ts
- packages/sdk/src/page-utils.ts
- packages/sdk/src/url-pattern.test.ts
- packages/sdk/src/url-pattern.ts
URL patterns should not be included in the sitemap. For instance, before this PR, we included paths like /:slug in the sitemap.
Open
https://fix-sitemap-slug.staging.webstudio.is/builder/8404e444-093d-4e70-b5c2-03fd89b9eb6d?pageId=EksrLskoGCCreyVN4xp2r
See dynamic page is excluded
> fix: URL patterns should not be included in the sitemap

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/add.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/combobox.stories.tsx
- packages/design-system/src/components/combobox.tsx
- packages/design-system/src/components/select.stories.tsx
- packages/design-system/src/components/select.tsx
> fix: Make select and combobox description height stable

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
AI sometimes adds components we don't have
here is just a hint for user that some component is missing.
Here's json to paste
```json
{
"@webstudio/template": [
{
"type": "instance",
"component": "ContentEmbed",
"children": []
}
]
}
```
> fix: show visually missing component in canvas

- apps/builder/app/canvas/shared/commands.ts
Here trying to fix the issue with text editor loosing focus after cliking on buttons and as a result blur never happen and changes are not saved.
> fix: enforce text editor focus after clicking on toolbar

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/shared/nano-states/variables.ts
We want users to get good first impression and show already working cms page when clone from marketplace. Here improved bindings logic to always use the first history entry as default.
> feat: restore system params from history first entry

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
Empty stub was used as drop target in empty collection. Missing stub does not work for this case.
> fix: show drop stub when collection is empty

- packages/jsx-utils/package.json
- packages/jsx-utils/src/jsx.test.ts
- packages/jsx-utils/src/jsx.ts
- packages/jsx-utils/src/parser.ts
- pnpm-lock.yaml
Babel is very big package. It brings a lot of transitive dependencies. A lot of projects like remix, storybook and jest depends on it.
Updating it is always a challenge because it usually lead to duplicates.
So here I switched to acorn we already use for expressions. JSX parsing is not builtin but available as a plugin. The only downside is lack of node types. Though very straightforward to get them from jsx estree extension spec.
See build sizes change
```diff
- 4716	build/server
+ 3992	build/server
6096	build/client
```
Additionally in this PR prevented "Fragment" component generation, it should not be used with anything except Slot.
> refactor: parse jsx ai output with acorn

- apps/builder/app/builder/shared/expression-editor.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3401
Ref https://github.com/webstudio-is/webstudio/issues/3080
Simple logic here, one variable matched by name then can be replaced with actual variable id otherwise user has to select variable explicitly.
> feat: match unambiguous variables by name

- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/templates.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- packages/sdk/src/schema/pages.ts
Fixes https://github.com/webstudio-is/webstudio/issues/3405
Reusing existing fields for marketplace does not work well when fields are dynamically bound to cms data. Here we replaced existing fields used in marketplace with static ones.
- ws:title ?? page title -> page name
- social image url ?? social image asset -> marketplace thumbnail ?? social image asset
- exclude page from searcg -> marketplace include
- ws:category -> marketplace category
> feat: add marketplace section in page settings

- apps/builder/app/builder/features/address-bar.tsx
We show all history at the moment even when path is changed. Here improved logic to exclude all paths from history not matching current page path pattern.
> fix: prevent showing not matching history

- apps/builder/app/builder/shared/code-editor-base.tsx
Ref https://github.com/webstudio-is/webstudio/issues/3343
Copying text was broken because of user-select: none defined globally. Without contenteditable=true codemirror still simulates text selection but everything else stops working.
Testing
- try to copy anything from variable "inspect"
> fix: support copying text from code editor

- apps/builder/app/builder/features/sidebar-left/panels/marketplace/overview.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/shared/array-utils.test.ts
- apps/builder/app/shared/array-utils.ts
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/shim.test.ts
- apps/builder/app/shared/shim.ts
Here moved our utility polyfill for Map.groupBy into shims module we are using for all stuff we will replace with native methods.
Used it in marketplace to group by category.
> refactor: move Map.groupBy into shims

- packages/sdk-components-react-remix/src/remix-form.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3435
Remix just does not work well on canvas/preview. Both links and forms are rendered natively without remix.
> fix: switch to native form in preview

- apps/builder/app/shared/nano-states/props.ts
Our stores updates does not support transactions
which leads to a lot of updates with empty state.
Empty and valid states are both used to load resources and override each other. Here workarounded by scheduling loading to the next frame.
> fix: try to avoid race conditions while loading resources

- packages/cli/src/commands/link.ts
- packages/cli/src/commands/sync.ts
@clack/prompts supports spinner out of the box
so we can replace ora with it too.
Here switched sync command to this spinner
and added handling server errors.
https://github.com/webstudio-is/webstudio/assets/5635476/f6984b7c-c782-4859-a58d-335a39340119
> feat: improve CLI sync command

- packages/cli/src/commands/build.ts
- packages/cli/src/prebuild.ts
Got rid of spinner around fs operations because user does not see messages anyway. Wrapped only assets download with spinner. Logged errors with clack logger.
https://github.com/webstudio-is/webstudio/assets/5635476/02a20dfb-e300-45e2-b923-06671d52fe7f
> feat: improve CLI build command

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/inspector-edits.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/canvas-api.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
closes #3021
Currently if we are in a text edit mode we sometimes can't focus on any input inside builder.
This fixes this.
2. expect xyz
> fix: Fix focus bugs with text editing on canvas

- apps/builder/vite.config.ts
For unknown reason port forwarding on Oleg's dev machine works only if `host: "0.0.0.0",`
Works on localhost on mine
2. expect xyz
> build: Add host for vite config

- apps/builder/app/builder/shared/code-editor-base.tsx
Current codemirror theme has very light comment which is hard to read. Here switched to comment color from another theme.
> fix: use darker comment color

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
This seem does not affect wide screens anymore. Maybe caz we moved builder to client side rendering. build.breakpoints are no longer used so we can move data loading to client side as well.
> refactor: remove canvas max width detection

- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/design-system/src/components/combobox.tsx
Key prop can't be spread
2. expect xyz
> chore: Fix react key spread warning

- apps/builder/.env
- apps/builder/vite.config.ts
Having that we use network_mode: service:db
we can use localhost for the db connection string
2. expect xyz
> fix: Make env compatible across all envs

- .github/workflows/migrate.yaml
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/about.tsx
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/marketplace.tsx
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/templates.tsx
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/marketplace/db.server.ts
- apps/builder/app/shared/marketplace/types.ts
- packages/design-system/src/components/button.tsx
- packages/design-system/src/components/link.tsx
- packages/prisma-client/prisma/migrations/20240530162819_marketplace-token/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/trpc-interface/src/authorize/project.server.ts
- packages/trpc-interface/src/context/context.server.ts
ref #3446
We now display the marketplace project link only if it has a shared link with view permission. If there is no shared link, we show disabled buttons with a tooltip.
Open marketplace, see one has link the other is not
Check that link is working in incognito
> fix: Permission error when opening marketplace projects (marketplace projects need to add any view permission link)

- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-tabs.tsx
Additionally refactored the logic a bit and moved AI to the bottom. This way its more consistent with upper part all handling sidebar panels, being tabs
1. focus and hover should show a tooltip
2. open tab should have open state
> fix: Fix open state indication of the tabs in the left side bar

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/rest.data.$projectId.ts
- apps/builder/app/shared/builder-data.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/vite.config.ts
To synchronize data between tabs it should be consistent and be easily accessible. Loading from server creates huge latency and data can be changed by loading from another tab.
Here moved data loading to client side so it can be shared through IndexedDB.
Added new `/rest/data/:buildId` endpoint and defined global setter and getter for current state.
> refactor: move builder data loading to client side

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/3080
Here improved variables list in bindings to insert variable at cursor instead of full expression override.
Also bumped codemirror and disabled autocomplete in variable "name".
https://github.com/webstudio-is/webstudio/assets/5635476/2a5482e2-b880-4bcd-abdf-10ce6db68d31
> feat: insert a variable at the caret position from the list

- packages/design-system/src/components/primitives/arrow-focus.tsx
Ref https://github.com/webstudio-is/webstudio/issues/3343 https://github.com/webstudio-is/webstudio/issues/3080
2. expect xyz
> fix: Fix arrow focus

- .github/pull_request_template.md
- apps/builder/.env
- apps/builder/.env.production
- apps/builder/app/env/env.server.ts
- apps/builder/app/services/auth.server.ts
- apps/builder/app/shared/db/user-plan-features.server.ts
- apps/builder/app/shared/db/user.server.ts
closes #3400 
`+` on dev login its now possible to add any email
like 
`{code}:hello@world.xx` to login as other user
Login on main with `{code}:ice@yandex.ru`
- See no plan
---
Login on main as usual
- See user has plan
---
Login locally
See user has plan
> feat: Make it easy for a self-hosted version to set the plan features

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
Looks like it would be useful to support curl in graphql resources as well.
> feat: support curl paste in graphql resource url

- apps/builder/app/canvas/interceptor.ts
- packages/sdk-components-react-remix/src/shared/remix-link.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3478
This fixes the issue with reloading pages when href="?" and href="#" are specified without any pathname.
> fix: treat link urls without pathname as self reference

- apps/builder/app/builder/features/project-settings/section-general.tsx
We missed to specify html language here.
Users in discord noticed this.
> feat: highlight Custom Code as html

- package.json
- packages/cli/package.json
- packages/css-data/package.json
- packages/design-system/package.json
- packages/generate-arg-types/package.json
- packages/icons/package.json
- packages/jest-config/package.json
- packages/prisma-client/package.json
- pnpm-lock.yaml
Upgraded both tsx and esbuild to the latest version and removed override for esbuild. As a result we have 5 duplicates of esbuild but they will go away with time.
> build: bump tsx and relax esbuild

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3480
Here always close popover when variable is created to avoid duplicating with a few "Enter" presses on "name" field.
> fix: close variable after creating

- .github/workflows/release.yml
Here added workflow to automatically create release when tag is pushed to the repo.
All unconfigured types will go into "Other changes" section
Example of changelogs
https://github.com/TrySound/test-auto-release/releases
> build: automatically create release

- apps/builder/middleware.js
- apps/builder/package.json
- packages/prisma-client/migrations-cli/cli.ts
- packages/prisma-client/package.json
- pnpm-lock.yaml
Refs
- https://nodejs.org/docs/latest/api/process.html#processloadenvfilepath
- https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs
Here switched from dotenv to node env loader.
Solves both command line and runtime cases.
The only issue is inability to specify --env-file with NODE_OPTIONS.
Also fixed dev migrations by optionally loading .env.development
> build: replace dotenv with node env loader

- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx
fixes
- when choosing an image after having a url, url is normally being reset, so you don't have both, now I managed to have both
- Code area label should be Code
Regarding the 
- jump when switching between image and gradient.
This is a little tricky, to restrict from jumping. Thought about this while implementing itself. But there is too much negative spacing for gradients tab. We need to set `min-height`. Which is showing too much empty spacing for background gradients in my opinion. Let me know, if it's still fine and we can go ahead.
- shouldn't all properties land in the Code area? not just the url()?
This, i am not sure if its possible. Because, in every code-editing areas. We are showing only the property value and not the key. In this case, of we want to show multiple …
> fix: reset image url in inputs when users select a uploaded image after adding a remote url to the same.

- apps/builder/app/builder/builder.css
- package.json
- patches/@radix-ui__react-scroll-area@1.0.5.patch
- pnpm-lock.yaml
closes #3504
Reflow caused by Style element rerender sometimes cause focus lose.
It can be or chrome issue or Mutattion observer used in radix focus scope.
2. expect xyz
> fix: Image Manager. Ensure picture click and delete functionality work consistently

- apps/builder/app/builder/features/sidebar-left/panels/marketplace/templates.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3450
Got rid of ws:cetegory meta and excludePageFromSearch fallbacks in marketplace. Social image is the only fallback we agreed to left.
> fix: drop marketplace legacy fallbacks

- .devcontainer/devcontainer.json
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/shared/assets/asset-upload.tsx
- apps/builder/app/builder/shared/assets/assets-shell.tsx
- apps/builder/app/builder/shared/assets/drag-monitor.tsx
- apps/builder/app/builder/shared/assets/image-formats.ts
- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/builder/shared/image-manager/filename.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/routes/cgi.image.$name.ts
- apps/builder/app/routes/rest.assets.$name.tsx
- packages/feature-flags/src/flags.ts
https://github.com/webstudio-is/webstudio/assets/5077042/ea38835c-ec5c-4333-a982-f5bb9580d9e0
URLs can be dropped on Image Manager
+ small fixes.
- Files without extensions broke FileName control
- svg files were not shown on local builder after upload
Open Image Manager, drag urls
> feat: Enable URL drop functionality in Image Manager

- apps/builder/app/builder/features/project-settings/section-general.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/image/src/image-loaders.ts
- packages/image/src/image-optimize.ts
width,height must be multiple of 48 https://developers.google.com/search/docs/appearance/favicon-in-search
- In case of non square favicon uploaded add paddings to make it square [favicon-non-sqare](https://favicon-non-sqare-saas-1noth.wstd.work/) see white paddings
https://favicon-non-sqare-saas-1noth.wstd.work/cgi/image/IMG_2882_(1)_LY_eDOEMEwtikKi5Pyld-.png?width=144&quality=100&format=auto&height=144&fit=pad
_padding crop is used because all other `fit` modes we have can't upscale images as I know to get exact final height and width set_
corresponding SAAS PR https://github.com/webstudio-is/webstudio-saas/pull/300
Open 
https://favicon.staging.webstudio.is/builder/28fb95a3-5236-430c-950e-dda451a31c4d?authToken=2627c718-308e-4690-8919-1e1f00e5b3a5&mode=preview
Publish
See <link …
> fix: Favicon sizes conform to Google Search guidelines

- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
Here added new utlity to expand css shorthand properties into longhands. Parsing is not trivial. csstree could help a lot with builtin lexer but it does not expose matched nodes on properties. Here we can leverage lexer to match big pieces and refined them into set of properties.
Supported following properties
- border
- border-radius
- border-image
- outline
- margin/padding
- inset
- gap
- place-content
- place-items
- place-self
Will do the rest in separate PRed them to `.env` file
> experimental: add css shorthands utility

- apps/builder/app/builder/features/topbar/publish.tsx
- packages/cli/.npmignore
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/.npmrc
- restrict node to >= 20.12 with "engines" field
- write .npmrc by code instead of copying from template because publish always cuts it from cli package
- use `npx webstudio@latest` to always install fresh cli if necessary
> fix: improve cli installing

- apps/builder/app/builder/builder.tsx
- packages/design-system/src/components/progress.tsx
When project loads very quickly, loading animation will end where it started at 0%. To make sure it always finishes at 100%, we need to let it do so.
Before
https://share.descript.com/view/TnNtRBlnxGq
After
https://share.descript.com/view/0WqOiBbVy8B
2. expect xyz
> experimental: Always finish up builder loading animation

- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/html-to-jsx.test.ts
- packages/cli/src/html-to-jsx.ts
Following code in Project Setting Custom Code 
```
<script data-cf-beacon='{"token": "123"}'>
```
failed on build
2. expect xyz
> fix: Correct single-quoted attribute handling in Custom Code

- apps/builder/app/routes/rest.ai._index.ts
- packages/ai/src/chains/operations/__generated__/operations.system.prompt.ts
- packages/ai/src/chains/operations/chain.server.ts
- packages/ai/src/chains/operations/operations.system.prompt.md
Closes https://github.com/webstudio-is/webstudio/issues/3517
Completion would often start with  \`\`\`json  instead of the actual json that we want to parse, so I added a command to not start with \`\`\`json
2. expect xyz
> chore: Update gpt 3.5 model and improve reliability

- packages/sdk/src/expression.test.ts
- packages/sdk/src/expression.ts
Looks like acorn skip thes rest of the input after successfully parsing expression. This resulted in weird syntax errors our linter allow user to enter.
The fix is simple, force acorn to consider whole input as expression by wrapping with parentheses. Though it also requires tuning diagnostics position.
> fix: lint weird cases in expressions

- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/shared/floating-panel.tsx
fixes #3511 
This is an experiment to see if setting `collisionPadding` can reduce the background panel jumps when switching tabs. `Popover` content always opens close to trigger, but there is no defined way to know when it repositions when the content is dynamically changed.
So, when the panel is opened close to the bottom of the screen, the panel moves away from arrows under the cursor. 
- Add a background
- Now, open the background panel and switch between the tabs.
> experimental: set collisionPadding for background panel to reduce panel jumps.

- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
Added support for 3 shorthand properties
- font
- text-decoration
- text-emphasis
white-space and text-wrap left untouched caz expanded versions have worse support and even mdn is not clear on shorthand syntax.
We will be able to migrate with client migrations in the future.
> experimental: expand text shorthands

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/custom-data.ts
Closes https://github.com/webstudio-is/webstudio/issues/3529
Values that can have custom identifiers (user defined string) were tested to accept a unit value and they did, because anything is valid.
Now they are not tested with units any more
1. add animation-name in advanced panel
2. use any name it should stay as-is
3. previously we would add a "px"
> fix: Properties like animation-name were receiving unneeded px suffix

- .github/workflows/release.yml
Main reason is github sends tags in alphabetical order so changelog generated from very old accidental tag like `diff` from mistyped `gt diff` command.
I dropped all such tags. Though semver is another thing which can guarantee correct tag lookup. Let's try this for next release.
> build: enable semver check in changelog

- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
fixes #2967 
This will save the content when the content box is blur. This will wrap up all the things that we need to handle under the #2967 issue.
- Add a layer to any of the `shadow` or `filter` properties.
- Now, edit the values using the content box and click somewhere else on the panel.
- This should save the values once the box looses focus.
> refactor: Save content when content box is closed/blur

- apps/builder/app/builder/builder.tsx
- apps/builder/app/shared/builder-api.ts
Add ability to make direct calls to builder API, like toast.
usage.
```
import { builderApi } from 'blaba';
builderApi.toast('ANYTHING')
```
> chore: Add buider API

- packages/react-sdk/src/component-generator.test.tsx
- packages/sdk/src/jsx.test.tsx
- packages/sdk/src/jsx.ts
Here enahnced our jsx with props support and rewrote component generator tests with it as an example.
Props are solved in straightforward way, type of value described prop type. Though in case of expression, parameter, asset, page, action used classes as opaque types.
> refactor: use jsx in component generator tests

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
fixes #3069 
The properties `transition-delay` and `transition-duration` are being saved directly considering they are being valued using the `CSSValueItemProperty`. But not all values in long hand are valid in `short-hand` property. So, we need to validate the property value before saving them
- Add a transition layer.
- Now change the values in the transition-delay and transition-duration and try to save them.
> fix: validate using long-hand property for transition while saving

- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Here fixed the issue with detecting root as first instance in the fragment. The idea of this utility is to not rely on any root but instead insert with new ids all instances outside of portals/components. Roots semantics is left for outer utilities.
> refactor: insert fragments with multiple roots

- apps/builder/app/shared/canvas-api.ts
Already released as hotfix
https://cdn.discordapp.com/attachments/1252596836729094184/1252596837056118834/image.png?ex=6672cb36&is=667179b6&hm=fc5718dfac9bd0e5a430b22a09cf0889831a767f5c60e2ca1731e6f3fd43a779&
Install Zotero extension
Then open 
https://main.development.webstudio.is/builder/a1371dce-752c-4ccf-8ea4-88bab577fe50
See error
`Failed to read a named property '__webstudio__$__canvasApi' from 'Window': Blocked a frame with origin "https://main.development.webstudio.is" from accessing a cross-origin frame.`
Now open
https://fix-zotero.development.webstudio.is/builder/a1371dce-752c-4ccf-8ea4-88bab577fe50
See no Error
> fix: Skip inaccessible iframes added by extensions to prevent cross-origin errors

- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/sdk-components-react/src/html-embed-patchers.ts
- packages/sdk-components-react/src/html-embed.tsx
Reload scripts in HTML Embed on dynamic pages
Closes #3581
Open
https://scripts-reload-saas-2-pgmkm.wstd.work/test/1
dynamic link clicks should cause `console.log` from IFrame
Anchor link should not.
> fix: Reload scripts in HTML Embed on dynamic pages

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/style-panel/sections/size/size.tsx
- apps/builder/app/shared/builder-data.ts
- apps/builder/app/shared/webstudio-data-migrator.test.ts
- apps/builder/app/shared/webstudio-data-migrator.ts
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/html.ts
- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
- packages/css-engine/src/__generated__/types.ts
- packages/sdk-components-react-radix/src/theme/tailwind-classes.ts
Here refactored overflow UI to update "overflow-x" and "overflow-y" longhands instead of "overflow" shorthand.
Removed "overflow" from advanced panel suggestions.
Added support for expanding overflow shorthand for webflow copy paste.
And implemented very basic migrations utility
which always run after data is loaded from server
and sends patch for expanding overflow longhands.
Patch is not sent when no properties are modified. Though eventually we will need to support versioning to avoid executing old migrations.
> feat: switch to overflow longhands

- apps/builder/app/canvas/shared/styles.ts
- packages/react-sdk/src/css/css.test.tsx
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/global-rules.ts
- packages/react-sdk/src/css/style-rules.ts
Moved preset styles to new nesting rules in css engine. Will simplify future prefixer solution.
> refactor: switch preset styles to nesting rules

- apps/builder/app/builder/features/sidebar-left/panels/navigator/css-preview.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- packages/css-engine/src/core/css-engine.stories.tsx
- packages/css-engine/src/core/index.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
- packages/css-engine/src/core/style-sheet-regular.ts
- packages/css-engine/src/core/style-sheet.ts
Switched to nesting rule and style map generator
everywhere in builder.
Now will be much easier to implement properties prefixing and merging utilities.
> refactor: drop legacy style rule

- apps/builder/app/entry.server.tsx
- apps/builder/app/routes/$.tsx
1. 404 error instead of redirect on assets.
2. Vercel sets Cache-Control: public, max-age=31536000, immutable for all /assets/* paths,
even when a 404 error occurs during deployment.
This causes 404 errors on assets to be cached permanently, preventing updates.
To prevent this, we set "Cache-Control": "public, max-age=0, must-revalidate" when an asset is not found.
2. expect xyz
> fix: Static assets redirect to dashboard

- fixtures/webstudio-cloudflare-template/app/__generated__/_index.tsx
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/css-engine/src/core/atomic.test.ts
- packages/css-engine/src/core/prefixer.test.ts
- packages/css-engine/src/core/prefixer.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/to-property.test.ts
- packages/css-engine/src/core/to-property.ts
- packages/react-sdk/src/css/css.test.tsx
These fields should have -webkit- prefix additionally to unprefixed version to support more browsers.
- background-clip
- user-select
- text-size-adjust
> fix: prefix more css properties

- apps/builder/app/builder/features/sidebar-left/panels/navigator/css-preview.tsx
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
- packages/css-engine/src/core/atomic.test.ts
- packages/css-engine/src/core/atomic.ts
- packages/css-engine/src/core/index.ts
- packages/css-engine/src/core/merger.test.ts
- packages/css-engine/src/core/merger.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
Here added optimization to css engine to produce much less classes when some lonhands can be combined into shorthand.
Supported following properties
- border
- outline
- margin
- padding
Later the same utility will be used to make white-space and text-wrap longhands better supported.
> feat: merge longhand css into shorthands

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
ref #2647
We already had logic to handle style sources on paste: if the destination has the same styleSource.id as the source, we do nothing.
Now, we add deterministic ID generation for Webflow classes. This, combined with the existing logic, achieves the desired behavior.
Paste anything from single webflow project multiple times. See no duplicated.
> fix: Deduplicate styles on data paste from Webflow

- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/utils/font-data.test.ts
- packages/asset-uploader/src/utils/font-data.ts
- packages/asset-uploader/src/utils/get-asset-data.ts
Closes https://github.com/webstudio-is/webstudio/issues/3626
Some fonts lack any family information in the meta data. For such fonts we will fall back to their file name.
2. expect xyz
> fix: Fallback to file name when family name is not defined in the meta

- packages/css-engine/src/core/merger.test.ts
- packages/css-engine/src/core/merger.ts
Css wide keywords should be used only in longhand values not as part of shorthands.
> fix: prevent merging var with unset, initial and inherit

- apps/builder/app/routes/$.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/css-data/src/property-parsers/background.test.ts
- packages/css-data/src/property-parsers/background.ts
Add support for background parsing into webstudio layers.
With partial support of webflow copy-pasting.
Main support will be in the next PR.
https `id`s are temporary used instead of real URLs to avoid various encoding/decoding issues, will be changed in next PR or PRs
Copy-Paste something like this
Get this
> chore: Parse css backgorund support

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/copy-paste/asset-upload.test.tsx
- apps/builder/app/shared/copy-paste/asset-upload.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
- apps/builder/package.json
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/css-data/src/property-parsers/background.test.ts
- packages/css-data/src/property-parsers/background.ts
- pnpm-lock.yaml
Upload backgrounds on webflow paste.
Create backgrounds with images at webflow
paste into the new project.
Example (everything is pasted from webflow in a single copy-paste)
https://upload-style-assets.development.webstudio.is/builder/dc6eae9d-dae6-4ba8-ade2-abd86f733d6a
Layers use assets
> experimental: Upload Webflow background-image assets on copy-paste

- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/animatable-properties.ts
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/custom-data.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/css-engine/src/__generated__/types.ts
- packages/sdk-components-react-radix/scripts/generate-tailwind-theme.ts
Ref https://github.com/webstudio-is/webstudio/issues/2647 Closes https://github.com/webstudio-is/webstudio/issues/3427
Here added -webkit-line-clamp and -webkit-box-orient properties support which is the only way to add multiline truncation at the moment.
All properties with prefixes are stored without camel casing. With font smoothing as the only exception because added very early.
> feat: support -webkit-line-clamp

- packages/css-data/package.json
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-data/src/tailwind-parser/parse.ts
- packages/css-data/src/tailwind-parser/shorthand.ts
- pnpm-lock.yaml
We duplicate the logic for parsing css for ai and webflow. Here a bit of cleanup to simplify further work on shorthands.
Also upgraded unocss and got rid of bug workaround (fixed in unocss)
> refactor: reuse css parser in tailwind parser

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- apps/builder/package.json
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/css-data/src/property-parsers/background.test.ts
- packages/css-data/src/property-parsers/background.ts
- packages/css-data/src/property-parsers/parsers.ts
- packages/css-data/src/property-parsers/to-longhand.ts
- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
Here added support for background shorthand in css parser. Refactored background image parser and simplified figma paste parser.
> experimental: expand background shorthand

- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- apps/builder/package.json
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-engine/src/core/merger.ts
- packages/css-engine/src/css.ts
- packages/css-engine/src/index.ts
Here added universal support for css wide keywords. initial, inherit and unset will be parsed the same way for layered properties and singular properties.
It will never be part of layers and always be represented as root keyword.
> experimental: parse css wide keywords correctly

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-utils.ts
- apps/builder/app/builder/features/style-panel/style-layers-list.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/property-parsers/transition-property-extractor.ts
- packages/css-data/src/property-parsers/transition.test.ts
- packages/css-data/src/property-parsers/transition.ts
Fixed parsing "none" in transition-property.
Switched to unparsed as property type to semantically distinct from keyword.
> experimental: improve parsing transition-property

- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- packages/css-data/src/shorthands.test.ts
- packages/css-data/src/shorthands.ts
According to spec css-wide keywords on shorthands should be passed to all their longhands as is.
> experimental: expand shorthands with css-wide keywords

- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
Here improved our value parser to not output invalid type every now and then and just represent unknown properties as unparsed. This will let us parse it in the future without loosing anything on paste.
> experimental: parse unknown properties as unparsed value

- packages/css-data/src/property-parsers/transition-property-extractor.ts
- packages/css-data/src/property-parsers/transition.test.ts
- packages/css-data/src/property-parsers/transition.ts
Numbers like `.65` were not parsed as valid.
Also I don't think we need to use regexps to check functions validity. There can be vars calc and anything inside
2. expect xyz
> fix: Correct transition timing function for Webflow paste

- packages/sdk-components-react-radix/src/theme/styles.ts
Current fix does not fix existing Sheet components, but fixes new
Because of design tokens a little bit different size. (Can preserve if needed but will need some additional work)
Example: 
https://btn-style.staging.webstudio.is/builder/ff5ca76c-dd27-44a9-8608-23e9b02e0427?authToken=e8a517f5-b699-4b73-9dc1-049fdadaa207&mode=preview
Result
https://sheettest-rpbvy.wstd.work/
The problem on IOS
It's because Safari IOS default button paddings are
```
padding-left: 1em;
padding-right: 1em;
```
instead of defaults in other browsers. 
To solve safari IOS issue we need to set padding to explicit values
2. expect xyz
> fix: Sheet button padding for ios are now explicit

- fixtures/webstudio-custom-template/app/__generated__/[hello]._index.ts
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/route-templates/redirect.tsx
- packages/react-sdk/placeholder.d.ts
Here decoupled redirect generation from cli.
Moved remix related code to template and
generated only module with url and status.
> refactor: move redirect into template

- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/css-data/src/tailwind-parser/parse.ts
We need to support more grouping properties in parsed css for example breakpoints would require additional nesting.
Here I took slightly different approach and moved all styles into single array with additional `selector` property.
Now we can easily support parsing styles without selectors and parsing styles without breakpoints. And optionally we can always use `Map.groupBy(styles, styleDecl => styleDecl.selector)` and the same later by breakpoint.
> refactor: parse styles into flat list

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- packages/design-system/src/components/css-value-list-item.stories.tsx
- packages/design-system/src/components/css-value-list-item.tsx
closes https://github.com/webstudio-is/webstudio/issues/3668
Ensure trigger stays open when menu is opened, otherwise radix will loose anchor for positioning
1. hover variable item in the settings
2. click inspect
3. see menu position is correct
> fix:  dropdown menu position on list ittems (variables list)

- apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
- apps/builder/app/shared/breakpoints/select-breakpoint-by-order.ts
Close https://github.com/webstudio-is/webstudio/issues/3682
1. on initial load resize handes were not visible because initial width was not set
2. expect xyz
> fix: Set initial canvas width once selected breakpoint is known

- apps/builder/app/shared/copy-paste/plugin-webflow/__generated__/style-presets.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
Here added additional `breakpoint` property to parsed style declaration. It basically a sanitized media query like `(min-width:768px)` which is easy to parse. Styles inside unsupported conditions are just stripped away.
> experimental: support breakpoints in css parser

- apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
That schema is currently too string, and throws an error
2. expect xyz
> experimental: Relax asset schema for wf data

- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
Canvas crash.
When store.subscribe callback can be called sync and unsubscribe function isn't yet defined, it will crash
1. open project
2. go back to dashboard
3. open project again
4. should not crash
> fix: Fix nsubscribe logic when entering builder second time

- apps/builder/app/builder/features/style-panel/style-layer-utils.test.ts
- apps/builder/app/builder/features/style-panel/style-layers-list.tsx
- packages/css-engine/src/core/to-value.ts
- packages/css-engine/src/schema.ts
This simplifies maintaining style values.
No more checked for hidden possibility. Just check the flag for true.
> refactor: allow any style value to be hidden

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
Instead of adding all wf breakpoints at once, we now will add them incrementally if there are styles on a particular breakpoint
2. expect xyz
> experimental: Only add a breakpoint when there are styles on that breakpoint

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
Webflow wraps its custom properties (which are not actually custom properties) with `@raw<|value|>` which our parser just skips because unable to parse.
Here simply stripped with regex all such wrappers.
> experimental: support webflow custom properties

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/property-parsers/index.ts
- packages/css-data/src/property-parsers/transform.ts
Parse `transform` value into tuples. We need to use shorthand transform property for `skew` and `rotate` to support the UX. 
- **skew** doesn't have individual property yet. So need to use this as backup.
- **rotate** doesn support setting individual `x, y, z` properties on the long hand property like in the design. So, we are can use transforms as backup and allow to set individual `rotateX`, `rotateY` and `rotateZ` values. 
> experimental: parse transform css property into tuples

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-engine/src/schema.ts
Here refactored value parser with literal parser
which can be reused in all functions, tuples and layers.
Color parser now relies on specific ast types.
Tuples are generated for all values with multiple nodes.
This all will let us build more universal parsers with less effort.
> refactor: split css literal parser

- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
Ref https://github.com/webstudio-is/webstudio/issues/3399 https://github.com/webstudio-is/webstudio/issues/1536
Here added optional support for custom properties in css parser. Also refactored basic style object model tests with css/jsx fixtures.
> experimental: optionally support parsing custom properties

- packages/sdk-components-react/src/html-embed.tsx
closes #3724
https://embed.staging.webstudio.is/builder/f3843f61-c4dd-4fc6-9463-bb88e8cc5f9b
2 "Client Only" Embeds
```html
<script type="module">
import _ from 'https://cdn.jsdelivr.net/npm/lodash-es/lodash.js';
console.log(_.join(['Hello', 'World', '1'], ' '));
document.addEventListener('DOMContentLoaded', (event) => {
console.log('DOM fully loaded 1');
});
</script>
<script type="module">
console.log('Hello 2');
document.addEventListener('DOMContentLoaded', (event) => {
console.log('DOM fully loaded 2');
});
</script>
```
Before this PR gave output with following errors:
- Broken order
- Broken `DOMContentLoaded`
```log
Hello 2
Hello World 1
```
Now no issues
```log
Hello World 1
Hello 2
DOM fully loaded 1
DOM fully loaded 2
```
- …
> fix: DOMContentLoaded is not firing for inline module scripts

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
Here fixed the issue with pasting gradients from webflow. Their css engine output -webkit-fill-color: transparent along with background-clip property. This is very implicit behavior from css point of view.
Here I instead added logic to add color: transparent from paste from webflow overriding previously set color. It will not work in 100% but should cover relume templates.
> experimental: add transparent color when paste bg clip from webflow

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/schema.ts
This error happened because we assumed local styles to be strings but for example order can be number. Relaxed validation to unknown. Value is used only in template literal.
> experimental: fix webflow validation error

- packages/css-engine/src/core/prefixer.test.ts
- packages/css-engine/src/core/prefixer.ts
Safari was the first to build this feature but still supports only prefixed version. Might land unprefixed in safari 18.
> fix: support backdrop-filter in safari

- packages/cli/src/framework-remix.ts
- packages/cli/src/framework.ts
- packages/cli/src/prebuild.ts
We wanna support other frameworks than remix.
At least to support SSG we need to additionally deploy vike.dev.
Here split all remix specifics into separate module. It provides the list of components (including overrides) and templates getter.
Templates allow to provide multiple module per route which is essential for many frameworks like svelte and vike which do not rely on treeshaking for client/server splitting.
> refactor: isolate remix specifics in cli

- apps/builder/app/routes/builder.$projectId.tsx
- packages/project-build/src/db/build.ts
Loading of html (first request)
https://project-load-perf.development.webstudio.is/builder/be939bf2-9095-4e17-b175-69de2bbf9597
700ms
Same on main 8sec
https://main.development.webstudio.is/builder/be939bf2-9095-4e17-b175-69de2bbf9597
10x difference
2. expect xyz
> fix: Do not load full Build data at builder loader

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3751
Clicking on a label that toggles the switch is not necessary and leads to accidental changes.
2. expect xyz
> fix: Prevent accidental clicks on label with boolean control

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
Skipping unnecessary combo class
1. in webflow, add element with class .a, define color
2. add element with class .b, define font size
3. add element with class .a.b  don't define anything
4. paste .a.b into webstudio - see .a .b tokens are added, but no .a.b
> fix: Skip empty combo class when pasting from webflow

- apps/builder/app/shared/copy-paste/plugin-webflow/instances-properties.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
We were currently not setting the tag that comes from webflow properties
2. expect xyz
> fix: Set correct tag when pasting a Block from webflow

- apps/builder/app/builder/shared/tree/index.tsx
- packages/design-system/src/components/tree/tree-node.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/3750
Indicate show=false in the navigator
1. toggle show switch
2. see item in the navigator opacity changed including it's children
> feat: Display navigator item show state

- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/cli/templates/defaults/app/route-templates/xml.tsx
- packages/react-sdk/placeholder.d.ts
Here made constants path easier to access from dynamic paths by automatically replacing __CONSTANTS__ with actual relative path.
This is necessary for vike support which has folder based routes.
> refactor: replace constants in templates

- apps/builder/app/builder/shared/tree/index.tsx
1. when show was not set before, its undefined and needs to be treated as false
2. when instance has no properties at all, show prop needs to be created
1. test with a new instance that has no properties e.g. body
2. test with an instance that had never set show to true or false, so its undefined
> fix: Fix show property handling from navigation

- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-cloudflare-template/tsconfig.json
- fixtures/webstudio-custom-template/package.json
- fixtures/webstudio-custom-template/tsconfig.json
- fixtures/webstudio-remix-netlify-edge-functions/package.json
- fixtures/webstudio-remix-netlify-edge-functions/tsconfig.json
- fixtures/webstudio-remix-netlify-functions/package.json
- fixtures/webstudio-remix-netlify-functions/tsconfig.json
- fixtures/webstudio-remix-vercel/package.json
- fixtures/webstudio-remix-vercel/tsconfig.json
- packages/cli/src/prebuild.ts
- packages/cli/templates/cloudflare/tsconfig.json
- packages/cli/templates/defaults/tsconfig.json
- packages/cli/templates/internal/tsconfig.json
- packages/cli/templates/saas-helpers/tsconfig.json
Here changed tsconfig copying logic to merge instead of override. This simplifies alternative frameworks support.
> refactor: merge tsconfig from CLI templates

- apps/builder/app/dashboard/resources/intro-video.tsx
Recorded a new video series and added them to a playlist. Changed intro vid in dashboard to open the playlist.
2. expect xyz
> docs: change dashboard intro video to use new 101 playlist

- packages/design-system/src/components/css-value-list-item.tsx
Currently it reserves space for the menu when it shouldn't
before
after
2. expect xyz
> fix: style panel layers list rendering

- apps/builder/app/builder/features/sidebar-left/help-popover.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
Decided to move bug report into the help menu, because that's the most likely place people will go anyways
2. expect xyz
> feat: move bug report into help menu

- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/react-sdk/src/css/css.test.tsx
- packages/react-sdk/src/css/css.ts
- packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/label.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
- packages/sdk/src/jsx.ts
Closes https://github.com/webstudio-is/webstudio/issues/3788
Here switched from attribute selector to classes when atomic styles are disabled. This will let us get rid from data-ws-* attributes in generated html.
> feat: use classes for regular styles

- packages/ai/src/chains/command-detect/__generated__/command-detect.system.prompt.ts
- packages/ai/src/chains/command-detect/command-detect.system.prompt.md
Detect route started returning json in markdown instead of pure json `json\n[\"generate-template-prompt\"]\n` 
2. expect xyz
> fix: Ensure AI doesn't return json markdown

- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
- packages/feature-flags/src/flags.ts
This PR moves the `transforms` section behind a feature flag. The section needs to add tooltips for all properties and scale need to have a `lock` behaviour between the `scaleX` and `scaleY` properties.
> chore: move transforms section behind a flag

- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/form-handlers/src/n8n.ts
- packages/form-handlers/src/shared.ts
- packages/sdk/src/resource-loader.ts
Closes https://github.com/webstudio-is/webstudio/issues/3789
Here stopped submitting webhook form with custom action to n8n and requested directly from generated code. This has a few benefits
- self-hosted websites (vercel, netlify) no longer have to setup n8n to support forms
- we can pay n8n for these executions no more
- user no longer have to unsubscribe from emails when setup custom webhook
> feat: submit webhook form without n8n

- packages/prisma-client/package.json
`cp` is a hell command
it works differently depending on does destination folder exists
2. expect xyz
> fix: Prisma generation

- packages/prisma-client/prisma/migrations/20240730131207_clone_project_preview_imagea/migration.sql
Fixes https://github.com/webstudio-is/webstudio/issues/3823
This fixes the issue with preview images set before assets are copied to the new project.
> fix: clone projects with preview images properly

- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/sdk/src/resources-generator.test.tsx
- packages/sdk/src/resources-generator.ts
Closes https://github.com/webstudio-is/webstudio/issues/3826
When user deleted action prop was still converted to resource but resource itself was not created.
> fix: handle empty action in webhook form

- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/db/user-plan-features.server.ts
- apps/builder/app/shared/trpc/trpc-client.ts
- packages/domain/src/trpc/domain.ts
- packages/trpc-interface/src/context/context.server.ts
AuthorisationToken didn't used in case of trpc call for context creation
Closes #3786
Open in incognito
https://fix-plan.development.webstudio.is/builder/d68d6dd1-bc0a-4b21-b5e5-08b7f99336f7?authToken=9d196f63-4256-4e74-98d4-ea678f9f94f1&mode=edit
Add domain, owner plan settings will be used 
> fix: Wrong user is used when counting available custom domains on a free plan

- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/shared.ts
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react-remix/src/webhook-form.tsx
- packages/sdk/src/form-fields.ts
- packages/sdk/src/index.ts
- pnpm-lock.yaml
Form handlers no longer rely on reserved form fields. They are excluded before passing form data to n8n handler.
> refactor: move reserved form fields to sdk

- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/social-preview.tsx
- packages/image/src/image.tsx
Placeholders in page settings and project settings marketplace got wrong size, new version:
2. expect xyz
> fix: fix placeholder images

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
fixes #3821 
Fixes the bug related to updating values for `scrub` and `key strokes`. 
@TrySound @kof was there anything changed in the `CSSValueInputContainer` or something recently. Because, i see the values are `unit` values when it is scrub and key down. But it's sending the whole parsed value when it is just a `onChange` update. Faced a similar issue in #3812 too.
Steps to reproduce
- Add a transition layer.
- Change the values inside the delay and duration using scrub
- Now, try to repeat the same using key up and down arrows.
- The values will reset back to the original values.
> fix: scrub and arrow strokes are not working for transition content and delay

- packages/sdk/src/scope.test.ts
- packages/sdk/src/scope.ts
Fixes https://github.com/webstudio-is/webstudio/issues/3837
This fixes the issue with duplicating classes for different instances. Affected both atomic and non-atomic styles because non-atomic class is used as identifier internally.
> fix: resolve conflicts in variabld and class names

- packages/domain/src/trpc/domain.ts
- packages/postgrest/src/__generated__/db-types.ts
- packages/prisma-client/prisma/migrations/20240731170412_create_production_build/migration.sql
- packages/project-build/src/db/build.ts
- packages/project-build/src/db/deployment.ts
Moved sql for cloning build with production deployment into sql function. Now all clone build logic is removed from codebase.
> refactor: create production build with sql function

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
Was broken while refactoring. Now all background values parsed as layers.
> fix: save custom background size

- apps/builder/app/builder/features/topbar/publish.tsx
Set vanilla export as default and add static site help link
2. expect xyz
> experimental: Set vanilla export as default and add static site help link

- .github/workflows/release.yml
Github started defaulting to tag + commit instead of just tag as release name. So set it here explicitly for future releases.
> build: set tag as release name

- apps/builder/app/shared/marketplace/db.server.ts
- packages/project-build/package.json
- packages/project-build/src/db/build.ts
- packages/project/src/db/project.ts
- pnpm-lock.yaml
Migrated prisma with postgrest in project build.
Got two cases
- in many cases it is ok to use a couple of select queries since round trip is low
- transactions can be avoided with late binding to user
> refactor: migrate project build to postgrest

- .github/workflows/main.yml
- fixtures/ssg/package.json
Prettier makes minified scripts huge.
Need to format only html.
> build: stop formatting minified ssg scripts

- packages/css-engine/src/core/to-value.ts
This PR helps in returning empty strings for keyword values which are hidden from the UI. This support is needed in #3802 backface-visibility in transforms
> experimental: return empty values for hidden keyword properties

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
The current parser is not able to parse all the possible values for `transform-origin` property. The property takes `single`, `double` and `triple` values. So these need to be parsed as `tuples` to support `triple` values now.
> fix: parse transform-origin property values as tuples

- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- packages/design-system/src/components/tree/tree-node.tsx
In some cases copy/paste didn't work
1. Focus on an input in the style panel (width, style source) or name input in settings. Select the text, then copy and paste any instance in the Navigator tree or on the Canvas.
2. Edit text in a paragraph on the Canvas. Select text (single or multiple lines), then press Cmd+X. The paragraph should not be deleted.
3. Select CSS preview text, then select an instance in the Navigator. Press Cmd+C, then Cmd+V.
> fix: broken copy paste when inputs or text selection were used before

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
fixes #3898 
fixes the background-position indicator in the position grid ui.
- Set the background-position-y while is top in the UI to bottom.
- The value is saved as it is a valid keyword for the property.
- The position indicator should be in sync with the canvas.
> fix: background-position indicator in position grid for keywords

- packages/domain/src/trpc/domain.ts
- packages/project/package.json
- packages/project/src/db/project.ts
- pnpm-lock.yaml
Switched to postgrest in "project" package.
Do 3 requests now when load project to get
latest build and latest static build since
they are not inferred as related in postgrest.
> refactor: migrate project to postgrest

- apps/builder/app/builder/shared/code-editor-base.tsx
> fix: Make Navigation Items editable after opening Binding dialog

- packages/sdk-components-react/src/components.ts
- packages/sdk-components-react/src/metas.ts
- packages/sdk-components-react/src/props.ts
Here added RemixForm alias to native form in base sdk components. It should allow users to write at least native forms. Naming was not chosen well though.
> fix: support html form in ssg

- apps/builder/app/builder/features/sidebar-left/panels/pages/folder-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
Part of https://github.com/webstudio-is/webstudio/issues/3914
Clicking on info icon page settings was resulting in input focus, because it was inside the label
2. expect xyz
> fix: Stop wrapping icon with the label

- packages/design-system/src/components/tree/tree-node.tsx
Part of https://github.com/webstudio-is/webstudio/issues/3914
when clicking on collapsible trigger, previously focused item blinks if we don't click event propagation
https://github.com/user-attachments/assets/f31507a3-8ccd-4ef2-97d4-590563724351
2. expect xyz
> fix: fix blinking navigator item focus ring

- apps/builder/app/builder/features/style-panel/sections/position/position-control.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/sections/position/position.tsx
- apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
Part of https://github.com/webstudio-is/webstudio/issues/3914
To allow entering a value from keyboard for all or opposite sides in spacing and position controls, we now support same modifiers as we use for drag guesture
1. open spacing
2. click on padding top number to open input
3. enter value, hold option or shift modifiers, then press enter
4. option places the value into opposite values, top/bottom, left/right, shift changes all sides 
> feat: add shift/option modifiers to spacing and position input popovers

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
Part of https://github.com/webstudio-is/webstudio/issues/3914
Users often type comma instead of dot when entering css value numbers, we want to auto convert them to dot.
1. type 1,2 in width input
2. hit enter, see it was converted to 1.2
3. type 1,2rem
4. hit enter, see it was converted to 1.2 and rem unit was applied
> feat: tolerate comma instead of dot typo in style value input

- apps/builder/app/builder/features/style-panel/sections/transforms/transform-extractors.test.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-extractors.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-skew.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.test.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.ts
This PR adds an extractor for `transform-origin` property which helps in handling individual values of the property. Moved all the extractors to an individual file keeping them aside of utils is making the file too big
- Extract  any `transform-origin` properties using the extractor.
> experimental: add transform-origin extractor for individual property handling in the style-panel

- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/canvas/collaborative-instance.ts
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/canvas-api.ts
- apps/builder/app/shared/dom-utils.test.ts
- apps/builder/app/shared/dom-utils.ts
Closes #3807
Test cases are here 
- [Failing](https://main.development.webstudio.is/builder/5aecde38-362a-4315-8fd6-df7b94a1baad)
- [Fixed](https://fix-styles.development.webstudio.is/builder/5aecde38-362a-4315-8fd6-df7b94a1baad)
They are fail on main and works in current PR
Components with `display: contents` and only text nodes inside now have outline (using range to get rect)
- [Failing](https://main.development.webstudio.is/builder/5aecde38-362a-4315-8fd6-df7b94a1baad)
- [Fixed](https://fix-styles.development.webstudio.is/builder/5aecde38-362a-4315-8fd6-df7b94a1baad)
> fix: Incorrect style calculations

- packages/design-system/src/components/primitives/dnd/use-auto-scroll.ts
When dragging, scrolling starts to early an becomes annoying
2. expect xyz
> fix: navigator scrolling starts too early

- apps/builder/app/routes/rest.data.$projectId.ts
- apps/builder/app/shared/builder-data.ts
- packages/project-build/src/db/build.ts
Load only arrays instead of maps from server
and convert data to map on client.
This reduces download size and server cpu usage.
340 kB -> 269 kB
218 kB -> 170 kB
22%
> refactor: load compact data into builder

- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
- apps/builder/package.json
- packages/css-data/bin/html.css.ts
- packages/css-data/package.json
- packages/css-data/src/__generated__/html.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/css/normalize-type-check.ts
- pnpm-lock.yaml
The new version exports types with normal casing,
the package is completely esm and reexports json with new syntax.
https://github.com/sindresorhus/html-tags/blob/main/index.js#L1
Also reused voidHtmlTags in collapsed instance logic.
> refactor: upgrade html-tags

- apps/builder/app/builder/features/style-panel/sections/transforms/transform-perspective.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
This PR adds support for `perspective` property to be managed under the transforms panel. This behaves very similar to `backface-visibility` property that is under transforms.
- Add the `perspective` property under the transforms using the dropdown.
- You can add `none` or any of the `length` values for the property.
- Able to reset the property and update using the `keyboard`, `scrub` and `up and down` interactions.
> experimental: add ui controls for perspective under transform controls

- apps/builder/app/builder/features/style-panel/sections/transforms/transform-extractors.test.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-extractors.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-origin.tsx
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
This PR allows to parse the `perspective-origin` property value as `tuple`. And added test cases for different possible values. 
- Allows to parse `perspective-origin` values as tuples.
> experimental: parse perspective-origin property value as tuples for x and y values

- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
Here added very basic setup for style object model. Computed all normalized data with "computed" store.
It will let us to integrate style object model
into a few controls and test new engine.
Instance selector now is an input for getComputedStyleDecl to allow looking into parent styles, like we do for flex child.
> refactor: setup reusable style object model

- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.test.tsx
- apps/builder/app/shared/copy-paste/plugin-webflow/styles.ts
Closes https://github.com/webstudio-is/webstudio/issues/3953
We forgot to use hflex/vflex style presets when copying from webflow.
2. expect xyz
> fix: Add hflex/vflex styles

- apps/builder/app/builder/features/sidebar-left/panels/marketplace/marketplace.tsx
- apps/builder/app/builder/features/sidebar-left/panels/marketplace/utils.ts
- apps/builder/app/routes/cgi.image.$.ts
- apps/builder/app/shared/marketplace/db.server.ts
- apps/builder/app/shared/marketplace/router.server.ts
- apps/builder/app/shared/marketplace/types.ts
- packages/project-build/src/db/build.ts
- packages/project-build/src/types.ts
Now marketplace will load compact build from server and convert into webstudio data with maps.
Replaced prisma with postgrest for loading marketplace data.
Fixed asset images on dev.
> refactor: switch to compact build data for marketplace

- packages/postgrest/src/index.server.ts
- packages/project-build/src/db/build.ts
[Discussion Link](https://github.com/orgs/supabase/discussions/28757)
To reduce traffic size, temporarily remove the `.single()` call from the “Build” table until the issue under discussion is resolved.
Notice that the `content-encoding` header is null.
[View Logs](https://vercel.com/getwebstudio/webstudio-builder/9ua91vyJRZbQQyyJoLXEEEBiWtrE/logs?slug=app-future&slug=en-US&slug=getwebstudio&slug=webstudio-builder&slug=9ua91vyJRZbQQyyJoLXEEEBiWtrE&slug=logs&page=1&timeline=past30Minutes&startDate=1724132921408&endDate=1724134721408&searchQuery=%3D%3D%3D%3D%3D%3DENCODING%20IS%3D)
Here, the `content-encoding` header is `null` only for Build `update` requests; everything else has `br` encoding.
[View Logs](https://vercel.com/getwebstudio/webstudio-builder/EdRGvZRBKBJbT4Wzp2AnYFCkSYgg/logs?slu …
> chore: Remove single() PostgREST calls from Build to improve compression

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
fixes #3958 
This PR fixes the `enter` key behaviour for the transition-property combo box. And we updated the sort mechanism at the time of searching to show the most related property at the top. So, users don't need to scroll all the way to see the matched property. 
- Add a transition property layer.
- Now, click on the layer and the UI panel to edit the properties opens up.
- Type `height` or any other property in the combo box.
- Now, press `Enter`. The action should save the value of the property and update the layer.
- Next, search for some random property with a possibility for more results. Eg: `width`. 
- `width` or any other matching value that you searched for should always show up at the top of the list.
- detailed …
> fix: better sorting of transitions and allow `enter` key to save

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/canvas/instance-selected.ts
Closes https://github.com/webstudio-is/webstudio/issues/3984#event-13965863574
- when clicking on canvas reset active sidebar panel state
- when clicking outside of canvas on workspace or pressing escape, the navigator shouldn't close
1. undocked
- click on canvas doesn't close navigator
- open components panel
- click on canvas closes components, and shows navigator
3. docked
- click on canvas always hides any open panel
> fix: when clicking on canvas reset active sidebar panel state

- apps/builder/app/builder/features/blocking-alerts/alert.tsx
increase text contrast for screen size alert by making background darker
2. expect xyz
> fix: increase text contrast for screen size alert

- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.stories.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- packages/sdk/src/page-utils.ts
closes https://github.com/webstudio-is/webstudio/issues/3941
Allow inserting instances into the body when it has text content
1. select body, add text content over props
2. one-click insert any component
3. should insert and wrap text
> fix: allow inserting instances into the body when it has text content

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
Here switched to computed style declarations in color control. Used only to get value (used value) and currentcolor (computed value).
> refactor: switch to style object model in color control

- apps/builder/app/builder/shared/navigator-tree.tsx
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.tsx
Closes https://github.com/webstudio-is/webstudio/issues/3757
When instance on canvas is hovered, we want to highlihgt the same instance in the navigator
2. expect xyz
> feat: Highlight navigator item when canvas instance is hovered

- apps/builder/app/builder/features/ai/ai-fetch-result.ts
- apps/builder/app/routes/rest.ai._index.ts
- apps/builder/app/routes/rest.ai.detect.ts
- packages/ai/src/chains/README.md
- packages/ai/src/chains/command-detect/chain.server.ts
- packages/ai/src/chains/command-detect/schema.ts
- packages/ai/src/chains/copywriter/README.md
- packages/ai/src/chains/copywriter/chain.server.ts
- packages/ai/src/chains/copywriter/schema.ts
- packages/ai/src/chains/operations/chain.server.ts
- packages/ai/src/chains/operations/schema.ts
- packages/ai/src/chains/template-generator/schema.ts
- packages/ai/src/types.ts
- packages/design-system/bin/transform-figma-tokens.ts
- packages/prisma-client/prisma/migrations/20220909124542_builds-data/migration.ts
- packages/prisma-client/prisma/migrations/20220915144008_breakpoints-build_data/migration.ts
we decided to stick for now with zod schema naming without suffix. This makes it consistent.
2. expect xyz
> chore: make Schema suffix consistent

- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
- apps/builder/package.json
- packages/react-sdk/package.json
- pnpm-lock.yaml
Here added more information about property value source like breakpoint, instance, style source and state to style object model.
Now this info can be used in property label (simpler version of property name).
Migrated color, font weight and font family properties to new labels.
> experimental: generate property tooltip from style object model

- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-timing.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
Here replaced NonResettablePropertyName with PropertyInlineLabel. It no longer requires to drill currentStyle. Switched to it in transitions and backgrounds.
Also fixed background labels truncating
> refactor: add property inline label for complex controls

- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/shared/canvas-api.ts
- fixtures/webstudio-custom-template/app/web-vitals.ts
- fixtures/webstudio-custom-template/custom-template-stage/app/web-vitals.ts
- packages/prisma-client/src/prisma.ts
This has always been our convention, I have a feeling our linter used to check this. Now its also important so that AI doesn't give you wrong suggestions.
2. expect xyz
> chore: always use error, not e 

- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/backdrop-filter/backdrop-filter.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/filter/filter.tsx
- apps/builder/app/builder/features/style-panel/sections/text-shadows/text-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-utils.ts
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
- packages/design-system/src/components/section-title.tsx
Ref https://github.com/webstudio-is/webstudio/issues/3914
New property label is used for section titles.
> refactor: migrate to property section label

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
Removed setProperty, deleteProperty and createBatchUpdates from react hook. All parameters can be accessed from global stores.
Note: review with hidden spaces.
> refactor: decouple style updates from react

- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- packages/design-system/src/components/icon-button.tsx
Here migrated menu control and toggle control from style panel
to new style engine and improve UX a bit.
Instead of disabling button, it gets "disabled" style and tooltip with warning. Though user still can use control to override advanced value in place.
> refactor: switch menu and toggle controls to style object model

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
Show `rotate` and `skew` next to the transform list dropdown values.  When applied it should show just the transform in the layer list.
- Add a transform layer list.
- Now, click on the layer to edit the layer and search for transform.
- The dropdown list should show `rotate` and `skew` next to the dropdown list. 
- When added it should show `Transform` alone in the label.
> fix: show rotate and skew in the transform property dropdow listn

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
Color control can be a thin wrapper around color picker
- fixed "inherit" keyword support
- moved intermediate value into color picker
- merge highlight and change low level events
> refactor: improve color picker

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/sections/outline/outline.tsx
- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
- packages/design-system/src/components/input-field.tsx
Simplified color control and reimplemented border color and shadow color as separate controls based on new color picker.
Relaxed "advanced" state in border color, so text field only visually look disabled but still accessible.
Test color, border color, border bottom color and box shadow color.
> experimental: migrate color control to style object model

- packages/sdk-components-react/src/time.test.ts
- packages/sdk-components-react/src/time.tsx
Last PR broke the generator because if there are multiple types exported it starts getting a different namespace
2. expect xyz
> chore: fix types generator in time component

- .github/actions/vercel/action.yaml
- .github/workflows/fixtures-test.yml
- .github/workflows/vercel-deploy-staging.yml
- apps/builder/app/routes/_ui.(builder).tsx
- apps/builder/app/services/builder-auth.server.ts
- apps/builder/app/shared/$resources/sitemap.xml.server.ts
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/router-utils/origins.ts
- fixtures/ssg/package.json
- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-custom-template/package.json
- fixtures/webstudio-remix-netlify-edge-functions/package.json
- fixtures/webstudio-remix-netlify-functions/package.json
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/commands/link.ts
- packages/http-client/jest.config.js
- packages/http-client/package.json
- packages/http-client/src/index.test.ts
- packages/http-client/src/index.ts
- pnpm-lock.yaml
closes #4048
see fixtures
We are still supporting `BUILDER_URL_DEPRECATED` (in a single fixture) and all other fixtures uses modern link format 
> fix: Support new project links in the cli

- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
Here improved property label to show css declaration with computed (used) value.
> feat: show generated css in property label

- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
- packages/feature-flags/src/flags.ts
fixes #3411 
This PR removes the feature flag for css-transforms which makes it available to all the users. So, we might want to test the whole section once.
- Add `translate`, `rotate`, `skew`, `scale`, `perspective`, `backface-visibility`, `perspective-origin` properties in the style panel.
- When any of these properties are added, the property need to be disabled in the dropdown that comes up when clicked on the `+` button at the top.
- Ability to show/hide the first four (translate, rotate, skew, scale) properties.
- Scale `x` and `y` properties can be updated together or individually using the locked behaviour. 
- Ability to set the `x-offset` and `y-offset` properties for the `transform-origin` property.
- When users adds the `z-offset` property too for `transform-origin` using the …
> feat: Add support for css-transforms in style panel

- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/builder/features/style-panel/style-layers-list.tsx
fixes #3797 
Allow layers to be deleted even when the layers are in hidden state. This change should reflect for all the following layer based properties.
- transforms
- translate
- filter
- backdrop-filter
- box-shadow
- text-shadow
- backgrounds
- Add a layer to any of the following layer based proeprties.
- Hide a layer in the list
- Now, delete the layer that is hidden
> feat: allow deleting style layers even when in hidden state

- apps/builder/app/builder/builder.tsx
- apps/builder/app/shared/pubsub/create.ts
https://github.com/webstudio-is/webstudio-saas/issues/317#issuecomment-2317121292
See postMessage
Doesn't work as can be intercepted using `addEventListener`.
In chrome dev console in window and canvas context 
```js
globalThis.postMessage = (...args) => console.log(...args); // no messages
```
```js
globalThis.postMessage({
"action": {
"type": "sendStoreData",
"payload": {
"source": "builder",
"data": [
{
"namespace": "hoveredInstanceSelector",
"value": [
"w2emY6HYI160BmYG9WA6C",
"_BKGofOEhOFV_zLiN0iZk"
]
}
]
}
},
"token": "development-token-2"
}, '*'); // Error in console "Invalid token"
```
```js
window["__webstudio__$__api_token"] // is undefined
```
```js
window.addEventListener(
"message",
e=>console.log({...e.data}), {capture: true}); // token prop is undefined
```
- conceptual …
> chore: Add  postMessage token to secure against Canvas script execution

- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
Refactored flex gap with new style engine.
Synchronize linking both ways not only row=column.
> experimental: migrate gap controls to style object model

- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/sections/size/size.tsx
Most changes is object position switching to new style engine.
> experimental: migrate size section to style object model

- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-radius.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-width.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/utils.ts
Fixes https://discord.com/channels/955905230107738152/1281501486580502568/1281501486580502568
Refactored borders section with new style engine. And fixed the issue with default border radius in shorthand input.
> experimental: migrate borders section to style object model

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
Fixes a number of style panel value parsing errors:
- `transition-duration: 1s, 2s;`
- `width: 1.5px + 1.5rem`
> fix: fix comma parsing in style value and support comma in numbers with math expressions

- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/shared/builder-data.ts
- apps/builder/app/shared/fetch.client.ts
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/trpc/trpc-client.ts
Use authToken token implicitly. Except queue cases like image upload and patches.
Open any project with build or admin share link, upload image.
https://p-a82eaa2b-698e-4d3f-aa46-d4f3eee05fe0-dot-img-fix.development.webstudio.is/?authToken=a74ddf79-2638-47af-9dd1-e62f78187a8d&mode=edit
> fix: Image upload via share link

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-utils.ts
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
Here migrated transitions section to new style engine along with "repeated style" control.
Changed behavior of transition code blue to write non-ephemeral changes caz ephemeral do not have enough visual feedback.
Note: review with hidden spaces
> experimental: migrate transitions to style object model

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx
- packages/design-system/src/components/input-field.tsx
- packages/design-system/src/components/primitives/arrow-focus.tsx
Closes https://github.com/webstudio-is/webstudio/issues/1244
1. see even outer spacing 
2. see border appears when color nears white but doesn't show up when color is far from white
3. See that you can focus color swatch with keyboard arrows
4. See that keyboard enter opens the color picker
5. See that transparent chessboard pattern still works
> fix: fix color control spacing, border and accessibility

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
Closes https://github.com/webstudio-is/webstudio/issues/4075
> feat: forgive semicolon in css value inputs

- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/text-shadows/text-shadows.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
- apps/builder/app/builder/features/style-panel/style-layer-utils.test.ts
- apps/builder/app/builder/features/style-panel/style-layer-utils.ts
Refactoed box shadow and text shadow sections with "repeated style" control and switched to new style engine. Simplified layer label logic.
> experimental: migrate shadows sections to style object model

- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/shared/array-utils.test.ts
- apps/builder/app/shared/array-utils.ts
Refactored image control to maintain styles internally. Important to not this is the first repeated style control. It accepts property and additionally index of repeated style. Would work with future sections like mask-image
We can also improve it to support both singular and repeated styles in the future.
> experimental: migrate image control to style object model

- apps/builder/app/builder/features/style-panel/sections/backdrop-filter/backdrop-filter.tsx
Fixes https://discord.com/channels/955905230107738152/1283966766258585621/1283966766258585621
Accidentally made "backdrop filters" section to render "filter" styles.
> fix: use backdrop-filter styles in section

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/custom-data.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- added custom properties autocomplete in advanced styles
- fixed unit value detecting to not break var()
- show inherited custom properties in advanced styles
- dropped "types" from properties meta
- parse not top level var(), for example inside layers or function as unparsed for now
> experimental: add css custom properties support to advanced styles

- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.tsx
Related to https://github.com/webstudio-is/webstudio/issues/3399
Rewrote keyboard navigation in navigator tree with focus manager from @react-aria/focus. Now navigating with keyboard rely on dom instead of data representation. It will help to integrate ":root" without huge rewrite.
> refactor: switch to react aria focus in navigator

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/shared/nano-states/pages.ts
I noticed people are annoyed by the need to click the pages first, then find the right page and click settings in webflow https://x.com/thepixelgeek/status/1833583918756597875
While this is an advanced need and bloating the UI is not very good, there must be a way to do this, so I added a modifier.
Now you can hold alt/option modifier + click or enter on page button in the top bar  and its going to open the navigator and
Demo: https://share.descript.com/view/mzqZLue17q7
Todo
2. expect xyz
> feat: Open the page settings in one click or key press from the top bar

- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
Last pr introduced a regression when font family is used that isn't in the stakcs
1. type a random font family
2. expect it to land in the dom
> fix:  fix unknown font family support

- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-skew.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.test.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.ts
- apps/builder/app/builder/features/style-panel/sections/transforms/transforms.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/unit-select-options.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/unit-select.test.ts
Switched translate, scale, rotate and skew panels to new style engine. Simplified style updates.
> refactor: migrate transform panels to new style engine

- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
Previously defining a custom stack - comma separated list of fonts, was broken, we only used the first font
1. comma separated fonts, more than one
2. see that its rendered in dev tools and that we don't add a default fallback to it
> fix: allow user to define a custom font stack

- packages/postgrest/supabase/tests/cleanup-builds.sql
- packages/postgrest/supabase/tests/latest-builds-domains.sql
- packages/postgrest/supabase/tests/latest-builds-projects.sql
- packages/postgrest/supabase/tests/project-domains.sql
- packages/prisma-client/prisma/migrations/20240924174536_cleanup/migration.sql
> fix: Resolve failing database tests on production environment

- apps/builder/app/builder/features/topbar/add-domain.tsx
- apps/builder/app/builder/features/topbar/collapsible-domain-section.tsx
- apps/builder/app/builder/features/topbar/domain-checkbox.tsx
- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/entri.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/db/canvas.server.ts
- packages/cli/src/prebuild.ts
- packages/design-system/src/components/checkbox.stories.tsx
- packages/design-system/src/components/checkbox.tsx
- packages/design-system/src/components/section-title.tsx
- packages/domain/src/trpc/domain.ts
- packages/postgrest/supabase/tests/cleanup-builds.sql
- packages/postgrest/supabase/tests/latest-builds-domains.sql
- packages/postgrest/supabase/tests/latest-builds-projects.sql
- packages/postgrest/supabase/tests/project-domains.sql
- packages/prisma-client/prisma/migrations/20240920091253_domain-ordering/migration.sql
- packages/prisma-client/prisma/migrations/20240924174536_cleanup/migration.sql
- packages/sdk/src/schema/deployment.ts
- packages/trpc-interface/src/shared/deployment.ts
closes #2644
- If the user has no custom domains:
- If the user has custom domains:
- No Pro:
- Pro:
- Users can select any checkbox (no Tooltips).
- Current indexing logic:
- If a user has custom domain(s), upon publishing, the `*.wstd.io` domain will receive the meta tag:
```html
<meta name="robots" content="noindex, nofollow">
```
- "With the Pro, you’ll gain the ability to publish to each domain independently!"
- Login as a new non Pro User `pass:vaska@pupkin.ru`
- Create a new Project, Click Publish. Expect  Disabled Checkbox with Tolltip is visible. Publish is Enabled.
- Publish, check it published.
- Add custom domain, Publish, check both are published.
- Login as a Pro User `pass`
- Open new Project. Expect No checkbox. One wstd domain.
- Publish. Expect it published.
- Add …
> feat: Preview by publishing to subdomain only aka staging

- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
- apps/builder/app/builder/shared/fonts-manager/fonts-manager.tsx
Turns out value in controls can also be {type: 'inherit'}, not just type fontFamily
2. expect xyz
> fix: fix font family control when value is inherit

- packages/design-system/src/components/tooltip.stories.tsx
- packages/design-system/src/components/tooltip.tsx
> fix: Tooltip delay removed when doing things other than hovering over tooltip trigger

- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/shared/copy-to-clipboard.tsx
- apps/builder/app/shared/share-project/share-project.tsx
> fix: DNS copy buttons don't trigger/show tooltips like "Copied"

- apps/builder/app/canvas/collapsed.ts
closes #4169
Shoud be tested well as having various scroll/resize/mutation obserevers we have, everything can cause infinite cycle
> fix: canvas autoscroll issue when selecting instances

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/insert.ts
- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/nano-states/misc.ts
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/properties.ts
- packages/design-system/src/components/tree.tsx
- packages/react-sdk/src/core-components.ts
- packages/sdk-components-react/src/body.ws.ts
Now we have a way to change rem and define global css variables
- show root node in navigator behind flag
- show style panel when root is selected
- inherit styles from root
- show advanced styles defined on root in descendents
- show browser styles for root (`html { display: block }`)
- show initial values instead of `inherit` in root typography
- render root styles on canvas
- property label shows root as the source
Note: generated sites are not supported yet
> experimental: add :root support

- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
2 bugs are getting fixed here:
1. when opening fonts manager, we immediately set a value on blur, but when font manager is open this should not be needed
2. when on blur and onhighlight (dropdown)  value is set, its not being parsed as css, so the entire stack: "Arial, Verdana, serif" becomes a value in a stack {type: 'fontFamily', value: ['Arial, Verdana,serif']} instead of  {type: 'fontFamily', value: ['Arial', 'Verdana', 'serif']}
3. expect xyz
> fix: Fix font family bugs

- apps/builder/app/builder/features/sidebar-left/panels/components/insert.ts
- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/package.json
- fixtures/ssg-netlify-by-project-id/app/__generated__/index.css
- fixtures/ssg/app/__generated__/index.css
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/cli/src/prebuild.ts
- packages/css-engine/package.json
- packages/css-engine/src/core/atomic.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/core-components.ts
- packages/react-sdk/src/css/css.test.tsx
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/global-rules.ts
- packages/sdk/src/__generated__/normalize.css.ts
- packages/sdk/src/instances-utils.ts
- packages/sdk/src/normalize.css
- pnpm-lock.yaml
- render layout hack (display: grid; min-height: 100%) as root preset styles
- generate root user styles on published sites
- moved typography preset from body to the root
- bumped a couple of deps
> experimental: generate root styles for published sites

- apps/builder/app/builder/features/inspector/inspector.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/4190
Broke the logic of auto switching to first available panel.
> fix: switch to available inspector panel

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/style-object-model.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-engine/src/core/merger.test.ts
- packages/css-engine/src/core/merger.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
- packages/css-engine/src/schema.ts
- packages/sdk-components-react-radix/src/theme/tailwind-classes.ts
Initially css variable fallback was defined in schema as array though it's actually a single value by spec and may contain commas. We don't have css variables in data yet so should be safe to change schema before too late.
> refactor: simplify var value fallbacks

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/feature-flags/src/flags.ts
He added support for paste style declarations into style source or state. It will let us create collections of custom properties like open props with a few clicks.
The downside is browser prompt with permission confirmation because we use "unsafe" navigator.clipboard.readText() instead of paste event.
https://github.com/user-attachments/assets/8e0153b6-5b98-4f07-bb2c-aac6bc51c6d3
> experimental: allow pasting styles into style source

- apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx
Noticed this 1px misalignment because display inline-block is affected by line-height.
2. expect xyz
> fix: fix color thumb vertical alignment

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/package.json
- packages/design-system/src/components/input-field.tsx
- pnpm-lock.yaml
Here did a few things to improve performance of advanced panel with hundreds if css variables.
- remove unused dom elements
- replaced field-sizing polyfill with css property which is supported in chrome since March
Here's perf stats from local test, both scripting and rendering cut 1s each
Here's the result in branch preview
> refactor: improve advanced section performance

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/shared/dom-utils.ts
- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/props.test.ts
- packages/react-sdk/src/props.ts
We can also do not skip but 
do `<Dom {...{"1unsafe": value}} />` 
BTW that looks useless.
closes #3573
closes https://github.com/webstudio-is/webstudio-community/discussions/190#discussioncomment-10832279
2. expect xyz
> fix: Skip unsafe attribute names on generation

- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
Needed to support all wf presets for fixing this https://github.com/webstudio-is/webstudio/pull/4155
2. expect xyz
> experimental: support nested and attribute selectors

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-and-perspective-origin.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-skew.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
Added support for entering and autocomplete of css variables to dedicated style sections like size and typography.
- color control
- text control
Also improved autocomplete to search with both var(--name) and --name.
> experimental: support css variables in dedicated sections

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-and-perspective-origin.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/design-system/src/components/combobox.stories.tsx
- packages/design-system/src/components/combobox.tsx
- packages/design-system/src/components/menu.stories.tsx
Here improved combobox component to accept
options factory instead of ready to use array.
This function is invoked only when combobox is open.
As a result each of 500 css variables will no longer subscribe to available variables which should reduce scripting time and lagging.
Here's local test
Preview test
> refactor: autocomplete variables lazily

- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
- apps/builder/app/shared/tree-utils.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4192 https://github.com/webstudio-is/webstudio/issues/4202
Figured the way we address instances and render tree should be the same to compute proper drop targets. As a result collection got extra level of depth.
> fix: find proper drop target in collections

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
Added autocomplete for css variables in border width, color and radius. Sadly no support for blob and drawn radius because they require shorthand.
> experimental: support css variables for borders

- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/schema.ts
Here relaxed converting to css variables for fast preview in canvas. Now variables can be used as fallbacks for preview variables.
> experimental: preview css variables on highlight in combobox

- packages/design-system/src/components/combobox.tsx
> experimental: preserve numeric order in css variables autocomplete

- apps/builder/app/builder/features/style-panel/sections/position/inset-control.tsx
- apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
- apps/builder/app/builder/features/style-panel/sections/space/tooltip.tsx
Here migrated space section to new style engine and added support for autocompleting css variables. Rendering css variables was already in place.
> experimental: support css variables in space section

- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4233
When added support for merging root styles when import from marketplace forgot to check only :root styles should be merged and others duplicated.
> fix: duplicate local style sources

- apps/builder/app/canvas/shared/styles.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4232
Broke it when serialized as unparsed without assets transform.
> fix: render images on canvas

- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
Here used computed values with resolved variables to get the list of gradients and preview in backgrounds list.
Though the new gradient field sets whole background-image property when variables are used.
> experimental: support gradient variables

- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/package.json
- pnpm-lock.yaml
closes #3940
Removed logic with undefined replacement on paste as it doesn't look stable.
Seems like `undefined` variables must be decorated or replaced on blur.
Anyway now it has linter
In any expression editor enter
1. `'aaa'  + system` see system is decorated (blue) cursor is after the system
2. `'aaa' system` see system is not decorated 
then add `+` after 'aaa' see system now decorated, cursor is after `+`
> fix: Expression Editor cursor position jumps to wrong place

- apps/builder/app/builder/shared/url-pattern.test.ts
- apps/builder/app/builder/shared/url-pattern.ts
> fix: Publish crashes on pages with dynamic paths ending in ‘?’

- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.ts
- packages/css-engine/src/schema.ts
Here added support for computing css variables inside layers and tuples to support cases like
```css
transition-timing-function: var(--ease), var(--ease-in);
```
> refactor: support css vars in repeated values

- apps/builder/app/canvas/shared/styles.ts
Ref https://github.com/webstudio-is/webstudio/issues/4244
When started rendering all preview var() fallbacks as unparsed. Styles renderer was not able anymore to rerender those.
So here at least temporary just added computed with transform value to always rerender when assets are changed.
> fix: render background styles after builder reload

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
> fix: Can't save Dynamic Page Setting when Title is undefined

- apps/builder/app/builder/shared/expression-editor.tsx
2 bugs
Error messages:
2. expect xyz
> fix: Fix expression editor decoration

- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-utils.ts
One thing I noticed, our implementation does not compose scale and rotate well.
According to spec rotate should be computed before scale but in our implementation rotate goes after scale.
https://www.w3.org/TR/css-transforms-2/#ctm
> experimental: support css variables in transforms

- packages/sdk-components-react-remix/src/remix-form.tsx
closes #4229
https://form-scroll-reset-iodju.wstd.work/?opt=c
> fix: Form filters reset scroll position

- apps/builder/app/builder/features/style-panel/shared/parse-css-fragment.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
Here added support for parsing var() when paste styles and fixed cyclic dependency when use the same var() a few times like `background-image: var(--gradient), var(--gradient)`.
> experimental: improve css variables parsing

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- packages/css-engine/src/core/to-value.ts
Here added a few improvements to repeated style to handle variables properly. For now all changes affects only backgrounds section.
- single layer can use css variable with multiple gradients
- with multiple layers each can have css variable with single gradient
- when single variable inside multiple layers has multiple gradients all thumbnails become transparent, it should be and indicator of invalid gradients
- fixed toggling hidden considering variables
- fixed deleting layers considering variables
- now when single layer has variable with multiple gradients only first gradient can be deleted or toggled
> experimental: improve repeated styles with css variables

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
> fix: CSS unitless properties parsing

- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
> experimental: add more hints about css variables

- apps/builder/app/auth/brand-button.tsx
- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-tabs.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/builder/app/builder/features/style-panel/sections/position/inset-control.tsx
- apps/builder/app/builder/features/style-panel/sections/space/layout.tsx
- apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/builder/shared/image-manager/image-thumbnail.tsx
- apps/builder/app/dashboard/shared/card.tsx
- packages/design-system/src/components/__DEPRECATED__/list.tsx
- packages/design-system/src/components/button.tsx
- packages/design-system/src/components/checkbox.tsx
- packages/design-system/src/components/component-card.tsx
- packages/design-system/src/components/css-value-list-item.tsx
- packages/design-system/src/components/focus-ring.ts
- packages/design-system/src/components/icon-button.tsx
- packages/design-system/src/components/input-field.tsx
- packages/design-system/src/components/panel-tabs.tsx
- packages/design-system/src/components/position-grid.tsx
- packages/design-system/src/components/primitives/small-button.tsx
- packages/design-system/src/components/section-title.tsx
- packages/design-system/src/components/select-button.tsx
- packages/design-system/src/components/switch.tsx
- packages/design-system/src/components/text-area.tsx
- packages/design-system/src/components/toolbar.tsx
- packages/design-system/src/components/tree.tsx
Most controls are affected 2px > 1px
Navigator and project settings lists now use background color instead of outline
2. expect xyz
> feat: Switch to 1px outline for all inputs and buttons, as well as use background color in lists

- apps/builder/app/builder/features/project-settings/project-settings.stories.tsx
- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/features/project-settings/section-publish.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.stories.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/nano-states/project-settings.ts
- apps/builder/app/shared/nano-states/seo.ts
Closes https://github.com/webstudio-is/webstudio/issues/4272
- I moved the only publish setting we have to a separate section, so we can add more in the future.
- Added a settings button in publish dialog
2. expect xyz
> feat: Publish settings section in project settings

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/combobox.tsx
> fix: Input arrow up and down pulls up autocomplete now instead of incrementing

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-timing.tsx
fixes #4197 
This PR improves the UX for `custom` option in the easing functions. Currently it is displaying every time, with the PR we show them only when value added by the users are `custom` and hides it when the entered value doesn't come under custom category.
- Add a transition on a node and then select a value from the dropdown.
- When the dropdown is open and the easing that is added is a valid one. The `Custom` option should be hidden.
- When a custom value is added under the text-area, then the select box should show `Custom` value.
https://github.com/user-attachments/assets/938a8452-ae77-48d9-a395-db6b5ca23851
> fix: show custom option in easing dropdow only when used

- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator-tree.tsx
Users somehow make instances tree inconsistent. For example deleting instances does not delete id from parent children.
I still have not idea how to reproduce this but we need to stop failing users with broken state. Here just logged into console instead of throwing error.
> fix: prevent failing navigator when instances are inconsistent

- packages/design-system/src/components/combobox.tsx
> fix: Сombobox if the menu is opened using the up or down arrows, we want to display all items without applying any filters

- apps/builder/app/builder/builder.tsx
- apps/builder/app/canvas/shared/inert.ts
Style Source looses focus after adding Token
closes #4309
closes #4306
2. expect xyz
> fix: After modifying style, it takes two clicks to select the next instance

- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/custom-data.ts
- packages/css-engine/src/core/merger.test.ts
- packages/css-engine/src/core/merger.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4218
Turned out text-wrap-style got removed but supported alternative text-wrap: wrap was not generated instead.
Now all should work.
Also removed invalid text-wrap-mode: auto
> fix: generate text-wrap-style: auto

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
Closes https://github.com/webstudio-is/webstudio/issues/4292
Here instead of validation error I just remove "create" option. It is consitent with just random invalid name not starting with `--`.
https://github.com/user-attachments/assets/214b71b9-1b88-49de-8eb0-4e815c67486f
> fix: prevent creating css variable with invalid name

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/feature-flags/src/flags.ts
Ref https://github.com/webstudio-is/webstudio/issues/3399 https://github.com/webstudio-is/webstudio/issues/3540
Here added two more features to advanced panel
1. When search for property, user can enter css declarations like `width: 100px; height: 200px;` and press enter instead of searching for property and editing property after creation.
2. When search for property, user can paste css declarations from some theme editor or figma, this is useful interop with other tools
Note: this does not support breakpoints, states or tokens. Declarations are inserted only within currently selected style source and state.
https://github.com/user-attachments/assets/1f37f5d1-11b9-4f05-ae4d-a7c647ae14b6
> feat: support paste styles in advanced section

- apps/builder/app/builder/features/style-panel/property-label.tsx
> fix: show "delete variable" in variable tooltip

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-scale.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/schema.ts
Here added 2 things to improve accessibility of variables for users
1. Added color and unit values preview in autocomplete list
2. Color inputs no longer autocomplete unit values and unit inputs no longer autocomplete color values.
> feat: preview variable values in autocomplete

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
Css variables takes a lot of space inside of input and user need to have text selection work natively. Scrub does not fit in this.
> fix: forbid scrubbing css variables

- .github/actions/vercel/action.yaml
- .github/workflows/migrate.yaml
- apps/builder/package.json
- package.json
- packages/prisma-client/migrations-cli/args.ts
- packages/prisma-client/migrations-cli/cli.ts
- packages/prisma-client/package.json
- pnpm-lock.yaml
This shaves a few seconds from all GitHub actions
> build: drop prisma build

- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- packages/feature-flags/src/flags.ts
We have advanced panel which allows to set any value. No need to have display: contents behind the flag anymore.
> refactor: drop display: contents

- .storybook/main.ts
- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/pubsub/create.ts
- fixtures/ssg-netlify-by-project-id/app/__generated__/index.css
- fixtures/ssg/app/__generated__/index.css
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/design-system/src/components/tree.tsx
- packages/sdk-components-react/src/html-embed.ws.ts
- packages/sdk-components-react/src/markdown-embed.ws.ts
- packages/sdk/src/__generated__/normalize.css.ts
- packages/sdk/src/normalize.css
- Double click now sets cursor to the click position
- Up/Down arrows on a first/last line trying to preserve cursor x position (visible in case of block above block)
- Right/Left arrows switch blocks if cursor is at block begin/end.
2. expect xyz
> feat: Block editing with arrow keys

- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/prebuild.ts
- packages/sdk-components-react/src/xml-node.tsx
closes #4343
https://p-cddc1d44-af37-4cb6-a430-d300cf6f932d-dot-sitemap.staging.webstudio.is/?pageId=FsnS9ui6btzM4W3YELE3Q&authToken=1cdc6026-dd5b-4624-b89b-9bd45e9bcc3d
Resulting xml
https://webstudio-fixture-project-a-0su3o.wstd.work/sitemap.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"><url><loc>https://webstudio-fixture-project-a-0su3o.wstd.work/</loc><lastmod>2024-05-07</lastmod><xhtml:link rel="alternate" hreflang="en" href="https://webstudio-fixture-project-a-0su3o.wstd.work/en"></xhtml:link></url><url><loc>https://webstudio-fixture-project-a-0su3o.wstd.work/olegs-test</loc><lastmod>2024-05-07</lastmod><xhtml:link rel="alternate" hreflang="en" …
```
> fix: Xml namespaces support

- apps/builder/app/builder/features/project-settings/section-redirects.tsx
Fixes https://discord.com/channels/955905230107738152/1300622567740018730
Users cannot specify dynamic path in redirect new path.
> fix: allow project redirects to dynamic paths

- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/route-templates/xml.tsx
closes #3715
paste in chrome
`view-source:https://webstudio-fixture-project-a-0su3o.wstd.work/sitemap.xml`
See title tag exists
> fix: XML Node with title tag nested in any other XML Node breaks document

- packages/design-system/src/components/select.tsx
Up Down arrows in case of huge list caused list jumps, and hover lost in some cases
Replaced with scroll
No jumps.
Both solution shows that select list has overflow. Scroll has no visual issues.
2. expect xyz
> fix: Select jumps if  list is scrollable

- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
fix for
When you click into an instance to edit it, such as a paragraph, the hover outline no longer shows when you hover over other instances. Only in the navigator does the hover show.
Hover outlines now display on all elements except those that have been edited.
https://github.com/webstudio-is/webstudio/issues/4095
Start editing the text, hover outlines are now shown for all elements except edited.
> fix: Show hover outlines during text editing

- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/builder/app/canvas/instance-selection.ts
partial fix for 1 from
https://github.com/webstudio-is/webstudio/issues/4095
The issue was incorrect clickCount count
2. expect xyz
> fix: When quickly selecting different instances, the instance is not selected.

- apps/builder/app/builder/features/pages/page-utils.test.ts
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/app/builder/features/pages/pages.tsx
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/nano-states/variables.ts
Closes https://github.com/webstudio-is/webstudio/issues/4372
Editing another page settings is confusing to users and complicates the logic. Win-win
> feat: select the page when opening the page settings

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- apps/builder/app/builder/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/sidebar-left/sidebar-tabs.tsx
- use one border for both upper and lower part of the left sidebar menu
- use box pseudo element instead of border to avoid overlapping 1 px of the workspace
- make caret visible when user is editing content and parent has an instance outline from hover
2. expect xyz
> fix: avoid left sidebar border covering the workspace outline

- apps/builder/app/builder/features/ai/ai-fetch-result.ts
- apps/builder/app/builder/features/ai/apply-operations.ts
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/navigator/css-preview.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/settings-section.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
- apps/builder/app/builder/features/style-panel/shared/instances-kv.ts
- apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/builder/features/style-panel/style-source-section.test.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/nano-states/misc.ts
We need to avoid accessing instance selector where possible to make logic hookable.
Here moved `$selectedInstance` into awareness and switch to it in many places instance selector is accessed directly.
> refactor: move selected instance store into awareness

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/nano-states/components.ts
Here added $instanceKey store which can be used to access props and variables from any part of the tree. This replaces manual JSON.stringify(selectedInstanceSelector) in a few places.
> refactor: add instance key store

- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/shared/db/user-plan-features.server.ts
- packages/trpc-interface/src/context/context.server.ts
Closes https://github.com/webstudio-is/webstudio/issues/4390
Users requested to setup multiple emails in our default form action.
**Testing**
- try to enter multiple emails in project settings
- submit form from published site
> feat: support contact email list

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/builder/sidebar-left/sidebar-left.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/4158
none is confused with undefined value, replaced it with more explicit "auto".
> fix: prevent closing navigator when drag and drop on canvas

- apps/builder/app/builder/features/components/insert.ts
- apps/builder/app/shared/copy-paste/plugin-embed-template.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- packages/sdk/src/jsx.ts
Here replaced a bunch boilerplaty code with more general findClosestInsertable. This also reduced amount of explicit instance selector calls. Prevented inserting list item into body. Refactored tests with jsx.
> refactor: generalize insertable lookup

- packages/cli/package.json
- packages/cli/src/commands/init-flow.ts
- packages/prisma-client/migrations-cli/cli.ts
- packages/prisma-client/migrations-cli/commands.ts
- packages/prisma-client/migrations-cli/prisma-migrations.ts
- packages/prisma-client/package.json
- pnpm-lock.yaml
No dependencies, windows support, not trying to recreate shell.
> refactor: replace execa with tinyexec

- apps/builder/app/dashboard/projects/project-card.tsx
Remove uppercasing on dashboard card titles and also enable user-select.
2. expect xyz
> fix: Remove uppercasing on dashboard card titles and also enable user-select.

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/navigator/navigator.tsx
- apps/builder/app/builder/features/pages/pages.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/topbar/editor.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/collapsible-section.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/sidebar-left/sidebar-left.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/shared/copy-paste/index.ts
- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/share-project/share-project.tsx
- apps/builder/app/shared/sync/sync-stores.ts
- packages/feature-flags/src/flags.ts
Part 1 Of #3994 
This PR introduces a feature flag, `contentEditableMode`, that hides the `EditorButton` in the top bar. This button is now intended for **testing purposes only** and will **never be used in production**.
1. **Notion-like Editing**: Elements are editable with a single click.
2. **Restricted Element Editing**: Binded elements, such as expressions, are non-editable.
3. **Selective Property Editing**: Only properties for `img` and `link` elements are editable.
Additional changes:
- **Copy/Paste and Drag/Drop**: Disabled to maintain a controlled testing environment.
Refer to the issue `Part 1` for further details on upcoming changes and planned enhancements.
Play play 
- test it on …
> feat: Add builderMode, add mode "edit"

- apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
- packages/design-system/src/components/tooltip.tsx
Partially (or may be fully) Fixes #4406
Closes #4410
Some issues can't be fixed with current tooltips - i.e. if hover from tooltip is going onto the canvas we can't set delay on hover back.
1. Fixes focusable buttons had tooltip.
2. 
2. expect xyz
> fix: Tooltips trigger without a delay

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/pages/page-settings.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.stories.tsx
- apps/builder/app/builder/features/topbar/domain-checkbox.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/routes/_ui.(builder).tsx
- apps/builder/app/routes/rest.patch.ts
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/share-project/share-project.tsx
- packages/authorization-token/package.json
- packages/authorization-token/src/trpc/authorization-tokens-router.ts
- packages/trpc-interface/src/authorize/project.server.ts
- pnpm-lock.yaml
Part 2 Of #3994
Hidden under flag
Links with `?mode=content` from free plan should not work
Content edit shared links have no design mode
2. expect xyz
> feat: Add Content Editor share permission

- packages/trpc-interface/src/authorize/project.server.ts
**Waiting to merge until other areas are complete.**
Craft (Style Guide)
3f260731-825b-486a-b534-e747f0ed6106
Positivus (Agency)
400b1bde-def1-49e0-9b64-e26416d326fa
Visual Designer (Portfolio)
2e802ad7-ef32-48e6-8706-3a162785ef95
Personal (Portfolio)
01f6f1d8-06f5-4a6c-a3b1-89a0448046c7
Has IDs for 4 new templates including Craft and three landing pages.
Appears they need to be added here as packages don't have access to .env.
*Before release, update .env with the templates so this release triggers .env changes.*
Will wait to merge until other areas of this release are finalized.
2. expect xyz
> chore: Add new template IDs to trpc

- apps/builder/package.json
- packages/asset-uploader/package.json
- packages/domain/package.json
- packages/prisma-client/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- pnpm-lock.yaml
Nanoid was used in very old migrations. Forgot we need to run them all when setup new db.
Also bumped nanoid version to the latest.
> build: bring back nanoid to prisma

- apps/builder/app/builder/features/command-panel/command-panel.tsx
- apps/builder/app/builder/features/style-panel/sections/shared/input-popover.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/shared/commands.ts
- packages/design-system/src/components/command.stories.tsx
- packages/design-system/src/components/command.tsx
- packages/design-system/src/components/kbd.tsx
- packages/design-system/src/components/popover.tsx
Ref https://github.com/webstudio-is/webstudio/issues/1696
Here adding new idea into command search.
User searches for an object and can navigate actions over this object. In case of pages user can open page or open pangel settings panel.
https://github.com/user-attachments/assets/a5d6c039-ba6b-4dbb-b0b4-bb9f1782dd20
> experimental: add tabbable command actions

- apps/builder/app/builder/features/style-panel/shared/configs.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4431
> fix: stop failing when retrieve mdn url for css variables

- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- packages/design-system/src/components/tooltip.tsx
closes #4435
Cherry Pick from https://github.com/webstudio-is/webstudio/pull/4428
2. expect xyz
> fix: Page title field becomes unfocused after entering one character

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
fixes #4444 
Fixes a bug related to selecting transition property values that have an exact match. We used to bring up the exact matched values to the top of the list at the time of searching the transition property. But then when we added "properties on the node" feature we need to take care of sorting again. Because these values are always on the top irrespective of the search.
While fixing i noticed another side effect of refactor. We are setting transition property as duration.
- Add a transition property on node.
- Search for `traisiton`, `border` or any common property with full text.
- Use arrows to move and select the values now.
> fix: transition property selection when an exact property matched during search

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/shared/sync-client.test.ts
- apps/builder/app/shared/sync-client.ts
- apps/builder/app/shared/sync/sync-stores.ts
Sync client is getting some shape. Here I abstracted all immerhin related api into SyncObject and added SyncObjectPool to combine multiple objects. Objects are identified by unique name.
> refactor: add sync object pool

- apps/builder/app/shared/sync-client.ts
Fixes payloads with File Map Set etc.
Upload image. see it works
> chore: Use structured clone for transactions

- apps/builder/app/builder/builder.css
- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/shared/loading.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/builder/sidebar-left/sidebar-tabs.tsx
- apps/builder/app/dashboard/header.tsx
- packages/design-system/src/components/list-position-indicator.tsx
A better looking loading screen
2. expect xyz
> feat: make loading screen background dark

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/label.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
- apps/builder/app/canvas/features/build-mode/editable-block-template.tsx
- apps/builder/app/canvas/features/build-mode/editable-block.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/shared/nano-states/canvas.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/react-sdk/src/core-components.ts
ref #3994 
Outline for content mode Editable Childs
https://p-64ece825-f290-4de0-8dac-223c8e88c258-dot-editable-block.development.webstudio.is/?mode=content
Like in notion if eny keyboard event is occured inside outlined block, we hide it
Also + hovers are only on canvas
2. expect xyz
> feat: Add Editable Block Component

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/body.tsx
We want to decouple remix in cli and published sites from remix in builder.
Here I stopped importing remix override components. So now we could migrate CLI to react router without changes in builder.
> refactor: stop importing remix overrides on canvas

- apps/builder/app/builder/features/style-panel/shared/model.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/4458
Collection is not stylable and was checked for display: flex but instead should be skipped.
> fix: show flex child for collection item

- packages/asset-uploader/package.json
- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/delete.ts
- packages/asset-uploader/src/patch.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/upload.ts
- packages/asset-uploader/src/utils/font-data.ts
- packages/asset-uploader/src/utils/get-asset-data.ts
- packages/asset-uploader/src/utils/mime.ts
- packages/asset-uploader/src/utils/size-limiter.ts
- packages/asset-uploader/src/utils/to-bytes.ts
- packages/asset-uploader/tsconfig.json
- pnpm-lock.yaml
Simplified types in asset uploader and covered all exports to enable isolated declarations flag which also potentially may improve checking performance.
> refactor: enable isolated declarations in asset uploader

- apps/builder/app/builder/features/navigator/css-preview.tsx
Huge amount of css variables adds something like 8k of dom elements to highlighted css preview.
Here as fast fix killed inherited styles so at least only root will lag and everything else will not get performance hit.
> fix: stop rendering inherited styles in css preview

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/nano-states/components.ts
- apps/builder/app/shared/nano-states/props.ts
- packages/react-sdk/src/hook.test.ts
- packages/react-sdk/src/hook.ts
- packages/sdk-components-react-radix/src/accordion.tsx
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/navigation-menu.tsx
- packages/sdk-components-react-radix/src/popover.tsx
- packages/sdk-components-react-radix/src/select.tsx
- packages/sdk-components-react-radix/src/sheet.tsx
- packages/sdk-components-react-radix/src/tabs.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
- packages/sdk-components-react/src/select.tsx
We need to remove reliance on instance selector iteration as much as possible. In most cases we need only instance key which is a JSON.stringify or instance selector to access computed props and variables.
Here got rid of instance selector in component hooks and instead made api to accept "instance data" with instance id, key and component inside.
> refactor: remove instance selector from component hooks

- apps/builder/app/builder/features/workspace/canvas-tools/outline/editable-block-instance-outline.tsx
- packages/design-system/src/components/kbd.tsx
ref #3994
Add alt click (insert before)  to editable block
(Both Alt-click are supported, when opening menu, when clicking on menu item even if menu was opened without alt)
2. expect xyz
> feat: Add alt click (insert before)  to editable block

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/editable-block-instance-outline.tsx
- apps/builder/app/builder/shared/commands.ts
In content mode children of the Editable Block can be reordered and deleted now.
ref #3994 
2. expect xyz
> feat: Allow delete/reorder Content Block children in Content mode

- apps/builder/app/builder/features/workspace/canvas-tools/outline/editable-block-instance-outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- packages/design-system/src/components/icon-button.tsx
ref #3994
Menu Icons are now from meta
Red is hover polygon (used to not lost hover) (small quad before was not enough)
2. expect xyz
> feat: Plus button hover polygon and menu icons

- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
When I migrated to 24px inputs height, I forgot this one.
2. expect xyz
> fix:  flex dropdown items height consistency

- apps/builder/app/builder/features/topbar/builder-mode.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
- apps/builder/app/builder/shared/commands.ts
- 24px height for menu items
- drive-by: content mode + shortcut cmd+c
2. expect xyz
> experimental: Set the menu items height along with the content mode shortcut and name

- .github/workflows/main.yml
- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/footer/footer.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[content-block]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[content-block]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/routes/[content-block]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/component-generator.ts
1 commit = fixtures
2nd commit = code changes
3rd = size changes
ref #3994
Publish result:
https://webstudio-fixture-project-a-0su3o.wstd.work/content-block
See fixtures for generated code.
2. expect xyz
> feat: Content Block publish component generator

- apps/builder/app/builder/features/style-panel/sections/shared/value-text.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
fixes #4439 
While displaying tokens in the spacing section, it gets too cluttered if the css-variable names are long. This PR will truncate text, to make it less cluttered.
- Create a super long css-variable.
- Now, use the variable for padding/margin.
> fix: truncate text for while showing text for padding and margin tokens

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/shared/sync/command-queue.ts
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/routes/rest.patch.ts
- apps/builder/app/shared/builder-data.ts
- apps/builder/app/shared/sync-client.test.ts
- apps/builder/app/shared/sync-client.ts
- apps/builder/app/shared/sync/sync-stores.ts
Another layer in sync engine is composable storage.
Now you can specify a chain of storages. Each can listen transactions to update some state. Though subscription for state is invoked one by one until non-undefined is provided.
See tests to understand API.
Here I also migrated our server data loading and synchronization to this storage api.
> refactor: add server as storage to sync engine

- apps/builder/app/builder/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
Before, there was no way to select a link inside the text on the canvas in content mode (it was only possible through the navigation menu).
Now, when the cursor is over a link, it is displayed in the settings panel.
This does not work with newly created links. Will do in the following PR.
https://github.com/user-attachments/assets/7472bfd1-3cf7-4ad5-9d39-1bd2effdab26
2. expect xyz
> feat: Allow select link selector during text edit

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- packages/react-sdk/src/core-components.ts
Ref https://github.com/webstudio-is/webstudio/issues/3994
> experimental: show only block and ts children in navigator

- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/prebuild.ts
- packages/sdk-components-react/src/__generated__/xml-time.props.ts
- packages/sdk-components-react/src/components.ts
- packages/sdk-components-react/src/metas.ts
- packages/sdk-components-react/src/props.ts
- packages/sdk-components-react/src/xml-time.tsx
- packages/sdk-components-react/src/xml-time.ws.ts
Tested with fixtures.
2. expect xyz
> feat: Create xml-time component to convert time to iso string in xml documents

- apps/builder/app/canvas/interceptor.ts
Prevent forwarding the click event on an input element when the associated label has a "for" attribute
In real browser emulates click event on input when label is clicked.
closes #4513
2. expect xyz
> fix: Prevent focus when selecting form label in builder

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/matcher.test.tsx
- apps/builder/app/shared/matcher.ts
- packages/sdk-components-react-radix/src/tabs.ws.ts
Now we have two more matcher for direct children and descendants. Eventually they will replace "detachable" flag in meta.
Here used new matchers to prevent user from deleting last tab trigger or last tab content which cannot be readded from components panel.
Added matchers check to "delete" and "cut"
> refactor: add child and descendant matchers

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
Forgot to clear fallback after variable values preview.
> refactor: remove variable fallback on autocomplete

- .github/workflows/release.yml
We often forget to publish CLI packages after release and get some bug reports from users because of it.
Here invoked publishing along with release generation when tag is pushed.
The version is taken from release name and
will no longer be committed to repo.
Gonna test it once merged.
> build: automatically publish CLI along with release

- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
- apps/builder/app/canvas/instance-selected.ts
ref #3994
Scroll is seriously changed so need to be carefully tested.
As side effect this fixes "When clicking "Content Block" in the navigator, nothing is scrolled into view."
`+` fixed: When inserting a template instance, it should be selected automatically.
2. expect xyz
> fix: Scroll to display contents elements.

- apps/builder/app/builder/features/style-panel/shared/style-section.tsx
Forgot to set the default  for chevron to be hidden when there are no items and no colapsible property passed explicitely
2. expect xyz
> fix: hide chevron consistently when there are no items in the style panel section

- apps/builder/app/shared/share-project/share-project.tsx
> fix: When a mode like "Content" is selected in share links, it's odd that clone and copy are checked and blue

- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/share-project/share-project.stories.tsx
- apps/builder/app/shared/share-project/share-project.tsx
- packages/authorization-token/src/db/authorization-token.ts
- packages/authorization-token/src/trpc/authorization-tokens-router.ts
- packages/postgrest/src/__generated__/db-types.ts
- packages/prisma-client/prisma/migrations/20241207052014_can-publish/migration.sql
- packages/project-build/package.json
- packages/project-build/src/db/build.ts
- pnpm-lock.yaml
> feat: Add "can publish" to content editors

- apps/builder/app/canvas/features/build-mode/block.tsx
> fix: Do not show empty content blocks in preview mode

- apps/builder/app/builder/features/ai/apply-operations.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Turns our delete does not clear instances when detachable check fails. Good news: new child constraints were added only to tabs. Bad news: I think deleting pages kept instances in the build, oops.
Fixed reparent and added checks for delete only where necessary.
How to test
- insert tabs content
- delete second trigger and content
- reposition trigger
- it is duplicated
> fix: stop duplicating required children on reparent

- packages/image/src/image-dev.stories.tsx
- packages/image/src/image-optimize.ts
- packages/image/src/image.tsx
- packages/image/tsconfig.json
React components need to be annotated with ForwardRefExoticComponent until we migrate to react v19
> refactor: enable isolated declarations for image package

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
We decided to show whole block tree so clients could open popover or tab content and edit text inside.
> fix: show whole block tree to support radix components

- apps/builder/app/builder/builder.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/dashboard/dashboard.tsx
- apps/builder/app/dashboard/projects/project-card.tsx
- apps/builder/app/dashboard/projects/projects.tsx
- apps/builder/app/dashboard/projects/thumbnail.tsx
- apps/builder/app/env/env.server.ts
- apps/builder/app/routes/_canvas.canvas.tsx
- apps/builder/app/routes/_ui.(builder).tsx
- apps/builder/app/routes/_ui.dashboard.tsx
- apps/builder/app/routes/cgi.image.$.ts
- apps/builder/app/shared/nano-states/misc.ts
- packages/image/src/image-loaders.ts
Builder rely on cloud based image resolution which does not require additional configuration. Here I dropped IMAGE_BASE_URL env and replaced bypassing it to loader with loader default.
> refactor: drop image base url from builder

- packages/trpc-interface/src/authorize/project.server.ts
FinanceFlow
e761178f-6ac6-47f6-b881-56cc75640d73
Ascend
ef82ee51-e4d6-4a69-a4cc-7bf1dee65ed7
2. expect xyz
> chore: add ascend and financeflow to trpc

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/marketplace/card.tsx
- apps/builder/app/builder/features/pages/search-preview.tsx
- apps/builder/app/builder/features/pages/social-preview.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
- apps/builder/app/builder/features/project-settings/section-marketplace.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/dashboard/projects/thumbnail.tsx
- apps/builder/app/routes/cgi.image.$.ts
- apps/builder/app/shared/nano-states/misc.ts
- packages/cli/src/prebuild.ts
- packages/image/src/image-dev.stories.tsx
- packages/image/src/image-loader.test.ts
- packages/image/src/image-loaders.ts
- packages/image/src/image-optimize.test.ts
Split our saas image loader into separate function which is passed directly everywhere without createImageLoader.
> refactor: pass wsImageLoader directly

- fixtures/ssg-netlify-by-project-id/app/constants.mjs
- fixtures/ssg/app/constants.mjs
- fixtures/webstudio-cloudflare-template/app/constants.mjs
- fixtures/webstudio-remix-netlify-edge-functions/app/constants.mjs
- fixtures/webstudio-remix-netlify-functions/app/constants.mjs
- fixtures/webstudio-remix-vercel/app/constants.mjs
- packages/cli/templates/defaults/app/constants.mjs
- packages/cli/templates/netlify-edge-functions/app/constants.mjs
- packages/cli/templates/netlify-functions/app/constants.mjs
- packages/cli/templates/ssg-netlify/app/constants.mjs
- packages/cli/templates/ssg-vercel/app/constants.mjs
- packages/cli/templates/ssg/app/constants.mjs
- packages/cli/templates/vercel/app/constants.mjs
- packages/image/src/image-loader.test.ts
- packages/image/src/image-loaders.ts
- packages/sdk-components-react/src/image.tsx
Asset base url is now automatically added by builder or component generator and passed to loader as is.
Saas loader removes /cgi/asset when detected.
All other loaders just use full relative path without changes which simplifies them a lot.
> refactor: remove assetBaseUrl from image loaders

- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/tabs.tsx
- packages/sdk-components-react/package.json
- packages/sdk-components-react/src/vimeo-play-button.tsx
- pnpm-lock.yaml
https://vercel.com/blog/demystifying-inp-new-tools-and-actionable-insights
https://inp-inp-inp-inp.wstd.work/
https://no-inp-no-no.wstd.work/
2. expect xyz
> feat: Experimental INP fix

- apps/builder/.env
- apps/builder/.gitignore
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/stores.ts
- apps/builder/app/env/env.server.ts
- apps/builder/app/routes/_canvas.canvas.tsx
- apps/builder/app/routes/cgi.image.$.ts
- apps/builder/app/shared/asset-client.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
We hardcoded asset base url in image loader.
Though locally different one is not resolved properly. So aligned local and deployed image paths with /cgi/asset/ everywhere. Images are now uploaded to public/cgi/asset locally.
> refactor: hardcode asset and upload path in builder

- @types/detect-font.d.ts
- apps/builder/app/canvas/features/webstudio-component/get-browser-style.ts
- apps/builder/package.json
- pnpm-lock.yaml
Looks like we don't use it for a long time.
Browser style is used only to convert keywords into unit values.
> refactor: drop detect-font

- apps/builder/app/builder/features/style-panel/property-label.tsx
fixes #4411 
When `PropertyLabel` is used inside `ToggleGroupControl` if we don't stop after handling the reset. The event keeps bubbling up and effect the reset shortcut handler of `ToggleGroupControl` and ends up resetting the whole group.
- Add a `div` and make the parent's display as `flex`
- And now add some values for `sizing` under the `flex-child`. 
- Click on advanced option, and use `Alt + click` on any of the property label.
More details about reproducing are here #4411 
> fix: multiple property reset when using shortcuts on toggle groups

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/pages/page-settings.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/floating-panel.tsx
- apps/builder/app/builder/sidebar-left/sidebar-left.tsx
- packages/design-system/src/components/card.tsx
- packages/design-system/src/components/css-value-list-item.stories.tsx
- packages/design-system/src/components/dialog.tsx
- packages/design-system/src/stitches.config.ts
We need to make the dependency on 240px size more clear, its the sidebar width
2. expect xyz
> chore: Use sidebarWidth variable everywhere

- apps/builder/app/builder/shared/code-editor-base.tsx
> fix: Code Mirror autocomplete click closes popovers and dialogs

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
closes #4585
Do not show description panel if zero descriptions are available
2. expect xyz
> fix: Empty description space for color-inputs in the combobox

- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
> fix: Pasting gradient into color field breaks CSS parser

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/value-editor-dialog.tsx
Added a bunch of other value types for which we show maximize button in css value input
2. expect xyz
> fix: improve complex value detection to show maximize button

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/awareness.ts
Ref https://github.com/webstudio-is/webstudio/issues/4364
The new $selecedInstancePath is a list of co-located instance and its selector from selection until the root. It allows to skip the knowledge about missing collection item and removes boilerplate of resolving "instance" from selector.
> refactor: add instance path

- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/nano-states/index.ts
- More discoverable export dialog access from the menu
- shift+P and shift+E shortcuts, same es webflow 
2. expect xyz
> feat: Add export dialog to the menu, add shortcuts shift+P and shift+E

- apps/builder/app/canvas/instance-selected.ts
> fix: Canvas crash with Failed to execute 'matches' on 'Element': ':current' is not a valid selector.

- apps/builder/app/shared/matcher.test.tsx
- apps/builder/app/shared/matcher.ts
- packages/template/src/jsx.test.tsx
- packages/template/src/jsx.ts
- packages/template/tsconfig.json
Here added new renderTemplate function which outputs simplified format with arrays instead of maps and "children" array to describe roots.
This format is partial of webstudio fragment but does not implement it fully.
Added support for top level fragment to allow having multiple roots.
> refactor: simplify template format

- apps/builder/app/builder/features/workspace/canvas-tools/block-editor-context-menu.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/nano-states/instances.ts
ref #4595 
- Enter on block creates new paragraph, text or h1 block if any exists in templates
- New text added through `/` command is fully selected
- If after command block is empty it's replaced with another block
- esc now closes the `/` menu
- backspace on empty now deletes block
Play here
https://p-0b40acbe-34df-4475-8f52-120d5b97da4e-dot-enter.development.webstudio.is/?mode=content
to reproduce
`Enter`, `/` select Heading, type `blabla`, then `/`, then `Enter`
2. expect xyz
> experimental: Enter support

- @types/arrgv.d.ts
- apps/builder/app/builder/features/settings-panel/curl.ts
- apps/builder/package.json
- pnpm-lock.yaml
Created new package https://github.com/TrySound/args-tokenizer for curl parser. Might be useful in combination with tinyexec.
> refactor: migrate curl parse to args-tokenizer

- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
Looks like parent/child constraints will work only for tags and not for components.
> fix: remove parent/child constraints from navigation menu

- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-utils.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/instance-hovering.ts
- packages/react-sdk/src/core-components.ts
> experimental: Rich Text list item support

- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/commands.ts
Accidentally positioned on the right instead of left
Also fixes shfit+P and shift+E when pressed in the inputs 
https://github.com/webstudio-is/webstudio-community/discussions/208
https://github.com/webstudio-is/webstudio/issues/4638
2. expect xyz
> fix: fix bindings panel placement

- apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx
Title for css fragment was forgotten 
2. expect xyz
> fix: Fix CSS fragment editor dialog title

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- fixtures/ssg/app/__generated__/index.css
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/index.css
- fixtures/webstudio-remix-netlify-functions/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/react-sdk/src/core-components.ts
- packages/react-sdk/src/props.ts
- packages/sdk-components-react/src/blockquote.ws.ts
- packages/sdk-components-react/src/heading.ws.ts
- packages/sdk-components-react/src/link.ws.ts
- packages/sdk-components-react/src/list-item.ws.ts
- packages/sdk-components-react/src/paragraph.ws.ts
ref #4595
https://p-cfc5b051-3b7a-4a59-a994-44d8d2f8b836-dot-styles.development.webstudio.is/
The following components are considered non-collapsible in **Edit** and **Content** modes:  
*Paragraph*, *Heading*, *ListItem*, *Blockquote*, *Link*.
We are adding placeholders for these components when they are empty, using the following logic (partially inspired by Notion):  
1. **If a component is empty and not being edited**, we display the same label as shown in the components tree.  
2. **If a component is empty and being edited**, the behavior depends on its location:  
- **Inside a content block:**  
- For *Paragraph*, we display: `Write something or press '/' for commands...`.  
- For all other components, we display the label.  
- **Outside a content block:**  
- Always display the …
> experimental: Use placeholders for editable elements

- packages/design-system/src/components/scroll-area.tsx
Because we don't have enough space and  touch device user scrolls the entire area directly anyways
2. expect xyz
> chore: remove increased target size for scroll thumbs

- apps/builder/app/builder/features/components/components.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.stories.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/components.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/sdk-components-react/package.json
- packages/sdk-components-react/src/button.template.tsx
- packages/sdk-components-react/src/button.ws.ts
- packages/sdk-components-react/src/list.template.tsx
- packages/sdk-components-react/src/list.ws.ts
- packages/sdk-components-react/src/templates.ts
- packages/template/src/index.ts
- packages/template/src/jsx.test.tsx
- packages/template/src/jsx.ts
- packages/template/src/template.ts
- pnpm-lock.yaml
- vite.sdk-components.config.ts
Here added one more description file for components `*.template.tsx`.
It is decoupled from component meta to fix the issue with some templates like Sheet being treated as components though we don't have actual components with this name.
Another reason is have it separately to not include builder specific code and dependencies into CLI and published websites. Template package is defined as optional in peer dependencies meta.
In this PR migrated only Button and List as examples. There is still not support for data sources and styles.
Added support for text placeholders in children
> refactor: add templates meta support

- packages/react-sdk/package.json
- packages/sdk-components-react/package.json
- pnpm-lock.yaml
Fixes https://github.com/webstudio-is/webstudio/issues/4654
template package is private for now so better move it into dev dependencies.
> fix: avoid cli installing private template package

- apps/builder/app/builder/features/breakpoints/width-input.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/settings-section.tsx
- apps/builder/app/builder/features/style-panel/sections/space/layout.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/form-utils/use-ids.ts
- apps/builder/app/shared/share-project/share-project.tsx
- packages/design-system/package.json
- packages/design-system/src/index.ts
- pnpm-lock.yaml
React has builtin useId, now we can get rid of radix package for it.
> refactor: replace radix/react-id with useId from react

- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
- packages/sdk-components-react-radix/src/shared/theme.ts
- packages/sdk-components-react-radix/src/tabs.template.tsx
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/templates.ts
- support `&[data-state=active]` as state in css parser
- added more theme values
- migrated radix tabs to jsx templates
> refactor: rewrite radix tabs template with jsx

- packages/sdk-components-react-radix/src/checkbox.template.tsx
- packages/sdk-components-react-radix/src/checkbox.ws.ts
- packages/sdk-components-react-radix/src/switch.template.tsx
- packages/sdk-components-react-radix/src/switch.tsx
- packages/sdk-components-react-radix/src/switch.ws.ts
- packages/sdk-components-react-radix/src/templates.ts
Here avoided using variables and instead made Switch uncontrolled which should cover most use cases where variables just complicates everything.
Checkbox already works this way.
Both checkbox and switch templates are migrated to jsx.
> refactor: rewrite radix switch and checkbox templates with jsx

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/shared/styles.ts
Fixes this
with 
2. expect xyz
> fix: Blockquote editing placeholder

- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/services/csrf-session.server.ts
- apps/builder/app/shared/dom-utils.stories.tsx
- apps/builder/app/shared/dom-utils.ts
closes  #4631
tested in Safari, FF, Chrome
2. expect xyz
> fix: Scroll into view doesn't work any more for scrollable divs 

- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4678
Missed a case markdown can insert multiple new instances.
> fix: insert multiple instances when paste from markdown

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
There is no blur event in FF and Safari when focused node is detached from the DOM
2. expect xyz
> fix: Support content editable in FF and Safari

- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/canvas-api.ts
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/sync/sync-stores.ts
Got rid of computing tags from dom in canvas. Now tags are computed from possible preset styles and tag prop if available.
> perf: compute tags statically

- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/package.json
- packages/ai/package.json
- packages/sdk-components-react/package.json
- packages/sdk-components-react/src/content-embed.template.tsx
- packages/sdk-components-react/src/markdown-embed.template.tsx
- packages/sdk-components-react/src/markdown-embed.tsx
- pnpm-lock.yaml
Markdown embed now can convert tables like this into html
```
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |
```
Both markdown embed and content embed have descendants to style tables. Added table, row, header and cell.
> feat: support tables in content and markdown embed

- apps/builder/app/builder/features/command-panel/command-panel.tsx
- packages/template/src/template.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4689
While refactoring with new component templates
forgot to register them in command panel.
Looks like the prod is affected a little too
> fix: restore missing components in command panel

- packages/sdk-components-react-radix/src/accordion.template.tsx
- packages/sdk-components-react-radix/src/accordion.ws.ts
- packages/sdk-components-react-radix/src/collapsible.template.tsx
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/templates.ts
Css variables in templates are easier to understand now.
> refactor: rewrite collapsible and accordion templates with jsx

- packages/sdk-components-react-radix/src/checkbox.template.tsx
- packages/sdk-components-react-radix/src/radio-group.template.tsx
- packages/sdk-components-react-radix/src/radio-group.ws.ts
- packages/sdk-components-react-radix/src/select.template.tsx
- packages/sdk-components-react-radix/src/select.ws.ts
- packages/sdk-components-react-radix/src/templates.ts
- got rid of variables and expressions in template, both use defaultValue
- returned back radix label in checkbox template
> refactor: rewrite radio group and select templates with jsx

- apps/builder/app/builder/features/settings-panel/controls/code.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/4589
Just added xml parser before html one.
> fix: prevent auto closing valid xml in svg

- packages/sdk-components-react-radix/src/navigation-menu.template.tsx
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
- packages/sdk-components-react-radix/src/shared/styles.ts
- packages/sdk-components-react-radix/src/templates.ts
> refactor: rewrite radix navigation menu template with jsx

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
closes https://github.com/webstudio-is/webstudio/issues/4550
1. Detect radix dropdown,select and co as part of the form controls that also implement keyboard shortcuts and don't use global shortcuts on these
2. Simplify shortcut settings by having just one setting that works for everything: form tags, content editable, radix
3. expect xyz
> fix: Fixes hotkeys on radix select, dropdown etc

- apps/builder/app/builder/shared/code-editor-base.tsx
> fix: Gradient code with var goes away after clicking out

- .github/workflows/cli-r2-static.yaml
- fixtures/ssg-netlify-by-project-id/.webstudio/data.json
- fixtures/ssg-netlify-by-project-id/package.json
- fixtures/ssg/.webstudio/data.json
- fixtures/ssg/package.json
- fixtures/webstudio-cloudflare-template/.webstudio/data.json
- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/package.json
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/package.json
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/package.json
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/sync.ts
- packages/cli/src/prebuild.ts
- packages/http-client/src/index.ts
We figured assets can be loaded from shared url without additional manipulation. Here got rid of asset origin detection and dropped excessive --preview flag. Now local, staging and prod will work automatically.
> refactor: drop --preview flag from CLI

- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/canvas/shared/styles.ts
closes #4615
Also fixes various of other issues. 
2. expect xyz
> fix: Clicking out of input without selecting dropdown still selects it

- .github/workflows/fixtures-test.yml
- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
Closes https://github.com/webstudio-is/webstudio/issues/4670
> fix: remove "show" toggles on descendant component

- fixtures/webstudio-custom-template/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/templates/defaults/app/route-templates/xml.tsx
- packages/react-sdk/src/runtime.ts
- packages/sdk-components-react/src/xml-node.tsx
closes #4695
Also allow link in xml
closes #4401
2. expect xyz
> fix: Sitemap Index - Unexpected Server Error

- apps/builder/app/root.tsx
- apps/builder/app/routes/_ui.tsx
- apps/builder/app/shared/nano-states/props.ts
closes #4403
We have no way to show good errors on naviagation errors (remix does not support this)
Here I reduced amount of reloads on link clicks on preview
2. expect xyz
> fix: Rate limit on shared link clicks

- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/shared/nano-states/pages.ts
- apps/builder/app/shared/pages/use-switch-page.ts
> fix: Jump links don't work in preview after first click

- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
Removed logic based on preventDefault
2. expect xyz
> fix: Deleting in the code editor causes the instance on the canvas to be removed.

- apps/builder/app/builder/builder.tsx
> fix: When toggling undock navigator, outlines show above navigato

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- packages/design-system/src/components/input-field.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
Need to be heavily tested
closes #4511 
Fixes:
2. expect xyz
> fix: Various Scrub bugs and issues

- apps/builder/app/builder/features/ai/apply-operations.ts
- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/matcher.test.tsx
- apps/builder/app/shared/matcher.ts
Every time somebody is facing invalid constraint issue whole tree is blocked from deleting instances except the problematic one with actual issue.
Here rewrote detachability check to validate only ancestors and avoid traversing potentially problematic siblings.
> fix: relax detaching constraint

- apps/builder/app/builder/features/marketplace/templates.tsx
Fixes https://github.com/webstudio-is/webstudio/issues/4723
We removed body from template data but didn't fix roots. Later insertion logic started to rely on these roots.
> fix: insert properly from marketplace

- apps/builder/app/builder/features/topbar/publish.tsx
- packages/trpc-interface/src/shared/deployment.ts
This should fix users confusion when they try to publish from development version.
> fix: make publish error more descriptive

- apps/builder/app/canvas/shared/styles.ts
Safari does not change the cursor based on 
`-webkit-user-select: none;`
We need to explicitly set `cursor`
ref #1818
2. expect xyz
> feat: Make canvas cursor style compatible across all browsers

- apps/builder/app/builder/features/command-panel/command-panel.tsx
- apps/builder/app/builder/features/components/components.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/sdk-components-react/src/templates.ts
- packages/sdk-components-react/src/webhook-form.template.tsx
- packages/sdk-components-react/src/webhook-form.ws.ts
- packages/template/package.json
- packages/template/src/jsx.test.tsx
- packages/template/src/jsx.ts
- pnpm-lock.yaml
Big one
- added `new Variable(name, initialValue)` to defined unique variable
- added `expression\`${variable}\`` to access variables by reference
- added `new Action(args, expression\`\`)` support
- added `ws:show` prop which is converted to data-ws-show under the hood
All these features are necessary to represent all webhook form features. They also may be handy in tests.
> refactor: rewrite webhook form template with jsx

- packages/sdk-components-react/src/__generated__/vimeo.props.ts
- packages/sdk-components-react/src/__generated__/youtube.props.ts
- packages/sdk-components-react/src/components.ts
- packages/sdk-components-react/src/metas.ts
- packages/sdk-components-react/src/props.ts
- packages/sdk-components-react/src/templates.ts
- packages/sdk-components-react/src/vimeo-play-button.ws.ts
- packages/sdk-components-react/src/vimeo-preview-image.ws.ts
- packages/sdk-components-react/src/vimeo-spinner.ws.ts
- packages/sdk-components-react/src/vimeo.template.tsx
- packages/sdk-components-react/src/vimeo.tsx
- packages/sdk-components-react/src/vimeo.ws.ts
- packages/sdk-components-react/src/youtube.stories.tsx
- packages/sdk-components-react/src/youtube.template.tsx
- packages/sdk-components-react/src/youtube.tsx
- packages/sdk-components-react/src/youtube.ws.ts
closes #1747
closes #3741
closes #3649
Suggestions:
Additions:
2. expect xyz
> feat: YouTube Component

- packages/design-system/src/components/combobox.tsx
That's because LI items collapsed under Flex
2. expect xyz
> fix: Items in combobox have zero height

- apps/builder/app/builder/features/project-settings/project-settings.stories.tsx
- apps/builder/app/builder/features/project-settings/section-general.tsx
Now there is an official place where to find the project id, besides the URL where user can't know
2. expect xyz
> feat: add a project id to project settings dialog

- .storybook/main.ts
Fix obvious typos.
- [] hi @kof, I need you to do
> chore: Update main.ts

- packages/sdk-components-react/src/vimeo.template.tsx
- packages/sdk-components-react/src/youtube.template.tsx
When clicking on object position on image preview in the style panel builder crashes because object-position: cover doesn't exist
2. expect xyz
> fix: fix vimeo and youtube player crash in the builder

- fixtures/ssg-netlify-by-project-id/app/__generated__/_index.tsx
- fixtures/ssg/app/__generated__/[another-page]._index.tsx
- fixtures/ssg/app/__generated__/_index.tsx
- fixtures/webstudio-cloudflare-template/app/__generated__/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/[world]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[class-names]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[content-block]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[expressions]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/component-generator.ts
Closes https://github.com/webstudio-is/webstudio/issues/4749
Classes were merged without considering ternaries like this
```js
"cls1" + " " + condition ? "cls2" : ""
```
which made condition part always truthy
Fixed by generating template literal instead of concatenation operator.
> fix: merge generated classes and class prop properly

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- packages/design-system/src/components/select.tsx
Allow resetting optional items in the following cases:
1. The item has a value and undefined defaultValue
2. The item has a value, defaultValue is not undefined and is not equal to value
Remove empty prop check https://github.com/webstudio-is/webstudio/blob/42af9210934f0c5c8fb1f1943bd66cd086c85032/packages/sdk-components-react/src/head-meta.tsx#L27
Switch on undefined.
Case 1. 
Select value, reset value
Case 2. 
Unselect 
Reset to default.
> fix: Allow reset optional items

- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[head-tag]._index.tsx
- fixtures/webstudio-remix-vercel/package.json
- packages/sdk-components-react/src/head-link.tsx
- packages/sdk-components-react/src/head-meta.tsx
- packages/sdk-components-react/src/head-title.tsx
- packages/sdk-components-react/src/xml-node.tsx
This #4759 allows to not filter out empty props
2. expect xyz
> feat: Do not filter out empty props

- fixtures/react-router-docker/Dockerfile
- fixtures/react-router-docker/app/constants.mjs
- fixtures/react-router-docker/app/routes/[_image].$.ts
- fixtures/react-router-docker/package.json
- packages/cli/package.json
- packages/cli/templates/react-router-docker/Dockerfile
- packages/cli/templates/react-router-docker/app/constants.mjs
- packages/cli/templates/react-router-docker/app/routes/[_image].$.ts
- packages/cli/templates/react-router-docker/package.json
- pnpm-lock.yaml
Added image a route for image processing in docker template based on ipx package.
There a few things to note
- it does not have persistent caching and rely only on client cache control
- performance is not good for remote images
- the package adds 30MB to node_modules, though it will be fixed soon
There is a DOMAINS env variable with comma-separated hosts to restrict remote images processing similar to netlify and vercel.
Can be tested only locally for now.
> experimental: support image processing in docker template

- fixtures/ssg-netlify-by-project-id/app/constants.mjs
- packages/cli/templates/ssg-netlify/app/constants.mjs
- packages/cli/templates/ssg-vercel/app/constants.mjs
- packages/image/src/image-optimize.ts
SSG templates have @webstudio-is/image imports which is not installed when prebuild.ts imports constants.mjs.
Here removed URL.canParse checks in favor of netlify and vercel domains configuration.
> fix: avoid imports of not installed packages when setup SSG

- fixtures/react-router-docker/app/constants.mjs
- fixtures/ssg-netlify-by-project-id/app/constants.mjs
- fixtures/ssg-netlify-by-project-id/vike.d.ts
- fixtures/ssg/app/constants.mjs
- fixtures/ssg/vike.d.ts
- fixtures/webstudio-cloudflare-template/app/constants.mjs
- fixtures/webstudio-remix-netlify-edge-functions/app/constants.mjs
- fixtures/webstudio-remix-netlify-functions/app/constants.mjs
- fixtures/webstudio-remix-vercel/app/constants.mjs
- packages/cli/templates/defaults/app/constants.mjs
- packages/cli/templates/netlify-edge-functions/app/constants.mjs
- packages/cli/templates/netlify-functions/app/constants.mjs
- packages/cli/templates/react-router-docker/app/constants.mjs
- packages/cli/templates/ssg-netlify/app/constants.mjs
- packages/cli/templates/ssg-vercel/app/constants.mjs
- packages/cli/templates/ssg/app/constants.mjs
- packages/cli/templates/ssg/vike.d.ts
- packages/cli/templates/vercel/app/constants.mjs
- packages/image/src/image-loaders.ts
- packages/react-sdk/placeholder.d.ts
It is no longer configurable and always dictated by image loader.
> refactor: drop imageBaseUrl from constants.mjs

- apps/builder/app/builder/features/help/help-center.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/dashboard/dashboard.tsx
- apps/builder/app/shared/help.tsx
1. Added central place for all help links
1. Added same thing to the menu
1. Deemphasize github discussions, it works better with discord for everything
4. expect xyz
> chore: Reuse help menu

- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[another-page]._index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[head-tag]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[class-names]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[content-block]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[expressions]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[head-tag]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/package.json
- fixtures/webstudio-remix-vercel/proxy-emulator/dedupe-meta.ts
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/react-sdk/src/page-settings-canonical-link.tsx
- packages/react-sdk/src/runtime.ts
> feat: Add default canonical link

- packages/asset-uploader/package.json
- packages/asset-uploader/src/utils/get-asset-data.ts
- pnpm-lock.yaml
Image-size is barely supported, works only in node.js.
Image-meta is a fork from unjs community, without dependencies, can work in browsers, we already use it inside of ipx.
> refactor: replace image-size with image-meta

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/position/inset-control.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.stories.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/shared/awareness.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.ts
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
- packages/sdk-components-react-radix/src/popover.ws.ts
- packages/sdk-components-react-radix/src/select.ws.ts
- packages/sdk-components-react-radix/src/tooltip.ws.ts
- packages/sdk-components-react/src/fragment.ws.ts
- packages/sdk-components-react/src/head-link.ws.ts
- packages/sdk-components-react/src/head-meta.ws.ts
- packages/sdk-components-react/src/head-slot.ws.ts
- packages/sdk-components-react/src/head-title.ws.ts
- packages/sdk-components-react/src/slot.ws.ts
- packages/sdk-components-react/src/xml-node.ws.ts
- packages/sdk-components-react/src/xml-time.ws.ts
- packages/sdk/src/core-metas.ts
- packages/sdk/src/schema/component-meta.ts
There is no need in additional flag if we add preset style to every stylable component already.
> refactor: drop stylable flag in component meta

- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/css/css.test.tsx
- packages/template/src/jsx.ts
renderData is similar to renderTemplate but returns maps of data which is used by most of builder utilities and component generator.
Here migrated to it css and component generator and used it to generate data sources where possible.
> refactor: add renderData utility to template package

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/props.test.ts
- packages/design-system/src/components/css-value-list-item.tsx
- packages/sdk/src/schema/data-sources.ts
Ref https://github.com/webstudio-is/webstudio/issues/4768
Here made a few changes to align data variables with css variables.
1. inherited variables are also shown in "Data Variables" section in Settings
2. local and remote variables have blue and orange labels
3. local variables with the same name "mask" inherited variables in the list
4. inherited variables can only be inspected
> feat: show inherited data variables

- .github/workflows/publish-beta.yml
Beta version is published without replacing packages version in templates. Reused the code from release action.
> build: fix publishing beta version of packages

- .github/workflows/publish-beta.yml
Install should happen after replace-in-files which follows symlinks and hangs when pnpm node_modules present.
> build: fix install in publish beta

- packages/sdk-components-react/src/youtube.tsx
With this PR user can paste an embed url like this https://youtube.com/embed?listType=playlist&list=UUjk2nKmHzgH5Xy-C5qYRd5A and we will still be able to render it
2. expect xyz
> feat: Support youtube list embed URL

- apps/builder/app/canvas/shared/use-drag-drop.ts
User reported he was able to drop components into images. Added lookup for containers first and then for matching ones.
Testing
- add image
- try to drop box into it
> fix: prevent dropping into image instance

- apps/builder/app/builder/features/pages/custom-metadata.tsx
- apps/builder/app/builder/features/pages/page-settings.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/shared/data-variables.test.ts
- apps/builder/app/shared/data-variables.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- packages/design-system/src/components/floating-panel.tsx
- packages/design-system/src/components/label.tsx
- packages/react-sdk/src/component-generator.test.tsx
- packages/sdk/src/expression.test.ts
- packages/sdk/src/expression.ts
Ref https://github.com/webstudio-is/webstudio/issues/4768 https://github.com/webstudio-is/webstudio/issues/4753
User can paste expression with not defined variable and should get it saved in case of accidental closing popover.
Now such expressions can be executed in builder and will be compiled with undefined instead of variables in published sites.
In the future we need to add global diagnostics to let users find such places faster.
Also fixed a couple of ui issues
- react error about using button inside of button in data variables list
- react error about using unknown middlewareData prop from floating-ui
> feat: allow saving expressions with unset variables

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/package.json
- packages/design-system/src/components/floating-panel.tsx
- pnpm-lock.yaml
Closes https://github.com/webstudio-is/webstudio/issues/4753
Variable validation especially resources shouldn't be too destructive. User may configure complex resource and get it all wiped out because url is invalid or header has empty value.
Here I tweaked the logic to require only not duplicated "name" and everything else is saved even when invalid.
This will not break anything in generation process and will still show user an error.
> feat: save variable/resource even with validation errors

- packages/cli/package.json
- packages/cli/src/prebuild.ts
- pnpm-lock.yaml
Here removed image package from CLI which depends on react and warn-once. CLI can be a little smaller without it.
> refactor: drop react and warn-once from CLI

- packages/sdk/src/expression.test.ts
- packages/sdk/src/expression.ts
User found syntax error which was accepted by linter. Turns out parseExpressionAt allows something like this
```js
(a + b))
```
Switched back to `parse` which actually gives proper result when expression is wrapped with parens.
> fix: validate unexpected closing paren in expressions

- .github/actions/submodules-checkout/action.yml
- .github/workflows/check-submodules.yml
- .github/workflows/chromatic.yml
- .github/workflows/cli-r2-static.yaml
- .github/workflows/cli-r2.yaml
- .github/workflows/fixtures-test.yml
- .github/workflows/main.yml
- .github/workflows/vercel-deploy-staging.yml
- .gitmodules
- .storybook/main.ts
- @types/scroll-timeline.d.ts
- apps/builder/app/routes/_ui.playground.tsx
- apps/builder/vite.config.ts
- package.json
- packages/sdk-components-animation/package.json
- packages/sdk-components-animation/src/components.ts
- packages/sdk-components-animation/src/scroll.tsx
- packages/sdk-components-animation/src/shared/animation-types.tsx
- packages/sdk-components-animation/src/shared/proxy.ts
- packages/sdk-components-animation/tsconfig.json
- patches/scroll-timeline-polyfill@1.1.0.patch
- pnpm-lock.yaml
- submodules.sh
ref #2645
Proof of Concept for the Animation Component Using ScrollTimeline
For FF and Safari `scroll-timeline-polyfill` is used.
SSR Support https://animate.development.webstudio.is/playground
Storybook Part 1. 
https://6382151c8b47d4399fb9fc69-limlyrmprp.chromatic.com/?path=/story/sdk-components-animation-scroll-animations--in-out
Next steps:
- Add stories with additional examples i.e. closest usage, images etc. https://scroll-driven-animations.style/
- Add support to view animations
- Add view animations examples
- Add enter/leave actions and animations support
- Builder UI
- Add lottie, rive etc compatibility (should work through context.getAnimations()[0].effect.getComputedTiming().progress)
2. expect xyz
- …
> experimental: Proof of concept of the Animation component using ScrollTimeline

- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml]._index.tsx
- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/component-generator.ts
User got 500 on published site. Turned out collection got invalid data (not array). We need to keep site working in such cases, missing piece will be more intuitive than 500 on whole website.
> fix: render nothing on website when collection is invalid

- packages/design-system/src/components/tree.tsx
https://share.descript.com/view/spOG60yRmmg
Actions in navigator now always visible even when horizontal scroll is involved
2. expect xyz
> feat: Sticky actions in navigator

- packages/sdk/src/schema/pages.ts
[Discussion](https://discord.com/channels/955905230107738152/1334938982882082847)
2. expect xyz
> fix: Improve redirect error message

- packages/sdk-components-react/src/head-link.ws.ts
- packages/sdk-components-react/src/head-meta.ws.ts
Users should not be able to add children in meta and link elements.
> fix: forbid text content in head meta and link

- apps/builder/app/builder/features/ai/apply-operations.ts
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Ref https://github.com/webstudio-is/webstudio/issues/4093
Here a few delete instance improvements
- fixed deleting resources bound to props (action in webhook form)
- rewrote all tests with jsx template
- switched from instance selector to instance path
- added slot test
> refactor: delete prop resources

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- packages/design-system/src/components/label.tsx
- packages/design-system/src/components/nested-icon-label.tsx
1. We want to group entries by origin
2. We want to sort by alphabet
3. expect xyz
> experimental: Advanced panel sorting and grouping

- apps/builder/app/auth/secret-login.tsx
Password field makes it harder to enter email for new user. Since thew feature is dev only there is no need to protect it as password.
> refactor: use text field for devlogin

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- packages/design-system/src/utilities.ts
https://github.com/webstudio-is/webstudio/issues/4804
When user is trying to create a variable but forgot to add --, we can help
2. expect xyz
> feat: Suggest a variable when user forgets -- in advanced panel

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
Here improved creating variables to override deeper bindings when new variable overrides ancestor variable similar to css variables behavior.
Here's a video with example
https://github.com/user-attachments/assets/41f93f5b-fd2d-4a3b-97d1-076f0ded5f01
> feat: rebind masked variables

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- packages/design-system/src/components/label.tsx
Improved readability by:
1. indentation
2. setting gray color for preset properties
3. making colon bolder
4. expect xyz
> experimental: Improve readability in advanced section

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- When adding a new property, you sometimes don't know the property name, e.g. you know you want to "center" it but you don't remember if its align-items, align-content or any other and you need to see the list.
- Currently you can create a css variable "bla" and it will bypass validation, now it will validate
- also try "color" esc autocomplete, enter
- or "color:red" esc autocomplete enter
Try typing "center"
2. expect xyz
> feat: Autocomplete values in advanced panel 

- apps/builder/app/shared/nano-states/props.test.tsx
- apps/builder/app/shared/nano-states/props.ts
Here improved computing variables logic to exclude masked variables from bindings popover list.
Also rewrote related tests with jsx template.
> fix: remove masked duplicates in binding popover

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/shared/copy-paste/init-copy-paste.ts
Closes https://github.com/webstudio-is/webstudio/issues/4856
Current logic broke in Chrome 133
1. Select instance in navigator
2. Copy
3. Paste
4. Should still allow selecting text and copying it
2. expect xyz
> fix: Fix copy instance if no text is selected 

- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Was missed while refactoring. Wrong data was mutated.
> fix: cleanup parent children when delete instances

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
Ref https://github.com/webstudio-is/webstudio/issues/4768
Before we disabled deleting variables which are used in expressions. Now we will ask confirmation and unset this variable. This way user will not be locked if variable is lost and we will show diagnostics (in the future) where all unset variables are.
> feat: allow deleting variables used in expressions

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
- apps/builder/package.json
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/4768
Forgot to handle the case with rebinding with parent variables after variable on child is deleted.
Also fixed the case with rebinding variables outside of slot scope.
> fix: rebind variables after delete

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/copy-paste.test.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/props.test.tsx
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/page-utils.ts
- packages/react-sdk/src/component-generator.test.tsx
Ref https://github.com/webstudio-is/webstudio/issues/4166 https://github.com/webstudio-is/webstudio/issues/3686
Added "Settings" section to global root. Now users can create data variables which are available for all pages and inside slots.
https://github.com/user-attachments/assets/be2cf862-08ec-427e-aea3-076fa03a4437
> feat: support global data variables

- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/page-utils.test.tsx
- packages/template/src/jsx.ts
Missed the case. Global variables were recreated and got invalid state. Now global variables are reused or added without changes.
> fix: preserve global variables when duplicate page

- apps/builder/app/builder/features/style-panel/sections/advanced/add-styles-input.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/copy-paste-menu.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- packages/design-system/package.json
- packages/design-system/src/components/context-menu.tsx
- packages/design-system/src/index.ts
- pnpm-lock.yaml
1. right click in advanced 
2. copy all
3. copy one
4. paste
5. search now works for properties AND values
6. backspace in add styles input when its empty now also closes the input same as esc
7. expect xyz
> feat: Context menu for advanced style panel

- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/add-styles-input.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/shared/event-utils.test.ts
- apps/builder/app/shared/event-utils.ts
1. improved composeEventHandlers implementation
2. delete value text, then hit backspace - same as reset
3. in advanced panel all property tooltips now show "Delete property" wording instead of "Reset value"
4. expect xyz
> feat: Backspace to reset the value in CSS Value Input

- packages/design-system/src/components/primitives/numeric-gesture-control.ts
https://discord.com/channels/955905230107738152/1337534586707644416
There are other bugs I see on Windows on my machine - `requestPointerLock` seems too buggy.  
1. In my case, wrap-around is not working.  
2. Fast clicks and movements can cause `pointerup` to not be intercepted (because of the fix above).  
Here’s how I see the issue:  
- `requestPointerLock` is asynchronous.  
- During `requestPointerLock`, we might get a `lostpointercapture` event.  
- This has a very low probability of happening on Mac.  
- On Windows, the probability is very high _(it can be caused by calling `requestPointerLock` itself, depending on the machine)_.  
- On Mac, if this happens, the `pointerup` event will most likely be lost.  
- On Windows, the `pointerup` event is usually preserved but can be lost as …
> fix: Scrub on windows

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
> fix: Space in navigation menu button trigger exits text editing

- apps/builder/app/builder/features/topbar/publish.tsx
- packages/cli/src/config.ts
- packages/feature-flags/src/flags.ts
- packages/sdk/src/schema/deployment.ts
Here dropped vanilla and legacy vercel templates.
Replaced vanilla with docker in publish dialog.
> feat: drop legacy CLI templates

- apps/builder/app/builder/features/navigator/css-preview.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/add-style-input.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/add-styles-input.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/copy-paste-menu.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/parse-style-input.test.ts
- apps/builder/app/builder/features/style-panel/sections/advanced/parse-style-input.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/css-engine/src/core/rules.ts
https://github.com/user-attachments/assets/a2446685-e7dc-4c01-bf03-4ee64b8f5e16
2. expect xyz
> chore: Unreleased bugs with advanced section

- apps/builder/app/shared/data-variables.ts
- apps/builder/app/shared/instance-utils.ts
- packages/sdk/src/schema/data-sources.ts
Some templates have variables with missing scopeInstanceId on dialogs or something else from broken embed template. Here allow it in validation because migration would be more complex.
> fix: allow broken variables when validate updates

- apps/builder/app/builder/features/pages/page-settings.tsx
- apps/builder/app/canvas/interceptor.ts
Tested forms only on home page. John caught the issue on other pages.
Forms now submit system.search on non-home pages proeprly.
> refactor: fix system on non-home pages

- fixtures/react-router-docker/app/__generated__/index.css
- fixtures/react-router-netlify/app/__generated__/index.css
- fixtures/react-router-vercel/app/__generated__/index.css
- fixtures/ssg-netlify-by-project-id/app/__generated__/index.css
- fixtures/ssg/app/__generated__/index.css
- fixtures/webstudio-cloudflare-template/app/__generated__/index.css
- fixtures/webstudio-features/app/__generated__/index.css
- packages/sdk/src/css.test.tsx
- packages/sdk/src/css.ts
Closes https://github.com/webstudio-is/webstudio/issues/4796
CSS Cascade Layers are already widely support for almost 3 years. See https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
We can switch to it instead of wrapping selectors with `:where` all preset selectors.
For older browsers impact will be insignificant as in most cases we use presets only to normalize browser styles.
Generated code now looks like this
```css
@layer presets {
div.w-box {
display: block;
}
}
```
Here's how presets look in chrome devtools. As you can see browser styles are defined as layer too.
> refactor: generate presets with css cascade layers

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/matcher.ts
- packages/react-sdk/src/props.ts
- packages/sdk-components-react/src/blockquote.ws.ts
- packages/sdk-components-react/src/heading.ws.ts
- packages/sdk-components-react/src/link.ws.ts
- packages/sdk-components-react/src/list-item.ws.ts
- packages/sdk-components-react/src/paragraph.ws.ts
- packages/sdk/src/schema/component-meta.ts
Closes https://github.com/webstudio-is/webstudio/issues/4897
Added "placeholder" field to component meta to signal the instance accepts should not be insertion target. This reverts us to previous behavior even with empty instances.
Also slightly refactored placeholder rendering to use attr() instead of extra css variable.
> fix: prevent inserting into instance with placeholder

- apps/builder/app/builder/features/pages/page-settings.tsx
- apps/builder/app/builder/features/pages/page-utils.test.ts
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/props.test.tsx
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/page-utils.test.tsx
- apps/builder/app/shared/page-utils.ts
- apps/builder/app/shared/webstudio-data-migrator.test.ts
- apps/builder/package.json
- packages/project-build/src/db/build.ts
- pnpm-lock.yaml
Closes https://github.com/webstudio-is/webstudio/issues/4166
Now system is global variable and can be accessed in slots.
Legacy one can be deleted
> feat: add global system variable in builder

- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
When opening slash menu in content block and using arrow keys, current item is not highlighted
2. expect xyz
> fix: Show highlighted item in slash menu in content block

- .devcontainer/postinstall.sh
* This PR fixes an issue where `pnpm` was not being correctly installed or configured within the Devcontainer environment when using `postinstall.sh`.
* This was causing errors during container startup and when running `pnpm` commands inside the Devcontainer.
* The fix ensures `pnpm` is properly set up in `postinstall.sh`, resolving the Devcontainer setup issue.
1. Start the Webstudio Devcontainer.
2. Expect the Devcontainer to start successfully without `pnpm` related errors.
3. Verify that `pnpm` commands can be executed correctly within the Devcontainer terminal (e.g., `pnpm --version`).
> fix(devcontainer): Fix pnpm installation issue in postinstall.sh

- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
Global variables will be replaced with "name" or unset when deleted from data variables section.
There are few cases to test
1. variable is unset on a few pages when delete
2. variable is unset on inside of slots when delete
> feat: unset global variables when delete

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
- packages/sdk/src/schema/animation-schema.ts
Adds experimental debug mode
2. expect xyz
> experimental: Add debug info

- apps/builder/app/builder/features/settings-panel/props-section/animation/animations-select.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/new-scroll-animations.ts
- apps/builder/app/builder/features/settings-panel/props-section/animation/new-view-animations.ts
Added few composable In, Out animations to the predefined `Add Animation`
2. expect xyz
> experimental: New predefined animations

- apps/builder/app/builder/features/marketplace/templates.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
Closes https://github.com/webstudio-is/webstudio/issues/4902
Rapid prototyping requires slightly different logic for inserting from marketplace so sections could be added one after another.
> fix: insert marketplace sections after selected instance

- release.sh
See script title comment why it's for
New docs
```md
Run ./release.sh
If release contains a migration: git commit -m "::migrate::" --allow-empty
Push created branch into the main repo, create draft Pull Request. (Draft pull request to ensure that it will not be merged by mistake)
```
2. expect xyz
> build: Automate release creation

- apps/builder/app/builder/features/topbar/topbar.tsx
> fix: Shorten page name correctly in the top bar

- apps/builder/app/builder/features/style-panel/style-source/style-source-control.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
1. Local token clickable area is now the entire button surface, closes https://github.com/webstudio-is/webstudio/issues/4864
2. When editing token name, now local doesn't jump around
2. expect xyz
> fix: Fix local token clickable area

- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/system.ts
Closes https://github.com/webstudio-is/webstudio/issues/4925
Loading resources with system variables
broken while switching to global system.
> fix: pass system to resources in builder

- apps/builder/app/shared/data-variables.test.tsx
- apps/builder/app/shared/data-variables.ts
Found broken cases with rebinding variables
when they are renamed or just saved.
> fix: rebind variables within scope

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/keyframe-helpers.test.ts
- apps/builder/app/builder/features/settings-panel/props-section/animation/keyframe-helpers.ts
- apps/builder/app/builder/features/settings-panel/props-section/animation/new-scroll-animations.ts
- apps/builder/app/builder/features/settings-panel/props-section/animation/new-view-animations.ts
- apps/builder/tsconfig.json
> experimental: Animation reorder keyframes on offset change

- apps/builder/app/shared/data-variables.ts
Reduced amount iterations over all instances
to optimize rebinding variables on save.
> fix: optimize saving global variables

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/instance-selected.ts
https://discord.com/channels/955905230107738152/1345038669496586310/1345038669496586310
2. expect xyz
> fix: Strange behaviour on scroll with tooltip content

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
Use case 1
1. add a property
2. copy all
3. paste into any text editor
4. see that recent one is not copied
Use case 2
1. add 2 properties
2. use backspace to reset the second property
3. focus should be on the first value after deleting the second one
4. use backspace to delete the first property
5. see focus jumped to search
6. expect xyz
> fix: Fixes 2 bugs in advanced panel

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
- apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle-group/toggle-group-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/features/style-panel/sections/size/size.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/configs.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/style-section.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- packages/css-data/src/parse-css.test.ts
- packages/css-data/src/parse-css.ts
Here improved all reusable logic to accept both camel and hyphen cases in properties. This will ease migration to hyphen style.
> refactor: accept both camel and hyphen properties everywhere

- fixtures/webstudio-features/.template/vite.config.ts
- fixtures/webstudio-features/.webstudio/data.json
- fixtures/webstudio-features/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-features/app/__generated__/[sitemap.xml]._index.tsx
- fixtures/webstudio-features/package.json
- fixtures/webstudio-features/proxy-emulator/dedupe-meta.ts
- fixtures/webstudio-features/vite.config.ts
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/route-templates/xml.tsx
- got rid of svg hacks, suffix seems work well
- filtered data instead of generating empty components
- fixed sitemap in features fixture
> refactor: simplify xml generation

- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle-group/toggle-group-control.tsx
- apps/builder/app/builder/features/style-panel/controls/toggle/toggle-control.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/builder/app/builder/features/style-panel/sections/sections.ts
- apps/builder/app/builder/features/style-panel/sections/size/size.tsx
First style sections migrated from camel case to hyphenated style properties.
> refactor: migrate layout and size to hyphenated properties

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/shared/css-editor/css-editor-context-menu.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.stories.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
- packages/design-system/package.json
- packages/design-system/src/components/context-menu.tsx
- pnpm-lock.yaml
1. added additional way to delete a declaration in addition to cmd+click
2. delete all declarations
3. expect xyz
> feat: Delete declaration and delete all declarations in advanced style panel context menu

- apps/builder/app/builder/shared/css-editor/css-editor.tsx
> fix: When deleting property during search in advanced panel - remove it from results

- apps/builder/app/builder/features/pages/pages.tsx
- packages/design-system/src/components/tree.tsx
When we switched to 24px height of inputs, I forgot to update navigator items. Currently complex components are hard to navigate because they don't fit  in the panel and you are always scrolling too much
2. expect xyz
> feat: use 24px item height to fit more in the navigator

- apps/builder/app/builder/features/style-panel/sections/backdrop-filter/backdrop-filter.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-image.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/text-shadows/text-shadows.tsx
- apps/builder/app/builder/features/style-panel/shared/css-fragment.test.ts
- apps/builder/app/builder/features/style-panel/shared/css-fragment.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
These all are now using hyphenated properties instead of camel case
- background
- text-shadow
- box-shadow
- backdrop-filter
> refactor: migrate repeated styles to hyphenated properties

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/parse-css.ts
- packages/css-data/src/property-parsers/shadow-properties-extractor.test.ts
No longer need to use camel cased property in parseCssValue
> refactor: accept hyphenated property in css value parser

- apps/builder/app/builder/features/navigator/css-preview.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-color.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-radius.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-style.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-width.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.tsx
- apps/builder/app/builder/features/style-panel/sections/outline/outline.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
- apps/builder/app/shared/webstudio-data-migrator.ts
Migrated two more sections and made ComputedStyleDecl['property'] more strict instead of just a string, now can get rid from `as StyleProperty` casting all over the codebase.
> refactor: migrate border and outline to hyphenated properties

- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
[Discussion](https://discord.com/channels/955905230107738152/1347444065402224691)
When advanced css editor is used in the style panel, we are avoiding jumps by preserving the scroll height, but in advanced mode when there is no parent scroll - we don't need that, so we can avoid blank space scrollbar.
2. expect xyz
> fix: Optionally memorize min height in style panel advanced css editor

- apps/builder/app/canvas/shared/styles.ts
Fixes https://github.com/webstudio-is/webstudio/issues/4963
Looks like accidentally wrong method was used.
> fix: update display from none

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/color-thumb.tsx
Color thumb should be a button only inside of color picker when it is clickable. In case of repeated style it is just a visual indicator.
This fixes huge react warnings about button rendered inside of another button.
> refactor: avoid rendering button inside button

- @types/navigator.d.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
Fixes an issue in DEV MODE where, if text is center-aligned inside Flex/Grid,
the code below causes Chrome to scroll the editable text block to the center of the view.
2. expect xyz
> fix: Chrome dev mode scrolls into center aligned text editor

- apps/builder/app/builder/shared/css-editor/add-style-input.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
1. Allow matching "gr te co" -> "grid-template-columns" when searching
2. Same thing when adding a new property/value
3. expect xyz
> feat: Improve search and new property autocompletion in advanced style panel

- apps/builder/app/builder/features/navigator/css-preview.tsx
- apps/builder/app/builder/features/style-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transitions.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/style-panel/shared/repeated-style.test.ts
- apps/builder/app/builder/features/style-panel/shared/repeated-style.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/style-object-model.test.tsx
- apps/builder/app/shared/style-object-model.ts
Migrated style object model to hyphenated css properties. A lot of conversions no longer necessary.
> refactor: hyphenate style engine

- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/package.json
- fixtures/react-router-docker/package.json
- fixtures/react-router-netlify/package.json
- fixtures/react-router-vercel/package.json
- fixtures/ssg-netlify-by-project-id/package.json
- fixtures/ssg/package.json
- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-features/package.json
- package.json
- packages/authorization-token/package.json
- packages/cli/templates/defaults/package.json
- packages/cli/templates/react-router/package.json
- packages/cli/templates/ssg/package.json
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/generate-arg-types/package.json
- packages/jsx-utils/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- packages/sdk-components-animation/package.json
- packages/sdk/package.json
- packages/tsconfig/base.json
- pnpm-lock.yaml
Upgraded to 5.8 and bumped all type definitions.
Enabled erasable syntax only flag and got rid from one case in expression editor.
> build: upgrade typescript

- apps/builder/app/builder/shared/css-editor/add-style-input.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
In advanced panel in both search in put and add property autocomplete right now if you type dash it won't find anything with dash
2. expect xyz
> fix: allow searching css with dash e.g. flex-direction 

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
1. focus any style value
2. type to open dropdown
3. hit ESC
4. see the input is still focused
5. hit ESC again
6. see the change is resetted
> fix: restore focus after closing dropdown via Esc in CSS Value input

- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/select-asset.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.stories.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/shared.tsx
In image and link components we allow to delete added asset. Though with tooltip and "reset/delete" we no longer need additional controls.
> feat: remove "delete" button from props asset

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/controls/text/text-control.tsx
- apps/builder/app/builder/features/style-panel/sections/shared/scrub.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/value-editor-dialog.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
Migrated all css-value-input internals and usages to hyphenated properties. Touched animation section a little.
> refactor: hyphenate css-value-input

- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-position.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-and-perspective-origin.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-rotate.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-skew.tsx
- apps/builder/app/builder/features/style-panel/sections/transforms/transform-translate.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input-container.tsx
- apps/builder/app/builder/features/style-panel/shared/filter-content.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
Css input container is simplified version of css value input. setValue and deleteProperty callbacks do not follow callback style and have inconsistent implementation. deleteProperty requires property to be specified.
Here renamed setValue to onUpdate, deleteProperty to onDelete and removed property parameter.
```
onUpdate: (style: StyleValue, options?: StyleUpdateOptions) => void;
onDelete: (options?: StyleUpdateOptions) => void;
```
> refactor: rename callbacks in css input container

- packages/sdk-components-react/src/vimeo-play-button.tsx
- packages/sdk-components-react/src/vimeo.tsx
- packages/sdk-components-react/src/vimeo.ws.ts
- packages/sdk-components-react/src/youtube.tsx
Closes https://github.com/webstudio-is/webstudio/issues/5016
Since we are lazily initializing the player and using autoplay, players won't request full screen, so we need to request the fullscreen ourselves.
1. inline is now false by default 
2. only for mobile/touch, custom logic checks if the device has touch or has resolution lower than 1024px
1. add vimeo component
2. put a video url, e.g. https://vimeo.com/1062544169
3. publish
4. play on a touch device or just a resolution smaller than 1024
5. see it goes full screen
6. repeaat the same with youtube
> fix: Vimeo and youtube inline option fix

- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.ts
Ivan found a bug. Reparent slot child into another instance of the same slot got this child removed.
Now refactored whole thing (almost). The main difference is same parent move will not do delete/paste but will just update child position. This fixes bug above and makes other logic slightly simpler.
Rewritten reparentInstance with reparentInstanceMutable to simplify testing and make it composable (if ever need). Added more tests.
> fix: reparent within another slot instance

- apps/builder/app/builder/features/topbar/publish.tsx
When publish website locally or in test environment we cannot see failed build id. Here added one behind tooltip.
> refactor: show build id for debug purposes

- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
This was misleading because we acually only need "text-wrap-mode" and "white space" in the UI is not actually white-space property
> fix: fix the tip for ellipsis

- apps/builder/app/builder/features/settings-panel/controls/resource-control.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
- packages/design-system/src/components/nested-input-button.tsx
- packages/feature-flags/src/flags.ts
- packages/sdk-components-react/src/webhook-form.ws.ts
Ref https://github.com/webstudio-is/webstudio/issues/4093
Succeeds https://github.com/webstudio-is/webstudio/pull/4333
Added resource button in webhook form action prop
> feat: support resource in webhook form

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
- apps/builder/app/builder/features/style-panel/sections/advanced/advanced.tsx
- apps/builder/app/builder/shared/css-editor/css-editor.tsx
- apps/builder/app/builder/shared/css-editor/index.ts
> experimental: Always show css value input instead of an add button

- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/awareness.test.tsx
- apps/builder/app/shared/awareness.ts
Users don't know where to find pro features accidentally created while being on pro tier or added with marketplace.
Here wrapped items in used pro featured with links (buttons actually) which navigate to instances.
https://github.com/user-attachments/assets/7dd879fa-4e1b-4f66-9dd3-18308cd62f58
> feat: navigate to pro features on publish dialog

- apps/builder/app/builder/features/style-panel/shared/style-section.tsx
fixes issue #4872 
removed the checks for unparsed  style values that was returning an empty array
1. use calc as a value in any of the inputs.
2. then close the section accordian to see the blue dot.
> fix: style panel indication issue when we use calc()

- apps/builder/app/builder/shared/css-editor/css-editor.tsx
1. go to advanced
2. click + button - focus should happen
3. click again - it will quickly disappear and appear focused again - this is expected
4. hit enter or tab on recently added value - input will appear focused
> fix: Fix add style input focus when pressing + button

- apps/builder/app/builder/shared/css-editor/add-style-input.tsx
We broke this as we introduced  a more flexible search to combobox when you add properties
1. advanced panel
2. type --x
3. see you can create that variable right away without adding value
> fix: Allow creating variables when input starts with dashes in advanced style section

- fixtures/webstudio-features/.webstudio/data.json
- fixtures/webstudio-features/app/__generated__/$resources.sitemap.xml.ts
- fixtures/webstudio-features/app/__generated__/[animations]._index.tsx
- fixtures/webstudio-features/package.json
- packages/sdk-components-animation/src/__generated__/animate-text.props.ts
- packages/sdk-components-animation/src/animate-text.tsx
- packages/sdk-components-animation/src/animate-text.ws.ts
New Split By option
Animated Text 2nd example
https://p-1ada14ed-beb3-4910-8af1-dacaa550310b-dot-anim-txt.staging.webstudio.is/?authToken=1e621fc4-dfb0-4189-a9b0-4fe2e189ec93&mode=preview
https://animations.wstd.work/text-animations
See 2nd animated per word
2. expect xyz
> experimental: Animate Text Split

- packages/cli/src/commands/init-flow.ts
A non-zero exit code indicates that the process did not complete. Alternatively, we could use a 130 exit code, which commonly refers to Control+C termination.
> fix: use non-zero exit code for cancelled init flow

- packages/cli/src/commands/init-flow.ts
The `webstudio init` command was prompting for a template even if `--template` was used. This fix avoids that behavior.
<sup>Simple fix so I skipped the PR template 🙈 </sup>
> fix: skip template prompt if `--template` is used

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-section.tsx
> experimental: Animation axis Icons change

- apps/builder/app/builder/features/command-panel/command-panel.stories.tsx
- apps/builder/app/builder/features/command-panel/command-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/modifier-keys.ts
- apps/builder/app/builder/features/topbar/builder-mode.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
- packages/design-system/src/components/command.stories.tsx
- packages/design-system/src/components/kbd.stories.tsx
- packages/design-system/src/components/kbd.tsx
We are using "meta" in commands, but "cmd" in Kbd, now this is consistently called "meta" everywhere. 
2. expect xyz
> refactor: Use consistent naming of the meta key

- apps/builder/app/builder/features/pages/page-utils.test.ts
- apps/builder/app/builder/features/pages/page-utils.ts
- apps/builder/package.json
- packages/design-system/package.json
- pnpm-lock.yaml
User reported the case which probably bugged us a few times but we could not figure out why.
Here added guard to prevent reparanting page folder inside of itself or child folders.
> fix: prevent dragging folder inside of itself

- apps/builder/app/shared/matcher.test.tsx
- apps/builder/app/shared/nano-states/components.ts
- packages/cli/src/framework-react-router.ts
- packages/cli/src/framework-remix.ts
- packages/cli/src/framework-vike-ssg.ts
- packages/react-sdk/src/embed-template.test.tsx
- packages/react-sdk/src/embed-template.ts
- packages/sdk-cli/src/generate-stories.ts
- packages/sdk-components-animation/src/animate-text.ws.ts
- packages/sdk-components-animation/src/shared/meta.ts
- packages/sdk-components-animation/src/stagger-animation.ws.ts
- packages/sdk-components-react-radix/src/accordion.ws.ts
- packages/sdk-components-react-radix/src/checkbox.ws.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.ts
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
- packages/sdk-components-react-radix/src/popover.ws.ts
- packages/sdk-components-react-radix/src/radio-group.ws.ts
- packages/sdk-components-react-radix/src/select.ws.ts
- packages/sdk-components-react-radix/src/shared/meta.ts
- packages/sdk-components-react-radix/src/switch.ws.ts
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/tooltip.ws.ts
Here got rid from auto namespacing meta.constraints and meta.indexWithinAncestor to unlock using components from other sdk packages.
Now package prefixes should be explicitly specified in meta though with the help of proxy.
Though exports are still need to prefix automatically when install package.
> refactor: manually namespace meta

- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
We introduced html content model which restricts how html elements can be nested into each other. Here fixed two edge cases
- allow to put div into buttons, headings or any other phrasing content
- allow put images into interactive elements like a > img
> fix: add more insert edge cases

- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/sections/text-shadows/text-shadows.tsx
- apps/builder/app/builder/features/style-panel/shared/shadow-content.tsx
Ref https://discord.com/channels/955905230107738152/1356952800621494363/1356952800621494363
Forgot about labels while migrating to shadow value
> fix: show proper shadow labels

- apps/builder/app/builder/features/pages/folder-settings.tsx
- apps/builder/app/builder/features/pages/page-settings.tsx
fixes: #5038 
delete button shows on folder settings in content mode and duplicate button shows for page setting. this fix removes these buttons in content mode. 
1. switch to content mode on your project
2. got to page/folder settings
3. expect that duplicate icon/delete icon should not be visible
4. 
- [] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
> fix: render delete icon only in design mode for folder settings and duplicate icon for page settings #5038

- .github/workflows/main.yml
- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/controls/tag-control.tsx
- apps/builder/app/builder/features/settings-panel/property-label.tsx
- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/style-object-model.test.tsx
- packages/react-sdk/src/component-generator.test.tsx
- packages/react-sdk/src/component-generator.ts
- packages/sdk-components-react-radix/src/checkbox.template.tsx
- packages/sdk-components-react-radix/src/sheet.template.tsx
- packages/sdk-components-react/src/__generated__/box.props.ts
- packages/sdk-components-react/src/box.tsx
- packages/sdk-components-react/src/box.ws.ts
- packages/sdk-components-react/src/checkbox.template.tsx
- packages/sdk-components-react/src/heading.tsx
- packages/sdk-components-react/src/heading.ws.ts
- packages/sdk-components-react/src/radio-button.template.tsx
- packages/sdk-components-react/src/text.tsx
- packages/sdk-components-react/src/text.ws.ts
- packages/sdk/src/core-templates.tsx
- packages/sdk/src/runtime.ts
- packages/sdk/src/schema/instances.ts
- packages/sdk/src/schema/prop-meta.ts
- packages/template/src/jsx.test.tsx
- packages/template/src/jsx.ts
https://github.com/webstudio-is/webstudio/issues/3632
Here added dedicated tag property control which will automatically migrate Box, Text and Heading components to instance.tag internally and will be used for ws:element component.
Later will extend tag control with tag descriptions and auto inferring matching tags.
> refactor: add tag property control

- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/matcher.ts
Fixes the issue reported in discord (https://discord.com/channels/955905230107738152/1356788803624501370/1357299346558816306)
Found the spec actually allows to place button and input inside a label. So now we can generalize this logic.
Also content model validation no longer prevents inserting invalid structure and only warns user is something went wrong. This will let us to never block the user with false positives and maybe even figure out the issue on their own.
> fix: allow placing labelable elements inside of labels

- apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
The logic hid advanced properties from any remote source even other breakpoints. Here added a check to hide only when inherited from global root.
> fix: show advanced properties in global root from other breakpoints

- apps/builder/app/builder/features/settings-panel/controls/code.tsx
Closes https://github.com/webstudio-is/webstudio/issues/5093
> feat: limit html embed

- apps/builder/app/builder/shared/commands.ts
We added cmd+enter but we forgot to add ctrl+enter for windows
2. expect xyz
> feat: add ctrl+enter shortcut for windows

- apps/builder/app/builder/features/topbar/sync-status.tsx
- apps/builder/app/builder/shared/sync/index.ts
- apps/builder/app/builder/shared/sync/sync-server.ts
We need to make lack of connection more visible and will show toast along with offline status.
> feat: show toast when builder is offline

- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
- packages/sdk-components-react/src/head-link.ws.ts
- packages/sdk-components-react/src/head-meta.ws.ts
- packages/sdk-components-react/src/head-slot.ws.ts
- packages/sdk-components-react/src/head-title.ws.ts
- packages/sdk-components-react/src/html-embed.ws.ts
- packages/sdk-components-react/src/markdown-embed.ws.ts
- packages/sdk-components-react/src/vimeo-play-button.ws.ts
- packages/sdk-components-react/src/vimeo-preview-image.ws.ts
- packages/sdk-components-react/src/vimeo-spinner.ws.ts
- packages/sdk-components-react/src/vimeo.ws.ts
- packages/sdk-components-react/src/youtube.ws.ts
- packages/sdk/src/core-metas.ts
- packages/sdk/src/schema/component-meta.ts
Extended content model to support categories defined in component meta. Most components has transparent children categories to pass through constraints from parent, this way we allow descendants with non category.
Here migrated only core and base components.
Will extend more for animations in another PR.
> refactor: add component content model

- packages/sdk-components-animation/vitest.config.ts
Based on comments here
https://github.com/vitest-dev/vitest/issues/7377
2. expect xyz
> build: Fix firefox vitest tests timeout

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/matcher.test.tsx
- apps/builder/app/shared/matcher.ts
- apps/builder/app/shared/shim.test.ts
- apps/builder/app/shared/shim.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- packages/sdk-components-react/src/bold.ws.ts
- packages/sdk-components-react/src/italic.ws.ts
- packages/sdk-components-react/src/rich-text-link.ws.ts
- packages/sdk-components-react/src/span.ws.ts
- packages/sdk-components-react/src/subscript.ws.ts
- packages/sdk-components-react/src/superscript.ws.ts
- packages/sdk/src/schema/component-meta.ts
Here I finally got rid from "rich-text-child" necessity. With html elements in the tree it will no longer work so we need a new way to work with rich text.
Added a few new utilities to content model which detect rich text by text inside or any textual tags. Span and links can still be detected as containers rather than children when not surrounded by text and other textual elements.
> refactor: use content model to detect rich text

- apps/builder/app/builder/shared/css-editor/parse-style-input.test.ts
- apps/builder/app/builder/shared/css-editor/parse-style-input.ts
The logic assumed invalid values should become custom properties. Here replaced that heuristic with property name check.
> fix: autocomplete properties with invalid values

- apps/builder/app/builder/shared/css-editor/add-style-input.tsx
When user search to add css variable in advanced style section we show now added css variables as well. Can be handy to update value defined remotely.
> feat: autocomplete remote css variables

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-control.tsx
- apps/builder/app/shared/dom-hooks/use-content-editable.ts
Ref https://discord.com/channels/955905230107738152/1360809139810599063/1360809139810599063
There were two problems here
1. empty token name collapsed and was not editable; fixed it with nbsp
2. the label set with dom didn't have proper timing; fixed it by rendering label by react
> fix: show token name when convert local styles to token

- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-keyframes.tsx
- apps/builder/app/builder/features/settings-panel/props-section/animation/animation-panel-content.tsx
We want to add a few predefined fields in every keyframe. Here we split each keyframe into separate popover to avoid overloading the ui.
> experimental: split keyframe styles into popover

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
We no longer support scrub on input icons like in gap.
> fix: remove scrub icon from gap input

- apps/builder/app/shared/matcher.test.tsx
- packages/react-sdk/src/component-generator.test.tsx
- packages/sdk-components-animation/src/animate-children.ws.ts
- packages/sdk-components-animation/src/animate-text.ws.ts
- packages/sdk-components-animation/src/stagger-animation.ws.ts
- packages/sdk-components-animation/src/video-animation.ws.ts
- packages/sdk-components-react-radix/src/accordion.ws.ts
- packages/sdk-components-react-radix/src/checkbox.ws.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.ts
- packages/sdk-components-react-radix/src/label.ws.ts
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
- packages/sdk-components-react-radix/src/popover.ws.ts
- packages/sdk-components-react-radix/src/radio-group.ws.ts
- packages/sdk-components-react-radix/src/select.ws.ts
- packages/sdk-components-react-radix/src/switch.ws.ts
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/tooltip.ws.ts
- packages/sdk/src/schema/component-meta.ts
Replaced legacy constraints with component content model in radix components. Checked all locally.
Removed meta.type for good.
> refactor: migrate radix to component content model

- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/awareness.ts
- apps/builder/app/shared/nano-states/misc.ts
- apps/builder/app/shared/sync/sync-stores.ts
We had a few issues
- instance selector was resynced even though computed from awareness
- when click in navigator both click and focus events do selection
So fixed by reducing 6 or more reselections when click on instances in navigator.
> perf: improve instance selection performance

- apps/builder/app/builder/features/style-panel/sections/advanced/stores.ts
- apps/builder/app/builder/features/style-panel/shared/model.tsx
Opacity and others when defined are duplicated
and not shown at all when not defined.
> fix: show initial properties in advanced panel

- apps/builder/app/builder/features/blocking-alerts/alert.tsx
- apps/builder/app/builder/features/blocking-alerts/blocking-alerts.tsx
Ref https://github.com/webstudio-is/webstudio/issues/1818
Users want to use builder in safari and firefox even though we don't officially support them. So we will let users dismiss blocking error.
> feat: let users dismiss blocking error in unsupported browsers

- apps/builder/app/builder/features/settings-panel/props-section/animation/animations-select.tsx
Now user can copy and paste specific animations between animation groups.
> feat: add context menu to animations

- apps/builder/app/builder/features/navigator/navigator-tree.tsx
- packages/react-sdk/src/props.ts
- packages/sdk-components-animation/src/animate-children.tsx
- packages/sdk/src/runtime.ts
Vite 6 is having troubles bundling app which depends on whole sdk. Plus it may increase app bundle size.
> refactor: move animate property to sdk runtime

- apps/builder/app/builder/features/settings-panel/property-label.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
Description can be taken from attributes meta. Also moved binding warning inside of tooltip to avoid layout shift after binding.
> fix: show description in attributes tooltip

- apps/builder/package.json
- apps/builder/vite.config.ts
- fixtures/react-router-docker/package.json
- fixtures/react-router-docker/vite.config.ts
- fixtures/react-router-netlify/package.json
- fixtures/react-router-netlify/vite.config.ts
- fixtures/react-router-vercel/package.json
- fixtures/react-router-vercel/vite.config.ts
- fixtures/ssg-netlify-by-project-id/package.json
- fixtures/ssg-netlify-by-project-id/vite.config.ts
- fixtures/ssg/package.json
- fixtures/ssg/vite.config.ts
- fixtures/webstudio-cloudflare-template/package.json
- fixtures/webstudio-cloudflare-template/vite.config.ts
- fixtures/webstudio-features/.template/vite.config.ts
- fixtures/webstudio-features/package.json
- fixtures/webstudio-features/vite.config.ts
- package.json
- packages/cli/package.json
- packages/cli/templates/cloudflare/vite.config.ts
- packages/cli/templates/defaults/package.json
- packages/cli/templates/defaults/vite.config.ts
- packages/cli/templates/react-router-netlify/vite.config.ts
- packages/cli/templates/react-router/package.json
- packages/cli/templates/react-router/vite.config.ts
- packages/cli/templates/saas-helpers/vite.config.ts
- packages/cli/templates/ssg/package.json
- packages/cli/templates/ssg/vite.config.ts
- pnpm-lock.yaml
Got rid of "module" export condition everywhere.
Seems like it has very poor usage everywhere.
> refactor: upgrade to vite 6

- packages/sdk-components-react/src/__generated__/vimeo.props.ts
- packages/sdk-components-react/src/shared/video.ts
- packages/sdk-components-react/src/vimeo-play-button.tsx
- packages/sdk-components-react/src/vimeo-preview-image.tsx
- packages/sdk-components-react/src/vimeo-spinner.tsx
- packages/sdk-components-react/src/vimeo.tsx
- packages/sdk-components-react/src/youtube.tsx
We accidentally added wrong properties by exporting a function with iframe type.
> fix: remove invalid properties from Vimeo component

- apps/builder/app/builder/features/style-panel/sections/sections.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
Transforms don't work when display: inline is used. Here we hide transforms section just like "list item section" for non list tags.
Related video https://www.youtube.com/watch?v=KjpQF3nYGoc
https://github.com/user-attachments/assets/2f1c882f-c627-4e62-9e44-5284117d200a
> feat: hide transforms section for inline elements

- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
Users started to build own marketplaces. And we found paste something copied from other browser like firefox -> chromium based app doesn't work. This is because OSs guarantee only text/plain to be stored in system clipboard.
Here I changed copy paste logic to copy as text/plain and paste as both application/json and text/plain if possible.
> feat: support paste from other browsers

- apps/builder/app/shared/html.test.tsx
- apps/builder/app/shared/html.ts
Ref https://github.com/webstudio-is/webstudio/issues/4404
Inline styles are easy to support and tailwind templates occasionally use them for unsupported stuff. Also fixed space collapsing.
https://github.com/user-attachments/assets/35e7a8d7-ef5b-496c-9a6d-0b05e113e503
> experimental: paste inline styles

- fixtures/ssg-netlify-by-project-id/pages/index/+Head.tsx
- fixtures/ssg/pages/another-page/+Head.tsx
- fixtures/ssg/pages/index/+Head.tsx
- packages/cli/templates/ssg/app/route-templates/html/+Head.tsx
- packages/react-sdk/src/page-settings-meta.tsx
fixes #3104 
For forcing twitter to use large-card size. We need to set `summary_large_image` meta tag in the header.
- Create a new project with a page.
- Set an image for the social image in the page settings.
- Deploy the site, and check the open graph preview using some of the tools online
https://tweethunter.io/tweetpik/twitter-card-validator?url=https%3A%2F%2Fcelebrated-pony-026734.netlify.app%2F
https://robolly.com/twitter-card-preview?url=https://celebrated-pony-026734.netlify.app
> fix: default twitter og preview to use `summary_large_image` for bigger previews

- apps/builder/app/builder/features/pages/image-info.tsx
- packages/design-system/src/utilities.ts
Just a small fix for `elipsis` for longer file names for social images. Noticed while working with the social image bug.
- Upload any image with longer file names under page settings.
> fix: show elipsis for longer social image names

- apps/builder/app/canvas/shared/commands.ts
Fixes https://discord.com/channels/955905230107738152/1369211497590554675
Delete on canvas is separateed from the one in builder so we can safely remove preventDefault to allow entering or deleting from inputs in preview mode.
> fix: allow deleting from input in preview mode

- apps/builder/app/shared/html.test.tsx
- apps/builder/app/shared/html.ts
Now icons are added as HtmlEmbed component when paste html. This is essential for tailwind paste which use a lot of icons.
```html
<div
style="display: flex; border: 1px solid #ccc; border-radius: 5px; overflow: hidden;"
>
<button
style="background-color: #f8f8f8; border: none; padding: 10px; cursor: pointer; display: flex; align-items: center; justify-content: center; border-right: 1px solid #ccc; font-family: sans-serif; font-size: 12px;"
>
<svg
xmlns="http://www.w3.org/2000/svg"
width="24"
height="24"
viewBox="0 0 24 24"
fill="none"
stroke="currentColor"
stroke-width="2"
stroke-linecap="round"
stroke-linejoin="round"
style="margin-right: 5px;"
>
<line x1="3" y1="12" x2="21" y2="12"></line>
<line x1="3" y1="6" x2="21" y2="6"></line>
<line x1="3" y1="18" x2="21" y2="18"></line>
</svg> …
```
> experimental: allow pasting svg as html embed (for now)

- packages/sdk-components-react/src/__generated__/time.props.ts
- packages/sdk-components-react/src/time.tsx
- packages/sdk-components-react/src/time.ws.ts
All html attributes all converted to react style though in case of Time property was converted.
The easiest solution is to rename the actual property to accept converted time.
> fix: set correct date time property in Time component

- apps/builder/app/builder/features/components/components.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- packages/html-data/bin/elements.ts
- packages/sdk/src/__generated__/tags.ts
- packages/sdk/src/core-templates.tsx
Now element does not provide default tag and instead builder will try to find tag matching its parent.
This way we can insert element, give it "ul" tag
and then insert another element into it which will match only "li"
https://github.com/user-attachments/assets/3ea87624-9524-4f2e-91b2-d658d16d7a1b
> experimental: add matching tag when insert element component

- apps/builder/app/builder/features/settings-panel/controls/tag-control.tsx
Here improved tag control to allow updating with tag satisfying content model.
For example when ul has li it can only be changed to ol and menu. li inside ul cannot be changed with anything.
Also switch to combobox when there is more than 10 satisfying tags.
https://github.com/user-attachments/assets/ad42bba7-9be1-4f50-9b1a-6f6cda52f3e5
> experimental: adapt tag control to html content model

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/content-model.ts
- packages/sdk-components-react/src/blockquote.ws.ts
- packages/sdk-components-react/src/heading.ws.ts
- packages/sdk-components-react/src/link.ws.ts
- packages/sdk-components-react/src/list-item.ws.ts
- packages/sdk-components-react/src/paragraph.ws.ts
- packages/sdk-components-react/src/time.ws.ts
- packages/sdk/src/schema/component-meta.ts
Now content block is relying on instances tags instead of component names. Tested all cases. Should work smoothly.
Also dialog title now have placeholders inferred from tag as well
> experimental: support html elements in content block

- apps/builder/app/shared/content-model.ts
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-radix/src/__generated__/tabs.props.ts
- packages/sdk-components-react-radix/src/accordion.template.tsx
- packages/sdk-components-react-radix/src/accordion.tsx
- packages/sdk-components-react-radix/src/checkbox.tsx
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/dialog.ws.ts
- packages/sdk-components-react-radix/src/popover.tsx
- packages/sdk-components-react-radix/src/radio-group.tsx
- packages/sdk-components-react-radix/src/select.tsx
- packages/sdk-components-react-radix/src/switch.tsx
- packages/sdk-components-react-radix/src/tabs.template.tsx
- packages/sdk-components-react-radix/src/tabs.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
- pnpm-lock.yaml
Here improved handling radix states by making all components uncontrolled yet still synchronizing external state with local one.
> fix: make all radix components uncontrolled

- apps/builder/app/builder/features/command-panel/command-panel.tsx
- apps/builder/app/builder/features/components/components.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/copy-paste/plugin-html.ts
- packages/css-engine/src/core/atomic.test.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
- packages/feature-flags/src/flags.ts
- packages/html-data/src/pseudo-classes.ts
- packages/sdk-components-react/src/box.ws.ts
- packages/sdk-components-react/src/head-slot.template.tsx
- packages/sdk-components-react/src/html-embed.ws.ts
- packages/sdk-components-react/src/link.template.tsx
- packages/sdk-components-react/src/slot.ws.ts
- packages/sdk-components-react/src/templates.ts
- packages/sdk-components-react/src/vimeo.template.tsx
- packages/sdk-components-react/src/webhook-form.template.tsx
- packages/sdk-components-react/src/youtube.template.tsx
- packages/sdk/src/core-templates.tsx
Here unflagged element component in components panel and html paste.
Additionally
- migrate link template to html element
- added :local-link state to links which is replaced with [aria-current=page] when css is generated, sadly not yet supported in any browser
- migrated many templates from legacy components to html elements
- put tailwind paste behind flag
> feat: add element component

- apps/builder/app/canvas/interceptor.ts
User can click on checkboxes and radio inputs on canvas and make them checked. We don't want this in design mode.
> fix: prevent checkbox and radio changing in design mode

- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- apps/builder/app/shared/copy-paste/plugin-html.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/copy-paste/plugin-webflow/plugin-webflow.ts
Async in html paste broke markdown because await was missing in onPaste.
> fix: paste markdown

- apps/builder/app/shared/instance-utils.test.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.ts
Here changed insertion logic to wrap rich text with span element instead of Text component when drop into it. This is the last place which creates legacy components.
Refactored tests with jsx to make them more readable.
> feat: wrap text with span element when droppping instances into it

- apps/builder/app/builder/features/topbar/publish.tsx
- packages/sdk/src/core-templates.tsx
> feat: Built with webstudio badge check on publish

- apps/builder/app/builder/features/command-panel/command-panel.tsx
Added commands for all tags satisfying current tree
https://github.com/user-attachments/assets/6e7e29c4-1a9a-452d-a967-448e216e4703
> feat: insert tag commands

- apps/builder/app/canvas/interceptor.ts
Accidentally broke when fixed links download attribute
> fix: prevent typing only inside of textarea and input on canvas

- apps/builder/app/builder/features/command-panel/command-panel.tsx
Removed children from content model check in command panel tags.
> fix: autocomplete tags on body when page has invalid content

- apps/builder/app/builder/features/command-panel/command-panel.tsx
> fix: show correct component icons in command panel

- packages/sdk/src/__generated__/normalize.css.ts
- packages/sdk/src/normalize.css
Accidentally removed it while refactoring preset styles.
> fix: return back box-sizing: border-box on <hr>

- apps/builder/app/builder/features/topbar/publish.tsx
Trying to explain that user can change the styles and position and everything about that badge.
2. expect xyz
> fix: Improve made with webstudio badge tooltip

- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
We rely on "tag" in legacy components though it is primary way to setup tag on xml nodes. Here added exception for all xml components.
> fix: ignore content model checks for XmlNode component

- apps/builder/app/builder/features/settings-panel/controls/resource-control.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
Did you ever wonder why you can't edit inherited data variables? We wondered the same. Now you can edit variables and resources from anywhere deep in the tree.
https://github.com/user-attachments/assets/9e117fc7-9329-4b38-8a2f-c97360bc3e7d
> feat: allow editing remote resources

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/shared/awareness.ts
> feat: Open current page in the publish dialog

- apps/builder/app/builder/features/style-panel/shared/model.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
Checks:
- show
- display
- visibility
- opacity
- rel attribute
2. expect xyz
> feat: Improve badge checks

- apps/builder/app/builder/features/topbar/publish.tsx
> fix: Improve clarity of the upgrade banner

- apps/builder/app/shared/content-model.test.tsx
- apps/builder/app/shared/content-model.ts
- packages/html-data/bin/elements.ts
- packages/html-data/src/__generated__/elements.ts
This fixes headings inside of summary and interactive elements inside of details content.
> fix: properly support details and summary elements

- apps/builder/app/builder/features/command-panel/command-panel.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
Ref https://github.com/webstudio-is/webstudio/issues/2651
Added command to let users paste tailwind fragments.
- all classes are converted to local styles
- breakpoints are adapted to desktop-first if possible
- images are automatically uploaded
> feat: paste HTML with tailwind classes

- .devcontainer/devcontainer.json
- .devcontainer/postinstall.sh
Seems like no longer used and better remove.
> build: drop fzf

- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/entri.tsx
> chore: Better button colors, better upgrade request

- apps/builder/app/shared/tailwind/tailwind.test.tsx
- apps/builder/app/shared/tailwind/tailwind.ts
Ref https://github.com/webstudio-is/webstudio/issues/2651
When convert tailwind breakpoints to webstudio breakpoints our algorithm can find holes and will stop conversion. Though this will create mobile-first breakpoints which users do not expect.
Here I added workaround to specify "unset" value on property when tailwind breakpoints has holes. Here's examples
**sm:opacity-20** - here the hole is in the beginning, opacity: 0.2 can be defined on base breakpoint but we need to fill with something `max-width: 479`
**max-sm:opacity-10 md:opacity-20** - here the holr is in the middle, we have `max-width: 479` and base breakpoint but no `max-width: 767`
> fix: add unset values to adapt tailwind breakpoints

- apps/builder/app/shared/tailwind/tailwind.test.tsx
- apps/builder/app/shared/tailwind/tailwind.ts
Ref https://github.com/webstudio-is/webstudio/issues/2651
Didn't consider spaces on breakpoints when converted space-* to gap for example `md:space-x-6` -> `md:gap-x-6`
> fix: convert space-* on breakpoints when paste tailwind

- packages/domain/src/rdap.ts
- packages/domain/src/trpc/domain.ts
We detect cloudflare to preserve root domain and add www for everything else. Now we check official dns registry for top level domains and check its data for required nameservers.
> fix: improve www detection

- apps/builder/app/builder/features/topbar/add-domain.tsx
- packages/domain/src/rdap.ts
- packages/domain/src/trpc/domain.ts
We use iana registry to find if cloudflare nameserver is used for domain and we can avoid using www.
> fix: avoid error when domain does not exist in iana

- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/project-settings/section-backups.tsx
- apps/builder/app/shared/help.tsx
- apps/builder/app/shared/nano-states/project-settings.ts
- packages/postgrest/src/__generated__/db-types.ts
- packages/prisma-client/prisma/migrations/20250710163439_restore_development_build/migration.sql
- packages/project/package.json
- packages/project/src/trpc/project-router.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/5276
> feat: allow restore from published backup

- apps/builder/app/shared/copy-paste/plugin-html.ts
We want to reduce friction in pasting from inception and will automatically process tailwind classes and generate styles when paste into builder without using command panel.
> feat: automatically paste tailwind when html has inception mark

- packages/html-data/bin/elements.ts
- packages/html-data/src/__generated__/elements.ts
Ref https://github.com/webstudio-is/webstudio-community/discussions/241
Never supported heading outline algorithm was never supported and the latest update to html spec allowed paragraphs as part of this removal for lower level subtitles or descriptions.
Though indices tables were not updated. I [sent PR](https://github.com/whatwg/html/pull/11524)
> fix: allow <p> inside of <hgroup>

- packages/sdk-components-react/src/xml-node.tsx
Fixes https://discord.com/channels/955905230107738152/1398319996832059574/1398319996832059574
Here explicitly specified black color for text in xml and head slot. This prevents white color on root to override text.
> fix: avoid using global color for head slot and xml

- apps/builder/app/builder/features/project-settings/section-redirects.tsx
- packages/sdk/src/schema/pages.ts
Fixes https://github.com/webstudio-is/webstudio/issues/5337
1. checking specific characters will always be error prone
2. checking matching paths is no longer relevant with `/*` which matches them all
3. added check to validate url or path with `new URL()`
> fix: relax redirects validation

- packages/html-data/bin/attributes.ts
- packages/html-data/src/__generated__/attributes-jsx-test.tsx
- packages/html-data/src/__generated__/attributes.ts
Fixes https://discord.com/channels/955905230107738152/1400906922235920445/1400906922235920445
The spec does not clearly indicate possible values and in case of iframe and object name attribute accepts any string.
> fix: accept any string in <iframe> name attribute

- apps/builder/app/routes/_canvas.canvas.tsx
- apps/builder/app/routes/_ui.(builder).tsx
- apps/builder/app/routes/_ui.login._index.tsx
- apps/builder/app/routes/rest.patch.ts
These official documented route configs started to wipe whole builder. We should migrate away from vercel ASAP.
> fix: remove vercel route configs

- apps/builder/app/shared/db/user-plan-features.server.ts
This will let us to configure available features for each plan.
> fix: access available features from product plans

- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
Before we set false by default for boolean properties and attributes which is less intuitive and always requires additional click to switch boolean on.
Now when user add for example aria-atomic attribute it gets true by default.
When user see initial property, for example disabled in input element, it gets false.
> fix: set true by default for new boolean properties/attributes

- apps/builder/app/builder/features/workspace/canvas-tools/outline/block-instance-outline.tsx
- packages/sdk/src/core-templates.tsx
- content block menu now use `<tag>` format for label
- add human radable labels in default content block template
> fix: show proper labels in content block

- apps/builder/app/builder/shared/css-editor/css-editor.tsx
Edited value lost "listed" flag when threw it out of advanced panel.
> fix: keep property in advanced panel when use color thumb

- fixtures/react-router-docker/app/constants.mjs
- packages/cli/templates/react-router-docker/app/constants.mjs
IPX we use for image generation does not support .ico format and fails to process it. Here I just skip image optimization for .ico and pass url directly.
> fix: avoid optimizing .ico in docker template

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/shared/image-manager/image-info.tsx
- apps/builder/app/shared/nano-states/props.ts
- packages/asset-uploader/package.json
- packages/asset-uploader/src/utils/font-data.ts
- packages/react-sdk/src/props.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/3263
Now users can control "alt" for all image uses with asset description.
https://github.com/user-attachments/assets/c0e5ae4b-d2b0-4ec1-bf93-c385816369d1
> feat: allow user to add asset description

- fixtures/react-router-cloudflare/app/routes/[another-page]._index.tsx
- fixtures/react-router-cloudflare/app/routes/_index.tsx
- fixtures/react-router-docker/app/routes/[another-page]._index.tsx
- fixtures/react-router-docker/app/routes/_index.tsx
- fixtures/react-router-netlify/app/routes/[another-page]._index.tsx
- fixtures/react-router-netlify/app/routes/_index.tsx
- fixtures/react-router-vercel/app/routes/[another-page]._index.tsx
- fixtures/react-router-vercel/app/routes/_index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/[another-page]._index.tsx
- fixtures/webstudio-cloudflare-template/app/routes/_index.tsx
- fixtures/webstudio-features/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-features/app/routes/[animations]._index.tsx
- fixtures/webstudio-features/app/routes/[class-names]._index.tsx
- fixtures/webstudio-features/app/routes/[content-block]._index.tsx
- fixtures/webstudio-features/app/routes/[duration]._index.tsx
- fixtures/webstudio-features/app/routes/[expressions]._index.tsx
- fixtures/webstudio-features/app/routes/[form]._index.tsx
- fixtures/webstudio-features/app/routes/[head-tag]._index.tsx
- fixtures/webstudio-features/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-features/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-features/app/routes/[radix]._index.tsx
- fixtures/webstudio-features/app/routes/[resources]._index.tsx
- fixtures/webstudio-features/app/routes/[text-duration]._index.tsx
- fixtures/webstudio-features/app/routes/_index.tsx
- packages/cli/templates/defaults/app/route-templates/html.tsx
- packages/cli/templates/react-router/app/route-templates/html.tsx
- packages/sdk/package.json
- packages/sdk/src/resource-loader.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/4077
How it works
- Cache-Control opts in caching (Cache-Control: max-age=3600)
- cached response is matched by url, method and body
- cache is invalidated with Cache-Control change
- responses stored with the cache are not replicated across regions
- responses are not shared between projects
Link for testing
https://test-cache-hcevl.wstd.work/?message=hello
> feat: cache resources

- apps/builder/app/builder/builder.css
- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/project-settings/utils.ts
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
- apps/builder/app/builder/shared/code-editor-base.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- packages/design-system/src/components/dialog.tsx
- packages/design-system/src/components/floating-panel.tsx
Ref https://github.com/webstudio-is/webstudio/issues/3691
- moved response preview into resource dialog
- increased dialog size and centered it
- added maximize button to resource dialog
- removed inspect option from dropdown
- refactored centering dialogs without transform to fix nested popovers positioning
https://github.com/user-attachments/assets/901e086b-afcd-42e9-8866-d62d6cb662d2
> feat: new resources dialog

- apps/builder/app/builder/features/settings-panel/curl.test.ts
- apps/builder/app/builder/features/settings-panel/curl.ts
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/shared/nano-states/props.ts
- fixtures/webstudio-features/app/__generated__/[expressions]._index.server.tsx
- fixtures/webstudio-features/app/__generated__/[form]._index.server.tsx
- fixtures/webstudio-features/app/__generated__/[resources]._index.server.tsx
- packages/sdk/src/resource-loader.test.ts
- packages/sdk/src/resource-loader.ts
- packages/sdk/src/resources-generator.test.tsx
- packages/sdk/src/resources-generator.ts
- packages/sdk/src/schema/resources.ts
Ref https://github.com/webstudio-is/webstudio/issues/3691
Editing search params separately from url can improve experience working with external CMS or databases like baserow.
Also made headers list more compact and aligned with search params.
Validation is simplified, empty pairs will be just ignored without blocking user with validation errors.
https://github.com/user-attachments/assets/3102d2c8-a902-4e86-8011-d71346fb5491
> feat: add search params list to resource UI

- apps/builder/app/builder/features/settings-panel/curl.test.ts
- apps/builder/app/builder/features/settings-panel/curl.ts
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- packages/sdk/src/resource-loader.test.ts
- packages/sdk/src/resource-loader.ts
- packages/sdk/src/schema/resources.ts
- packages/sdk/src/to-string.ts
Ref https://github.com/webstudio-is/webstudio/issues/3691
This should improve experience when working with baserow filters or similar backends.
> feat: support json in resource search params and headers

- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- packages/html-data/bin/attributes.ts
- packages/html-data/src/__generated__/attributes.ts
Got broken when we switched links to element component.
> fix: show href on link in content mode

- apps/builder/app/routes/rest.resources-loader.ts
- apps/builder/app/shared/resources.ts
Sometimes users are able to save broken resource
for example without header value. We need to prevent failing all requests and instead fail only broken one.
> fix: show resource validation error as response
