webstudio-is/webstudio

- app/canvas/canvas.tsx
- app/canvas/shared/instance.ts
- app/canvas/shared/style.ts
- app/designer/features/style-panel/use-style-data.ts
All tree changes are running on the root instance, so when we undo changes, we need to set a new instance as a selected instance
Fixes #33
> Update selected instance when running undo

- apps/designer/.storybook/main.js
- apps/designer/package.json
- package.json
- turbo.json
- yarn.lock
Storybook no longer runs along with yarn dev, so now we need to start it separately with `yarn storybook`
> Decouple storybook from yarn dev

- apps/designer/app/designer/features/breakpoints/use-update-canvas-width.ts
- apps/designer/app/designer/shared/client-settings/settings.ts
- apps/designer/app/routes/auth/github.tsx
- apps/designer/app/routes/auth/google.tsx
- apps/designer/app/routes/canvas/$projectId.tsx
- apps/designer/app/services/auth.server.ts
- apps/designer/app/shared/db/breakpoints.server.ts
- apps/designer/app/shared/db/project.server.ts
- apps/designer/app/shared/db/props.server.ts
- apps/designer/app/shared/db/tree.server.ts
- apps/designer/app/shared/error/error-message.tsx
- apps/designer/app/shared/error/index.ts
- apps/designer/app/shared/sentry.ts
- apps/designer/package.json
- yarn.lock
This is trying to prevent cases like [this](https://github.com/webstudio-is/webstudio-designer/issues/127) in the future. We need to add zod to all ingoing/outgoing data in all routes
I haven't published SDK package, so if you want to test, will have to use yarn watch:sdk and check out [this](https://github.com/webstudio-is/webstudio-sdk/pull/8) on SDK repo. This workflow is soon going to be a thing of the past.
> Make sure we have validated at runtime data that isn't part of Prisma

- apps/designer/app/designer/shared/tree/tree.tsx
Related issue: #128
The flicker is caused by broken open/close animation ( https://www.radix-ui.com/docs/primitives/components/collapsible#animating-content-size )
The animation relies on `--radix-collapsible-content-height` CSS variable. In order for animation to work correctly the variable must be present during the animation.
There were two problems:
1. For the nodes that have children we used to remove the children as soon as the node is collapsed, which caused `--radix-collapsible-content-height` to disappear and animation to use incorrect height value.
2. For the nodes without children, the variable `--radix-collapsible-content-height` is never present, so animation was always broken.
> Fix tree flicker

- .github/workflows/main.yml
- README.md
- packages/react-sdk/bin/generate-arg-types.ts
- packages/react-sdk/bin/mdn-data.ts
- packages/react-sdk/package.json
This speeds up CI runs by about 20 seconds by caching downloaded dependencies.
I was hopping to cache the entire node_modules folder to cut install time to 0, but apparently it's not trivial and not recommended: https://stackoverflow.com/a/68565233/478603
> Speed up CI a bit

- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/docs/test-cases.md
- packages/react-sdk/src/components/box.props.json
- packages/react-sdk/src/components/box.tsx
- packages/react-sdk/src/components/heading.tsx
Box component should be able to render as a different tag than a div, but it seems there is no not-hardcoded way to select the tag, because you don't want to list all tags there, because for many tags we have separate components and others are not supposed to be used as a container, e.g. span
https://user-images.githubusercontent.com/52824/180659227-3b8ab1ba-e3ae-49f1-9428-8619bff6cc3b.mp4
> Add a tag prop with a list of predefined container tags

- apps/designer/.env.example
- packages/asset-uploader/src/helpers/get-asset-path.test.ts
- packages/asset-uploader/src/helpers/get-asset-path.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/targets/s3/handler.ts
This PR removes the `WORKER_URL` env and makes it into CDN_URL to be more generic
related https://github.com/webstudio-is/webstudio-designer/issues/37
> rename worker url env to CDN url

- .github/pull_request_template.md
- apps/designer/app/services/auth.server.ts
- apps/designer/docs/test-cases.md
The idea of this PR is that we only check the first four characters of the `AUTH_SECRET` so that in that way we can share it and make it easier fore anyone to contribute and deploy their branch
Also adds it to the pull request template
- [ x] made a self-review
- [ x] conceptual
- [ x] step by step interaction description and what is expected to happen
- [ x] tested locally and on preview environment (preview dev login: 5de6e)
- [ x] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
> Use only the first four characters in AUTH_SECRET

- apps/designer/app/canvas/shared/instance.test.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-drag-drop.ts
- apps/designer/app/shared/tree-utils/get-instance-path.test.ts
- apps/designer/app/shared/tree-utils/get-instance-path.ts
- apps/designer/docs/test-cases.md
- packages/design-system/src/components/primitives/dnd/dom-utils.ts
- packages/design-system/src/components/primitives/dnd/use-drop.ts
- This fixes the remaining todo item in #7
- Also fixed a bug with DnD when `<body>` is a drop target
When inserting an instance by clicking on a button in the panel instead of dragging it, the instance should be inserted in the current selected instance.
But if the current selected instance cannot accept a child, for example if it's a Heading, then the new instance should be inserted next to the selected instance.
-------------------------------
> Find a valid parent when inserting into selected instance

- apps/designer/package.json
- package.json
1. Moved the `"migrations"` script from app to root
2. Deleted `"migrate"` script from root as now `migrations migrate` can be used instead (see https://github.com/webstudio-is/webstudio/pull/17 )
> Fix migration yarn scripts

- apps/designer/package.json
- packages/prisma-client/migrations-cli/TROUBLESHOOTING.md
- packages/prisma-client/migrations-cli/commands.ts
- packages/prisma-client/prisma/migrations/20220909124542_builds-data/migration.ts
- packages/prisma-client/prisma/migrations/20220912142938_assets-meta-data/migration.ts
- packages/prisma-client/prisma/migrations/20220915144008_breakpoints-build_data/migration.ts
- packages/prisma-client/prisma/migrations/template.txt
1. Fixed the failed migration
2. Fixed how migration errors are captured in our CLI (it used to capture `[Object object]` as a message in some cases)
3. Added TROUBLESHOOTING.md where we can record the solution for known problems
4. All migrations in PREVIEW are now applied
> Fix failed migrations

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/shared/use-designer-ready.ts
- apps/designer/app/designer/designer.tsx
It is possible that the js of designer is loaded later than the js of canvas, because everything is server-rendered
we just ran into a case where disabling cache has hit the bug
> Wait for designerReady event on the canvas before publishing data

- apps/designer/app/designer/shared/tree/index.tsx
> Fix a bug where navigator attempts to show `string` children of Bold and crashes 

- packages/react-sdk/package.json
Since we are committing those build artefacts, there is no point in building them every time main build command is executed
> Speedup sdk build, avoid building things that haven't changed

- apps/designer/app/critical-css.ts
- packages/react-sdk/src/stitches/css.ts
We had 2 problems in https://github.com/webstudio-is/webstudio-designer/issues/305
1. globalStyles wasn't using the same stitches instance we were using to get the ssr'd styles for critical css
2. we weren't resetting the instance, which would be a potential problem for ssr with load
> Fix critical css for global styles, reset styles for ssr

- packages/http-client/package.json
- packages/http-client/src/index.test.ts
- packages/http-client/src/index.ts
`process.env` is not defined in the worker state, so URL is defined in a different way.
> fix: http-client should not have process.env

- packages/project/src/db/project.ts
1. Fixes a bug in `/rest/project/clone/webstudiois` where it says "Dev build already exists"
2. Makes project domains lowercase always, because domain names are case insensitive (needs more fixes, will do in a separate PR)
> Fix bugs in PROD

- apps/designer/app/canvas/features/wrapper-component/text-editor/nodes/node-instance.tsx
- apps/designer/app/canvas/features/wrapper-component/text-editor/plugins/plugin-instance.tsx
- apps/designer/app/canvas/features/wrapper-component/text-editor/utils/to-lexical-nodes.tsx
- apps/designer/app/canvas/features/wrapper-component/text-editor/utils/to-updates.test.ts
- apps/designer/app/canvas/features/wrapper-component/text-editor/utils/to-updates.ts
- apps/designer/app/shared/tree-utils/set-instance-children.ts
- packages/project/src/shared/tree-utils/set-instance-children.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
isNew and createInstance flags makes state management more complex. Instead tree of instances updates should be idempotent. This will let us do more straightforward mapping from lexical nodes to designer tree.
> Hydrate text editor instances

- packages/jest-config/index.js
Cherry picked from #378
`expect(obj).toMatchInlineSnapshot()`
cause `Jest: Couldn't locate all inline snapshots.` error without source maps support enabled.
> [jest] Allow inline snapshots

- apps/designer/app/canvas/features/wrapper-component/text-editor/example-text-editor.tsx
- apps/designer/app/canvas/features/wrapper-component/text-editor/plugins/plugin-instance.tsx
- apps/designer/app/canvas/features/wrapper-component/text-editor/plugins/plugin-toolbar-connector.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/canvas-tools.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/hooks/use-subscribe-selection-rect.ts
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
Added events to handle toolbar rect and toggled states.
Moved atom subscriber and events types to text toolbar for clarity.
Added event for formatting and moved instance creation to editor side.
> Prepare text toolbar to new text editor

- apps/designer/app/canvas/features/text-editor/index.ts
- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/designer/app/canvas/features/text-editor/text-editor.tsx
- apps/designer/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/shared/tree-utils/create-instance.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/289
Previous implementation relied on custom instance nodes which broke a lot of builtin behaviour.
With new editor I use only builtin nodes. To preserve styling when entering editing mode className is computed and assigned to lexical element. Instances are stored in map and reused by updates converted and className renderer.
Toolbar now shows "checked" state and allows to toggle off styling.
> Reimplement text editor

- apps/designer/docker-compose.yaml
- apps/designer/package.json
With previous docker setup I have a problem when switched between projects had to setup migrations again and loose current session.
Docker compose volumes solve this problem and preserve current db state. Can be destroyed with `docker compose down -v`.
> Save db state after docker compose down

- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/designer/app/canvas/features/text-editor/text-editor.tsx
- apps/designer/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/components/meta.ts
- packages/react-sdk/src/components/span.props.json
- packages/react-sdk/src/components/span.stories.tsx
- packages/react-sdk/src/components/span.tsx
- packages/react-sdk/src/components/span.ws.tsx
Ref https://github.com/webstudio-is/webstudio-designer/issues/400
- added span component to sdk
- added span support to text editor toolbar
Lexical has a great utility $patchStyleText which does exaactly what we need, split selection into stylable element. Though there is a catch. It requires to apply some styles. We do styling lazily and with clases so it doesn't fit to trigger split. To workaroud it I instead patch with css custom property which does not affect styling and considered a trigger for lexical.
> Allow span fragment in text editor

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-measure-instance.ts
- apps/designer/app/canvas/shared/use-measure.ts
- apps/designer/app/shared/dom-hooks/use-measure.ts
- apps/designer/app/shared/pubsub/index.ts
- packages/react-sdk/src/pubsub/create.ts
> Fix a bug where outline does not update for inline elements

- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/designer/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/components/meta.ts
- packages/react-sdk/src/components/subscript.props.json
- packages/react-sdk/src/components/subscript.stories.tsx
- packages/react-sdk/src/components/subscript.tsx
- packages/react-sdk/src/components/subscript.ws.tsx
- packages/react-sdk/src/components/superscript.props.json
- packages/react-sdk/src/components/superscript.stories.tsx
- packages/react-sdk/src/components/superscript.tsx
- packages/react-sdk/src/components/superscript.ws.tsx
Ref https://github.com/webstudio-is/webstudio-designer/issues/400
- added superscript
- added subscript
- added clear formatting, used same trick as with span
- refactored interop to cover more options with less code
- convert newlines to linebreaks instead of paragraphs when convert instances to lexical tree
Still missing icons for superscript, subscript and clear
> Add more options to text editor

- apps/designer/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/designer/package.json
- yarn.lock
Ref https://github.com/webstudio-is/webstudio-designer/issues/107
Text toolbar is badly positioned when flipped up. Keeping it too close to cursor makes text selection harder.
Here I replaced custom logic with computed rect from toolbar parent and state from canvas. A few middlewares polished offsets. Flip no longer overlap text.
Also fixed toolbar background.
- [xx] made a self-review
> Use floating-ui to position text toolbar

- apps/designer/app/canvas/features/text-editor/text-editor.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
Styles were lost when refactored with new css engine. Here used the same way as with className before but instead set data-ws-id attribute. Did not add data-ws-component to avoid selecting.
Fixed text toolbar background for dark mode.
> Fix styles when enter editor mode

- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
From design: 
Notice that the align-content icon button is not visible by default.
This property only applies when flex-wrap is set to "wrap".
> [release-fix] Show align-content only if wrap enabled

- apps/designer/app/designer/features/style-panel/sections/flex-child/flex-child.tsx
Fixes label align-items onto align-self
Probably in the future this should be used. `sectionStyle.alignSelf?.styleConfig.label`
> [release-fix] Change align-items onto align-self

- apps/designer/app/designer/features/props-panel/control.tsx
- packages/design-system/src/components/combobox.tsx
- packages/design-system/src/components/text.stories.tsx
- packages/eslint-config-custom/index.js
- packages/react-sdk/src/components/body.stories.tsx
- packages/react-sdk/src/components/bold.stories.tsx
- packages/react-sdk/src/components/bold.tsx
- packages/react-sdk/src/components/box.stories.tsx
- packages/react-sdk/src/components/button.stories.tsx
- packages/react-sdk/src/components/button.tsx
- packages/react-sdk/src/components/form.stories.tsx
- packages/react-sdk/src/components/form.tsx
- packages/react-sdk/src/components/heading.stories.tsx
- packages/react-sdk/src/components/image.stories.tsx
- packages/react-sdk/src/components/image.tsx
- packages/react-sdk/src/components/input.stories.tsx
- packages/react-sdk/src/components/input.tsx
- packages/react-sdk/src/components/italic.stories.tsx
- packages/react-sdk/src/components/italic.tsx
- packages/react-sdk/src/components/link.stories.tsx
- packages/react-sdk/src/components/link.tsx
- packages/react-sdk/src/components/paragraph.stories.tsx
- packages/react-sdk/src/components/paragraph.tsx
- packages/react-sdk/src/components/subscript.stories.tsx
- packages/react-sdk/src/components/text-block.stories.tsx
- packages/react-sdk/src/components/text-block.tsx
- packages/react-sdk/src/tree/wrapper-component.tsx
- packages/tsconfig/base.json
Eslint always had issues finding unused variables. And it's usually required two more plugins beside builtin functionality to handle this case.
Typescript has this builtin and handles all cases out of the box. Also it works faster and more responsive in ide than eslint.
> Find unused variables with typescript

- packages/asset-uploader/tsconfig.json
- packages/css-data/tsconfig.json
- packages/css-engine/src/core/css-engine.stories.tsx
- packages/css-engine/tsconfig.json
- packages/css-vars/tsconfig.json
- packages/design-system/tsconfig.json
- packages/fonts/tsconfig.json
- packages/http-client/tsconfig.json
- packages/icons/tsconfig.json
- packages/prisma-client/tsconfig.json
- packages/project/tsconfig.json
- packages/react-sdk/tsconfig.json
- packages/tsconfig/base.json
Here "include" often have list of extensions and forgotten .tsx so such modules are left unchecked. Replaced with just "src" which consider all typescript extensions.
Ideally stop using tsc to build artifacts, switch to esbuild and remove complex configuration from all tsconfig.json.
> Check all .ts and .tsx in packages src folder

- .github/workflows/package-tests.yml
- packages/react-sdk/package.json
- Added `detect-font` to `react-sdk` as a dependency.
- Do not run `package-tests` GitHub action on the main push, only on other branches.
> fix: missing dependency (detect-font) + github action

- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/shared/css-utils/__snapshots__/delete-css-rules-by-breakpoint.test.ts.snap
- apps/designer/app/shared/props-utils/__snapshots__/delete-prop.test.ts.snap
- apps/designer/app/shared/props-utils/__snapshots__/update-props.test.ts.snap
- apps/designer/package.json
- packages/design-system/src/components/primitives/dnd/__snapshots__/geometry-utils.test.ts.snap
- packages/fonts/src/__snapshots__/get-font-faces.test.ts.snap
- packages/jest-config/index.js
- packages/jest-config/package.json
- packages/project/src/shared/tree-utils/__snapshots__/delete-instance.test.ts.snap
- packages/project/src/shared/tree-utils/__snapshots__/insert-instance.test.ts.snap
- packages/project/src/shared/tree-utils/__snapshots__/reparent-instance.test.ts.snap
- packages/project/src/shared/tree-utils/get-css-rules.test.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/component-utils/image.test.ts
- yarn.lock
The new version got more readable snapshots, no longer depends jsdom and has much better esm support (will be enabled in next PR).
Had to switch to babel to support typescript, react and esm for now.
> Bump to jest 29

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/designer/app/designer/features/style-panel/shared/css-value-input/unit-select.tsx
- apps/designer/app/designer/features/style-panel/shared/get-final-value.ts
- apps/designer/app/designer/features/style-panel/shared/parse-css-value.ts
- packages/design-system/src/components/text-field.tsx
don't display chevron if there are no items to display in the dropdown and fix the bg on chevron's/unit text-field suffix button.
> don't display empty unitless dropdown

- packages/prisma-client/migrations-cli/prisma-migrations.ts
Missed __dirname while migrating to esm. Works locally.
> Fix esm in prisma migrations

- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- packages/fonts/package.json
Designer tests fail because of missing cjs in fonts package. Also fixed iso string timezone in one test, was failing for me.
> Output cjs in font package

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/text-editor/text-editor.tsx
- packages/css-engine/src/core/css-engine.ts
- packages/project/src/shared/tree-utils/set-instance-children.ts
- packages/react-sdk/src/components/italic.ws.tsx
Ref https://github.com/webstudio-is/webstudio-designer/issues/107
- fixed bold italic styling
- populate default style for instances created from text editor
- added unmount support to css engine
- auto focus text editor when start editing
> Improve text editor styling and enable auto focus

- package.json
See https://nodejs.org/api/corepack.html
Corepack is a way to setup specific yarn/pnpm version on the fly. Builtin with Node 16.9+
Requires to run `corepack enable`
Replaces https://github.com/webstudio-is/webstudio-designer/pull/370
> Use corepack to setup yarn

- package.json
- packages/css-vars/package.json
This one is missing when upgrade packages in webstudio-saas
> Publish css-vars package to npm

- apps/designer/app/root.tsx
- apps/designer/app/routes/$.tsx
- apps/designer/app/routes/designer/$projectId.tsx
- apps/designer/app/routes/index.tsx
- yarn.lock
This will allow to infer loader data instead of writing type for it as recommended in https://github.com/remix-run/remix/releases/tag/remix%401.6.5.
> Handle loader errors in error boundary

- apps/designer/app/dashboard/components/header.tsx
- apps/designer/app/dashboard/dashboard.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/routes/dashboard/index.tsx
- packages/asset-uploader/src/types.ts
- packages/asset-uploader/src/utils/format-asset.ts
New remix enforces types to be serialized.
Prisma output dates as Date instance and this is not customizable. Had to fix only 2 cases.
> Use serialized loader types

- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/text-editor/text-editor.tsx
- apps/designer/app/canvas/shared/styles.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/487
Before lexical created paragraphs when press enter which we tried to visually represent as line break by removing margins and converted to line break to instances.
This could lead to a few issues.
1. When paragraph block is inside `<a>` nothing can be typed in the beginning and in the end of paragraph
2. Paragraphs can be styled by users which can break text editor visually
Here I overwritten default Enter command and insert line break instead of paragraph. To protect from external sources like paste from clipboard added transform to merge all paragraphs if move than one.
We will still have one paragraph in the root with display: inline style. Though it will cause less damage to editor with user styles.
> Remove paragraphs from text editor

- packages/react-sdk/src/css/categories.ts
We need this so that user can decide when they don't want it and we can set it by default based on image size for the image and this way we remove layout shift for users automatically.
> Added aspect ratio property to sizes

- apps/designer/app/canvas/features/text-editor/interop.ts
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- packages/react-sdk/src/components/__generated__/rich-text-link.props.json
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/components/meta.ts
- packages/react-sdk/src/components/rich-text-link.stories.tsx
- packages/react-sdk/src/components/rich-text-link.tsx
- packages/react-sdk/src/components/rich-text-link.ws.tsx
Droppable link an link created in text editor have different requirements. We should split them. In the next PR they will get different types so we will avoid similar issues in the future.
> Split Link and RichTextLink components

- packages/design-system/lostpixel.config.ts
Preparation to the migration to lost-pixel platform v1. The URL introduced in this PR will point to legacy lost-pixel so that until we migrate to next version lost-pixel works undisrupted.
> Make lost-pixel request legacy backend

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-drag-drop.ts
- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/canvas/shared/use-track-selected-element.ts
- apps/designer/app/designer/features/sidebar-left/panels/components/components.tsx
- apps/designer/app/designer/shared/tree/index.tsx
- packages/project/src/shared/tree-utils/find-closest-non-inline-parent.ts
- packages/react-sdk/src/components/body.ws.tsx
- packages/react-sdk/src/components/bold.ws.tsx
- packages/react-sdk/src/components/box.ws.ts
- packages/react-sdk/src/components/button.ws.tsx
- packages/react-sdk/src/components/component-type.ts
- packages/react-sdk/src/components/form.ws.tsx
- packages/react-sdk/src/components/heading.ws.tsx
- packages/react-sdk/src/components/image.ws.tsx
- packages/react-sdk/src/components/input.ws.tsx
- packages/react-sdk/src/components/italic.ws.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/components/paragraph.ws.tsx
- packages/react-sdk/src/components/rich-text-link.ws.tsx
- packages/react-sdk/src/components/span.ws.tsx
- packages/react-sdk/src/components/subscript.ws.tsx
- packages/react-sdk/src/components/superscript.ws.tsx
- packages/react-sdk/src/components/text-block.ws.tsx
- tsconfig.json
Boolean flags may have a lot of combinations which can lead to unexpected bugs. Better approach is to categorize nodes with specific behaviours.
Here I added 5 types
- container - can accept other components with dnd
- control - usually form controls like inputs, without children
- embed - images, videos or other embeddable components, without children
- rich-text - can be edited on double click
- rich-text-child - formatted text fragment, not listed in components list
> Replace flags with component type

- packages/design-system/package.json
- yarn.lock
We use lost-pixel only as github action. Having it in dependenies adds ~270MB in node_modules and breaks vercel CI. With this change we can remove hack around odiff.
> Drop lost-pixel dependency

- packages/react-sdk/src/components/span.ws.tsx
Mistyped when added type to components.
> Fix span component type

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-drag-drop.ts
- apps/designer/app/designer/shared/tree/index.tsx
- packages/react-sdk/src/components/body.ws.tsx
- packages/react-sdk/src/components/component-type.ts
Body is the only container which should not be listed. After discussing with Oleg decided to give it separate body type.
> Give body separate type in sdk

- apps/designer/app/designer/features/style-panel/shared/dependencies.ts
- apps/designer/app/designer/features/style-panel/style-settings.tsx
For example property "clear"  was  not showing up in position section because of that. It is supposed to show when display is any block-level value
> Fix dependency mapping for blockLevelElements

- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/shared/feature-flags/flags.ts
- apps/designer/app/shared/theme/theme.ts
It will keep working if you enable feature flag "dark"
closes https://github.com/webstudio-is/webstudio-designer/issues/547
We are disabling it because our process for defining colors for both modes didn't work well and we don't have resources to properly test in both modes all components.
We will reenable it once we have redone the colors in the theme and got a process for designers to test each component in both modes.
> Disable dark theme for now until we got it up-to-date

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.stories.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
The issue is if we select on canvas instance of one Box for example, and then other box, scrub had in the state value of first selected Box.
https://user-images.githubusercontent.com/5077042/206211694-19124e0b-5b90-4aef-8848-7ebe7f1d7bae.mov
> Fix scrub uses other instance value

- packages/project/src/db/props.ts
- We've lost an `await` at `client.instanceProps.create` when we moved to tranasactions.
- Also I've removed "If our client is not a transaction client, we need to create a transaction", I think the reason this code exists is that we tried to preserve transaction that was originally added because we thought it creates parallelism.
> Fix props clone

- @types/css-tree.d.ts
- apps/designer/app/designer/features/style-panel/shared/parse-css-value.test.ts
- apps/designer/app/designer/features/style-panel/shared/parse-css-value.ts
Switching display from flex on block caused error in input field
We were not able to parse display block etc
As this is not fixed for display props.
```
setProperty should be called with a style object, string is deprecated
```
So we got that "parsed not valid behavior" which we decided to be invalid.
> Fix switch display

- apps/designer/app/routes/dashboard/index.tsx
- apps/designer/app/routes/login/index.tsx
- apps/designer/app/routes/rest/project/clone.$domain.ts
- apps/designer/app/services/auth.server.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/92
We store user session in storage and checked its existance to check if user is logged in. Though where we clear db or for example delete user this session becomes stale so we should check if user exists in db too.
> Check authenticated user against db

- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/sidebar-left/lib/header.tsx
- apps/designer/app/designer/features/sidebar-left/panels/pages/pages.tsx
- apps/designer/app/designer/features/sidebar-left/panels/pages/settings.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/lock.tsx
- apps/designer/app/designer/features/style-panel/sections/typography/typography.tsx
- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/designer/features/topbar/share.tsx
- apps/designer/app/designer/shared/design-tokens-manager/item-menu.tsx
- apps/designer/app/designer/shared/fonts-manager/item-menu.tsx
- packages/design-system/src/components/combobox.tsx
- packages/design-system/src/components/dialog.tsx
- packages/design-system/src/components/icon-button-deprecated.tsx
- packages/design-system/src/components/icon-button-with-menu.tsx
- packages/design-system/src/components/popover.tsx
- packages/design-system/src/components/search-field.tsx
- packages/design-system/src/components/sheet.tsx
- packages/design-system/src/components/text-field.stories.tsx
- packages/design-system/src/index.ts
We are implementing new design with different variants so first deprecate old implemention and then step by step migrate to new version.
> Deprecate legacy icon button in design system

- packages/css-engine/src/core/css-engine.test.ts
- packages/css-engine/src/core/css-engine.ts
- packages/css-engine/src/core/rules.ts
We haven't been sorting the media queries correctly
> Fix media query specificity

- apps/designer/app/designer/features/style-panel/controls/color/color-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-family/font-family-control.tsx
- apps/designer/app/designer/features/style-panel/controls/image/image-control.tsx
- apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
- apps/designer/app/designer/features/style-panel/controls/select/select-control.tsx
- apps/designer/app/designer/features/style-panel/sections/flex-child/flex-child.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/lock.tsx
- apps/designer/app/designer/features/style-panel/sections/typography/typography.tsx
- apps/designer/app/designer/features/style-panel/shared/color-picker.tsx
- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.stories.tsx
- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/designer/app/designer/features/style-panel/shared/get-final-value.ts
- apps/designer/app/designer/features/style-panel/shared/get-inherited-style.ts
- apps/designer/app/designer/features/style-panel/style-sections.tsx
- apps/designer/app/designer/features/style-panel/style-settings.tsx
- apps/designer/package.json
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/to-value.ts
- yarn.lock
The reason of use opaque types, as otherwise props like `value` reused everywhere.
Implemented same as CssValueInputLogic - during input editing nothing changed.
Error is shown on Enter click. Value resetted on blur.
> Add new RGB Style, then fix typescript errors

- packages/react-sdk/package.json
This should fix the problem reported on this line: https://github.com/webstudio-is/webstudio-saas/actions/runs/3657427162/jobs/6181006430#step:6:52 , cc @andrasbacsai 
Even though [you only reach for a type](https://github.com/webstudio-is/webstudio-designer/blob/1a66acb79c8c560b3a54b55512c2779991a68eff/packages/react-sdk/src/tree/root.ts#L11), you still should declare this package among your dependencies - otherwise, it won't be installed by your consumers and thus the TS compilation will fail for them.
> Move `@webstudio-is/design-tokens` to `@webstudio-is/react-sdk` prod deps

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
Fixes Enter non-working part of #603, but not fixes Check mark showing logic.
The wrong value is used to compare the selected field, https://github.com/webstudio-is/webstudio-designer/blob/26d0d0c2a6b3fe21c2298e451ffea5adc350290e/packages/design-system/src/components/combobox.tsx#L203 as its compares with current item but not with already selected
> Enter has no effect if menu is open and no value selected

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/props.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.ts
- apps/designer/app/shared/props-utils/update-props.test.ts
- apps/designer/app/shared/props-utils/update-props.ts
- packages/project/src/shared/canvas-components/instance-data.ts
- packages/react-sdk/src/user-props/types.ts
Will help with https://github.com/webstudio-is/webstudio-designer/issues/628
treeId is stored in every props update which complicates data flow and requires passing it everywhere. Here I instead pass it inside of transaction.
This allowed us pass undefined in props data when select instance so we no longer need to create empty instance props. Updates will create it lazily.
> Remove treeId from props updates

- packages/design-system/src/components/primitives/numeric-gesture-control.ts
- Fixed #626
- Limited movement of cursor to just one coordinate. Not sure it's a good idea, but currently in `main` we move both coordinates for "horizontal" but only one for "vertical", so I've made it consistent.
> Scrub fixes

- apps/designer/app/designer/shared/assets/types.ts
- apps/designer/app/designer/shared/assets/use-assets.tsx
- apps/designer/app/designer/shared/fonts-manager/item-utils.ts
- apps/designer/app/designer/shared/image-manager/image-manager.tsx
- apps/designer/app/designer/shared/image-manager/image-thumbnail.tsx
Now image delete is shown immediately on delete.
PR_1 of #546  (simplifies logic and types for image thumbnail)
> Hide deleting assets immediately on delete

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- packages/design-system/src/components/primitives/numeric-gesture-control.ts
- packages/design-system/src/components/text-field.tsx
https://discord.com/channels/955905230107738152/1052545317922406440
> so the problem is useScrub wants to remove focus from input: https://github.com/webstudio-is/webstudio-designer/blob/c70d9ff21a64da12a0562d046246a5e359d556e9/apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx#L111
> but popover wants to keep focus inside content while it's open (not configurable): https://github.com/radix-ui/primitives/blob/81b25f4b40c54f72aeb106ca0e64e1e09655153e/packages/react/popover/src/Popover.tsx#L261-L263
> and they fight
> Fix performance issue with scrub when used inside popover

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/canvas/shared/instance.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/628
Same issue as with selected outline. Styles were sent from detached element when tag prop is changed.
Moving it to selected instance connector just works because styles already applied when effect is called and it's remounted on every style change.
> Send selected instance data from connector

- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/inspector/inspector.tsx
Closes https://github.com/webstudio-is/webstudio-designer/issues/662
It was using flex-direction raw by default which led to that space, no idea though, why it worked when opened.
1. select any instance
2. style panel sections are all collapsed
3. see an additional  empty column visible in style panel
> Fix inspector layout when style panel sections are collapsed

- apps/designer/app/designer/features/breakpoints/use-subscribe-shortcuts.ts
- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/shared/shortcuts/index.ts
- apps/designer/app/shared/shortcuts/shortcuts.ts
This enables to keep browser zoom behavior for accessibility and zooming on canvas happens using +- keys without modifiers.
Closes https://github.com/webstudio-is/webstudio-designer/issues/658
1. press - on canvas and in designer for zoom out
2. press + for zoom in
> Use +- keys for zoom without cmd

- apps/designer/app/designer/features/inspector/inspector.tsx
- apps/designer/app/designer/features/sidebar-left/sidebar-left.tsx
- apps/designer/app/designer/shared/assets/assets-shell.tsx
- packages/design-system/src/components/flex.tsx
Previous changes with flex-direction: column broke the left sidebar height
1. click + button
2. see all components without scrollbars
> Make left sidebar grow full height

- .npmrc
- packages/prisma-client/package.json
- pnpm-lock.yaml
Pnpm supports yarn shell emulator under flag which fixes a few shell bugs and works the same on all operating systems.
Here it replaced huge concurrently library.
```diff
du -ck node_modules
-829592
+813384
```
2. expect xyz
> Replace concurrently with shell emulator

- apps/designer/app/designer/features/style-panel/controls/font-weight/font-weight-control.tsx
Fixes https://github.com/webstudio-is/webstudio-designer/issues/677
When we select a custom font, the previously selected font weight might be not supported, so we need to set the first supported weight.
2. open font-family selector
3. upload custom font
4. select custom font
5. see font is applied
6. font-weight will be empty if the custom font doesn't support the previous weight
> Apply the first available weight when current weight isn't supported 

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/features/workspace/canvas-tools/hooks/use-subscribe-instance-rect.ts
- apps/designer/app/designer/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/625
Frequently changed style values with for example scrub makes outline look laggy because of latency between iframe and designer (where outline is rendered).
Here I subscribed to previewStyle and send undefined to hide rect. We do the same when scroll canvas and cannot update outline fast.
2. use scrub to change for example top
> Hide outline when preview styles

- apps/designer/app/designer/features/style-panel/sections/spacing/spacing.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/tooltip.tsx
- packages/design-system/src/components/enhanced-tooltip.tsx
- packages/design-system/src/index.ts
Add delay to spacing control tooltip.
1. Hover spacing controls, see tooltip delayed
> Add delay to spacing tooltip

- apps/designer/.storybook/preview.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.stories.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.tsx
Ref https://github.com/webstudio-is/webstudio-designer/issues/590
Solution is simple. To represent flexbox we just use flexbox.
It does not strictly follow design but follow actual flexbox behaviour.
2. open layout styles
3. set display flex
4. play with flex grid
> Fix flex grid control states

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/shared/dom-hooks/use-window-resize.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/446 https://github.com/webstudio-is/webstudio-designer/issues/638
Here I solved 2 issues.
Outline is hidden while canvas is resizing.
And after resizing outline rect is recomputed.
1. select an instance
2. click on breakpoints menu
3. use slider to change the canvas width or choose one of preset breakpoints
> Hide outline when window is resizing

- apps/designer/app/canvas/hovered-instance-connector.ts
Found an issue when hover a few elements fast and then move cursor out of iframe hover gets stuck on some element. This is because we use combination of mouseover and mouseout events.
So when we move out of one instance to another it looks like this
over
out
over
out
Which may lead to race conditions. So here out is canceled by every hover and delayed a little to always emit last.
> Fix hover outline

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
Click into css-input, delete everything -  menu occured
Click tab - must show red rectangle instead of just tabbing into new control
> Fix onComplete event lost if was tab during opened menu and nothing selected

- apps/designer/app/designer/features/style-panel/controls/color/color-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-family/font-family-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-weight/font-weight-control.tsx
- apps/designer/app/designer/features/style-panel/controls/image/image-control.tsx
- apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
- apps/designer/app/designer/features/style-panel/controls/select/select-control.tsx
- apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
- apps/designer/app/designer/features/style-panel/sections/flex-child/flex-child.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
- apps/designer/app/designer/features/style-panel/style-sections.tsx
- apps/designer/app/designer/features/style-panel/style-settings.tsx
We might not need to pass style config everywhere and instead we can pass only property.
In another PR will remove passing style configs everywhere.
> Pass property to control

- apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
- apps/designer/app/designer/features/style-panel/controls/select/select-control.tsx
- apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
- apps/designer/app/designer/features/style-panel/shared/configs.ts
- apps/designer/app/designer/features/style-panel/style-sections.tsx
- apps/designer/app/designer/features/style-panel/style-settings.tsx
Since style config is hardcoded in module scope we can access it by property instead of passing style config everywhere.
> Access style config by property

- packages/css-data/package.json
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/to-value.ts
- packages/project/package.json
- packages/project/src/db/tree.ts
- pnpm-lock.yaml
ref  #534
Next PR #705
Db support for ImageValue style.
Having that ImageValue can contain assets we need to transform assets to `assetId` and back during save/load.
`zod + dataloader` is used for transform for simplicity, allows avoiding tree traversal, and highly simplifies code.
_I want to merge it to not make one huge PR, it has no breaking changes, just a new feature save/load support_
> Background image DB support

- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/designer/features/style-panel/controls/image/image-control.tsx
- apps/designer/app/designer/features/style-panel/shared/configs.ts
- apps/designer/app/designer/shared/assets/types.ts
- apps/designer/app/designer/shared/assets/update-asset-containers.test.ts
- apps/designer/app/designer/shared/assets/use-assets.tsx
- apps/designer/app/designer/shared/image-manager/image-manager.tsx
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/utils/format-asset.ts
ref  #534
PR atop of #701
Next PR: image-set support
Ability to select background image from asset
Create a div, and select an asset for the background image.
> Add Background image to Designer app (without image-set)

- apps/designer/app/designer/features/props-panel/control.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/style-panel/controls/color/color-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-family/font-family-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-weight/font-weight-control.tsx
- apps/designer/app/designer/features/style-panel/controls/image/image-control.tsx
- apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
- apps/designer/app/designer/features/style-panel/controls/select/select-control.tsx
- apps/designer/app/designer/features/style-panel/controls/text/text-control.tsx
- apps/designer/app/designer/features/style-panel/sections/flex-child/flex-child.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.stories.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/lock.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/spacing.tsx
- apps/designer/app/designer/features/style-panel/sections/typography/typography.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-sections.tsx
- apps/designer/app/designer/features/style-panel/style-settings.tsx
This is a step toward https://github.com/webstudio-is/webstudio-designer/issues/29
When merge browser style and local styles we can specify the source of the style. Later we can add additional info about inherited and cascaded styles.
> Add style info with source data

- packages/asset-uploader/src/targets/s3/upload.ts
As of now it's possible to directly upload via rest multiple files. 
The issue is that to get files count in request we need to parse request. 
Here I restrict uploading to just 1 file on request.
Next PR: Restrict file count per project.
Use hide whitespaces for review.
2. expect xyz
> Add assets upload restriction 1 file per request

- apps/designer/app/designer/features/style-panel/shared/style-info.test.ts
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/29 https://github.com/webstudio-is/webstudio-designer/issues/649
Now instead of showing computed styles which come from parent instances or other breakpoints we can show actual value we set there.
1. add Box to canvas
2. change font size on Body to 2rem
3. check Box font size
1. add Box to canvas
2. change font weight on Box to 600
3. select tablet breakpoint
4. check Box font weight
> Fallback to cascaded and inherited when value not set

- apps/designer/app/designer/features/style-panel/controls/menu/menu-control.tsx
- apps/designer/app/designer/features/style-panel/controls/toggle/toggle-control.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/layout.tsx
- apps/designer/app/designer/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/spacing.tsx
- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/designer/app/designer/features/style-panel/shared/property-name.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- packages/design-system/src/components/icon-button-with-menu.tsx
Added remote (ex inherited) highlight for controls.
Migrated menu control to new icon button.
> Show remote style source in UI

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/designer/app/designer/features/style-panel/shared/css-value-input/keyword-utils.test.ts
- apps/designer/app/designer/features/style-panel/shared/css-value-input/keyword-utils.ts
- apps/designer/app/designer/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- packages/design-system/src/components/combobox.tsx
ref #465 for css-value-input
Add beauty names to keywords, a little bit better search for keywords.
+ Fixes non-working scrub.
+ Fixes jumping cursor.
1.
Write `min-content` inside `width` field  - All options you see must have `Pascal Case`
Select value through menu - inputValue must be also in `Pascal Case`
2.
Edit width input, write `Min Content`, and click Enter - must be saved with `Min Content` value. 
(internally must be keyword with value=`min-content`) 
3.
Edit width input, write `min-content`, and click Enter - must be saved with `Min Content` value. 
(internally must be keyword with value=`min-content`) 
4. 
Write `min content`, click tab - must be saved with `Min Content` value. 
(internally must be keyword with value=`min-content`)
5. Edit input in any place of cursor it must …
> Fix css input (scrub, etc) Beautify options and input for css-value-input

- apps/designer/.env.example
- apps/designer/app/designer/shared/assets/use-assets.tsx
- packages/asset-uploader/src/db/create.ts
- packages/asset-uploader/src/db/load.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/targets/fs/upload.ts
- packages/asset-uploader/src/targets/s3/upload.ts
- packages/asset-uploader/src/utils/get-asset-data.ts
Set at VERCEL env 
Restrict assets by MAX_ASSETS_PER_PROJECT env variable.
Try upload more than 4 files.
Get Error: "`Max ${count} assets per project reached`"
> Restrict assets uploading by MAX_ASSETS_PER_PROJECT env variable

- apps/designer/app/designer/features/breakpoints/breakpoints.tsx
Issue:
Breakpoints panel suggests delete currently selected instead of specific breakpoint #691
1. click edit breakpoint in top bar
2. delete other breakpoint than the currently selected
3. expect to show the message to delete the breakpoint and not the currently selected in the confirm message
> Fix selected breakpoint to delete

- apps/designer/app/designer/features/style-panel/sections/spacing/input-popover.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/layout.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/scrub.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/spacing.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/types.ts
- apps/designer/app/designer/features/style-panel/shared/modifier-keys.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
Adds option / shift support to scrub in spacing. Closes #668
- Try to scrub in spacing while holding SHIFT or OPTION (ALT in Windows)
- Try to press and release SHIFT / OPTION multiple times during scrub
- Try to press SHIFT / OPTION while hovering over a property (other properties will highlight even without scrub)
> Support option/shift in spacing's scrub

- packages/design-system/src/components/box.tsx
because we removed width:100% from input it seems like ideal strategy is to always have minWidth: 0 defined since it just fixes flexbox everywhere
1. open style panel
> Style panel css value input layout was broken 

- apps/designer/app/designer/features/style-panel/shared/property-name.tsx
Ref https://github.com/webstudio-is/webstudio-designer/issues/29
Here added info in popover where cascaded and inherited styles come from.
> Show in popover where remote style comes from

- apps/designer/app/designer/features/style-panel/sections/spacing/keyboard.ts
- apps/designer/app/designer/features/style-panel/sections/spacing/layout.tsx
- apps/designer/app/designer/features/style-panel/sections/spacing/spacing.tsx
Adds keyboard support to the Spacing control. Closes #666
1. Focus spacing control using TAB
2. Blue outline should appear and "Margin Top" should get highlighted
3. Arrow keys should change highlighted item
4. `Enter` should open popover for the highlighted item
6. Mouse navigation should still work when control is focused
> Keyboard support in spacing control

- apps/designer/app/designer/features/style-panel/style-source-input/index.ts
- apps/designer/app/designer/features/style-panel/style-source-input/style-source-input.stories.tsx
- apps/designer/app/designer/features/style-panel/style-source-input/style-source-input.tsx
- apps/designer/app/designer/features/style-panel/style-source-input/style-source.tsx
1. Added a way to disable/enable style source item
1. source item menu > disable
2. source item menu > enable
- test it in the story
> Implement disable function for style source input

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/designer/designer.tsx
- apps/designer/app/shared/sync/sync-stores.ts
- apps/designer/package.json
- pnpm-lock.yaml
We finally can change states connected to immerhin from designer. Here I added subscription to designer changes and fixed cyclic events with new "source" parameter provided on transaction creation.
> Synchronize transactions created in designer

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/designer/features/style-panel/shared/style-info.test.ts
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- packages/project/src/shared/canvas-components/instance-data.ts
Here rewritten style info computing with normalized styles list. Was able to get rid of sending element css rules from canvas.
> Use normalized styles in style panel

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/designer/features/props-panel/use-props-logic.ts
- packages/project/src/shared/canvas-components/instance-data.ts
Props state is synchronized between designer and canvas. We can safely get rid of sending props in selectInstance event.
> Use props from synchronize state instead of selected instance

- packages/http-client/jest.config.js
- packages/http-client/package.json
- packages/http-client/tsconfig.json
- pnpm-lock.yaml
Forgot to migrate it to our build-package script before. Now we got rid of tsup.
```diff
-804060
+794324
```
```diff
root> pnpm build
-16s
+10s
```
> Use build-package for http-client

- apps/designer/app/shared/db/misc.server.ts
- packages/prisma-client/prisma/migrations/20230119013820_instance-props-uniq/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/prisma-client/src/prisma.ts
- packages/project/src/db/build.ts
- packages/project/src/db/project.ts
- packages/project/src/db/props.ts
2 Issues.
- Absense of unique index caused huge update times like 100ms.
- updateMany creates implicit transaction which in prisma has very small timeouts
2. expect xyz
> Fix Transaction already closed: Could not perform operation on InstanceProps

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/canvas/shared/styles.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/store-utils.test.ts
- apps/designer/app/shared/store-utils.ts
- apps/designer/package.json
- pnpm-lock.yaml
The new utility allows us to subscribe to filtered array and give the same reference when all items are the same. This prevents unnecessary rerenders in react because getSnapshot considers value unchanged.
This is necessary for styles and we'll need same for props.
The downside is filter and shallow compare will be called on every change for every instance. We will see if this give us performance issues.
> Add shallowComputed nanostores utility

- packages/project/package.json
- packages/project/src/db/styles.ts
- packages/project/src/db/tree.ts
- packages/react-sdk/src/db/style.ts
- pnpm-lock.yaml
Found zod allows to pass anything in transform without type checking. This means we can easily get unexpected result. In this case we could get undefined as asset.
As a solution I defined two versions of types, client side and stored in db. Conversion is implemented on db routes side.
This makes data flow more clear and let us describe only two versions of types instead of tree (in, out, client side).
> Transform styles without zod

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/footer/breadcrumbs.tsx
- apps/designer/app/designer/features/footer/footer.tsx
- apps/designer/app/designer/features/sidebar-left/lib/navigator/navigator.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
We often need to sync states between canvas and designer without sending to server. Here added logic to synchronize whole states between frames. Almost same as immerhin logic.
Here synchronized selectedInstanceId store.
> Synchronize non-immerhin stores

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/footer/breadcrumbs.tsx
- apps/designer/app/designer/features/inspector/inspector.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/designer/features/props-panel/use-props-logic.ts
- apps/designer/app/designer/features/sidebar-left/lib/navigator/navigator.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-panel.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/outline/selected-instance-outline.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/designer/app/designer/features/workspace/workspace.tsx
- apps/designer/app/designer/shared/inspector/component-info.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
- packages/project/src/shared/canvas-components/instance-data.ts
selectedInstanceData update is sent from canvas after every render in effect. The latency can be avoided by subscribing to selectedInstanceId directly. For styles added new store selectedInstanceBrowserStyle and synchronized it the same way. Works without flashing in UI even without reset.
> Migrate designer to selected instance store

- apps/designer/app/canvas/hovered-instance-connector.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/sidebar-left/lib/navigator/navigator.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/hooks/use-subscribe-instance-rect.ts
- apps/designer/app/designer/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
- packages/project/src/shared/canvas-components/instance-data.ts
Recently added support for synchronization of non-immerhin stores. Here refactored instance hovering from pubsub to such stores.
Designer and canvas can both set hovered instance id and instance connector subscribes to these changes and sends to designer outline rect.
> Migrate hovered outline to synchronized stores

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/shared/styles.ts
- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/styles/style-rules.test.ts
- packages/project/src/shared/styles/style-rules.ts
- packages/react-sdk/src/db/style.ts
- packages/react-sdk/src/db/types.ts
After discussing with @kof figured we do not need to store preset styles in db as after sdk upgrade components may still break.
Sdk versioning along with its hardcoded values will solve the problem better.
> Drop preset styles from db

- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/canvas/hovered-instance-connector.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/styles.ts
- apps/designer/app/canvas/shared/use-drag-drop.ts
- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/canvas/shared/use-track-selected-element.ts
- apps/designer/app/designer/features/props-panel/control.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.test.ts
- apps/designer/app/designer/features/props-panel/use-props-logic.ts
- apps/designer/app/designer/features/sidebar-left/panels/components/component-thumb.tsx
- apps/designer/app/designer/features/sidebar-left/panels/components/components.tsx
- apps/designer/app/designer/features/workspace/canvas-tools/outline/label.tsx
- apps/designer/app/designer/shared/inspector/component-info.tsx
- apps/designer/app/designer/shared/tree/index.tsx
- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/tree-utils/create-instance.ts
- packages/project/src/shared/tree-utils/find-closest-non-inline-parent.ts
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/db/instance.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/tree/wrapper-component.tsx
We want to decouple schema stored in db from sdk which generates a list of components. Components will be added dynamically later so better avoid component name enum.
> Treat component name as generic string

- package.json
- pnpm-lock.yaml
Ref https://github.com/usmanyunusov/nano-staged
Lint-staged has a lot of dependencies and a few versions of the same dependencies.
Nano-staged is smaller alternative used in many "nano" packages.
```diff
-766128
+763924
-900ms
+200ms
```
> Replace lint-staged with nano-staged

- packages/project/src/db/props.ts
- packages/project/src/db/tree.ts
Db data with asset ids was parsed as client data with resolved assets. Fixed by reusing props parsing/serializing logic in tree.
Asset inlining complicates code so we need to have two versions of types and transformations.
> Fix props with assets loading

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
Here added normalized props logic to transactions and replaced useAllUserProps with computed store.
> Migrate designer to normalized props

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/shared/db/canvas.server.ts
- apps/designer/app/shared/sync/sync-stores.ts
- packages/project/src/db/props.ts
- packages/react-sdk/src/db/index.ts
- packages/react-sdk/src/db/types.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/tree/root.ts
- packages/react-sdk/src/user-props/all-user-props.ts
Now all props is migrated on client side, we can drop legacy store and switch to new format server side.
> Switch to normalized props on server

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/shared/copy-paste/serialize.ts
- apps/designer/app/shared/copy-paste/use-instance-copy-paste.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/project/src/index.ts
- packages/project/src/shared/props/clone-user-props.ts
- packages/project/src/shared/props/index.ts
Copy/paste of props and styles was broken while converting to normalized data. Here fixed both by providing new instanceId.
> Fix copy paste of props and styles

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/828
Delete instance along with own and descendants styles and props.
This will let us to avoid bloating db with unused data.
> Delete instance styles and props

- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/shared/shortcuts/shortcuts.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/755
react-hotkeys by default prevents reacting when native elements are focused. Here I globally enabled input, select and textarea for both designer and canvas to catch undo/redo while focused.
> Fix undo/redo when input is focused

- packages/prisma-client/prisma/migrations/20230129141714_unused_schema/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/prisma-client/src/types.ts
DesignTokens was removed from schema but without migration. Removed everything else unused too.
- Tree.presetStyles
- InstanceProps
- DesignTokens
> Drop unused schema

- .github/workflows/main.yml
- package.json
- pnpm-lock.yaml
- turbo.json
We use very old version of turborepo which often fails. Here latest one with persistent tasks for watch mode support.
We also need to enable remote caching to get turbo benefits on CI.
While the size of turbo repo grew. Sice 1.3 a lot of artifacts for unpopular systems were removed so we still get smaller node_modules.
```
-797528
+788132
```
@kof to enable remote caching need to run `pnpm turbo login` and then `pnpm turbo link`.
> Upgrade to turbo 1.7

- @types/web-crypto.d.ts
- packages/asset-uploader/package.json
- packages/prisma-client/package.json
- packages/react-sdk/package.json
- packages/scripts/package.json
- packages/trpc-interface/package.json
- pnpm-lock.yaml
The latest version supports types for websubtle so no need for our types shim.
> Upgrade @types/node

- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/db/canvas.server.ts
- packages/project-build/src/schema/styles.ts
- packages/project-build/src/types.ts
- packages/project/src/db/build.ts
- packages/project/src/db/schema.ts
- packages/project/src/db/styles.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/styles/style-rules.test.ts
- packages/project/src/shared/styles/style-rules.ts
Designer data still rely on legacy style format though here I migrated preview styles to combination of style source selections and styles from build.
> Support multiple style sources in preview

- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/designer/features/breakpoints/breakpoints.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.test.ts
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
Replaced manual array manipulations with array utils and reused styles index to compute style info.
This will let to do less work when switch to build styles.
> Switch to utils for style management

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/inspector/inspector.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-panel.tsx
- apps/designer/app/routes/rest/patch.ts
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project/src/db/index.ts
- packages/project/src/db/style-source-selections.ts
- packages/project/src/db/style-sources.ts
Here added style sources and style source selections stores, added updates along styles and covered with tests. Patch utilities for rest endpoint are not used to avoid collision with temporary logic in styles.
Next step will be integration styles with style sources on client.
> Add style sources stores

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.test.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/routes/rest/patch.ts
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project-build/src/schema/styles.ts
- packages/project-build/src/types.ts
- packages/project/src/db/build.ts
- packages/project/src/db/schema.ts
- packages/project/src/db/style-source-selections.ts
- packages/project/src/db/styles.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/styles/style-rules.test.ts
- packages/project/src/shared/styles/style-rules.ts
Styles are resolved based on style sources of every instance. Here finally migrated whole logic to new variant.
For now the only local style source is used as default for style updates. In the next PR will add support for tokens.
> Migrate styles to style sources variant

- apps/designer/app/routes/rest/pages.$projectId.ts
- apps/designer/app/shared/db/canvas.server.ts
- packages/asset-uploader/src/db/create.ts
- packages/eslint-config-custom/index.js
- packages/prisma-client/prisma/migrations/20230202192437_composite_ids/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/project/src/db/breakpoints.ts
- packages/project/src/db/build.ts
- packages/project/src/db/props.ts
- packages/project/src/db/style-source-selections.ts
- packages/project/src/db/style-sources.ts
- packages/project/src/db/styles.ts
- packages/project/src/db/tree.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/896
Here changed Asset, Build and Tree tables to composite ids with projectId to improve security and simplify project management.
> Use projectId as composite id in tables

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/shared/instance.ts
- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/designer/features/sidebar-left/navigator/navigator.tsx
Synchronized stores allow us to change data anywhere we want so we can get rid of pubsub in almost all cases.
Here removed delete instance subscription and used delete instance command.
> Delete instance without pubsub

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/shared/shortcuts/shortcuts.ts
- apps/designer/package.json
- pnpm-lock.yaml
Here's the issue. We track shortcuts on canvas and designer though designer invoke hotkeys with shared configuration and loose edge cases. For example delete should not be invoked on inputs though shared configuration enforce it. If we disable inputs then undo/redo will stop working.
So for better safety we should track shortcuts in both designer and canvas with the same code and update synchronized stores instead of synchronizing shortcuts.
> Track delete shortcut on both canvas and designer

- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/topbar/topbar.tsx
- apps/designer/app/designer/features/topbar/view-mode.tsx
- apps/designer/app/designer/shared/sync/sync-server.ts
- apps/designer/app/routes/designer/$projectId.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/trpc-interface/src/authorize/project.server.ts
- packages/trpc-interface/src/index.server.ts
- packages/trpc-interface/src/shared/authorization-router.ts
Disable sync for user/token with "view" permit and show view mode icon
Create Share view link. Copy link. Insert into the incognito window. See the screenshot above. Any changes should not cause savings.
_Assets saving, for now, are not prevented_
> Disable sync for user/token with "view" permit and show view mode icon

- apps/designer/app/designer/features/sidebar-left/navigator/navigator.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Looks like calling onDelete in navigator duplicates global delete shortcut.
> Fix double delete when focused navigator tree

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/designer/app/designer/features/props-panel/control.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/props-panel/use-props-logic.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/tree-utils.test.ts
- packages/project-build/src/schema/props.ts
- packages/project-build/src/schema/styles.ts
We decided to get rid of "Item" naming, here renamed everything left.
- PropsItem -> Prop
- StylesItem -> StyleDecl
> Rename singular props and styles names

- apps/designer/app/designer/shared/assets/asset-upload.tsx
- apps/designer/app/designer/shared/fonts-manager/item-menu.tsx
- apps/designer/app/designer/shared/image-manager/image-info.tsx
In view mode, we need to prevent users from deleting / creating assets in UI. (Server-side protection already done in the previous PR)
The other way can be just to hide buttons from the UI.
Also tooltip duration for disabled actions can be smaller.
Share the Link with View permissions.
Open that link in incognito mode.
Try to create/delete an asset
> Assets view mode

- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/designer/features/topbar/publish.tsx
- apps/designer/app/designer/features/topbar/share.tsx
- packages/design-system/src/components/floating-panel-popover.tsx
Disable share and publish buttons if not owner
Also changed Deprecated Coponents on FloatingPanel
Share the Link with View/Build permissions.
Open that link in incognito mode.
Try to share / publish project.
> Disable share and publish buttons if not owner

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/designer/designer.tsx
- apps/designer/app/designer/features/inspector/inspector.tsx
- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-panel.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
this will let to reuse the logic and newly generated local style source with style source input.
> Move selected style source into separate store

- packages/project/src/db/build.ts
- packages/project/src/db/tree.ts
Currently if you try to duplicate a project the app crashes like this:
The problem is that we use destination `projectId` when trying to load source tree. This PR fixes the issue.
Go to dashboard and duplicate a project
> Fix crash when duplicating a project

- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-panel.tsx
- apps/designer/app/designer/features/style-panel/style-source-section.tsx
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/feature-flags/src/flags.ts
Here basic support for styles sources in style panel
- new token creation
- existing token adding for instance
- token removing from instance
- sorting with dnd
- style source selection for styles  editing
Added feature flag to hide it on prod for now.
> Implement basic style source ui

- apps/designer/app/designer/features/props-panel/props-panel.stories.tsx
- apps/designer/app/designer/features/props-panel/props-panel.tsx
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/sync/sync-stores.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project-build/src/schema/props.ts
- packages/project-build/src/types.ts
- packages/project/src/db/props.ts
- packages/project/src/db/tree.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/root.ts
While normalized array of props give us flexibility with atomic updates we still cannot use it for collaboration because patches are applied with index in this array which may leads to unexpected results when two users collaboate on the same tree, for example both put new prop and edit it before synchronization by the same index, we are getting conflict.
To avoid such issues we can switch client representation to maps. Almost all data have ids to use in map as keys. Map makes collaboration almost conflict free.
> Represent props on client as map

- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-source-section.tsx
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project-build/src/schema/style-sources.ts
- packages/project/src/db/build.ts
- packages/project/src/db/style-sources.ts
- packages/project/src/shared/schema.ts
Same as props. Fast access and fast update. So we no longer need separate store with style sources index.
> Represent style source as map

- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-source-section.tsx
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project-build/src/index.ts
- packages/project-build/src/schema/style-source-selections.ts
- packages/project-build/src/schema/style-sources.ts
- packages/project-build/src/types.ts
- packages/project/src/db/style-source-selections.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/styles/style-rules.test.ts
- packages/project/src/shared/styles/style-rules.ts
Patches by indexes are replaced with patches by keys so we could get almost conflict free collaboration.
> Represet style source selections as map

- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/designer/features/style-panel/style-source-section.tsx
Missed this case. We should always rely on either raw data or use computed store within single update.
> Fix multiple local style sources

- apps/designer/app/env/env.server.ts
- apps/designer/app/services/trpc.server.ts
- packages/trpc-interface/src/shared/client.ts
This branch will allow preview deployments of trpc authorization and other saas services 
Currently in this branch following variables are set:
```env
TRPC_SERVER_URL=https://wstd.work/services
TRPC_SERVER_API_TOKEN=secrettoken
```
It should use preview saas trpc service having `ory_setup` name
Here `https://wstd.work/services` is router url, router using `x-branch-name` reroutes traffic to the right saas preview
This is for test ONLY, variables would be removed if all is ok and testing will proceed on saas side
Create a new Project, create auth tokens, and check it works.
Check saas service preview logs that requests are there. …
> Add support of saas edge-api trpc preview router

- apps/designer/app/designer/features/style-panel/controls/font-weight/font-weight-control.tsx
- apps/designer/app/designer/features/style-panel/controls/font-weight/is-supported-font-weight.test.ts
- apps/designer/app/designer/features/style-panel/controls/font-weight/is-supported-font-weight.ts
- packages/css-engine/src/core/rules.ts
- packages/fonts/package.json
- packages/fonts/src/__snapshots__/get-font-faces.test.ts.snap
- packages/fonts/src/font-data.ts
- packages/fonts/src/get-font-faces.test.ts
- packages/fonts/src/get-font-faces.ts
- packages/fonts/src/schema.ts
- pnpm-lock.yaml
Closes https://github.com/webstudio-is/webstudio-designer/issues/994
Variable fonts were treated like normal fonts, so we were only showing one default font weight as available.
Now we not only detect variable fonts, but we also save all the meta data we get from them, so we can add a variable font settings UI in the future, which is a huge deal for designers, because variable fonts offer very interesting styling options and animations
2. font family, upload variable versions fonts like Monrope, Inter or Roboto Flex
3. see you can choose any font weight
4. use any styles on the font e.g. italic etc 
> Support for variable fonts

- apps/designer/app/canvas/canvas.tsx
- apps/designer/app/designer/features/props-panel/control.tsx
- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- packages/project-build/src/schema/props.ts
- packages/project/src/db/props.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/styles/global-rules.ts
- packages/react-sdk/src/context.tsx
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
- packages/react-sdk/src/tree/root.tsx
Before we checked looked for all asset ids in props, loaded assets and replaced ids with resolved assets. This is all on server. We faced a few problems with it.
- requires to maintain two versions of types: stored in db and resolved for client
- easy to break project by writing to db wrong version
Here I provide to sdk both props and assets and resolve on client with almost same amount of code.
Also replaced store setter with context, see https://github.com/webstudio-is/webstudio-designer/issues/213
> Resolve props assets on client

- apps/designer/app/designer/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/designer/app/designer/features/style-panel/shared/parse-css-value.test.ts
- apps/designer/app/designer/features/style-panel/shared/parse-css-value.ts
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/package.json
- packages/css-data/package.json
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/to-value.ts
- pnpm-lock.yaml
Enable using css functions in CssValueInput 
closes #990 
Add 
`blur(2px)` or 
`drop-shadow(16px 16px 20px blue)` or 
`blur(2px) drop-shadow(16px 16px 20px blue)` to the filter field
It should work.
> Enable using css functions in CssValueInput

- apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts
- apps/designer/app/canvas/shared/styles.ts
- apps/designer/app/designer/features/breakpoints/breakpoints.tsx
- apps/designer/app/designer/features/style-panel/shared/style-info.test.ts
- apps/designer/app/designer/features/style-panel/shared/style-info.ts
- apps/designer/app/designer/features/style-panel/shared/use-style-data.ts
- apps/designer/app/shared/copy-paste/copy-paste-instance.ts
- apps/designer/app/shared/css-utils/generate-css-text.ts
- apps/designer/app/shared/instance-utils.ts
- apps/designer/app/shared/nano-states/nano-states.ts
- apps/designer/app/shared/tree-utils.test.ts
- apps/designer/app/shared/tree-utils.ts
- packages/project-build/src/schema/styles.ts
- packages/project/src/db/build.ts
- packages/project/src/db/styles.ts
- packages/project/src/shared/schema.ts
- packages/project/src/shared/styles/style-rules.test.ts
- packages/project/src/shared/styles/style-rules.ts
Here patches by styles indexes are replaced with patch by key to prevent conflicts while collaborating.
The unusual part here is map key whiich is combined from a few fields: "styleSourceId:breakpointId:property"
This format is enforced with typescript to always use utility getStyleDeclKey to access specific style.
> Represent styles as map

- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/designer/features/breakpoints/breakpoints.tsx
- apps/designer/app/designer/features/breakpoints/trigger-button.tsx
- apps/designer/app/designer/features/breakpoints/use-subscribe-shortcuts.ts
- apps/designer/app/designer/features/breakpoints/zoom-setting.tsx
- apps/designer/app/designer/features/sidebar-left/panels/components/components.tsx
- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/designer/features/workspace/use-read-canvas-rect.ts
- apps/designer/app/designer/features/workspace/workspace.tsx
- apps/designer/app/designer/shared/nano-states/index.ts
- apps/designer/app/shared/nano-states/breakpoints.ts
- apps/designer/app/shared/shortcuts/shortcuts.ts
- apps/designer/app/shared/sync/sync-stores.ts
- apps/designer/package.json
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-designer/issues/1002
Synchronizing shortcuts with pubsub is complicated because we need to configure each case. Here instead I synchronized zoom store and run shortcuts on both designer and canvas. This way whole logic tied to state instead of event.
> Sync zoom and modify with shared shortcuts

- apps/designer/app/canvas/shared/use-shortcuts.ts
- apps/designer/app/designer/features/topbar/menu/menu.tsx
- apps/designer/app/shared/shortcuts/shortcuts.ts
Ref https://github.com/webstudio-is/webstudio-designer/issues/1004
After react-hotkeys-hook bump I didn't notice "cmd" stopped working because replaced with "meta" word as cross-platform variant.
Also moved undo/redo to shared shortcuts.
> Fix all cmd shortcuts

- apps/builder/app/builder/features/breakpoints/breakpoints-editor.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints.tsx
- apps/builder/app/builder/features/breakpoints/confirmation-dialog.tsx
- apps/builder/app/builder/features/breakpoints/preview.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/shared/breakpoints/will-render.ts
- apps/builder/app/shared/nano-states/breakpoints.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/css-data/src/schema.ts
- packages/project-build/src/index.ts
- packages/project-build/src/schema/breakpoints.ts
- packages/project/src/db/breakpoints.ts
- packages/project/src/db/build.ts
- packages/project/src/shared/canvas-components/instance-data.ts
- packages/project/src/shared/schema.ts
- packages/project/src/shared/styles/style-rules.ts
- packages/project/src/shared/tree-utils/set-instance-children.ts
- packages/react-sdk/src/css/breakpoints.ts
Breakpoints are not really related to css data and represent project build data so moving it before switching to map patches.
> Move breakpoints schema to project-build

- apps/builder/app/services/trpc.server.ts
We have trpc envs specified like this
TRPC_SERVER_URL=
TRPC_SERVER_API_TOKEN=
Which gives empty string in runtime though we check for undefined expecting envs are not defined.
In this PR I covered both undefined and empty string to not break new setups.
> Fix trpc client setup with default .env for local dev

- apps/builder/app/builder/features/breakpoints/breakpoints-editor.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/array-utils.test.ts
- apps/builder/app/shared/array-utils.ts
- apps/builder/app/shared/nano-states/breakpoints.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/project-build/src/schema/breakpoints.ts
- packages/project/src/db/breakpoints.ts
- packages/project/src/db/build.ts
- packages/project/src/shared/breakpoints/sort.test.ts
- packages/project/src/shared/breakpoints/sort.ts
- packages/project/src/shared/schema.ts
- packages/project/src/shared/styles/css.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/696
One more diff to support better conflict resolution in breakpoints patches. Breakpoints is now map and patches rely on keys instead of array indexes.
> Represent breakpoints as map

- apps/builder/app/builder/builder.tsx
Currently footer is visible in preview mode for no reason
> Hide footer in preview mode

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
- set min width to source source values
- added renaming support
- added user select for better dnd
- set default cursor when not renaming
- fix style source removing when press backspace while renaming
> Add rename support to style source input

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/routes/rest/pages.$projectId.ts
- apps/builder/app/routes/rest/patch.ts
- apps/builder/app/shared/pages/types.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- packages/project-build/src/index.ts
- packages/project-build/src/schema/pages.ts
- packages/project-build/src/types.ts
- packages/project/src/db/breakpoints.ts
- packages/project/src/db/build.ts
- packages/project/src/db/props.ts
- packages/project/src/db/style-source-selections.ts
- packages/project/src/db/style-sources.ts
- packages/project/src/db/styles.ts
- packages/project/src/db/tree.ts
- packages/project/src/shared/pages/find-by-id-or-path.ts
- packages/project/src/shared/schema.ts
- packages/project/src/shared/styles/css.ts
We are moving all build related code from project to project-build. Here moved pages schema and Build type.
> Move pages schema to project-build

- apps/builder/app/routes/$.tsx
- apps/builder/app/routes/index.tsx
- apps/builder/app/routes/rest/project.$projectId.tsx
- apps/builder/app/routes/s/css.ts
- apps/builder/app/shared/db/canvas.server.ts
- apps/builder/app/shared/router-utils/build-params.ts
- apps/builder/package.json
- packages/project/src/shared/styles/css.ts
- packages/react-sdk/src/app/root.tsx
- pnpm-lock.yaml
We are going to render CSS for all pages in production mode.
That allows us to switch on native remix links i.e. `export const links` 
Also now for `published` pages we use same data as SaaS will. 
That would allow for investigating SaaS issues faster.
[x] - Also now check does ssr css is needed at all at "edit" mode.
_Checked, as of now we don't render `style` tags serverside and that cause FOUC in designer on page switch,
cc @TrySound probably in Canvas we can render styles serverside too that would allow us to not use /s/css path for canvas inside designer_
closes #929
closes https://github.com/webstudio-is/webstudio-saas/issues/51
closes #606
In local dev mode, create 2 pages in a project, and add cross-links on both pages.
Do publish.
Go to the published page, see no fouc on link …
> Switch on link and generate css for all pages on server

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- support duplicating tokens
- removed autofocus to not block instance deleting right after instance selection
- prevent removing local style source
- refactored all operations to write generated local style source only on reorder
- select token when create
- select token when add
> Add token duplcate support in style sources

- apps/builder/app/routes/rest/patch.ts
- apps/builder/app/shared/db/canvas.server.ts
- packages/project-build/package.json
- packages/project-build/server.d.ts
- packages/project-build/server.js
- packages/project-build/src/db/props.ts
- packages/project-build/src/db/style-source-selections.ts
- packages/project-build/src/db/tree.ts
- packages/project-build/src/index.server.ts
- packages/project/src/db/build.ts
- packages/project/src/db/index.ts
- pnpm-lock.yaml
We are moving all build related stuff to project-build package including tree schema and db utils.
> Move tree db utils to project-build

- packages/react-sdk/package.json
- packages/react-sdk/src/app/custom-components/index.ts
- packages/react-sdk/src/components/body.ws.tsx
- packages/react-sdk/src/components/bold.ws.tsx
- packages/react-sdk/src/components/box.ws.ts
- packages/react-sdk/src/components/button.ws.tsx
- packages/react-sdk/src/components/component-type.ts
- packages/react-sdk/src/components/form.ws.tsx
- packages/react-sdk/src/components/heading.ws.tsx
- packages/react-sdk/src/components/image.ws.tsx
- packages/react-sdk/src/components/index.test.ts
- packages/react-sdk/src/components/input.ws.tsx
- packages/react-sdk/src/components/italic.ws.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/components/paragraph.ws.tsx
- packages/react-sdk/src/components/rich-text-link.ws.tsx
- packages/react-sdk/src/components/span.ws.tsx
- packages/react-sdk/src/components/subscript.ws.tsx
- packages/react-sdk/src/components/superscript.ws.tsx
- packages/react-sdk/src/components/text-block.ws.tsx
Partial fix for #1051
The full fix must include validating during props generation. Probably we could generate ts files with all 
typeinfo inside.
cc @rpominov 
Also I excluded Zod exports, only types https://github.com/webstudio-is/webstudio-builder/pull/1052/files#diff-5659b16effbbb5a7214ce728cf281efa2f2cac4332d31685b78ecb1b27ab0502
2. expect xyz
> Exclude zod parse and exports from read-sdk

- apps/builder/app/shared/copy-paste/copy-paste-instance.ts
- apps/builder/app/shared/copy-paste/copy-paste.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1057
Checks are now similar to those we use in shortcuts.
> Prevent instance cut in contenteditable

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/unit-select.tsx
- apps/builder/app/builder/features/style-panel/shared/parse-css-value.ts
closes #1033
Also fixes that 0 for props like top, left etc showed as 
Now 
Also now if the property allows `unitless` we allow the selection of `-` unit from UnitSelect _(top can be unitless if value is 0)_
And not if not _(top can't be unitless if value is not 0)_
See tests what's accepted, for unitless properties, it's allowed to enter for lineHeight
`10-`
`20 -`
`10 + 20-`
All become unitless.
For `top` you can enter `0-` it becomes unitless 0
then for example `10` it becomes `10px` as `top does not support unitless 10
> Typing "-" in unitless value types should select the unitless

- packages/project-build/src/db/build.ts
We already migrated all json ids from bson-objectid to nanoid. Looks like pages can be also migrated from nanoid since not stored directly in db.
Also removed unnecessary zod parses.
> Use nanoid for pagse

- apps/builder/app/builder/features/topbar/topbar.tsx
Page name had too little space even though we had plenty in the title, so I switched to min and max values and using name now instead of title, title can be SEO optimized, its not useful for builder
> Better page name layout and correct variable

- apps/builder/app/canvas/features/wrapper-component/wrapper-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/core/css-engine.ts
- packages/css-engine/src/core/style-element.ts
- packages/react-sdk/src/tree/wrapper-component.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/604
-  User can now override helper definitions on canvas
- only boxes that would collapse without helper -  receive helper
- helper is removed when any CSS property is changed on that instance that would prevent collapsing, so that helper can be removed
- Helper doesn't show on the preview or publish
- Helper goes away if an instance inserted as a child
- There is no need to set padding-right or padding-bottom if you just need a small div with a defined or layout-based size, as soon as div is not collapsing, helper is not applied
More: padding will be only added on the side that would collapse otherwise. 
For example when I add a div, it is a block element, it grows automatically full width but has 0 height, in this case …
> Make css helper tool for collapsing prevention on canvas really smart

- packages/feature-flags/src/flags.ts
Style source input is getting usable so we can enable it by default.
> Enable style source input for all users

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
User may not want to create necessary tokens but start styling right after dropping component and later may want to create token from local style source.
> Add "convert to token" for local style sources

- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1082
Added preset styles to style info and considered while computing inherited styles.
> Reflect preset style in style panel ui

- apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
- apps/builder/app/builder/features/style-panel/shared/parse-css-value.test.ts
- apps/builder/app/builder/features/style-panel/shared/parse-css-value.ts
- packages/eslint-config-custom/index.js
- packages/react-sdk/src/css/get-browser-style.ts
Found few bugs.
closes #1081
`+` Added transparent color (need be in design, looks better for most inputs if anything is shown)
Accessibility is not done fully for the color picker https://github.com/webstudio-is/webstudio-builder/issues/1092
1. You are now able to select colors by name
2. Colors with non-1 alpha will be shown on chessboard
> Fix color input does not accept CSS color names

- .npmrc
- package.json
- pnpm-lock.yaml
v8 is alpha is out (https://github.com/pnpm/pnpm/releases/tag/v8.0.0-alpha.0)
So we can prepare migration by enabling some options which gonna be default in v8.
auto-install-peers=true
resolve-peers-from-workspace-root=true
Easier peer deps management, already cut part of duplicates in lockfile
save-workspace-protocol=rolling
Will add workspace dependencies without version, only caret (workspace:^). We already faced issues because of it.
resolution-mode=lowest-direct
Will prevent unrelevant uprgades
> Upgrade pnpm to v7.27

- .npmrc
- pnpm-lock.yaml
Lockfile is getting more readable
- versions are sorted
- /package/version -> /package@version
- /package/version_hash > /package/version(dependant@version)
- specifier and resolved versions are grouped by package name
> Migrate to pnpm lockfile v6

- apps/builder/app/routes/rest/publish.ts
Just renaming one of the payloads to our publisher API to be consistent.
2. expect xyz
> Rename origin to webstudioApi in publish request to the new deployment process

- apps/builder/app/shared/copy-paste/plugin-markdown.test.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- packages/css-vars/src/index.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/components/__generated__/code.props.json
- packages/react-sdk/src/components/code.tsx
- packages/react-sdk/src/components/code.ws.tsx
- pnpm-lock.yaml
Introduces  Code component, no syntax highlighting just block and inline code
1. add code component, try toggle inline prop
2. try from markdown
block
```js
alert(123)
alert(123)
alert(123)
```
inline
```
test  test `alert(123)` test 
```
> Code component

- apps/builder/app/canvas/custom-components/link.tsx
- packages/generate-arg-types/src/arg-types.ts
- packages/react-sdk/src/app/custom-components/shared/remix-link.tsx
- packages/react-sdk/src/components/__generated__/blockquote.props.ts
- packages/react-sdk/src/components/__generated__/body.props.ts
- packages/react-sdk/src/components/__generated__/bold.props.ts
- packages/react-sdk/src/components/__generated__/box.props.ts
- packages/react-sdk/src/components/__generated__/button.props.ts
- packages/react-sdk/src/components/__generated__/code.props.ts
- packages/react-sdk/src/components/__generated__/form.props.ts
- packages/react-sdk/src/components/__generated__/heading.props.ts
- packages/react-sdk/src/components/__generated__/image.props.ts
- packages/react-sdk/src/components/__generated__/input.props.ts
- packages/react-sdk/src/components/__generated__/italic.props.ts
- packages/react-sdk/src/components/__generated__/link.props.ts
- packages/react-sdk/src/components/__generated__/list-item.props.ts
- packages/react-sdk/src/components/__generated__/list.props.ts
- packages/react-sdk/src/components/__generated__/paragraph.props.ts
- packages/react-sdk/src/components/__generated__/rich-text-link.props.ts
- packages/react-sdk/src/components/__generated__/separator.props.ts
- packages/react-sdk/src/components/__generated__/span.props.ts
- packages/react-sdk/src/components/__generated__/subscript.props.ts
- packages/react-sdk/src/components/__generated__/superscript.props.ts
- packages/react-sdk/src/components/__generated__/text-block.props.ts
- packages/react-sdk/src/components/link.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/components/rich-text-link.tsx
Adding target and prefetch to initial properties of a Link component along with the defaults
1. add a link
2. try target prop
3. try prefetch options
> Add target and prefetch to a link

- apps/builder/app/builder/features/settings-panel/use-settings-logic.ts
Save changes in settings when unmounting e.g. when switiching to another tab
1. change instance name in settings
2. switch to another tab
3. should save
> Save changes in settings when unmounting

- packages/design-system/src/components/floating-panel-popover.tsx
closes https://github.com/webstudio-is/webstudio-builder/issues/1158
to prevent panel taking more than screen height
1. upload lots of images
2. see they are scrollable in image manager when choosing source from properties or background image
> Set a meaningful default maxHeight 

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- packages/design-system/src/components/tree/tree-node.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/1157
When selecting in navigator - scroll into view on canvas and vice-versa
1. insert lots of elements to make navigator and canvas scroll
2. click in navigator last and first - see canvas scrolling
3. same as 2 but for canvas
> Scroll navigator into view when selecting instances on canvas/navigator

- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
We found a bug a bug after release. Any instances changes on the page erase instances of other pages.
Recently I migrated to normalized instances though didn't have time to migrate utilities and just added patchInstancesMutable utility to synchronize changes from denormalized rootInstance to normalized instances.
Though after merging instances of all pages into single list this synchronization started to clear instances not found in rootInstance.
To solve this I stopped clearing instances in patchInstancesMutable and migrate delete instances utility to mutating normalized instances directly.
1. create project
2. create new page
3. add box on this page
4. go to home page
5. see if body disappear (should not)
- …
> Migrate delete normalized instances

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/settings-panel/use-settings-logic.ts
Naming instance over settings has infinite update loop
2. go to settings
3. change name
4. hit enter
5. should not land in the loop
> Fix infinite dependencies loop

- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Here changed data flow a little. Instead of cloning data on copy. Clipboard store original as is and insert with new ids on every paste.
> Copy data before paste

- apps/builder/app/shared/copy-paste/init-copy-paste.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.test.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/src/components/rich-text-link.tsx
- packages/react-sdk/src/components/rich-text-link.ws.tsx
1. Don't handle global paste even when inside content-editable (before that when you paste inside texteditable, it would insert an instance additionally outside)
2. Insert links in paragraphs as RichTextLink
3. Make sure rich text link has the same props as link
> Markdown bugs

- apps/builder/app/routes/rest/publish.ts
This would allow testing saas preview deployments for specific branch.
Any interaction with 3rd party services like here should contain branchName to allow preview testing of 3rd party services too.
2. expect xyz
> Pass branchName to publish endpoint

- apps/builder/app/builder/builder.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/routes/builder/$projectId.tsx
- apps/builder/app/shared/sync/sync-stores.ts
Canvas no longer populate stores data. Builder load project build, populate stores and synchronize them into canvas.
This way we can simplify data flow, make builder responsible for both initial data and patches, do less work on canvas side.
This is also necessary to move pages management to client side.
> Move initial data to builder

- apps/builder/app/canvas/features/text-editor/interop.test.ts
- apps/builder/app/canvas/features/text-editor/interop.ts
- apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/jest.config.js
- apps/builder/package.json
- packages/asset-uploader/package.json
- pnpm-lock.yaml
Text editor relied on legacy denormalized tree which on updates may lead to orphan instances. Here migrated to normalized instances and considered deleting instances. Added tests for lexical conversions.
> Migrate text editor to normalized instances

- apps/builder/app/shared/context.server.ts
The issue it's the production bug only. In all other cases, session was used (same domain on canvas and on builder).
closes #1159
2. expect xyz
> Fix css on production You don't have access to this project

- apps/builder/app/shared/copy-paste/plugin-markdown.test.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Refactored markdown parser to produce normalized instances and added multiple roots support for insert utility.
Note: can be reviewed with hidden spaces
> Paste markdown as normalized instances

- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/settings-panel/use-settings-logic.ts
1. Don't set the label when id didn't change
2. workaround stale defaultValue in TextField
1. change instance name
2. select a different instance (see previous instance name is still in the text field)
3. select an different instance or different tab - instance name from previous instance went into a the currently selected instance
4. expect xyz
> Instance name bugs

- packages/react-sdk/src/components/__generated__/button.props.ts
- packages/react-sdk/src/components/button.stories.tsx
- packages/react-sdk/src/components/button.tsx
- packages/react-sdk/src/components/button.ws.tsx
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1198
- Button has a standard behavior with space key pressed that can't be turned off, so we can't type a space
- Even if we work around the space behavior somehow, we still  don't have an ability for rich-text to accept any instance and that makes a use case for icon button and button with icon on left/right impossible
The solution I went for is to make it container for accepting child instances and edit text using InnerText property. This may be not as intuitive as direct rich-text but its more capable.
Webflow does the same thing for a form button, though it uses an input element.
1. add button
1. change inner text
1. add image or text components
- detailed review …
> Allow button children and inner text over properties

- apps/builder/app/canvas/shared/use-track-selected-element.ts
Closes https://github.com/webstudio-is/webstudio-builder/issues/1193
When user is selecting text inside content editable and mouse goes up on a different instance - we don't want to select a different instance because that would cancel the text selection.
1. enter text editing
2. select text and let mouse go up on a different instance outside of the current
3. see text now stays highlighted, before it would select a different instance
> Fix text highlighing

- apps/builder/app/builder/features/props-panel/controls/number.tsx
- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/props-panel/shared.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
Fix for the bug reported in https://discord.com/channels/955905230107738152/1083358357743742998
Can't delete a value in width field:
- Add image component
- Set width
- try removing width - it won't be saved
> Allow to delete width/height on Image

- apps/builder/app/shared/nano-states/nano-states.ts
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1214
We ended up removing instance labels when sorting instances, is there more situations like this?
1. name instance
2. sort it in navigator or on canvas
> Keep the label from old instance

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- packages/project-build/src/index.ts
- packages/project-build/src/shared/instances-utils.test.ts
- packages/project-build/src/shared/instances-utils.ts
This utility is needed to filter loaded data per page on published sites. We aleady have it in builder so easy to move.
> Export instances tree lookup from project-build

- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/shared/form-utils/validation.ts
- packages/project-build/src/schema/pages.ts
We are moving pages logic to client side to support collaboration and do less work on server. Here migrated validation to client side. Server validation will be removed with endpoints in following PR.
> Validate pages on client

- apps/builder/app/builder/builder.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/routes/builder/$projectId.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
Before we send initial data from canvas which broke preview mode. Now builder is leader and fully maintain synchronization.
> Sync initial client store from builder to canvas

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/routes/builder/$projectId.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
Switching between pages takes very long time though all data already loaded. Here I added validation to not reload builder data when page is changed and render canvas with static id which is not really used for anything so iframe no longer reloads.
Switching pages now instant.
> Switch pages on client side

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/tree-preview/tree-preview.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/696
Here the last pieces to get rid of hacky patchInstancesMutable utility. Now will be easier to integrate slots.
> Migrate all left updates to normalized instances

- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/to-value.ts
- packages/project-build/src/schema/styles.ts
ref #877
Allows hiding background layers in edit mode, i.e. eye button now works
One of the assumptions I made was that `var` is used only in edit mode https://github.com/webstudio-is/webstudio-builder/blob/7ae3ed003e4d7f7fc99038ccdde57b5fa634bbe1/packages/css-engine/src/core/to-value.ts#L41
Add backgrounds, hide/unhide them
> Hide background layers

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-settings.tsx
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/shared/use-shortcuts.ts
- apps/builder/app/canvas/shared/use-track-selected-element.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
With slots there can be same ids in one tree so we need new way to address instances. Here I propose the list from target instance to the root.
Now instead of computing parents by normalized tree (one instance of slot can have many parents) we just access already computed list from rendered tree.
This address can be computed when user click in dom which can be traversed or it can be passed top-down with props.
The main con of this approach is collaboration. Reparanted instances on by one user makes "selected address" stale. Though we have similar situation with single id when instance is deleted.
Isolated mode for slots/components will make this problem less noticable.
> Address selected instance with tree path

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/use-track-selected-element.ts
"Click" based implemention had aa few important bugs. Selecting other instance was not possible when some text was selected in editing mode. This is consequence of a fix when other instance is selected user select text and move cursor outside of editor while still selecting.
Here's how all solved. We track both mousedown and mouseup. When their targets are different we do nothing because this is most likely text selection or drag'n'drop.
Editing state a little simplified by just looing for closest contenteditable instead of editing id comparison.
Instance address now computed by traversing dom.
> Improve instance selection

- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/hovered-instance-outline.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/shared/dom-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- apps/builder/app/shared/tree-utils.ts
Label again started flickering because hovered instance and hovered outline store changes have delay in between. Solution as before is to provide all info with outline. Here I just passed both label and component to get the shape for getInstanceLabel.
Removed react hook from instance hovering and refactored with instance selectors.
> Improve instance hovering

- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- packages/design-system/src/components/tree/item-utils.ts
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Selector is a list of ids from root to target to allow identify instances even with duplicated ids.
Here is the first step to support selectors in navigator. Passing selected instance selector already helped to get rid of one getItemPath usage.
> Pass selected instance selector to tree

- apps/builder/app/builder/features/settings-panel/use-settings-logic.ts
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1223
After handling settings update, I forgot to delete the update from the list, but if the user doesn't unmount component, switches instance, then unmounts, the same scheduled update is still there and applies to the new instance
1. name an instance
2. select a diff instsance
3. switch from settings tab to styles tab
> Remove handled updates from the updates list

- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/item-utils.ts
- packages/design-system/src/components/tree/tree.tsx
Before supporting selector in callbacks need to upport selectors in data. Here internal drag item and drop target supported as selectors.
In the future these states will be exposed so for drop target added custom representation without element to allow sending it via pubsub between realms.
> Refactor tree drag item and drop target with selectors

- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/test-tree-data.ts
- packages/design-system/src/components/tree/tree.tsx
Another step further. Now horizontal shift output item selector instead of item itself.
> Output item selector on tree drag end

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/workspace/canvas-iframe.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1213
when user drags color picker thumb, they can move mouse over canvas, with CORS canvas will hide the events and we loose control
1. see video in the issue
2. also affected dragging components onto canvas
> Make canvas iframe receive no pointer events for the time of dragging

- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/item-utils.ts
- packages/design-system/src/components/tree/tree.tsx
Now getIsExpanded and setIsExpanded accept selectors. Though still have to use findItemById for getChildren utility. Later whole data will be managed with ids.
> Support selectors in tree expanded logic

- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/design-system/src/components/combobox.tsx
- packages/design-system/src/components/menu.stories.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/1104
anything that uses position relative has higher stacking context, in this case spacing uses position relative, so we always use portal to prevent the need to use zIndex
1. open spacing
2. open style sources dropdown
3. it should not overlap
> Fix stacking context issues for any combobox dropdowns

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
In many cases the logic in tree component rely only on ids and it's additional complexity to resolve full instances.
Here I rewrite getItemChildren, canAcceptChild and canLeaveParent to accept instance id instead of instance.
> Access instance data by id in tree

- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/tree-preview/tree-preview.tsx
- packages/design-system/src/components/tree/index.ts
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Tree node is a renderer for pages and navigator instances. Selector of nodes is build by passing parent selectors.
Select and hover callbacks are now provide selectors.
> Refactor tree node with selectors

- @types/css-tree.d.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.test.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-parser.test.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-parser.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.stories.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/to-value.ts
ref #877 - the ability to parse multiple gradient layers from Figma 
closes #1255 - now background added at the top
fixes css value input invalid input now shows as invalid
Copy some background from figma like
```
background: linear-gradient(180deg, #11181C 0%, rgba(17, 24, 28, 0) 36.09%), none, linear-gradient(180deg, rgba(230, 60, 254, 0.33) 0%, rgba(255, 174, 60, 0) 100%), radial-gradient(54.1% 95.83% at 100% 100%, #FFFFFF 0%, rgba(255, 255, 255, 0) 100%), linear-gradient(122.33deg, rgba(74, 78, 250, 0.2) 0%, rgba(0, 0, 0, 0) 69.38%), radial-gradient(92.26% 201.29% at 98.6% 10.65%, rgba(255, 174, 60, 0.3) 0%, rgba(227, 53, 255, 0) 100%) /* warning: gradient uses a rotation that is not supported by CSS and may not behave as expected */, radial-gradient(84.64% 267.51% at 10.07% 81.45%, …
```
> Add simple background parser

- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/item-utils.ts
- packages/design-system/src/components/tree/tree.tsx
- root and getItemPath are no longer required
- dropTarget.data with instance no longer used, only selector is necessary
> Simplify horizontal shift computation

- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/design-system/src/components/tree/item-utils.ts
- packages/design-system/src/components/tree/test-tree-data.ts
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
We finally able to use normalized data to render tree. A few last improvements in tree drag and drop add support for slots with duplicating ids within tree.
> Render tree with normalized data

- apps/builder/app/canvas/instance-hovering.ts
1. If you mouse over and then mouse out directly to the side, without hovering other instances, the instance outline gets stuck
> Hide outline on mouse out

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/dom-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/use-subscribe-drag-drop-state.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- packages/project-build/src/schema/instances.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1116
Drag payload produce 2 kinds of actions insert and reparent and output tree compatible drop target.
> Refactor canvas drag and drop to rely on instance selectors

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- in many places root check can be replaced with selector.length === 1
- reparent and insert utilities now accept selectors
- findClosestDroppableTarget output end instead of last index and always fallback to root
> Refactor insert and reparent operations with selectors

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/test-tree-data.ts
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/1116
We need this to hide Fragment instance in navigator which is an implicit child of slot with persistent id.
> Allow to hide any item in the tree

- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
Lost pixel caught this issue with tree. Level is incremented inconsistenly. Here incremented only for nested tree node.
> Fix tree level to render root without collapse icon

- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/instance-hovering.ts
- apps/builder/app/shared/dom-utils.ts
- packages/feature-flags/src/flags.ts
Slots have display: contents to not affect layout. So we need a way to show correct hover and selected state. Here's added utility to traverse all descendants and get their rects and then compute the sum of those rects.
Added ability to set display: contents from UI under features flag.
> Compute bounding box by children when display: contents

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-settings.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1116
This is the last one slots blocker for sure.
Refactored inherited styles to compute from selectors and got rid of legacy traverser utility.
> Migrate style computing to instance selectors

- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-utils.ts
- apps/builder/app/builder/features/style-panel/sections/borders/borders.tsx
ref #1169 
Fixes bug that only borderTopColor changed 
Was:
Now:
Change borderStyle then change borderColor see all border colors has changed
> Fix border-color

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
One cyclic case I missed. When paste slot into itself as target then check miss unresolved fragment inside. Here added additional check before copying and covered with tests.
For slots show only settings panel.
> Fix possible cyclic slot and hide its styles and props panels

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/hook-utils/use-sync-initialize-once.ts
Atom data leaked into the server canvas.
ref #1313 
Open Vercel app. Any project. Reload a few times not fast to avoid scaling. 
Get the iframe link, then open it. Should be empty.
New relic logs must contain:
```
{
assetsStore: 0,
pagesStore: 0,
instancesStore: 0,
}
```
New relic query 
`"proxy.path":"*71f88d3e-9231-489e-8ba0-8adc10215335*" "message":"*assetsStore*"`
where `71f88d3e-9231-489e-8ba0-8adc10215335` is your project id 
(add vercel host 
> Fix atoms leak

- packages/design-system/src/components/tree/tree.tsx
Element was not swapped because slice was not reasigned so canAcceptChild didn't really work.
> Fix drop target when sort navigator tree

- packages/react-sdk/src/tree/webstudio-component.tsx
Spread cought us here. instanceselector was spread into components.
> Fix instance selector leaking into prod

- apps/builder/app/shared/array-utils.test.ts
- apps/builder/app/shared/array-utils.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Here a little refactored copy paste instance plugin.
Now we copy all data including slots and tokens though paste write them as is or do not write at all if already exist.
This let us to not do unnecessary patches for copy paste within project while still have whole UI pasted in different project.
There is still a problem with pasting styles which always have different breakpoint ids in each project. We will need to implement merging in other PR.
> Support cross-project instance copy paste

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings-panel.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar/text-toolbar.tsx
- apps/builder/app/shared/share-project/share-project.tsx
- packages/design-system/src/components/sidebar-tabs.tsx
- packages/design-system/src/components/text-field.tsx
- packages/design-system/src/components/toast.tsx
- packages/design-system/src/components/toggle-group.tsx
1. Fixed panel color. Closes #1245 
2. Also fixed backgrounds in TextField and ToggleGroup
1. Check a panel with controls like Style Panel
2. Background of the panel have changed and all controls have white background
> Panel color

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
Moved style source menu up to style source input. This way we will not need to drill a lot of callbacks and only pass menu element.
Later we will add even more callbacks. So this just simplifies further development.
> Refactor style source menu

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
isEditable is inferrable from the local "source" of style source. And no need to be passed into every item.
> Remove isEditable option from style source

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/index.ts
- apps/builder/app/builder/features/style-panel/style-source/style-source-badge.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-badge.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
We gonna have more complicated selected state with style source "states" so better split it into separate prop and simplify disabled state with boolean.
Also dropped "state" style source.
> Drop item state from style sources

- .github/workflows/main.yml
- .prettierignore
- apps/builder/package.json
- package.json
- packages/fonts/src/font-weights.ts
- pnpm-lock.yaml
Here add check to have formatting always applied in case git hook was ignored or not run for some reason.
Cached prettier for whole project is run within 2-3 seconds.
> Run global prettier check

- apps/builder/app/builder/shared/assets/types.ts
- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/asset-uploader/src/schema.ts
- packages/react-sdk/src/context.tsx
- packages/react-sdk/src/css/global-rules.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/1335
Here I replaced assetContainersStore with assetsStore. Now deleting and uploading states are maintained locally in assets provider. To preserve the order of uploading assets assetsStore map has value as undefined. This way assets.get(id) provides the same value. Though when iterating we see missing asset.
> Add assets store

- apps/builder/app/canvas/shared/scroll-state.ts
- apps/builder/app/shared/dom-hooks/use-window-resize.ts
- apps/builder/app/shared/pubsub/index.ts
- apps/builder/package.json
- apps/builder/remix.config.js
- packages/react-sdk/package.json
- packages/react-sdk/src/pubsub/create.ts
- pnpm-lock.yaml
- turbo.json
nanoevents doesn't have `*` we stopped using recently, have simpler api with unsubscribe function and allows to avoid patch upcoming changes https://github.com/webstudio-is/webstudio-builder/pull/1351.
> Replace mitt with nanoevents

- apps/builder/app/routes/$.tsx
- apps/builder/app/routes/builder/$projectId.tsx
- apps/builder/app/routes/dashboard/index.tsx
- apps/builder/app/routes/index.tsx
- apps/builder/remix.config.js
Ref https://remix.run/docs/en/1.15.0/pages/v2#catchboundary-and-errorboundary
Since 1.15 remix will force to switch with warnings.
> Migrate to remix v2 error boundary

- .github/workflows/chromatic.yml
- package.json
- packages/storybook-config/index.js
- pnpm-lock.yaml
We probably don't need to have chromatic in dependencies.
Especially since the latest version is getting 20MB bigger
https://packagephobia.com/result?p=chromatic
Also removed builds from chromatic workflows, "source" export condition allows to avoid it.
> Drop chromatic from dependencies

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/shared/assets/asset-upload.tsx
- apps/builder/app/builder/shared/assets/use-assets.tsx
- packages/asset-uploader/src/patch.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1335
- with persistent fetcher there is no need in assets provider
- replaced async FileReader api with sync URL.createObjectURL for preview while uploading
> Simplify assets uploading

- packages/tsconfig/base.json
allowImportingTsExtensions requires 2 additional flags but not used, removed
2. expect xyz
> Fix ts error

- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.stories.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/tree-utils.test.ts
- packages/project-build/src/db/styles.ts
- packages/project-build/src/schema/styles.ts
- packages/react-sdk/src/css/style-rules.test.ts
- added indicator state has styles in style source menu
- added style state to schema
- save state styles changed from style panel
> Store style states in db

- apps/builder/app/builder/features/style-panel/controls/font-weight/font-weight-control.tsx
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
Related to https://github.com/webstudio-is/webstudio-builder/pull/1403
Here I removed app specific case from css-engine toValue by providing transformValue function which is called on every individual style value inside nested structure (like var or layers).
With this function we can resolve assets and remove complex resolving logic from server.
> Allow to map individual style values when stringify to css

- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/canvas/shared/styles.ts
- packages/css-data/src/schema.ts
- packages/css-engine/package.json
- packages/css-engine/src/core/css-engine.test.ts
- packages/css-engine/src/core/css-engine.ts
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
- packages/project-build/src/db/styles.ts
- packages/react-sdk/src/css/css.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/issues/1179
Succeeded https://github.com/webstudio-is/webstudio-builder/pull/1403
Here added support for transformValue in css-engine StyleRule. So we can apply any transformation when render css.
In sdk added image transformation which accepts assets and provides image value with new url value.
Now we can get rid of resolving on server side and apply image loaders for images rendered in styles.
> Transform image value to resolve url

- apps/builder/app/shared/theme/theme.ts
Fixes Error in dev mode on every start or reload
```
react-dom.development.js:67 Warning: Prop `className` did not match. Server: "null" Client: "t-doScVt"
at html
at Root (http://localhost:3000/build/_shared/chunk-TNFZIIN2.js:36:22)
```
It works because of bug, now without bug it shows
https://github.com/webstudio-is/webstudio-builder/pull/1408
I would comment usetEffect for now
Run localy, see Error has gone
> Fix error in dev mode

- apps/builder/app/builder/features/style-panel/controls/image/image-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- packages/css-data/package.json
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/css-engine.test.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/project-build/package.json
- packages/project-build/src/db/build.ts
- packages/project-build/src/db/styles.ts
- packages/project-build/src/schema/styles.ts
- packages/react-sdk/src/css/css.ts
- pnpm-lock.yaml
This big chunk of legacy is no longer necessary.
We resolve style assets on client so css engine can accept db types now.
> Drop assets resolving from project-build

- apps/builder/app/builder/features/style-panel/shared/css-value-input/convert-units.test.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/convert-units.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/unit-select.tsx
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/design-system/src/components/input-field.tsx
closes #956
+ In case if user not edited the value but immediately clicked to unit select we are trying to convert em px etc values
1. Edit `width` value, enter 10
go to unit select set `em` - see 10em as final result
2. Click on unit select of the width, change em to px see 10em converted to 140px or like (depends on em size)
3. Enter `Auto` in width, click Enter. 
Click on UnitSelect select EM, see browser style is used to set em width.
4. Enter Auto in width, switch on Unit select, set px, see browser style is used.
5. See that now unit selector is visible always. With some exclusions like aspectRatio as it has keywords and numeric values.
> UX improvement for Inputs that have both keywords and units

- apps/builder/.env.example
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/env/env.public.server.ts
- apps/builder/app/routes/$.tsx
- apps/builder/app/routes/s.css.ts
- packages/asset-uploader/src/utils/get-asset-path.test.ts
- packages/asset-uploader/src/utils/get-asset-path.ts
- packages/image/src/image-dev.stories.tsx
- packages/image/src/image-loaders.ts
- packages/react-sdk/src/app/custom-components/image.tsx
- packages/react-sdk/src/app/params.ts
- packages/react-sdk/src/css/css.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1179
Added ASSET_PUBLIC_PATH env for local development
and publicPath option in local image loader.
Now fs asset client provides name as path without modification on server side.
> Add public path to local image loader

- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/shared/instance-utils.ts
Reduces amount of renders from 6 to 2 on addding/deleting instances
Reduction to 1 render is impossible in our current architecture as following situation happens.
On add node, we set selectedInstanceSelectorStore from the builder, what cause 
In the canvas "SelectedInstanceConnector" sets computed styles etc and sync back. Both are causing double rendering.
Can be avoided in the future allowing to set store from the builder in a canvas.
2. expect xyz
> Speedup add remove nodes

- apps/builder/app/builder/features/breakpoints/breakpoints-selector.tsx
- apps/builder/app/builder/features/breakpoints/cascade-indicator.tsx
- apps/builder/app/builder/features/style-panel/style-panel.tsx
Map used based on
https://react.dev/learn/manipulating-the-dom-with-refs#how-to-manage-a-list-of-refs-using-a-ref-callback
2. expect xyz
> Fix cascade indicators on scrub move

- packages/react-sdk/src/components/blockquote.ws.tsx
We had a mismatch between a component and meta
Closes https://github.com/webstudio-is/webstudio-builder/issues/1418
1. add blockquote
2. open properties
> Fix blockquote properties

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
- packages/react-sdk/src/tree/webstudio-component.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/696
Here we finally can switch to normalized instances for rendering tree
and get rid from denormalization for published sites.
> Switch canvas and published rendering to normalized instances

- apps/builder/app/canvas/shared/styles.ts
- packages/fonts/src/get-font-faces.test.ts
- packages/fonts/src/get-font-faces.ts
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/global-rules.ts
Fonts are resolved separately. Here provided same publicPath and cdnUrl options to font face resolver.
> Fix font assets resolving

- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/tree-utils.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/696
The last piece with denormalized tree. Now we rely only on normalized instances map.
> Drop legacy root instance store

- apps/builder/app/env/env.server.ts
- apps/builder/app/routes/rest.assets.$projectId.tsx
- apps/builder/app/shared/asset-client.ts
- packages/asset-uploader/src/constants.ts
- packages/asset-uploader/src/db/create.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/upload.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1179
Here all envs which were accessed and parsed in asset uploader moved to builder. Now we have better control over assets in different environments.
> Pass all asset uploader envs from builder

- apps/builder/app/builder/features/props-panel/props-panel.stories.tsx
- apps/builder/app/builder/features/style-panel/controls/font-weight/is-supported-font-weight.test.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/shared/assets/types.ts
- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/shared/asset-client.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/utils/format-asset.ts
- packages/css-engine/package.json
- packages/css-engine/src/core/css-engine.test.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/react-sdk/src/app/custom-components/image.tsx
- pnpm-lock.yaml
This is computed field which is after moving logic to loaders equal to asset.name so not really useful except for preview images.
Here object url for preview images is moved to container so there is no need in asset.path here too.
> Drop asset.path

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
Render label in breadcrumbs when possible
2. expect xyz
> Render label in breadcrumbs when possible

- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/canvas/features/text-editor/interop.test.ts
- apps/builder/app/canvas/features/text-editor/interop.ts
- apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.test.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- packages/project-build/src/schema/instances.ts
- packages/project-build/src/shared/instances-utils.test.ts
- packages/project-build/src/shared/instances-utils.ts
- packages/project-build/src/types.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/webstudio-component.tsx
InstancesItem is newer type introduced separately for gradual migration. Not all legacy tree Instance is migrated away so we can finally use better naming across whole system.
> Rename InstancesItem to Instance type

- apps/builder/.env.example
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-thumbnail.tsx
- apps/builder/app/builder/shared/image-manager/image.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/env/env.public.server.ts
- apps/builder/app/routes/$.tsx
- apps/builder/app/routes/s.css.ts
- packages/fonts/src/get-font-faces.test.ts
- packages/fonts/src/get-font-faces.ts
- packages/react-sdk/src/app/custom-components/image.tsx
- packages/react-sdk/src/app/params.ts
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/global-rules.ts
- packages/react-sdk/src/tree/root.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1179
publicPath and cdnUrl are separate environment variables for different deployments. Though they do exactly same thing we can unify them as asset base url.
> Pass asset base url for fonts and style images

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/canvas-shortcuts.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/css-data/src/schema.ts
- packages/css-engine/src/core/css-engine.stories.tsx
- packages/css-engine/src/core/css-engine.ts
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/style-rules.test.ts
- packages/react-sdk/src/css/style-rules.ts
Refactored styles rendering in canvas to consider states and added style states support to css text renderer.
> Render style states

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
- apps/builder/app/entry.client.tsx
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/react-sdk/src/pubsub/raf-queue.ts
Made handshake between canvas and builder.
Now publish actions are delayed in local array until handshake message from destination is received
Switched on hydrateRoot to enable concurrent mode
unstable_batchedUpdates are removed
> Concurency mode for React 18

- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
DnD in navigator stopped working after React update. This PR fixes it.
https://discord.com/channels/955905230107738152/1097637506649960519
1. Try to use drag and drop in navigator tree
> Fix navigator dnd

- packages/asset-uploader/package.json
- packages/authorization-token/package.json
- packages/css-data/package.json
- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/design-system/package.json
- packages/feature-flags/package.json
- packages/fonts/package.json
- packages/generate-arg-types/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/prisma-client/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- packages/trpc-interface/package.json
- packages/tsconfig/base.json
Fixed a regression from https://github.com/webstudio-is/webstudio-builder/pull/1470 . @TrySound noticed that by putting `declarationDir` in the base config all declaration were emitted relative to... that base config. By switching back to the CLI argument the issue is fixed.
> Fixed location of emitted declarations

- apps/builder/app/builder/features/props-panel/controls/combined.tsx
- apps/builder/app/builder/features/props-panel/controls/url.tsx
- apps/builder/app/builder/features/props-panel/props-panel.stories.tsx
- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/props-panel/shared.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
- apps/builder/app/canvas/features/webstudio-component/link.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- packages/design-system/src/components/select.tsx
- packages/project-build/src/schema/props.ts
- packages/react-sdk/src/app/custom-components/shared/remix-link.tsx
- packages/react-sdk/src/components/link.tsx
- packages/react-sdk/src/props.test.ts
- packages/react-sdk/src/props.ts
1. Made `href` always present (# is used when not set, similar to Webflow). Fixes #1380
2. Added "Section" option in URL Control. Closes #993 
3. Added "ID" prop that is visible in all components. Closes #991 
4. Closes #1475
1. Add ID prop to an instance
4. Add a link that references that instance by ID
- have a look at how I deal with stores to get list of available IDs
> Ability to link by #ID; Fixed a bug with links in RTE

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/components/link-block.ws.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/index.ts
Here added ability to extend states in style source menu list with a list defined in component meta.
As an example added `[aria-current=page]` support to links. For now can be statically set with props panel.
Note: review with hidden whitespaces
> Define component states in meta

- apps/builder/.storybook/preview.tsx
- packages/design-system/.storybook/preview.js
- packages/storybook-config/decorators.tsx
This should hopefully fix the unstable popover arrow ^. 
The theory is:
- when arrow position is calculated, fonts may or may not be loaded yet;
- arrow position does not update after the fonts load.
> Fix unstable lostpixel

- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/shared/pages/use-switch-page.ts
Forced reset when page is created, deleted or navigated. Selected instance should be reset to avoid manipulation from another page.
> Reset selected instance on page manipulation

- apps/builder/app/canvas/shared/styles.ts
- packages/css-engine/src/core/rules.ts
We have a bug that asset cannot be applied in background style section. This is because image transformer was set only once on rule creation. We need to reset it with actual assets on every styles updates.
> Update css-engine transformValue on every update

- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Here consider this scenario when reparenting
- Create a slot
- Put a Box in it
- Copy the Slot
- Drag copy of the slot inside Box in the original slot
> Prevent cyclic slot reparent

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1338 https://github.com/webstudio-is/webstudio-builder/issues/807
Used remote color for previous style sources and added messages to property name popup.
> Compute remote style source

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- packages/react-sdk/src/components/body.ws.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/1243
Changed body styles to black on transparent defaults.
Added white background to iframe to make canvas visible on workspace.
> Fix body preset styles

- apps/builder/app/builder/features/breakpoints/find-initial-width.test.ts
- apps/builder/app/builder/features/breakpoints/find-initial-width.ts
- apps/builder/app/builder/features/breakpoints/trigger-button.tsx
- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
when base breakpoint selected, always use a width between max and min breakpoints at the lowest value
> Fix switching to base breakpoint on a small screen

- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
Outline calculated incorrectly for new elements in case if new element has size and added into collapsed item
Create Box
Add Image inside
See outline now is on Image
> Fix new element outline issue

- packages/asset-uploader/tsconfig.json
- packages/css-data/tsconfig.json
- packages/css-engine/tsconfig.json
- packages/css-vars/tsconfig.json
- packages/dashboard/tsconfig.json
- packages/design-system/tsconfig.json
- packages/feature-flags/tsconfig.json
- packages/fonts/tsconfig.json
- packages/generate-arg-types/tsconfig.json
- packages/http-client/tsconfig.json
- packages/icons/tsconfig.json
- packages/image/tsconfig.json
- packages/prisma-client/tsconfig.json
- packages/project/tsconfig.json
- packages/react-sdk/tsconfig.json
- packages/sdk-size-test/tsconfig.json
- packages/trpc-interface/tsconfig.json
This should fix auto import from parent folders
which is very annoying right because tries to import from 'src'.
> Drop baseUrl from tsconfig in packages

- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- packages/css-data/bin/mdn-data.ts
- packages/css-data/package.json
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/html-check.ts
- packages/css-data/src/html.ts
- packages/css-data/src/index.ts
- packages/react-sdk/src/components/body.ws.tsx
- packages/react-sdk/src/css/normalize.ts
- packages/react-sdk/src/css/presets.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/issues/1067
We need to move away from getComputedStyle for not local styles in style panel.
Here added default html style from browser sources. Now we can render it and properties initial styles instead of computed styles.
Also fixed in properties data generation currentcolor -> currentColor and removed same from border presets.
> Show initial and html style in style panel

- .github/workflows/main.yml
- packages/react-sdk/src/embed-template.ts
This fixes the bug introduced in my previous PRs and reproducable only by running dts generation. Here added it to checks so we could avoid broken publishes while releasing.
> Run dts as additional checks in actions

- apps/builder/app/builder/builder.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/shortcuts/shortcuts.ts
Fixes bug:
- select an Input instance by clicking on it on canvas
- press backspace to delete it
- nothing happens
> Fix: can't delete a form element from canvas

- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
Now embed templates can define simplified version of our styles which is useful for radix components and as AI output.
```
styles: [
{
property: 'backgroundColor',
value: { type: 'keyword', value: 'red' }
}
]
```
> Insert styles from embed template

- apps/builder/app/builder/features/style-panel/sections/backgrounds/use-sortable.tsx
- apps/builder/app/builder/features/style-panel/style-source/use-sortable.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- packages/design-system/src/components/primitives/dnd/canvas.stories.tsx
- packages/design-system/src/components/primitives/dnd/sortable-list.stories.tsx
- packages/design-system/src/components/primitives/dnd/use-drop.ts
- packages/design-system/src/components/tree/tree.tsx
Here I allows to return undefined in swapDropTarget. This enables us to reset drop target when move cursor out of droppable elements.
For example before Body was always selected as drop target. Though this behavior prevent us from restricting parents for cases like Tabs>Tab and List>ListItem.
Also got rid from emulatePointerAlwaysInRootBounds which was used to workaround that fallback to Body. So now no longer necessary too.
https://user-images.githubusercontent.com/5635476/235142653-48b95ebe-9714-44c4-90d9-b69b930f2379.mov
> Allow to reset drop target

- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/utils/uuid-handler.ts
We had own uuid-handler utility to buffer streamed values for formData. Remix has own memory upload handler to do the same. A little less custom code for us.
> Use remix memory upload handler

- apps/builder/app/builder/features/props-panel/controls/text.tsx
- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
1. Removed a sanity check that started to give false positives (wasn't needed really in the first place)
2. Cmd+enter in textarea control now saves the value
3. Fixed layout of props panel in the case when there're no initial props
> Some fixes in props panel

- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/components/list-item.ws.tsx
Added `allowedParentComponents: string[]` option to meta which prevents dropping, inserting or pasting components into wrong parents. For example ListItem now can be placed only inside of List component.
This will unlock better experience with compound radix components.
> Restrict allowed parents with config in meta

- apps/builder/app/builder/features/props-panel/controls/combined.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
- packages/design-system/src/components/label.tsx
1. Fixed label's cursor: https://discord.com/channels/955905230107738152/1102616619219439676
2. Improved TS to make sure all prop types are always handled in props panel
> Fixed label's cursor & couple TS fixes

- packages/design-system/src/components/primitives/numeric-gesture-control.ts
Fix of the bug reported in https://discord.com/channels/955905230107738152/1102991527254446182:
1. Set value of any input that you can scrub to 1.3
2. Scrub to decrease it by 1 to 0.3
3. The value gets set 0.30000000000000004
> Fix floating point math issue in scrub

- apps/builder/app/builder/features/style-panel/sections/space/scrub.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
Fixes scrub control can set invalid unitless value 
2. expect xyz
> Fix scrub control

- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/rest.assets.tsx
- apps/builder/app/shared/db/canvas.server.ts
- packages/asset-uploader/src/db/load.ts
- packages/asset-uploader/src/patch.ts
Found the name super confusing when started to work on builder. Here renamed and dropped unused loadByIds utility.
> Rename loadByProject to loadAssetsByProject

- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Ref https://discord.com/channels/955905230107738152/955907841070346300/1103260031048241182
Here style sources were pasted without copying. Here I renamed the utility to clarify a little and provided proper list of instance ids.
> Fix copy paste of style sources

- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- packages/react-sdk/src/components/blockquote.ws.tsx
- packages/react-sdk/src/components/body.ws.tsx
- packages/react-sdk/src/components/bold.ws.tsx
- packages/react-sdk/src/components/box.ws.ts
- packages/react-sdk/src/components/button.ws.tsx
- packages/react-sdk/src/components/checkbox-field.ws.tsx
- packages/react-sdk/src/components/checkbox.ws.tsx
- packages/react-sdk/src/components/code.ws.tsx
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/components/form.ws.tsx
- packages/react-sdk/src/components/heading.ws.tsx
- packages/react-sdk/src/components/image.ws.tsx
- packages/react-sdk/src/components/input.ws.tsx
- packages/react-sdk/src/components/italic.ws.tsx
- packages/react-sdk/src/components/label.ws.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/components/list-item.ws.tsx
- packages/react-sdk/src/components/list.ws.tsx
- packages/react-sdk/src/components/paragraph.ws.tsx
- packages/react-sdk/src/components/radio-button-field.ws.tsx
- packages/react-sdk/src/components/radio-button.ws.tsx
- packages/react-sdk/src/components/separator.ws.tsx
- packages/react-sdk/src/components/span.ws.tsx
- packages/react-sdk/src/components/subscript.ws.tsx
- packages/react-sdk/src/components/superscript.ws.tsx
- packages/react-sdk/src/components/text-block.ws.tsx
- packages/react-sdk/src/components/textarea.ws.tsx
- packages/react-sdk/src/index.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1518
Now default states should be spread per component. And states have category with fallback to "states".
Note better review with hidden whitespaces
> Support state category in meta

- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
Outline was cut with overflow: scroll from scroll area. Here moved paddings inside and added bottom padding.
> Add padding to settings scroll area

- apps/builder/app/builder/features/style-panel/sections/backgrounds/use-sortable.tsx
- apps/builder/app/builder/features/style-panel/style-source/use-sortable.tsx
Need to render placement indicator in portal to avoid shifting because of position: relative on ancestors elements like ScrollView.
> Render placement indicator in portal

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
Ref https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1037-32728&t=HT5zNo0zhXDCpIX8-0
Here show next style sources as remote too. And add alert when next style source has same style as local so user see something overrides it.
> Support remote label for next style sources

- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
The current approach relies on batching behavior.
Here is fast fix to not reset atom if global atom has not been changed
2. expect xyz
> Fix scroll on edit

- apps/builder/app/canvas/shared/styles.ts
Image background layers are invisible during edit
fixes https://discord.com/channels/955905230107738152/955907841070346300/1104430743049994331
2. expect xyz
> Fix background image edit

- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
Ref https://discord.com/channels/955905230107738152/955907841070346300/1104446794211016744
Remote style sources should provide info only within current breakpoint. So when remote from other breakpoint we show cascaded remote instead.
> Compute remote style sources only for current breakpoint

- apps/builder/app/canvas/shared/styles.ts
Now on connected outlines, it will not be the thin border like before.
(But the thin border has an issue that in some cases it can become a solid line)
Imo this looks better vs thick 4px outlines at the webflow
2. expect xyz
> Fix collapsed outline sometimes not visible

- apps/builder/app/routes/rest.patch.ts
- packages/project-build/package.json
- packages/project-build/src/db/breakpoints.ts
- packages/project-build/src/db/instances.ts
- packages/project-build/src/db/pages.ts
- packages/project-build/src/db/props.ts
- packages/project-build/src/db/style-source-selections.ts
- packages/project-build/src/db/style-sources.ts
- packages/project-build/src/db/styles.ts
- pnpm-lock.yaml
We batching transactions though each transaction and each namespaace in it loads build data, applies patches and writes to db. This makes patches do a lot of connections to db within single request.
Here each patch request loads and updates build only once and apply patches of all transactions to intermediary state.
> Optimize patch endpoint

- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.test.ts
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-layers.ts
Fix editing of background gradient resetted other properties of the curent layer
https://discord.com/channels/955905230107738152/955907841070346300/1105100883542409279
To reproduce set position center
Goto "Code", add space then click enter
All values are resetted
> Fix editing of background gradient resetted other properties of the curent layer

- apps/builder/app/builder/features/style-panel/shared/style-info.ts
Ref https://discord.com/channels/955905230107738152/955907841070346300/1104517307478319257
Ideally make these values remote but as a fast fix made them local.
> Show stateless styles when state is selected

- packages/css-data/src/html.ts
- packages/react-sdk/src/css/normalize.ts
- packages/react-sdk/src/css/presets.ts
:active and :visited states on links have special behaviour. They are vendor defined until color on stateless link is defined. Similar to how vars work there is var with default. And when var is somewhere defined default is overriden.
Though using vars for this specific case is too complex here easier solution. We can just remove active and visited states on default styles. User may never see this inconsistency as usually would modify color on stateless link first and then go to active or visited states.
> Drop link preset states

- apps/builder/app/routes/rest.project.$projectId.tsx
- packages/form-handlers-mailchannels-test/src/index.ts
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/mailchanels.ts
- packages/form-handlers/src/n8n.ts
- packages/form-handlers/src/shared.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/app/custom-components/__generated__/form.props.ts
- packages/react-sdk/src/app/custom-components/form.tsx
- packages/sdk-size-test/package.json
- pnpm-lock.yaml
Part of #84 
Should be deployed together with https://github.com/webstudio-is/webstudio-saas/pull/148
1. Exposed `User.email` in the data we send to saas
2. Used Remix's form in the Form component
3. Refactoring in `form-handlers`
> Changes to enable forms submission in saas

- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
- apps/builder/app/builder/features/workspace/workspace.tsx
On project change breakpoints can be updated later than canvas with is calculated, so breakpoints from the previous project were used.
Here is the fix
2. expect xyz
> Fix width not set on prject change and breakpoints change

- packages/form-handlers/package.json
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/shared.ts
- pnpm-lock.yaml
1. Added `hasMatchingForm` that is needed for #1611 
2. Made sure we ignore File form entries for now
Corresponding saas PR: https://github.com/webstudio-is/webstudio-saas/pull/157
> Some fixes in form-handlers

- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/routes/rest.assets.tsx
- packages/asset-uploader/src/client.ts
- packages/asset-uploader/src/clients/fs/fs.ts
- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/s3.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/upload.ts
Content type is important when detect image or font parser and required (or recommended?) for uploading to s3.
Here temporary saved it in File.format and reuse in upload. Later overriden with parsed format.
This is a preparation to uploading only blob without additional information.
> Store content type before upload

- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/routes/rest.assets.$name.tsx
- packages/asset-uploader/package.json
- packages/asset-uploader/src/client.ts
- packages/asset-uploader/src/clients/fs/fs.ts
- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/s3.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/upload.ts
- packages/asset-uploader/src/utils/size-limiter.ts
- packages/asset-uploader/src/utils/to-uint8-array.ts
- pnpm-lock.yaml
Form data is complex format to work with and web api does not support its stream parsing and we had to use remix utilitties.
Here upload file as is so node or worker gets stream and do anything with it. So this is one less dependency  on node.
These streams are still bufferred but we can improve this at least for images later to not exceed vercel memory.
> Upload file instead of form data

- packages/asset-uploader/src/upload.ts
- packages/prisma-client/prisma/migrations/20230511173512_file-user/migration.sql
- packages/prisma-client/prisma/migrations/20230515112405_file_uploader_project/migration.sql
- packages/prisma-client/prisma/schema.prisma
We need to be able to track users who uploads files to prevent misuse of our storage.
Here added File.uploaderProjectId in db. This way we can always find project owner.
Saving user is less ideal because often can be no user for example when share edit permission by token.
> Save project uploader when create file

- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/routes/rest.assets.tsx
- packages/asset-uploader/src/delete.ts
- packages/asset-uploader/src/patch.ts
- packages/asset-uploader/src/upload.ts
- packages/asset-uploader/src/utils/format-asset.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1335
Successor of https://github.com/webstudio-is/webstudio-builder/pull/1376
Assets no longer created while uploading. Asset patch now tracks new assets to save in db.
> Create assets with patches

- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
1. Closes #1617
Before this PR `selectedInstanceIsRendered` behaved like this:
Switching to instance that **is** on canvas: `true -> false -> true`
Switching to instance that **is not** on canvas: `true -> false`
Issue: we can't tell apart brief `false` in the first case, and final `false` in the second
After this PR:
Switching to instance that **is** on canvas: `true -> undefined -> true`
Switching to instance that **is not** on canvas: `true -> undefined -> false`
Now we can distinguish temporary `undefined` from permanent `false` and don't hide style panel during `undefined`
Case 1:
1. Select a Box instance
2. Scroll style panel
3. Select another Box instance
4. Scroll should not reset
Case 2:
1. Select a Box instance
2. Select a Success Message instance in a Form
3. Style panel should …
> Fix scroll reset in style panel

- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
- apps/builder/app/canvas/shared/styles.ts
Ref https://github.com/webstudio-is/webstudio/discussions/30
Here fixed width update which always relied on base breakpoint instead of selected one.
Another issue found and fixed is wrong order of rendered breakpoints.
> Fix breakpoints width and rendering

- apps/builder/app/dashboard/projects/project-card.tsx
Fixed a bug where menu is obscured by the big letters of another project's card
> Fix project card menu z-index

- apps/builder/app/builder/features/style-panel/controls/font-weight/font-weight-control.tsx
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/html.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1535
Here instead of hacky preconverting to numeric font-weight value support "normal" and "bold" as input for font weight control.
Defaults can be checked on h1 and body.
> Support bold and normal font-weight

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/nano-states/components-meta.ts
- apps/builder/app/shared/nano-states/index.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/react-sdk/src/components/index.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1545 https://github.com/webstudio-is/webstudio-builder/issues/1129
Here moved props meta into store. Both default and custom meta should be registered as by default its empty.
Removed merging of overriden props with overrides because our cli still resolves all types in component.
Supported two-directional store initialization by checking if there was any .set calls. This let us send initial data from canvas.
> Register props meta into store

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/nano-states/components-meta.ts
- packages/react-sdk/src/components/components-utils.ts
- packages/react-sdk/src/css/css.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1545 https://github.com/webstudio-is/webstudio-builder/issues/1129
Here register all component metas to atom which is sychronized with builder.
Replaced getComponentNames with registered metas keys. We no longer need to maintain this list.
Old registration still there because there is a lot of usages of getComponentMeta.
> Store component meta in atom

- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Collapse/expand animation is glitchy in safari and adds a lot of complexxity.
Neither webflow nor figma animate this. It makes sense to remove it.
> Drop collapse/expand animation from tree

- packages/react-sdk/src/app/custom-components/index.ts
Remix image before inherited initial props from default image. Though the new simplified logic only replaces occurrences without merging.
> Bring back initial props to remix image

- apps/builder/app/builder/features/topbar/publish.tsx
- packages/domain/src/trpc/domain.ts
- packages/project/src/db/project-domain.ts
- packages/project/src/db/project.ts
- packages/project/src/index.ts
Services we need like `image-transform.wstd.io`, `local.wstd.io` 
can intersect with user-created domains. _in some cases that will cause disastrous results_
Do not allow to create domains we already use, and reserve `wstd-sys-` and `wstd_sys_` for future services we can create
2. expect xyz
> Add project domain validations

- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
Here refactored horizontal shift in tree to search available placement by selector. This enables us to add restricting ancestors with requiredAncestorss and invalidAncestors options in meta (in the next PR).
The idea of this refactoring to do similar search for both left and right directions based on item selectors which means from deepest to root. So before searching I compute deepest expanded selector when all items at the bottom.
> Search tree shift by selector

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/routes/$.tsx
- packages/react-sdk/package.json
- packages/react-sdk/src/components/components-utils.ts
- packages/react-sdk/src/components/index.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
- packages/react-sdk/src/tree/webstudio-component.tsx
- packages/sdk-size-test/app/page-components/page-main.ts
- packages/sdk-size-test/app/routes/$.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/1129
Here refactored registered components away from global state in react-sdk package in favour of components map.
The map can be easily computed in runtime or generated for worker. Default and custom (remix) components registering is unified now and both libraries can be split into separate packages.
Temporary added "@webstudio/react-sdk/components" entry point to get a record of components.
> Accept components map in renderers

- apps/builder/app/shared/asset-client.ts
- packages/asset-uploader/src/utils/get-unique-filename.ts
- packages/eslint-config-custom/index.js
- packages/generate-arg-types/src/cli.ts
Enable unicorn eslint rule to enforce `node:fs` like specifiers for node modules.
Previously `node:` prefix helped to find server code bundled in browser.
> Enforce node protocol

- apps/builder/app/builder/features/props-panel/props-panel.stories.tsx
- apps/builder/app/builder/features/style-panel/controls/font-weight/is-supported-font-weight.test.ts
- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/db/load.ts
- packages/asset-uploader/src/delete.ts
- packages/asset-uploader/src/patch.ts
- packages/asset-uploader/src/schema.ts
- packages/asset-uploader/src/upload.ts
- packages/asset-uploader/src/utils/format-asset.ts
- packages/asset-uploader/src/utils/get-asset-data.ts
- packages/prisma-client/prisma/migrations/20230514234913_drop_unused_asset_fields/migration.sql
- packages/prisma-client/prisma/migrations/20230530155049_drop_unused_asset_fields/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/prisma-client/src/types.ts
- packages/react-sdk/src/props.test.ts
Cleanup after refactoring. Now we can get rid of Asset.location because asset location is defined by environment. And remove fields moved to File table.
Should be merged after release.
> Drop unused asset table fields

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/label.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/nano-states/instances.ts
- packages/react-sdk/src/components/index.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1545
All complex use cases already switched to get meta from arguments and from atom.
Here migrated the last cases and dropped legacy meta register in react-sdk package. Now we ready to split components into separate packages.
> Use meta stored in atom in builder and canvas

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/get-meta-maps.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/components/get-meta-maps.ts
- packages/react-sdk/src/app/custom-components/form.ws.tsx
- packages/react-sdk/src/app/custom-components/index.ts
- packages/react-sdk/src/components/blockquote.ws.tsx
- packages/react-sdk/src/components/box.ws.ts
- packages/react-sdk/src/components/button.ws.tsx
- packages/react-sdk/src/components/checkbox.ws.tsx
- packages/react-sdk/src/components/code-text.ws.tsx
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/components/form.ws.tsx
- packages/react-sdk/src/components/heading.ws.tsx
- packages/react-sdk/src/components/html-embed.ws.ts
- packages/react-sdk/src/components/image.ws.tsx
- packages/react-sdk/src/components/input.ws.tsx
- packages/react-sdk/src/components/label.ws.tsx
- packages/react-sdk/src/components/link-block.ws.tsx
- packages/react-sdk/src/components/link.ws.tsx
- packages/react-sdk/src/components/list-item.ws.tsx
- packages/react-sdk/src/components/list.ws.tsx
- packages/react-sdk/src/components/paragraph.ws.tsx
- packages/react-sdk/src/components/radio-button.ws.tsx
- packages/react-sdk/src/components/separator.ws.tsx
- packages/react-sdk/src/components/slot.ws.ts
- packages/react-sdk/src/components/text-block.ws.tsx
- packages/react-sdk/src/components/textarea.ws.tsx
We want to be able to specify the order in which components are shown in the panel.
Right now the order property is not set where needed, because I am waiting for feedback from @taylornowotny 
1. Open add components panel
2. See components are in the right order
- give some thought to both components that need to be first which we set specific order to (the rest will go as is)
- recheck the categories, I feel like our split into categories is not intentional
> Sort components by order property in WsComponentMeta

- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/routes/rest.build.$buildId.tsx
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/db/canvas.server.ts
- packages/domain/src/db/domain.ts
- packages/domain/src/index.server.ts
- packages/domain/src/trpc/domain.ts
- packages/project-build/src/db/build.ts
- packages/trpc-interface/src/authorize/project.server.ts
- packages/trpc-interface/src/context/context.server.ts
At publish we would allow to check domains we want to publish. As of now we publish all project domains.
But already pass them from UI, so future move would be just UI changes, without touching API
2. expect xyz
> Add domains to publish

- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- packages/project-build/src/schema/style-sources.ts
Closes https://github.com/webstudio-is/webstudio-builder/issues/1672
We need to show a confirmation dialog when user hits delete to explain what will happen
1. add a token
2. click delete
> Token deletion confirmation

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/1247
We want color controls to not have the suffix button
1. open style panel
2. see color controls have no suffix button
> Make css value suffix optional and preventable

- packages/sdk-components-react-remix/index.d.ts
- packages/sdk-components-react-remix/metas.d.ts
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react-remix/props.d.ts
Here added types in exports and .d.ts for legacy module resolution.
> Fix sdk-components-react-remix types

- packages/asset-uploader/package.json
- packages/authorization-token/package.json
- packages/css-data/package.json
- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/feature-flags/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/generate-arg-types/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/prisma-client/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-remix/index.d.ts
- packages/sdk-components-react-remix/metas.d.ts
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react-remix/props.d.ts
Saas is swithing to moduleResolution=bundler.
Here I replaced types top level field with exoprts condition in all our packages. Thi should fix issues with new sdk components packages and simplify using additional entry points.
> Specify types with exports condition

- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- packages/tsconfig/remix.json
Here added toast with explanation why user cannot add some components. Uses Intl.ListFormat to make it human readable.
> Add toast when cannot add component

- apps/builder/app/builder/features/topbar/add-domain.tsx
- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/package.json
- packages/domain/src/db/domain.ts
- packages/domain/src/trpc/domain.ts
- packages/prisma-client/prisma/migrations/20230606165920_deployment-project-domain/migration.sql
- packages/prisma-client/prisma/migrations/20230606234538_latest-build/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/prisma-client/src/prisma.ts
- packages/prisma-client/src/types.ts
- packages/project-build/src/schema/deployment.ts
- packages/project/src/db/project.ts
- packages/project/src/shared/schema.ts
- packages/trpc-interface/src/shared/deployment.ts
- pnpm-lock.yaml
Add `latestBuild` for each entry in publish dialog
Now we are tracking publish stat for each domain. 
This information is needed to show checkboxes in publish design (next PRs).
2 new Views were created.
To get the latest build by project + domain
To get the latest build for wstd.xx domain
Publish status is shown per domain (as not every domain would be published each time)
During publish all buttons are disabled as per design
Also added tooltip on publish button (not in design)
2. expect xyz
> Publish tracking

- apps/builder/app/shared/nano-states/components-meta.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/sdk-components-react/src/__generated__/image.props.ts
- packages/sdk-components-react/src/__generated__/vimeo-preview-image.props.ts
- packages/sdk-components-react/src/image.tsx
- packages/sdk-components-react/src/image.ws.tsx
- packages/sdk-components-react/src/vimeo-preview-image.ws.ts
- packages/sdk-components-react/src/vimeo.ws.ts
- I used object position instead of object fit by mistake
- Unrelated: ignore loader prop
1. add vimeo
2. select preview image
3. see it has object fit cover
> Fix object fit, ignore loader

- apps/builder/app/builder/features/style-panel/sections/space/value-text.stories.tsx
- apps/builder/app/builder/features/style-panel/style-settings.tsx
- packages/design-system/src/components/__DEPRECATED__/heading.tsx
- packages/design-system/src/components/__DEPRECATED__/paragraph.tsx
- packages/design-system/src/components/__DEPRECATED__/popover.tsx
- packages/design-system/src/components/__DEPRECATED__/text-field.tsx
- packages/design-system/src/components/avatar.tsx
- packages/design-system/src/components/combobox.stories.tsx
- packages/design-system/src/components/dialog.tsx
- packages/design-system/src/components/enhanced-tooltip.tsx
- packages/design-system/src/components/floating-panel-popover.tsx
- packages/design-system/src/components/popover.tsx
- packages/design-system/src/components/primitives/dnd/canvas.stories.tsx
- packages/design-system/src/components/progress-radial.tsx
- packages/design-system/src/components/select.stories.tsx
- packages/design-system/src/components/select.tsx
- packages/design-system/src/components/sidebar-tabs.tsx
- packages/design-system/src/components/slider.tsx
- packages/design-system/src/components/tabs.tsx
- packages/eslint-config-custom/index.js
Default import cannot be optimized by mangling variables so better restrict with linter.
> Avoid default import from react

- apps/builder/app/builder/features/style-panel/sections/effects/effects.tsx
- apps/builder/app/builder/features/style-panel/sections/index.ts
- apps/builder/app/builder/features/style-panel/style-sections.tsx
ref #879
Known issues not fixed here.
Scrub on opacity doesn't work as expected
as depending on opacity dimension it has different min-max and step.
Also any numeric value of opacity is valid css value, and just clamped if it exceeds, so we can't consider values out of 0-1 range as percents too.
So couldn't be fixed fast.
2. expect xyz
> Add effects section with opacity and cursor

- packages/react-sdk/src/css/normalize.ts
Now we show in the builder the right color for visited and link itself
Tooltip is wrong and not fixed in this PR
2. expect xyz
not "what")
5de6)
cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md)
document
and the `builder/env-check.js` if mandatory
2. expect xyz
> Fix link color

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
Fix tooltip to show right color etc values
Before was `black`
2. expect xyz
> Fix tooltip

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- packages/css-data/src/index.ts
- Fixes a bunch of wrong logic for showing style source origin info in the tooltip
- Renders GPT descriptions
1. check tooltips in style panel
> Tooltips improvements

- apps/builder/app/canvas/collapsed.ts
Collapsed logic considered html as webstudio instance element. Here just skipped it.
> Fix position: fixed on body

- apps/builder/app/shared/copy-paste/plugin-instance.ts
Ref https://github.com/webstudio-is/webstudio/discussions/34
Looks like selection of pasted data does not work well so here remove it.
> Prevent selection of pasted data

- apps/builder/app/builder/features/sidebar-left/navigator/css-preview.tsx
Fixes this on each start
```
react_devtools_backend_compact.js:2367 Warning: Prop `className` did not match. Server: "c-dKXKjp c-gcikI language-css" Client: "c-dKXKjp c-gcikI"
at pre
at div
at div
```
Looks like a bug with pre and code element combination in react hydration
2. expect xyz
> Fix hydration error

- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
Show cursor on edit even if text is transparent
example https://webstudio-builder-git-caret-color-webstudio-is.vercel.app/builder/f74e30c0-acfd-4bab-bf35-beaa19f41d0c
Edit any text
3. expect xyz
> Change caret color to be visible

- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
Ref https://discord.com/channels/955905230107738152/955907841070346300/1118910260871168021
Container without children got additional empty text wrapper. Here fixed this by checking children existence.
> Fix insert into container without children

- apps/builder/app/builder/features/style-panel/sections/backgrounds/backgrounds.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-property.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-radius.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-style.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/border-width.tsx
- apps/builder/app/builder/features/style-panel/sections/borders/borders.tsx
- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- packages/css-data/src/__generated__/property-value-descriptions.ts
- packages/css-engine/src/core/index.ts
Ref https://github.com/webstudio-is/webstudio-builder/pull/1785
Here fixed generated height description and added custom descriptions for following controls
- background
- borderWidth
- borderStyle
- borderColor
- borderRadius
- sizing
> Add combined control descriptions

- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
Ref https://discord.com/channels/955905230107738152/955907841070346300/1118983173037105163
Newly created elements cannot obtain focus in effect. We need to focus in the next frame.
> Fix focus after style source duplicating

- apps/builder/app/builder/builder.css
- apps/builder/app/builder/features/blocking-alerts/alert.tsx
- apps/builder/app/builder/features/blocking-alerts/blocking-alerts.tsx
Ref https://discord.com/channels/955905230107738152/955907841070346300/1119664468557828156
Set overflow hidden as simplest way. Need to test on different devices.
> Disable scroll when browser or resolution is not supported

- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
- apps/builder/app/builder/features/style-panel/controls/font-weight/font-weight-control.tsx
- apps/builder/app/builder/features/style-panel/controls/menu/menu-control.tsx
- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
- apps/builder/app/builder/features/style-panel/sections/layout/shared/flex-grid.tsx
- apps/builder/app/builder/features/style-panel/sections/outline/outline-style.tsx
- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
Here removed legacy part which always set unparsed value and needed to parse it before saving in db. Many cases are easily converted to keywords.
Blocker for box-shadow support https://github.com/webstudio-is/webstudio-builder/pull/1634
> Set only parsed values from style panel

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/package.json
- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/properties.ts
- packages/sdk-components-react/src/body.ws.tsx
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/issues/1536
Here replaced browser getComputedStyle for currentColor with computing from data.
`color: inherit` is now considered same as `color: currentColor` and displayed properly in UI.
Changed initial value for color from inherit to black (in mdn-data it's canvastext).
> Compute currentColor

- packages/css-data/bin/mdn-data.ts
- packages/css-data/src/__generated__/properties.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/1794
Here fixed initial value in css data. Mdn provides unclear value because of legacy browsers. Here we need to override it with actual "start".
> Fix text-align control default value

- apps/builder/app/routes/rest.patch.ts
- packages/prisma-client/prisma/migrations/20230619131628_build_data_sources/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/project-build/src/db/build.ts
- packages/project-build/src/index.ts
- packages/project-build/src/schema/data-sources.ts
- packages/project-build/src/types.ts
Here initial setup for data sources which are will be used to maintain runtime stores. It has unique id, name for ui, type and defaultValue to initialize store with it.
For now added only string and boolean types which are necessary for Form component. In the future will be extended with more types.
> Add Build.dataSources

- apps/builder/app/builder/features/style-panel/controls/position/position-control.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-content.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-size.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
closes #1786
Labels inside background section are not resetable and always have default color.
Info icon has gone from `Code` just custom description is now used
cc @taylornowotny 
2. expect xyz
> Add background section tooltips

- apps/builder/app/builder/features/props-panel/controls/combined.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/project-build/src/schema/data-sources.ts
- packages/project-build/src/schema/props.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- added data sources store
- added dataSource type to props
- insert data sources from template (prop.dataSourceReference allows to bind several props to the same data source)
- convert to static prop on copying (simplification until requirements are clear)
> Support data source insert from template

- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
closes #1833
Create Flex box, add 2 boxes
Change order on any box
> Fix flex-child ordering

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts
- apps/builder/app/builder/features/style-panel/shared/css-value-input/parse-intermediate-or-invalid-value.ts.test.ts
closes #1829
paste non hex color from figma, see it works
enter something like `ereemc` see invalid state
> Allow input color without hex, also fx invalid

- packages/design-system/src/components/toolbar.tsx
Added the proper `aria` attributes to two selectors to make sure the intended design renders correctly for the selected item.
https://github.com/webstudio-is/webstudio-builder/assets/16368791/f6914be2-e5b5-49b5-bb5f-5425257b706b
Pinging @taylornowotny for a quick review.
> Fix breakpoints selected item styling

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/canvas/features/webstudio-component/link.ts
- apps/builder/app/shared/nano-states/pages.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/sync/sync-stores.ts
Changed pages synchronisation.
We had following path on link click in canvas:
- We intercept it in handleLinkClick and do publish('switchPage', {});
- We subscribe on 'switchPage' at builder and do navigate(builderPath, { pageId});
- We subscribe on useSearchParams extract from there pageId and do selectedPageIdStore.set(pageId)
- On Canvas we subscribe on selectedPageStore and finally render the page
Now we just change
`selectedPageHashStore`, `selectedPageIdStore` in a single function `switchPage`
`location.searchParams` used only for initial and popstate synchronisation.
pageHashStore added for future use, no logic now.
2. expect xyz
> Sync pages change

- apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx
closes #1846
Drag value scrub to make it eq to 0.
Stop drag.
See unit preserved
> Fix scrub lost unit on negative values

- apps/builder/app/builder/features/style-panel/sections/space/keyboard.ts
- apps/builder/app/builder/features/style-panel/sections/space/layout.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
Fixes following spacing issues:
Focus control play with buttons, enters, esc, shift mouse move
> Fix spacing issues

- packages/react-sdk/package.json
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- pnpm-lock.yaml
Here added two utilities:
validateExpression to parse syntax and replace identifier. For parsing used jsep package which is very limited subset of js.
executeExpression to execute the chain of expressions. The code is unoptimized and will not cache results between calls. But still should be fast enough because expressions are indented to be quite simple.
> Add expression utilities

- apps/builder/app/builder/features/props-panel/props-panel.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
- packages/project-build/src/schema/data-sources.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/tree/root.ts
- packages/sdk-size-test/package.json
- packages/tsconfig/base.json
Here introduced two types of data sources into "variable" and "expression". First stores the value, the second only executable code.
Execute expressions now output results of all expressions so we could access values globally with "computed" store
Embed template references now allow to define both variable reference and expression.
> Support data source expressions

- apps/builder/app/shared/instance-utils.ts
- packages/project-build/src/schema/data-sources.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/sdk-size-test/package.json
Here embed template will add scope to always be shown only within instance. Before we have data sources UI the only use case is deleting data sources along with instances.
Also found jsep enable ternary by default and forbid for now caz there is no generation implemented anyway.
> Scope data sources to instances

- apps/builder/app/builder/features/workspace/workspace.tsx
Chrome on Windows has a bug and makes everything slightly blurry if scale(1) is used together with translateX.
We have done a lot of comparisons between various fixes and they were producing slightly different sharpness,
using scale 0.9999 with opacity 0.9999 works best.
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Edition    Windows 11 Home
Version    22H2
Installed on    ‎10/‎18/‎2022
OS build    22621.1848
Experience    Windows Feature Experience Pack 1000.22642.1000.0
> Scale blurriness fix

- apps/builder/app/builder/features/style-panel/sections/space/scrub.tsx
- apps/builder/app/builder/features/style-panel/sections/space/space.tsx
- apps/builder/app/builder/features/style-panel/sections/space/tooltip.tsx
- apps/builder/app/builder/features/style-panel/shared/modifier-keys.ts
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/tsconfig.json
- packages/css-data/bin/property-value-descriptions.ts
- packages/css-data/src/__generated__/property-value-descriptions.ts
- packages/design-system/src/index.ts
- packages/tsconfig/remix.json
Based on discussion, now space section tooltips are shown only on label hovers
Supports alt/shift clicks
2. expect xyz
> Add modern tooltips to space control

- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/tree/root.ts
Here added another expression utility to generate function body generateExpressionsComputation.
InstanceRoot now requires computeExpressions(variables) prop which can be generated build time.
> Support generating expressions code

- packages/react-sdk/src/css/normalize.ts
- packages/react-sdk/src/css/presets.ts
- packages/sdk-components-react/src/blockquote.ws.tsx
EM seems to be challenging to use and people tend to use PX or REM instead ... I changed those values that come with EM by default from browsers to the values Webflow is using.
I am not sure why webflow is doing certain things: e.g. paragraphs have marginTop 0, h1-3 have marginTop 20; marginBottom: 10, h4- have marginTop 10 ; marginBottom 20
These seem to be inconsistent and weird choices.
> Override browser default tag based styles that use EM units

- packages/design-system/src/components/input-field.tsx
- packages/design-system/src/components/text-area.tsx
Textarea/inputs in the builder don't need spellcheck
1. open props panel
2. type something in any text inputs
> Disable spellcheck

- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- pnpm-lock.yaml
Here added two new utilities for generation and executing individual expressions. Such expressions can use assignment operator to change any variable.
This give us less opinionated solution for "set" action. We can just execute any code our parser supports.
> Support effectful expressions

- packages/design-system/src/components/primitives/numeric-gesture-control.ts
Affects storybook env, in the buider we don't have scorllable body so cursor doesn't cause body to overflow
2. expect xyz
> Fix numeric scrub in case of body is scrollable

- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-sections.tsx
- apps/builder/app/builder/features/style-panel/style-settings.tsx
Use same code to get StyleInformation by instanceId as was used for selectedInstanceId.
Works  right only for the ancestors of selected element
2. expect xyz
> StyleInfo unification

- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
- apps/builder/package.json
- pnpm-lock.yaml
This fixes an issue with text toolbar below top navigation because of wrong middlewares order. Here used the right order and bumped/deduped floating-ui.
> Fix text toolbar overflow

- apps/builder/app/builder/features/props-panel/controls/combined.tsx
- apps/builder/app/builder/features/props-panel/use-props-logic.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- package.json
- packages/generate-arg-types/src/types.ts
- packages/project-build/src/schema/props.ts
- packages/react-sdk/src/context.tsx
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
- packages/sdk-components-react-remix/src/form.tsx
Here added support for callbacks or event handlers on components which basically can do only assignment to variables for now with extended (with assignment operator) syntax of expressions.
> Support effectful expressions in component actions

- packages/design-system/src/components/icon-button.tsx
- packages/design-system/src/components/toggle-group.stories.tsx
- packages/design-system/src/components/toggle-group.tsx
> Fix toggle group focus interfere, show error in storybook

- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
- apps/builder/app/shared/dom-hooks/index.ts
- apps/builder/app/shared/dom-hooks/use-content-editable.ts
Bug discovered in this PR https://github.com/webstudio-is/webstudio-builder/pull/1909
When ending contenteditable, parent doesn't recalc the size of contents, so I have to detouch and reinsert the edited element to force it.
1. start editing style source name and put a LOT of characters
2. exit editing mode
3. before: it would have empty container
4. now: renders and shows ellipsis
> Fix ending contenteditable mode layout recalc

- apps/builder/package.json
- packages/asset-uploader/package.json
- packages/authorization-token/jest.config.js
- packages/authorization-token/package.json
- packages/css-data/package.json
- packages/css-engine/package.json
- packages/dashboard/jest.config.js
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/fonts/package.json
- packages/form-handlers/jest.config.js
- packages/form-handlers/package.json
- packages/http-client/package.json
- packages/image/package.json
- packages/jest-config/index.js
- packages/jest-config/package.json
- packages/project-build/package.json
- packages/react-sdk/package.json
- pnpm-lock.yaml
Here added custom condition to jest config to make it load source code instead of build artifacts.
This means we no longer need to rebuild after changing code in other package
and we may even no need to generate cjs anymore.
> Run jest with sources

- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- packages/sdk-components-react/src/checkbox.ws.tsx
- packages/sdk-components-react/src/input.ws.tsx
- packages/sdk-components-react/src/label.ws.tsx
- packages/sdk-components-react/src/radio-button.ws.tsx
Fixed the issue with pasting checkbox into button
which is wrapped into label
Prevented inserting label, checkbox, radio button and input into buttons.
> Fix invalid ancestors for deeply nested instances

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
- apps/builder/app/builder/features/workspace/workspace.tsx
We are going to get rid of react-use.
Here replaced its useMeasure with resize observer. Sometimes using native api without wrappers gives cleaner logic. Here we avoid using effect as watcher and update store directly from callback.
> Replace useMeasure with resize observer

- apps/builder/app/builder/shared/tree/index.tsx
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.tsx
1. Use keyboard to navigate between the tree elements.
2. Click `Ctrl + E` to enter into edit mode.
3. Edit the name of the tree-node and then press `Enter`.
4. Use the up/down arrows to navigate to other nodes in the tree.
> (fix): Re-focus the tree-node after completion of editing the name

- packages/generate-arg-types/src/arg-types.ts
isValid check has 0 effect on existing components, but prevents Radix components type generation
Instead of empty types it now generate right type for at least single radix component
```ts
export const props: Record<string, PropMeta> = {
defaultOpen: { required: false, control: "boolean", type: "boolean" },
delayDuration: {
description:
"The duration from when the pointer enters the trigger until the tooltip gets opened. This will\noverride the prop with the same name passed to Provider.\n@defaultValue 700",
required: false,
control: "number",
type: "number",
},
disableHoverableContent: {
description:
"When `true`, trying to hover the content will result in the tooltip closing as the pointer leaves the trigger.\n@defaultValue false",
required: false,
control: "boolean",
type: "boolean", …
```
> Fix props filtering

- packages/generate-arg-types/src/cli.ts
Allow multiple exports in components. Most radix components will look like 
`export const Tooltip = TooltipPrimitive.Root;`
The others would be a simpe wrappers over radix with just type changes like like `Omit<TriggerProps, "className">
It's too much to create for each sucj export a standalone file.
After this PR following will work.
```ts
import * as TooltipPrimitive from "@radix-ui/react-tooltip";
export const Tooltip = TooltipPrimitive.Root;
export const TooltipTrigger = TooltipPrimitive.Trigger;
```
Generated exports in case of multiple entries are
```
export propsTooltip: ...
export propsTooltipTrigger ....
```
In case of single export previous behaviour is preserved for now, but should be changed IMO in the future PRs
Known bugs
Until this merged we should not use displayName (have …
> generate-arg-types: Allow multiple exports in component files

- apps/builder/app/dashboard/projects/project-dialogs.tsx
- apps/builder/app/shared/remix/trpc-remix-proxy.ts
- apps/builder/app/shared/share-project/share-project-container.tsx
I moved the fix to trpc layer to affect other calls as well. Turned out the hook is called many times - as many as there are items in dashboard, so I think relying on state dependency even though it works for completely unknown reasons is better from perf standpoint (I think ... who knows ...)
2. expect xyz
> Attempt to fix useFetch for all our trpc calls

- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/copy-paste/plugin-embed-template.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1950
Here added new utility to compute constraints for tree when insert embed template, paste something or reparent. I previous implementation all constraints were merged which gave us false positives like when paste List>ListItem we got "requiredAncestors: [List]". Here tree layout is considered to exclude such false positives.
For testing try to copy paste List>ListItem
> Compute insert constraints for tree

- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/tree-utils.test.ts
- apps/builder/app/shared/tree-utils.ts
- apps/builder/package.json
- apps/builder/remix.config.js
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- pnpm-lock.yaml
Here fixed the case when copy pasted form looses state and give errors on submit.
Immerhin now converted to esm to work in tests.
Added tests for instances copy paste plugin.
The new logic is copy data sources as is if they are bound to copied instances.
The new computeExpressionsDependencies used to detect if expression depends on data sources outside of copied instances scope.
> Support copy pasting of data sources

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/dom-utils.ts
- apps/builder/package.json
- packages/feature-flags/src/flags.ts
- packages/generate-arg-types/src/arg-types.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
- packages/react-sdk/src/tree/webstudio-component.tsx
- packages/sdk-components-react/package.json
- packages/sdk-components-react/src/__generated__/radix-tooltip.props.ts
- packages/sdk-components-react/src/components.ts
- packages/sdk-components-react/src/metas.ts
- packages/sdk-components-react/src/props.ts
- packages/sdk-components-react/src/radix-tooltip.tsx
- packages/sdk-components-react/src/radix-tooltip.ws.tsx
- pnpm-lock.yaml
Left
1. Portals support through passing [selectorIdAttribute](https://github.com/webstudio-is/webstudio-builder/blob/20c3b9fdea4a6f8e7a2cc00211b6e4ca95db13a5/apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx#L290) 
2. [Hidden ScreenReader elements detection](https://github.com/webstudio-is/webstudio-builder/blob/20c3b9fdea4a6f8e7a2cc00211b6e4ca95db13a5/apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx#L129)
3. [New elements on Canvas detection]https://github.com/webstudio-is/webstudio-builder/blob/20c3b9fdea4a6f8e7a2cc00211b6e4ca95db13a5/apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx#L179
To support screen readers
https://github.com/twbs/bootstrap/blob/master/scss/mixins/_screen-reader.scss
Radix here …
> Add tooltip

- apps/builder/app/builder/features/topbar/domains.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/1906
Changed the field size to fit more info for domains
1. open publish dialog
2. add domain, open settings
> Make name and value for domain records equal size

- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
closes https://github.com/webstudio-is/webstudio-builder/issues/1964
1. Just updates spacings
> Update style source sizes, make it more compact

- packages/domain/jest.config.js
- packages/jest-config/esbuild-jest.js
- packages/jest-config/index.js
- packages/jest-config/package.json
- pnpm-lock.yaml
Esbuild is not officially supported by jest
and all available packages do not fit all our need.
esbuild-jest we used for a long time have problems too.
The most important one is frigile heuristik to instrument any code with `ock(` in text. And we have some `pointerLock(` in design-system.
The other problem is instrumentation converts to commonjs and result goes to esbuild which tries to convert back to esm but with only default export. So jest fails anywhere we try to import design-system in tests.
The other problem is lack of maintanance and very old packages inside.
Here refactored original package and removed everything we don't need including mocks instrumentation.
This should fix the build in https://github.com/webstudio-is/webstudio-builder/pull/1986
```diff
Packages:
- 1924
+ 1782 …
```
> Migrate to custom jest transform

- .github/workflows/vis-reg-tests.yml
- turbo.json
Since storybook is able to build from packages sources we no longer need to run build script before storybook.
It can reduce build time for 30-60s
> Speed up visual regressions build

- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
- apps/builder/app/shared/store-utils.test.ts
Fixes https://github.com/webstudio-is/webstudio-builder/issues/1994
Here changed behavior when copy and paste without changing instance selection. Now it works as duplicating and copy is inserted after selection.
Added cmd+d and ctrl+d shortcut to do this with single press without polluting clipboard.
> Support duplicating instances

- apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts
- apps/builder/app/canvas/features/webstudio-component/visually-hidden.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
Avoid any selection on Visually Hidden elements
Fixes https://discord.com/channels/955905230107738152/1133719755371585546
2. expect xyz
> Fix selection on visually hidden elements

- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/sdk-components-react/src/radix-tooltip.ws.tsx
Here added meta.detachable flag which allows when set to true disable copying, dragging and deleting instances of this component without ts parent instance.
This is necessary to constrain components based on external code and prevent deleting hidden components user cannot add again.
> Allow to disable components detaching

- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
Here added action copy paste support.
When all action dependencies are scoped to copied instance new variable nams are ussed.
When some any dependency is not scoped execution is removed from copied prop.
> Support actions copy paste

- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- packages/react-sdk/src/tree/root.ts
Here fixed droping new components on canvas.
Template was used to check constraints but failed
when no template found. Fixed by using fallback.
> Fix drag&drop on canvas

- apps/builder/app/builder/builder.tsx
- apps/builder/app/root.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
Radix provider in canvas couples too tight with radix we should go the other way. Here wrapped each
tooltip sdk component with provider and wrapped
with provider in builder instead of root.
> Remove global tooltip provider

- apps/builder/app/auth/login.tsx
Added missing tooltip provider on login page.
> Fix tooltips on login page

- apps/builder/app/canvas/canvas.tsx
- packages/react-sdk/src/component-renderer.tsx
- packages/react-sdk/src/context.tsx
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/instance-utils.test.ts
- packages/react-sdk/src/instance-utils.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/react-sdk/src/tree/root.ts
Ref https://github.com/webstudio-is/webstudio-builder/pull/1516
Here added utility to compute indexes within ancestors. This should let us easily co-locate tabs triggers and contents by their inedexes.
> Compute indexes within required ancestors

- apps/builder/app/shared/nano-states/components.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
Ref https://discord.com/channels/955905230107738152/1135965820602831036/1135965820602831036
This fixes the issue with adding any radix component. It got broken because of unprefixed constraints.
> Add namespace prefix to constraints

- packages/react-sdk/src/css/style-rules.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
Fix presets in case of namespaeces added `"` to selector
Added presets to radix components
2. expect xyz
> Fix presets in radix (namespaces issue)

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
Fixes https://discord.com/channels/955905230107738152/1136931915044237402
2. expect xyz
> Add more label spacing for boolean props

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/label.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/shared/instance-utils.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/sheet.ws.tsx
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
Ref https://discord.com/channels/955905230107738152/1137068758511394929/1137068758511394929
Full component name was used instead of meta or instance labels.
Also removed unnecessary instance labels.
> Fix breadcrumbs labels

- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-selected.ts
- packages/sdk-components-react-radix/src/__generated__/popover.props.ts
- packages/sdk-components-react-radix/src/__generated__/tooltip.props.ts
- packages/sdk-components-react-radix/src/popover.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
https://discord.com/channels/955905230107738152/1137094092417941695
Fixes positioning. But still have tooltip content blink, seems like tooltip doesn't like changing trigger on the fly.
Blinking will not be fixed until we change how editor works
I created a simple reproducible example changing the trigger using setInterval and get same behaviour as we have
2. expect xyz
> Partially fix tooltip trigger editing

- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
fixes Toolbar positioning if canvas has zoomed https://discord.com/channels/955905230107738152/1137141681007886388
2. expect xyz
> Fix toolbar positioning on scale

- packages/css-data/src/html.ts
Ref https://discord.com/channels/955905230107738152/1136979487993638973
Added form control styles from browser presets
Also a bit refactored other styles with simpler utilities.
> Add browser styles for form controls

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/shared/styles.ts
https://discord.com/channels/955905230107738152/1137452246876033114
2. expect xyz
> Fix jumps on editing text inside tooltips, and probably other components

- apps/builder/app/canvas/features/text-editor/toolbar-connector.tsx
Fixes 3
https://discord.com/channels/955905230107738152/1137452246876033114
Toolbar selection is not working inside tooltip content text.
Open tooltip, start editing tooltip content text. Select some text with mouse. Mouse is now visible
> Fix Toolbar dissapears in the tooltip

- packages/asset-uploader/src/clients/fs/upload.ts
- packages/asset-uploader/src/clients/s3/upload.ts
- packages/asset-uploader/src/utils/to-uint8-array.ts
Looks like node now provides nice utilities to convert stream into json, buffer, text etc. Super handy
https://nodejs.org/docs/latest-v18.x/api/webstreams.html#utility-consumers
Cloudflare node compat supports this as well
https://developers.cloudflare.com/workers/runtime-apis/nodejs/streams/
> Use stream consumers while uploading

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/nano-states/components.ts
- packages/react-sdk/src/hook.ts
- packages/react-sdk/src/index.ts
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/hooks.ts
We want to control some builder behavior specific to some components. For example set open state on dialog, collapsible etc when select in navigator.
Here I added hooks to be called from builder and executed in canvas. For now added 2 hooks onNavigatorSelect and onNavigatorDeselect.
> Add component hooks

- packages/sdk-components-react-remix/src/__generated__/link.props.ts
- packages/sdk-components-react-remix/src/__generated__/rich-text-link.props.ts
- packages/sdk-components-react-remix/src/shared/remix-link.tsx
- Add prefetch viewport for as a link prefetch option
- Prevent leaking prefetch property and other remix props to the dom
1. add a link
2. set prefetch to viewport
3. see that it prefetches a linked page (internal page only) as the link scrolls into view
> Add prefetch viewport for as a link prefetch option

- apps/builder/app/builder/features/style-panel/controls/select/select-control.tsx
- apps/builder/app/builder/features/style-panel/sections/index.ts
- apps/builder/app/builder/features/style-panel/sections/list-item.tsx
- apps/builder/app/builder/features/style-panel/style-sections.tsx
- apps/builder/app/builder/features/style-panel/style-settings.tsx
- packages/css-data/bin/mdn-data.ts
- packages/css-data/package.json
- packages/css-data/src/__generated__/keyword-values.ts
- packages/css-data/src/__generated__/properties.ts
- packages/css-data/src/custom-data.ts
- packages/sdk-components-react/src/list.ws.tsx
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/pull/2063 https://github.com/webstudio-is/webstudio-builder/issues/2079 https://github.com/webstudio-is/webstudio-builder/issues/2060
Here added new "List Item" section specifically for List and ListItem components. Now user can cutomize list item markers for whole list or per each item.
Changed behavior of Select Control to put current value into the list of options if not present. This way display shows "List Item" instead of nothing.
> Add list item section to style panel

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/workspace/canvas-iframe.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/resize-handles.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- packages/design-system/package.json
- packages/design-system/src/components/tooltip.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/utilities.ts
- pnpm-lock.yaml
When the mouse leaves Tooltip.Content and moves over an iframe, the Radix Tooltip stays open.
This happens because Radix's internal grace area relies on the pointermove event, which isn't triggered over iframes.
The current workaround is to set pointer-events: none on the canvas when the tooltip is open.
Here are:
2. expect xyz
> Fix if mouse leaves Tooltip.Content and moves over an iframe, the Radix Tooltip stays open

- packages/prisma-client/migrations-cli/commands.ts
- packages/prisma-client/migrations-cli/prisma-migrations.ts
- packages/prisma-client/migrations-cli/umzug.ts
- packages/prisma-client/package.json
- pnpm-lock.yaml
The new execa version added support for zx like api. It's much smaller and does not pollute globals.
> Rewrite migrations with zx like api

- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/resize-handles.tsx
- packages/design-system/src/components/tooltip.tsx
- packages/design-system/src/utilities.ts
Fix bug with drag component etc
implemented disableCanvasPointerEvents as disposable resource. 
That makes it much easier to control order of execution (disable first then enable), be sure that counter is always >=0, 
and easier control about enable/disable events allowing to dispose only if resource was created.
2. expect xyz
> Fix pointer events

- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/shared/nano-states/components.ts
- packages/react-sdk/src/hook.test.ts
- packages/react-sdk/src/hook.ts
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/hooks.ts
- packages/sdk-components-react-radix/src/tabs.tsx
Here added tabs hooks to auto select tab when its content is selected.
Added new utils to hook context getPropValue and indexesWithinAncestors.
Renamed instanceSelection to instancePath.
Had to pass all props in edit mode in webstudio component
https://github.com/webstudio-is/webstudio-builder/assets/5635476/1f1211bc-0ea4-4d21-9205-1439668e08b4
> Automatically open tab content on select in navigator

- packages/sdk-components-react-radix/src/__generated__/dialog.props.ts
- packages/sdk-components-react-radix/src/__generated__/popover.props.ts
- packages/sdk-components-react-radix/src/__generated__/sheet.props.ts
- packages/sdk-components-react-radix/src/__generated__/tooltip.props.ts
- packages/sdk-components-react-radix/src/collapsible.tsx
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.stories.tsx
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/hooks.ts
- packages/sdk-components-react-radix/src/popover.stories.tsx
- packages/sdk-components-react-radix/src/popover.tsx
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/sheet.tsx
- packages/sdk-components-react-radix/src/sheet.ws.tsx
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/tooltip.stories.tsx
- packages/sdk-components-react-radix/src/tooltip.tsx
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
Fix https://github.com/webstudio-is/webstudio-builder/issues/2046
- replaced isOpen with open
- added builder hooks to open content when select in navigator
- remove unselect hook from collapsible
- added stories to preview templates
> Use open prop in radix components

- packages/jest-config/index.js
- packages/react-sdk/src/component-renderer.tsx
- packages/react-sdk/src/generator.test.ts
- packages/react-sdk/src/generator.ts
- packages/react-sdk/src/tree/root.ts
Here moved code generation of utilities from saas into sdk.
Now InstanceRoot accepts utils object with these 3 fields
- indexesWithinAncestors,
- executeComputingExpressions,
- executeEffectfulExpression,
Generation utility can be shared between cli and saas to simplify maintanance.
> Add utilities generator to sdk

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
- apps/builder/app/builder/features/sidebar-left/panels/components/use-draggable.tsx
- apps/builder/app/shared/instance-utils.ts
- packages/react-sdk/src/components/component-meta.ts
- packages/sdk-components-react-radix/src/accordion.ws.ts
- packages/sdk-components-react-radix/src/button.ws.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/input.ws.ts
- packages/sdk-components-react-radix/src/label.ws.ts
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/sheet.ws.tsx
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/textarea.ws.ts
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
Here made meta.label optional to simplify adding new stuff. Most of the time label is just a "humanized" version of component name. With radix there is an additional action to strip namespace. But still would be less repetition if the name is just inferred.
> Infer label from component name

- packages/sdk-components-react-radix/src/button.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/sheet.ws.tsx
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
For Sheet used variant="ghost" size="icon" with svg embed 
2. expect xyz
> Use styled radix button at dialog, sheet, popover and tooltip

- packages/sdk-components-react/src/__generated__/text.props.ts
- packages/sdk-components-react/src/blockquote.ws.tsx
- packages/sdk-components-react/src/text.tsx
Closes https://github.com/webstudio-is/webstudio-builder/issues/2118
Added cite tag to Text component as well as cite prop in initial props to Blockquote component
Now you can create same html structure as https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote
```html
<blockquote cite="https://www.huxley.net/bnw/four.html">
<p>Words can be like X-rays, if you use them properly—they’ll go through anything. You read and you’re pierced.</p>
<footer>—Aldous Huxley, <cite>Brave New World</cite></footer>
</blockquote>
```
> Added cite tag to Text component as well as cite prop in initial props to Blockquote component

- apps/cli/package.json
Prebuild should not be run in ci as all artifacts committed anyway.
> Fix cli build

- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
This adds inline-flex display option as requested here https://github.com/webstudio-is/webstudio/discussions/50
The use case is having a button with icon and text, without turning it into block element with full width.
1. select any element and set display: flex
> Add inline-flex display option

- apps/builder/app/builder/features/style-panel/style-source-section.test.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-badge.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source.tsx
- apps/builder/app/shared/copy-paste/plugin-embed-template.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/package.json
- packages/react-sdk/src/component-renderer.tsx
- packages/react-sdk/src/components/component-meta.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/sdk-components-react-radix/src/button.stories.ts
- packages/sdk-components-react-radix/src/button.tsx
- packages/sdk-components-react-radix/src/button.ws.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/issues/2137
Here added static tokens support to meta. Id of resulting style source become persistent like this "componentName:tokenName". Such token styles are inserted only if style source with same id not exist. This way we prevent breaking styles already changed by user.
Style source input now autocomplete global tokens and suggest to create predefined component tokens.
Also disabled spell check in style source input.
> Add component tokens support

- packages/sdk-components-react-radix/src/accordion.ws.ts
closes https://discord.com/channels/955905230107738152/1142493917862973450
All changes
2. expect xyz
> Fix accrodion trigger not editable

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/shared/nano-states/components.ts
Here subscribed selected instance selector store instead of navigator events. Now selection from canvas trigger hooks as well. Necessary to support navigation menu component.
> Subscribe selected instance for component hooks

- packages/design-system/src/components/scroll-area.stories.tsx
- packages/design-system/src/components/scroll-area.tsx
- packages/design-system/src/components/tree/tree.tsx
This is a workaround because we don't have a resizable panel yet. With deep nested trees we need more space
1. nest radix components with a lot of depth
2. see that you can scroll both vertically and horizontally
3. horizontal bar is invisible, its a separate problem, not sure why
> Allow horizontal scrolling in navigator

- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.tsx
- packages/sdk-components-react-radix/src/accordion.tsx
Ref https://github.com/webstudio-is/webstudio-builder/issues/2151
Here added alt+click or opt+click support to navigator chevron to expand whole tree and simplify user navigation into hidden contents.
Also changed accordion hooks behaviour. Now only selecting accordion content expands its item. Before was possible to expand on item select.
Alt+click will help to reach accordion contents faster.
> Support expand all when alt+click on navigator chevron

- packages/sdk-components-react-radix/src/tabs.tsx
- packages/sdk-components-react-radix/src/tabs.ws.ts
Ref https://github.com/webstudio-is/webstudio-builder/issues/2151
Separate buttons from tab triggers does not make much sense and complicate logic.
Here I merged tab trigger and button into single styleable component.
> Merge tabs trigger and button into single component

- apps/builder/app/builder/features/style-panel/parent-style.ts
- apps/builder/app/builder/features/style-panel/sections/position/position.tsx
- apps/builder/app/builder/features/style-panel/style-settings.tsx
- packages/sdk-components-react-radix/src/button.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/sheet.ws.tsx
If the parent component has `meta.stylable = false`, we need to skip it to get the correct style of the parent.
Create the Box and add the Sheet to it. 
When you go to the sheet/trigger/button, you will notice that it does not have a 'Flex Child' section or a 'zIndex' property. 
To add these, add 'display: flex' to the box you created initially. When you go back to the sheet/trigger/button, you will see that it now has a 'Flex Child' section and a 'zIndex' property.
> Fix parent style calculation for unstylable parent components

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- packages/react-sdk/src/props.test.ts
- packages/react-sdk/src/props.ts
On onmount outdated onSave were used. What cause creation of additional href property on instance.
Use hide whitespaces.
2. expect xyz
> Fix new href property duplicated on unmount

- packages/fonts/src/font-data.ts
- packages/fonts/src/font-weights.ts
Ref https://discord.com/channels/955905230107738152/1144505313358254120
Here turns out there is not standard in naming font subfamilies. To fix I expanded the list of weights wiith spaceless variants. Added "regular" keyword to detect normal font weight.
> Fix font weight detection of uploaded fonts

- apps/builder/app/dashboard/header.tsx
- packages/design-system/src/components/scroll-area.tsx
- packages/design-system/src/components/tree/tree.tsx
ref #2151 
https://discord.com/channels/955905230107738152/1143789794426638377
Also made that scrollbars are not intersected
Add a lot of elements into the tree.
Be sure last element has a long long label.
See it can be selected, 
See both scrolls work
> Fix horizontal scroll and last element selection in the Tree

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/index.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/package.json
- packages/react-sdk/src/props.ts
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio-builder/issues/2151 https://github.com/webstudio-is/webstudio-builder/pull/2112
Here splitted webstudio component wrapper for preview and canvas. This allows us to have more granular control over preview behavior. For example canvas requres all elements to be focusable for instance selection to work. Prevew should be close to published sites and reflect user experience.
> Fix focus navigation in preview

- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
Setting max-w-max we are forcing menu to be left aligned.
2. expect xyz
> Fix navigation menu by aligning it to the left

- packages/sdk-components-react-radix/src/navigation-menu.tsx
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
Menu items without content (just with Link)
2. expect xyz
> No content Nav menu items

- apps/builder/app/canvas/instance-selection.ts
Here improved instance selection by using pointerdown and pointerup. This solves issues with libraries like radix preventing firing mouse events.
Though there is a problem. Pointer events do not support event.detail to inform about double clicks. So here I implemented multiple clicks detection. For this I track time between latest pointerup and next pointerdown events.
> Reimplement instance selection with pointer events

- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/instance-utils.ts
- packages/sdk-components-react-radix/src/__generated__/select.props.ts
- packages/sdk-components-react-radix/src/select.tsx
Before when start dragging we searched for closest rich editor under cursor and did nothing when the instance is not detachable (for example select value or switch indicator).
Here I changed the behavior to also look for closest detachable instance and drag whole thing. This way we do not need toast like in navigator and can canvas dnd just work.
Also fixed placeholder in "Select Value" component. Before was no way to change it.
> Drag on canvas closest detachable

- packages/sdk-components-react-radix/src/dialog.ws.tsx
Close button was missing CSS states
1. select close button in dialog
2. see the states on local token
> Add dialog close button states

- packages/sdk-components-react/src/input.ws.tsx
- packages/sdk-components-react/src/radio-button.ws.tsx
- packages/sdk-components-react/src/textarea.ws.tsx
Closes https://github.com/webstudio-is/webstudio/issues/2029
Once we add a submenu, all advanced states will go there
1.  see that button, input, textarea no longer have these states on style source
disabled", 
enabled", 
read-only",
read-write"
> Hide additional states, they should go into a submenu

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
Closes https://github.com/webstudio-is/webstudio/issues/1991
Updated new page icon to using Plus icon
1. open pages panel
2. see new icon
> Use PlusIcon for new page

- apps/builder/app/builder/shared/assets/types.ts
- apps/builder/app/builder/shared/assets/use-assets.tsx
- packages/asset-uploader/src/patch.ts
- packages/asset-uploader/src/schema.ts
- packages/react-sdk/src/css/css.ts
- packages/react-sdk/src/css/global-rules.ts
We used to set undefined in assets map value to preserve the order between uploading and uploaded states. Now we started sorting uploaded assets by create time and stubbing no longer do anything useful.
> Remove assets stubbing

- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/canvas/features/text-editor/interop.ts
- apps/builder/app/canvas/features/text-editor/text-editor.tsx
- apps/builder/app/routes/rest.patch.ts
- apps/builder/app/shared/tree-utils.ts
- packages/project-build/src/db/breakpoints.ts
- packages/project-build/src/db/build.ts
- packages/project-build/src/db/data-sources.ts
- packages/project-build/src/db/deployment.ts
- packages/project-build/src/db/instances.ts
- packages/project-build/src/db/pages.ts
- packages/project-build/src/db/props.ts
- packages/project-build/src/db/style-source-selections.ts
- packages/project-build/src/db/style-sources.ts
- packages/project-build/src/db/styles.ts
- packages/project-build/src/index.server.ts
- packages/project-build/src/schema/breakpoints.ts
- packages/project-build/src/schema/data-sources.ts
- packages/project-build/src/schema/instances.ts
- packages/project-build/src/schema/props.ts
- packages/project-build/src/schema/style-source-selections.ts
- packages/project-build/src/schema/style-sources.ts
- packages/project-build/src/schema/styles.ts
- packages/react-sdk/src/embed-template.ts
We had db data validation enabled before but it made api requests very slow. We disabled this validation and seems like there is no need to enable again.
Also dropped all zod list types of our data because validation was the only use case.
> Drop unused db validation

- apps/builder/app/shared/shortcuts/shortcuts.ts
Ref: https://github.com/webstudio-is/webstudio/issues/2028
Changed `useHotkeys.enableOnFormTags` to be enabled just when in canvas for undo/redo.
> Ensure no conflicts on undo and redo hotkeys

- apps/builder/app/builder/features/style-panel/style-source-section.test.ts
- apps/builder/app/builder/features/style-panel/style-source-section.tsx
- apps/builder/app/builder/features/style-panel/style-source/style-source-input.tsx
- apps/builder/app/builder/features/style-panel/style-source/use-sortable.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/design-system/src/components/primitives/dnd/use-drag.ts
- packages/react-sdk/src/embed-template.ts
Ref https://github.com/webstudio-is/webstudio/issues/1965
Tweaked logic and dnd to always put local style source in the end and tokens before it.
> Enforce local style source at the end

- apps/builder/app/builder/features/footer/breadcrumbs.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/builder.domains.$method.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/share-project/share-project.tsx
- packages/authorization-token/src/trpc/authorization-tokens-router.ts
- packages/domain/src/db/domain.ts
- packages/feature-flags/src/flags.ts
- packages/prisma-client/prisma/migrations/20230831150459_add-administrators/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/trpc-interface/package.json
- packages/trpc-interface/src/authorize/authorization-token.server.ts
- packages/trpc-interface/src/shared/authorization-router.ts
- packages/trpc-interface/src/shared/trpc.ts
Add admin permissions to shared links
Share links for now disabled for admin role. Will do in the next iteration after releasing above.
Create admin token link.
Open in incognito, see Publish is working.
> Add admin (publish) permissions to tokens

- packages/cli/package.json
This PR will revert the name of the package back to `@webstudio/cli`. And adds the `files` field in package.json. This will fix the publish of files to npm
> Add missing build files for `npm` publish for cli

- apps/builder/app/canvas/interceptor.ts
Ref https://github.com/webstudio-is/webstudio/issues/2233
Capture mode fixes unexpected submit of form when placed inside radix dialog. Though didn't find a trace why this happen. There is `form.method = 'dialog'` which has special behavior inside `<dialog>` but it is not our case.
> Prevent submit inside dialog in builder

- package.json
- packages/asset-uploader/package.json
- packages/authorization-token/package.json
- packages/cli/package.json
- packages/css-data/package.json
- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/error-utils/package.json
- packages/feature-flags/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/generate-arg-types/package.json
- packages/html-data/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react/package.json
- packages/sdk/package.json
- packages/trpc-interface/package.json
- pnpm-lock.yaml
Seems like we no longer need commonjs in most packages. Only prisma cannot be bundled on server because has binary.
Now new package setup is easier and require only esbuild instead of custom solution.
Cli install size
```diff
du -ck node_modules
- 35516
+ 33192
```
> Drop commonjs

- packages/asset-uploader/package.json
- packages/authorization-token/package.json
- packages/css-data/package.json
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/feature-flags/package.json
- packages/generate-arg-types/package.json
- packages/html-data/package.json
- packages/prisma-client/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/trpc-interface/package.json
We need to stop publishig all packages. Many of them not used and maybe never be used in public. Though they bloat packages search, makes publish step longer. Prisma client publishes 700MB package every time.
> Mark unused packages as private

- packages/asset-uploader/package.json
- packages/authorization-token/package.json
- packages/cli/package.json
- packages/css-data/package.json
- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/dashboard/package.json
- packages/design-system/package.json
- packages/domain/package.json
- packages/error-utils/package.json
- packages/feature-flags/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/generate-arg-types/package.json
- packages/html-data/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/project-build/package.json
- packages/project/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react/package.json
- packages/sdk/package.json
- packages/trpc-interface/package.json
Here removed sources and stories from published packages. Sources were used in the past instead off .d.ts. But since we generate them we can reduce packages size significantly.
Cli install size
```diff
du -ck node_modules
- 33192
+ 29176
```
> Stop publishing sources and stories

- packages/cli/src/commands/init-flow.ts
- packages/cli/src/prompts.ts
This PR
- Allows the prompts to be cancelable at any time.
- Prompts the user if the dependencies can be installed, when the project is being connected for the first time.
- Shows the spinner once all the prompts are responded. Which was previously clearing the prompts to be displayed.
> Show spinners after the prompts are responded and close the prompts on `ctrl + c` in the cli

- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/src/__generated__/router.ts
- packages/cli/templates/route-template.tsx
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/shared.ts
Instances checks are excessive and requires instances data to be present in runtime. We can remove it.
> Drop instances checks from form server logic

- packages/cli/src/cli.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init-flow.ts
- Improves the help message that is displayed for `webstudio --help`
- Runs the dev server if the user opts in for the dependencies installation.
> Improve help and run dev-server after init of a project while using cli

- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/sdk/src/index.ts
- packages/sdk/src/scope.test.ts
- packages/sdk/src/scope.ts
Here added `createScope()` utility to maintain collision free and readable identifiers. Integrated it for component imports.
In the future will be used for jsx and data sources generation.
> Add scope utility for code generation

- packages/cli/package.json
- packages/cli/src/commands/init-flow.ts
- pnpm-lock.yaml
Dev server no longer executed in cli
2. expect xyz
> Remove dev server from cli, add info about how to execute it

- package.json
- patches/@radix-ui__react-focus-scope@1.0.3.patch
- pnpm-lock.yaml
Shared link name is not editable because every input change closes popover with the input.
Here is the fix and the explanation.
This is already fixed in rc radix versions and will be in the next stable release
https://github.com/radix-ui/primitives/blob/28bebf2c6992d056244845c898abeff45dec2871/packages/react/focus-scope/src/FocusScope.tsx#L115
Without this PR the issue looks:
Editing input 
cause this button 
to switch onto `pending` state
what cause handleMutations to move focus onto parent popover 
Child popover lost focus and closes.
Click Share, Edit link name, see it works
> Fix shared link name is not editable

- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/error-utils/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react/package.json
- packages/sdk/package.json
Remix do a few things wrong. Here it checks for dependencies to be present using commonjs only utility which fails to resolve. esm only packages.
Here I tricked it to resolve "require" export condition. Though it is dangerous as may give impression our packages has commonjs support.
> Trick remix checks and avoid useless warnings

- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
After renaming the link was pointing to the wrong repo
> Fix bugs link

- apps/builder/app/builder/features/topbar/publish.tsx
- fixtures/webstudio-remix-vercel/README.md
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/package.json
- pnpm-lock.yaml
As per discussion renaming it to be usable consistently with less typing using npx webstudio-cli as well as pnpm webstudio-cli
> Rename CLI to webstudio-cli

- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/sdk-components-react-remix/src/metas.ts
- packages/sdk-components-react-remix/src/props.ts
- packages/sdk/src/instances-utils.test.ts
- packages/sdk/src/instances-utils.ts
Here replaced Object.assign logic with overriding components at build time. This will simplify migration to jsx generator and let bundler load less components.
Changed fixture to include link from remix overrides.
> Simplify generated remix overrides

- fixtures/webstudio-remix-vercel/README.md
- packages/cli/bin.js
- packages/cli/package.json
Fixes local installation of cli 
The issue was that at `pnpm install` 
`./lib/bin.js` wasn't exists.
Solution is to create it and forward all calls to `./lib/bin`
2. expect xyz
> Fix local install of cli binaries

- packages/cli/src/cli.ts
- packages/cli/src/commands/sync.ts
…when using cli
Adds a error message when the project config like, `host` and `token` are missing from the root.
> Throw error message if the project config is missing in the users env when using cli

- packages/cli/bin.js
- packages/cli/package.json
- packages/css-engine/package.json
- packages/css-vars/package.json
- packages/error-utils/package.json
- packages/fonts/package.json
- packages/form-handlers/package.json
- packages/http-client/package.json
- packages/icons/package.json
- packages/image/package.json
- packages/react-sdk/package.json
- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-remix/package.json
- packages/sdk-components-react/package.json
- packages/sdk-size-test/package.json
- packages/sdk/package.json
Here changed build command to bundle all cli packages so we would not need to resolve .js extensions in es modules. This will fix ubuntu, windows and node 20 usages.
> Bundle cli packages

- fixtures/webstudio-remix-vercel/app/constants.ts
- fixtures/webstudio-remix-vercel/app/routes/[blog].[page].[deep-nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[blog].[page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[blog]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/__generated__/index.ts
- packages/cli/src/__generated__/router.ts
- packages/cli/src/__generated__/templates.ts
- packages/cli/src/config.ts
- packages/cli/templates/build.ts
- packages/cli/templates/defaults/app/constants.ts
- packages/cli/templates/route-template.tsx
- packages/cli/tsconfig.json
Now route-templates is normal ts file. And can be typechecked
2. expect xyz
> Make route-templates typeable

- fixtures/webstudio-remix-vercel/.vercelignore
- packages/cli/src/__generated__/templates.ts
- packages/cli/src/commands/init-flow.ts
- packages/cli/templates/defaults/.vercelignore
This avoid uploading builds/caches etc onto vercel
2. expect xyz
> Add vercelignore to templates

- apps/builder/app/builder/shared/assets/asset-upload.tsx
Cloudflare supports only jpeg, png, gif, webp and svg as input. We should forbid any other format.
> Limit images formats to upload

- packages/cli/src/commands/init-flow.ts
Removed a default `folderName` prompt that is not needed. We need to check for folder name only when the config is missing.
> Fix folder name prompt in the cli init flow

- packages/cli/src/prebuild.ts
> Fix image loader warning in cli

- .github/workflows/publish-beta.yml
Publish npm to `xxx` tag every time you add Label `publish:xxx` to your PR
To republish remove label and add again.
If we would need to republish on every commit since published we would need to use `contains(github.event.pull_request.labels.*.name, 'publish:')` check
2. expect xyz
> Add beta publish

- packages/asset-uploader/package.json
- packages/asset-uploader/src/utils/get-asset-data.ts
- pnpm-lock.yaml
Sharp is image processing library. Though we use it only to detect format and size of images. Proocessing is done on build step or on request by vercel or cloudflare.
Here I replaced sharp with smaller and simpler alternative designed specifically for format and size detection. Potentially this library can be used for uploading in worker.
https://github.com/image-size/image-size
```diff
- 680068
+ 659988
Packages
- 1983
+ 1962
```
> Replace sharp with image-size

- packages/react-sdk/package.json
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/index.ts
- pnpm-lock.yaml
Here added jsx component generator. It allows us to have less tree traversing and more clear output for debugging.
For now data sources are managed the old way with stores. In the future we can switch to react `useState`.
In the future will be integrated into stories generator and cli
> Add jsx component generator

- fixtures/webstudio-remix-vercel/app/constants.mjs
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/tsconfig.json
- packages/cli/package.json
- packages/cli/src/commands/init-flow.ts
- packages/cli/src/config.ts
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/constants.mjs
- packages/cli/templates/defaults/tsconfig.json
- packages/cli/templates/route-template.tsx
- packages/cli/tsconfig.json
- pnpm-lock.yaml
Read constants.mjs during prebuild step and use that constants. (need for saas and other templates)
Fixes windows version of cli. Now everything works on windows platform too.
Changes:
using `execa` instead of `exec`
using `import { fileURLToPath } from "node:url";` instead of url.pathname
do not using `join` for import generation
2. expect xyz
> Use eval to parse shared consts during prebuild, add windows support

- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
Here removed all left usages of previous data sources implementation and removed no longer used expression utilities.
> Drop legacy data sources from builder

- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
Here reused new data sources generator to produce
hurman readable page components and leverage builtin React.useState instead of nanostores.
> Use new data sources in jsx component generator

- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/__generated__/index.ts
- packages/cli/src/prebuild.ts
- packages/cli/templates/route-template.tsx
- packages/form-handlers/package.json
- packages/form-handlers/src/index.ts
- packages/form-handlers/src/shared.ts
- packages/react-sdk/src/generator.test.ts
- packages/react-sdk/src/generator.ts
- pnpm-lock.yaml
Here decoupled actions from props data in runtime by generating prepared forms data. It will let us get rid of props after migrating to jsx generator.
> Pregenerate forms properties

- packages/design-system/src/components/__DEPRECATED__/list.tsx
Currently it was showing text cursor in font manager font item
1. open font manager
2. hover font item
3. cursor should be default, not text
> Fix font item cursor

- apps/builder/remix.config.js
Need to use slightly different glob for watching packages. `**` means anything between slashes and `**.js` in the end looks like `**/.js`
> Fix remix watcher

- packages/cli/src/prebuild.ts
Use dynamic import instead of `node --eval`
`pathToFileURL` is used in import to support windows
2. expect xyz
> [Refactor] Replace Node eval Hack with Dynamic Import

- apps/builder/app/shared/instance-utils.ts
This fixes the issue with computing data sources logic. insertTemplateData first calls propsStore.set and then dataSourceStore.set which triggers computing 2 times and first time prop refers to not existing data source.
Here fixed by setting data sources first and then props.
> fix: prevent error when insert components

- apps/builder/app/canvas/collapsed.ts
closes #2239
:has selector was used for optimisation purposes only 
No we leave optimisation only if selector is supported, and use body element if not.
2. expect xyz
> fix: Project not opening on outdated browsers

- packages/sdk-components-react/src/__generated__/html-embed.props.ts
- packages/sdk-components-react/src/html-embed.tsx
- packages/sdk-components-react/src/html-embed.ws.ts
Some scripts cause hydration errors on execution and must be executed only after hydration
https://discord.com/channels/955905230107738152/1136275535572516986
After release this https://apps.webstudio.is/builder/12c30bde-73af-40f0-8fcf-bc3581f06fac?authToken=6c442116-66ce-4a45-8471-db1e9a667069&mode=preview should work well after publish
2. expect xyz
> fix: Allow client-only embeds to avoid hydration errors

- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/route-template.tsx
v2 remix meta has changed behaviour from object to array.
See fixtures
> fix: Metadata lost on published sites

- packages/prisma-client/src/prisma.ts
Add pgbouncer
closes https://github.com/webstudio-is/webstudio-builder/issues/1878
Tested using following k6
```js
import encoding from 'k6/encoding'
import http from 'k6/http'
import { check } from 'k6'
export const options = {
vus: 100,
duration: '20s',
}
export default function () {
const res = http.get("https://webstudio-builder-git-bgbouncer-webstudio-is.vercel.app/builder/cddc1d44-af37-4cb6-a430-d300cf6f932d?authToken=1cdc6026-dd5b-4624-b89b-9bd45e9bcc3d&mode=preview", {
"headers": {
"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
"accept-language": "en-US,en;q=0.9",
"cache-control": "max-age=0",
"sec-ch-prefers-color-scheme": "dark",
"sec-ch-ua": "\"Chromium\";v=\"116\", …
```
> feat: Use pgbouncer for prisma client

- apps/builder/app/canvas/canvas.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- package.json
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/hook.test.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/props.test.ts
- packages/react-sdk/src/props.ts
- packages/sdk-components-react-remix/src/shared/remix-link.tsx
- packages/sdk-components-react/src/link.tsx
Moved links resolve into props normalizing which is called for whole project before rendering converting page prop into string.
Remix links now check only if provided path matches any page. Ideally it should be handled with navigation api to remove all complexity from links components.
This will let us stop rendering props and assets data in generated pages.
Also fixed links with hashes.
> perf: generate page prop for links

- apps/builder/app/canvas/canvas.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/__generated__/index.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/route-template.tsx
- packages/react-sdk/src/context.tsx
- packages/react-sdk/src/generator.test.ts
- packages/react-sdk/src/generator.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/props.ts
- packages/react-sdk/src/tree/create-elements-tree.tsx
- packages/sdk-components-react-remix/src/shared/remix-link.tsx
Here generated a list of pages paths. It is used in link component to switch to remix link internally when the link is app route.
Providing whole pages list can bloat runtime when there are many pages or when there are many seo data so having single page per route should be enough.
The list is always empty in builder because links are managed with global interceptor. Ideally frameworks should uses navigation api and distinct routes from other paths so we would not need to generate anything.
> perf: generate pages paths

- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/props.ts
Moved canvas props logic from react-sdk to builder. Added new context to pass props store, not global because depends on params.
> refactor: move props logic to canvas

- apps/builder/app/builder/builder.tsx
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/pages.ts
These functions are unnecessary boilerplate. Having single useMount in builder root give us better understanding of set logic and allow to easily find other store references.
> refactor: drop store initial value setters

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/preview.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/canvas/canvas-shortcuts.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/app/shared/sync/sync-stores.ts
Nanostore react wrappers in many cases introduce additional renders because of subscription even when only store.set is used. Searching for references become complicated because we have both direct store access and react wrapper.
Here migrated to use direct store access for preview mode store and renamed it to $previewMode according to new convention.
> refactor: drop react wrapper from preview mode store

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
- apps/builder/app/builder/features/topbar/share.tsx
- apps/builder/app/builder/features/topbar/view-mode.tsx
- apps/builder/app/builder/shared/assets/asset-upload.tsx
- apps/builder/app/builder/shared/assets/use-assets.tsx
- apps/builder/app/builder/shared/fonts-manager/item-menu.tsx
- apps/builder/app/builder/shared/image-manager/image-info.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- apps/builder/app/shared/router-utils/path-utils.ts
Similar to https://github.com/webstudio-is/webstudio/pull/2365
Here migrated auth permit and auth token to direct access and renamed them according to new convention.
> refactor: drop react wrappers from auth stores

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/use-subscribe-drag-drop-state.ts
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/canvas/shared/use-drag-drop.ts
- apps/builder/app/shared/nano-states/nano-states.ts
Similar to https://github.com/webstudio-is/webstudio/pull/2365
Here migrated drag and drop store away from react wrapper.
> refactor: drop react wrappers from dnd store

- packages/css-data/package.json
- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-data/src/tailwind-parser/parse.ts
- packages/css-data/src/tailwind-parser/substitute.test.ts
- packages/css-data/src/tailwind-parser/substitute.ts
- pnpm-lock.yaml
- apply tailwind transform, expand and substitute to get compatible css with webstudio
- media and pseudo classes temporarily removed from variable substitution (need specificity calculations for both, we don't support media in templates)
see tests
> feat: Parse tailwind to ordinary css compatible with webstudio

- packages/css-data/package.json
- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-data/src/tailwind-parser/parse.ts
- packages/css-data/tsconfig.json
- pnpm-lock.yaml
transform tailwind classes to webstudio format
Next PRs.
Postprocessing backgrounds and shadows support. As of now backgrounds will be drawn but will not be visible at style panel
see tests
> feat: transform tailwind classes to webstudio format

- packages/css-data/src/parse-css-value.test.ts
- packages/css-data/src/parse-css-value.ts
- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-data/src/tailwind-parser/parse.ts
1. Add support of simple tuple types to the parseCssValue
2. Add background properties conversion
see tests
> feat: Extend tailwind-to-webstudio conversion to support background properties

- packages/css-data/src/tailwind-parser/parse.test.ts
- packages/css-data/src/tailwind-parser/parse.ts
- packages/css-data/src/tailwind-parser/shorthand.test.ts
- packages/css-data/src/tailwind-parser/shorthand.ts
1. I was wrong about borders conversion when wrote shorthand, fixed.
2. Add border-style: solid whenever needed if borderWidth is defined (tailwind has border-style: solid predefined)
3. Add box-shadows transform
tests
> feat: Add Webstudio borders and shadows support to Tailwind conversion

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/preview.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/canvas-shortcuts.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/pubsub/create.ts
- apps/builder/app/shared/pubsub/index.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
- apps/builder/app/shared/sync/sync-stores.ts
Added new commands emitter utility to manage hotkeys across plugins and separate a lot of logic from canvas.
Here migrated only togglePreview as an example.
Later we can build commands panel and hotkeys overrides on top of this utility.
> refactor: add commands emitter

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/navigator/navigator.tsx
- apps/builder/app/builder/features/sidebar-left/panels/navigator/navigator.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/shortcuts/use-publish-shortcuts.ts
- apps/builder/app/builder/shared/sync/sync-server.ts
- apps/builder/app/canvas/canvas-shortcuts.ts
- apps/builder/app/canvas/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
- apps/builder/app/shared/sync/sync-stores.ts
Here fixed two-way synchronization of commands between builder and canvas. Added flag to not share hotkey with other apps.
Added first two commands specific to canvas: editInstanceText and escapeSelection. Builder is able to reuse commands by specifying inn "externalCommands" which basically extends the union of commands.
> refactor: move text editing into commands

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/canvas-shortcuts.ts
- apps/builder/app/shared/breakpoints/index.ts
- apps/builder/app/shared/breakpoints/select-breakpoint-by-order.ts
- apps/builder/app/shared/breakpoints/stores.ts
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
Moved breakpoints menu view state into nanostore.
Added open breakpoints menu and select breakpoint commands.
> refactor: migrate breakpoints to commands

- packages/sdk-components-react/src/blockquote.tsx
- packages/sdk-components-react/src/blockquote.ws.tsx
- packages/sdk-components-react/src/button.tsx
- packages/sdk-components-react/src/button.ws.tsx
- packages/sdk-components-react/src/code-text.tsx
- packages/sdk-components-react/src/code-text.ws.tsx
- packages/sdk-components-react/src/heading.tsx
- packages/sdk-components-react/src/heading.ws.tsx
- packages/sdk-components-react/src/link.tsx
- packages/sdk-components-react/src/link.ws.tsx
- packages/sdk-components-react/src/list-item.tsx
- packages/sdk-components-react/src/list-item.ws.tsx
- packages/sdk-components-react/src/paragraph.tsx
- packages/sdk-components-react/src/paragraph.ws.tsx
- packages/sdk-components-react/src/text.tsx
- packages/sdk-components-react/src/text.ws.tsx
When we put placeholders into data ai may confuse them with actual content. So here put placeholders into component and render when no content present.
Though this bring one side effect in UX. When user start to edit text it gets empty content without cursor. This will be fixed later.
For now just unblock ai changes.
> fix: remove placeholders from data

- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
Here migrated instances shortcuts like delete, duplicate and edit label to commands.
Added two more options disableHotkeyOnContentEditable and disableHotkeyOnFormTags to not break builtin shortcuts.
> refactor: migrate instances to commands

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/breakpoints/use-set-initial-canvas-width.ts
- apps/builder/app/builder/features/workspace/workspace.tsx
Fixes this.
Now on all screens initially rendered canvas width is same.
Reload project, see canvas not jumping.
> fix: Canvas width jump on initial load

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/shared.tsx
- packages/feature-flags/src/flags.ts
Instead of `aspect-ratio`  css property set `width` and `heigh` html attributes for the image and set css property `height` to `fit-content` to preserve ratio.
This removes all known issues we had with images. 
- No layout shift on published site load
- No layout shift on  published site  and 404
- No small image size jumps during canvas resize
Next PR.
Apply full image optimisation even if width property is set (with some adjustments).
Add image, see `width`, `height` html attributes has changed.
See css property `height` has changed to `fit-content`
> feat: Optimize image loading to prevent layout shifts

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- packages/feature-flags/src/flags.ts
- packages/image/src/image-optimize.test.ts
- packages/image/src/image-optimize.ts
Previous PR: #2414
Now, by default, we set the width attribute when adding an image. This change could cause mobile screens to load oversized images—specifically, width * 2. To mitigate this, we're adopting the viewport width descriptor for srcSets. This approach ensures optimized image loading on smaller screens and maintains previous behavior on screens wider than the image's actual size.
Add images of various sizes, see srcSet
> feat: Switch on viewport-based srcSets for width-defined Images

- apps/builder/app/builder/features/workspace/canvas-tools/outline/collaborative-instance-outline.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/index.ts
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
- apps/builder/app/shared/nano-states/canvas.ts
- apps/builder/app/shared/nano-states/instances.ts
https://github.com/webstudio-is/webstudio/assets/52824/06094b9e-ffd1-4888-ae92-c0c8306d7c47
This is the visual part of the collaborative instance outline we will use for AI and when other user is editing an instance
Not implemented in this PR:
CollaborativeInstanceOutline needs  $collaborativeInstanceSelector and $collaborativeInstanceOutlineAndInstance to have been set when AI is applying styles to an instance.
1. To test it right now just add  on <SelectedInstanceOutline  variant="collaboration" />
> feat: Collaborative instance outline

- packages/sdk-components-react-radix/package.json
- packages/sdk-components-react-radix/src/__generated__/dialog.props.ts
- packages/sdk-components-react-radix/src/__generated__/sheet.props.ts
- packages/sdk-components-react-radix/src/dialog.tsx
- packages/sdk-components-react-radix/src/sheet.tsx
Fixes #2206 
Copies what the `sdk-components-react` package does for the Headings so users can control whats being rendered
1. Click the + button
2. Add a Radix Sheet or Radix Dialog component
3. Select the root on the layers
4. On the right side panel Toggle the `Open` to true
5. Select the Sheet/Dialog Title
6. On the right side panel go to `Settings`
7. Should be able to see a Tag input with a predefined value of `h1`
> fix: use proper heading props for dialog and sheet components

- packages/cli/package.json
- packages/prisma-client/migrations-cli/commands.ts
- packages/prisma-client/package.json
- packages/prisma-client/src/prisma.ts
- pnpm-lock.yaml
Replaced old version of inquirer with prompts package we already use in cli.
Also fixed running migrations by letting prisma lazily load .env
> refactor: replace inquirer with prompts for migrations

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- apps/builder/app/builder/features/ai/hooks/media-recorder.ts
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- packages/design-system/src/components/button.tsx
Placeholder during audio:
1. On Recording start  - "Recording voice..."
2. On stop - "Transcribing voice..."
Shift-Enter now used to add newline inside AI Input
Cancel voice recording is now working well even on canvas (pointer up during long press out of recording button)
Additionally fixes from
https://github.com/webstudio-is/webstudio/issues/2418#issuecomment-1754059088
2. expect xyz
> fix: Add right placeholders on audio transcribing, and shift-enter for new line in AI Command Bar

- apps/builder/app/routes/rest.ai.audio.transcriptions.ts
Whisper often returns lots of spaces before or after text, now we are trimming them
> fix: Trim the text we get from transcriptions

- apps/builder/app/builder/features/workspace/canvas-iframe.tsx
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/sync/sync-stores.ts
Found we have race condition because of handshake
which complicates synchronizatio of commands.
Here removed handshake. Instead iframe now rendered client side after first effect and canvas sends "connect" event so builder start sending updates.
In the future this can be simplified even more with computed updates from current state like yjs does.
- try to delete instance after selecting on canvas
- try to press enter to edit text after selecting from navigator
> fix: sync commands after builder and canvas initialized

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
> fix: Overflow issue with  AI Command Bar prompt outline 

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- packages/design-system/src/components/ai-command-bar/command-bar.tsx
Prompt click on AI Command Bar adds text to the input
Also fixed space on audio transcribing
Click on any prompt in prompts history, see it's text in input field
> fix: Add prompt click to AI Command Bar

- packages/ai/src/image.ts
Added title prop with `Credit: author` for attribution.
> feat: add attribution to images generated by ai

- apps/builder/app/builder/shared/commands.test.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/pubsub/index.ts
Quite requested improvement. Instead of selecting parent on delete select next or previous sibling to be able to clean items within collections with minimal amount of actions.
For testing
- delete first item in a list
- delete last item in a list
- delete the only item in a list
> feat: select sibling after delete instance

- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/select-asset.tsx
Looks like "disabled" state triggered "delete" button near "Choose source".
> fix: prevent image delete when close image dialog

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/menu/menu.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/shared/commands-emitter.ts
- apps/builder/app/shared/shortcuts/shortcuts.ts
Ref https://github.com/webstudio-is/webstudio/issues/2354
Here moved last pieces of shared shortcuts into commands. Fixed distinction of cmd+z and cmd+shift+z to workaround react-hotkeys-hook implementation.
> refactor: move undo/redo into commands

- apps/builder/app/builder/features/ai/ai-fetch-result.ts
- apps/builder/app/builder/features/ai/apply-operations.ts
Check `currentInstance.children.length===0` was used as check does element can have children.
Fixed using meta.
2. expect xyz
> fix: AI, Enable adding text to empty container nodes

- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.stories.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/outline/outline.tsx
Issue: outline sizes do not match
Fixed:
2. expect xyz
> fix: Outline variants sizing

- apps/builder/app/builder/features/ai/apply-operations.ts
Like with text insertions, when inserting a generated template we need to check whether the host element is a container.
> fix: Allow inserting templates only inside container components

- packages/sdk-components-react/src/list.ws.tsx
When adding List component to canvas - its currently empty, but we should have some items inside by default
1. Drop List component on canvas
2. See some default items
> feat: Add some default list items when creating a List instance

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
User pointed out that keeping pages tab open after selecting a page is confusing
1. open pages panel
2. click on any other page than current
3. see page is switched and pages tab is closed
> feat: When user selects a page - close the pages tab

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- apps/builder/app/builder/shared/client-settings/config.ts
- apps/builder/app/builder/shared/client-settings/index.ts
- apps/builder/app/builder/shared/client-settings/settings.ts
State of the AI menu now in local storage. Opened by default
2. expect xyz
> feat: Preverve AI menu state, make it initially open

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- apps/builder/app/canvas/instance-selected-react.ts
- apps/builder/app/shared/hook-utils/use-effect-queue.ts
- When inserting prompt from history, now I can hit enter right away or delete or copy.
- Update placeholder text
- Prevent inserting prompts when textarea disabled
1. click history item
2. see inserted text being selected
> feat: Ai placeholder + select prompt text after inserting prompt from history

- apps/builder/app/builder/features/ai/ai-command-bar.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/shared/client-settings/settings.ts
- apps/builder/app/shared/nano-states/nano-states.ts
When the user hides the AI bar and reloads, it should stay hidden. Some people won't be using it and having to hide it every time is going to be annoying.
1. hide AI bar
2. reload
3. see its still hidden
4. show AI bar
5. reload
6. see its visible
> feat: Remember the AI bar open state

- apps/builder/.env.example
Fix typographical error in [.env.example](https://github.com/webstudio-is/webstudio/blob/c1e330d7b920c154ae7ebbd400776aa379504b0e/apps/builder/.env.example#L35)
> fix: typo in .env.example

- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-layers.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadows.tsx
- apps/builder/app/builder/features/style-panel/style-layer-utils.test.ts
- apps/builder/app/builder/features/style-panel/style-layer-utils.ts
I have a separate [branch](https://github.com/webstudio-is/webstudio/tree/add-css-transitions) going for the transitions section. But better to pull out the main changes that are needed, a lot of things go hand-in-hand for shadows and transitions as both are layers based. So, extracting common things out. Please let me know about the naming convention of the file and the location. This felt the best for me, but if needed changes.
Will be doing a series of small ones, by pulling out all the common changes that needed for the both. Next will do with the design components.
> refactor: Extract layer handling functions into individual helpers

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/canvas-tools.tsx
- apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx
- apps/builder/app/builder/features/workspace/workspace.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/canvas/features/text-editor/text-editor.stories.tsx
- apps/builder/app/canvas/features/text-editor/toolbar-connector.tsx
- apps/builder/app/canvas/shared/commands.ts
Ref https://github.com/webstudio-is/webstudio/issues/2354
We are moving away from emitting events and subscriptions. Here migrated lexical toolbar to canvas commands.
Command handlers rely on global active editor to update currently edited instance.
In the future we can explore alternative way to synchronize text editor between builder and canvas with yjs.
> refactor: replace editor events with commands

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/features/settings-panel/controls/color.tsx
- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select-asset.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/settings-section/settings-section.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- packages/design-system/src/components/input-field.tsx
Here dropped soft delete because it does not play well with history. Instead numbers now get invalid state when input is empty and other cases just delete prop.
> refactor: replace soft delete with delete and invalid state

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/settings-panel.tsx
- apps/builder/app/builder/features/style-panel/shared/use-style-data.ts
- apps/builder/app/builder/features/style-panel/style-panel.tsx
- apps/builder/app/canvas/shared/styles.ts
- apps/builder/app/canvas/stores.ts
- apps/builder/app/shared/sync/sync-stores.ts
Here replaced updateStyle and previewStyle pubsub events with synchronized $ephemeralStyles store to reduce pubsub spread across the codebase.
> refactor: render ephemeral styles with synced store

- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
Fixes https://github.com/webstudio-is/webstudio/issues/2505
For some reason text prop used uncotrolled defaultValue which broke history management.
> fix: switch to controlled value in text prop

- apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/canvas/instance-selection.ts
- apps/builder/app/canvas/shared/commands.ts
One less pubsub event replaced with clickCanvas.
Added store for sidebar active panel to manage from commands.
1. close breakpoints menu by clicking on canvas
2. close sidebar panel by clicking on canvas
> refactor: move click canvas event to commands

- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/builder/features/style-panel/sections/backgrounds/background-gradient.tsx
- apps/builder/app/builder/features/style-panel/sections/box-shadows/box-shadow-content.tsx
- packages/design-system/src/components/text-area.stories.tsx
- packages/design-system/src/components/text-area.tsx
This pull request enhances the TextArea component in the following ways:
- Added support for auto-growing, which dynamically resizes the textarea as you input text.
- Introduced the `maxRows` property to limit the maximum number of rows for the textarea, preventing infinite resizing.
- Updated the settings panel to utilize auto-growing textareas.
empty code
filled code
Made background Code field autoGrow until 4 lines
2. expect xyz
> feat: Add unified scroll to textarea, allow autogrow

- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Split instances slicer into separate utility from copy paste plugin. Will be used to duplicate pages. Along with splitting added more tests to better cover behavior.
> refactor: split instances slice into separate utility

- packages/design-system/src/components/text-area.tsx
Found negative margin didn't work again an broke in safari.
> fix: prevent textarea scrollbar in safari

- apps/builder/app/builder/features/settings-panel/code-editor.stories.tsx
- apps/builder/app/builder/features/settings-panel/code-editor.tsx
- apps/builder/package.json
- packages/design-system/src/components/menu.tsx
- packages/design-system/src/index.ts
- pnpm-lock.yaml
Here added code editor with variables completion support for bindings UI. Simple textarea would not work because same names can be used for different variables
to support seamless dnd for user. `$` is used to trigger completion, in the future can be replaced with tab or something like this. Current implementation is mostly a copy paste from lexical playground.
To test try CodeEditor component in storybook
1. Our variables can have the same names for easier copy-pastability
To address specific variable they should be chosen from available list.
2. renaming variable should rename it everywhere to not break bindings.
So variables behave as symbol in text editor and removed completely on backspace.
- conceptual review (architecture, …
> feat: add basic code editor

- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- fixtures/webstudio-custom-template/app/extension.ts
- fixtures/webstudio-custom-template/app/routes/[robots.txt].tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/remix.env.d.ts
- fixtures/webstudio-remix-netlify-edge-functions/app/extension.ts
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/remix.env.d.ts
- fixtures/webstudio-remix-netlify-functions/app/extension.ts
- fixtures/webstudio-remix-netlify-functions/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/remix.env.d.ts
- fixtures/webstudio-remix-vercel/app/extension.ts
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/remix.env.d.ts
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/app/extension.ts
- packages/cli/templates/defaults/app/routes/[robots.txt].tsx
- packages/cli/templates/defaults/app/routes/robots.txt.ts
- packages/cli/templates/defaults/remix.env.d.ts
- packages/cli/templates/route-template.tsx
ref #2544
Corresponding SAAS PR https://github.com/webstudio-is/webstudio-saas/pull/215
- Support of page property - `excludePageFromSearch`
- Introduced functionality to enable the meta robot noindex tag for the entire website.
- Implemented robots.txt support, which appears to be essential for Twitter meta cards functionality.
Needs corresponding PR in SAAS deploy.
2. expect xyz
> feat: Add Twitter card support & exclude pages from search/index

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
Commands always prevent default to not conflict with any default bahavior. Escape is probably the only case which is manageed by radix too. Though it checks event.defaultPrevented so we need an additional flag with exception.
> fix: stop preventing escape for radix components

- apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.stories.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.tsx
I have changed Field Labels and Subtle text, 
As all meta we support are `<meta property={} content={}`
cc @taylornowotny 
2. expect xyz
> feat: Add custom metadata UI Component

- apps/builder/app/builder/features/settings-panel/variables.tsx
- packages/sdk/src/scope.test.ts
- packages/sdk/src/scope.ts
Here added names normalizer to scope utility
to generate valid variable name from anything provided by user without unnecessary restrictions.
This will let us safely use prop name to reference expressions when those move to prop type.
> feat: normalize variable names

- apps/builder/app/builder/features/settings-panel/code-editor.tsx
- apps/builder/app/builder/features/settings-panel/variables.stories.tsx
- apps/builder/app/builder/features/settings-panel/variables.tsx
Here extended variables panel UI with expressions bound to props which may reference and compute from variables.
Expressions editor supports completion with `$` or can be auto generated by selecting variable from list.
> feat: support binding props to variables

- apps/builder/middleware.js
Image were ratelimited as authorized calls
2. expect xyz
> fix: Fix image ratelimiting

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
- packages/sdk-components-react-radix/src/accordion.ws.ts
- packages/sdk-components-react-radix/src/checkbox.ws.ts
- packages/sdk-components-react-radix/src/collapsible.ws.ts
- packages/sdk-components-react-radix/src/dialog.ws.tsx
- packages/sdk-components-react-radix/src/navigation-menu.ws.ts
- packages/sdk-components-react-radix/src/popover.ws.tsx
- packages/sdk-components-react-radix/src/radio-group.ws.ts
- packages/sdk-components-react-radix/src/select.ws.ts
- packages/sdk-components-react-radix/src/sheet.ws.tsx
- packages/sdk-components-react-radix/src/switch.ws.ts
- packages/sdk-components-react-radix/src/tabs.ws.ts
- packages/sdk-components-react-radix/src/tooltip.ws.tsx
- packages/sdk-components-react-remix/src/form.ws.tsx
We decided to treat expressions as props bindings
so it makes sense to move expression data to props as well. This will make expression and action simetrical and simplify data sources management.
As you can see all expressions have same "expression" name now. In another PR will change to prop name.
1. check newly created Form states
2. Check all radix components states
> refactor: move expressions to props in embed template

- apps/builder/app/builder/shared/sync/command-queue.ts
- apps/builder/app/routes/builder.$projectId.tsx
Fixing 
`The project is outdated. Synchronization was incomplete when the project was opened`
at least in case of preview clicks 
Trying to prevent 
https://github.com/webstudio-is/webstudio-builder/blob/a379a98c1f480397d1ddb0b1caffdc07d64b5d24/apps/builder/app/builder/shared/sync/sync-server.ts#L263
The issue is that data reload cause loading outdated version from the build
during ordinary user work
2. expect xyz
> fix: Project outdated when switching on preview and link hashes

- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-custom-template/app/routes/[robots.txt].tsx
- fixtures/webstudio-custom-template/app/routes/[sitemap.xml].tsx
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/[sitemap.xml].tsx
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-netlify-functions/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/[sitemap.xml].tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-vercel/app/routes/[robots.txt].tsx
- fixtures/webstudio-remix-vercel/app/routes/[sitemap.xml].tsx
- packages/cli/templates/defaults/app/__generated__/[sitemap.xml].ts
- packages/cli/templates/defaults/app/routes/[robots.txt].tsx
- packages/cli/templates/defaults/app/routes/[sitemap.xml].tsx
Generates following sitemap.xml for published sites
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://localhost:3000/</loc>
<lastmod>2023-11-03</lastmod>
</url>
<url>
<loc>https://localhost:3000/radix</loc>
<lastmod>2023-11-03</lastmod>
</url>
<url>
<loc>https://localhost:3000/_route_with_symbols_</loc>
<lastmod>2023-11-03</lastmod>
</url>
<url>
<loc>https://localhost:3000/form</loc>
<lastmod>2023-11-03</lastmod>
</url>
<url>
<loc>https://localhost:3000/heading-with-id</loc>
<lastmod>2023-11-03</lastmod>
</url>
</urlset>
```  
2. expect xyz
> feat: Add sitemap generation

- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/instance-utils.ts
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
Here changed accessing expression from data source id to prop id in builder and data source name to prop name in generated code.
This is another step to migrate expressions from data sources to props.
See generated output for clarification.
Note: review with hidden spaces
> refactor: compile prop expressions

- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
- packages/cli/src/prebuild.ts
Omit excluded pages from sitemap generation
2. expect xyz
> fix: Omit excluded pages from sitemap generation

- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
Here improved copy/paste behavior.
Before variables outside of copied tree were inlined. For example ErrorMessage were loosing its expression when duplicated within same form.
Now expressions and variables are preserved
and variables are inlined into expressions when paste target do not have such variable. For example ErrorMessage get `"initial" == "error"`. With upcoming UI it will be more obvious. The main idea here to not loose all expressions but only references to unavailable variables.
> feat: reuse variables on copy/paste within same tree

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/color.tsx
- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/variables.stories.tsx
- apps/builder/app/builder/features/settings-panel/variables.tsx
- packages/feature-flags/src/flags.ts
- packages/react-sdk/src/component-generator.ts
- packages/sdk/src/schema/props.ts
Here integrated variables into props. Now it can be tested considering instances tree.
> feat: add variables to settings panel

- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/variables.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/components.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
- packages/sdk/src/schema/props.ts
On the last discussion about bindings we agreed expression are always bound to single prop and cannot be reused.
Here added new prop.type = 'expression' as a replacement to dataSource.type = 'expression'.
This will let us unify expression/variable reference and avoid deep dependencies. Expressions and actions become similar.
For now both expression prop and legacy expression data source are supported until we migrate completely in db.
> refactor: add expression prop

- .github/workflows/add-status.yml
- apps/builder/app/env/env.public.server.ts
To have ability to test some cloudflare worker issues we are now have *.prs.webstudio.is domains. 
Builder app now can be accessed through such urls.
Here we add prs.webstudio app url at the end of status list
Known issues:
will not work if branch names exceed 24 chars,
Gonna not fix for now.
2. expect xyz
> feat: Report deployment url at *.prs.webstudio.is

- .github/workflows/add-status.yml
`refs/heads/` must be omited
2. expect xyz
> fix: Wrong branch name used on main push

- apps/builder/app/builder/features/seo/site-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/social-preview.tsx
- apps/builder/app/env/env.server.ts
Also add default asset path to remove env variables from setup
2. expect xyz
> fix: Fix image loader paths

- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/features/settings-panel/variables.tsx
- packages/react-sdk/src/prop-meta.ts
We need json control in settings panel to support editing current value of variables for example for collection data.
Here tweaked props logic and fixed a few bugs related to switching prop type based on variable type.
- type something in body id
- add this expression to body id `{ id: 1 }`
- remove expression
- add variable with `{ id: 1 }`
- select variable
- remove expression
> feat: add json prop control

- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/core-components.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- packages/sdk/src/schema/props.ts
Here first part for collection support. Collections are generated as
```tsx
list.map((item, index) => <Fragment key={index}></Fragment>)
```
Added new "parameter" prop type to represent "item" which always refers to variable. "parameter" reflects same semantics as js functions where in function call it is argument `fn(1, 2, 3)` and in function definition it is parameter `function fn(a, b, c) {}`.
Collection children are always wrapped with fragment to let having more than one child and always pass key to avoid react warnings.
> feat: support generating collection

- apps/builder/app/env/env.server.ts
- apps/builder/app/routes/n8n.$.tsx
- apps/builder/app/routes/n8n.tsx
Link to `apps.webstudio.is/n8n/anything` solves 2 things.
1. Login user if it's not logged in
2. Executes schema in n8n passing userId and all query parameters inside.
Example:
```
https://n8n.prs.webstudio.is/n8n/buy/stripe/com?link=test_dR67uJ0bu3fS2Zi4gh
```
Will execute [dev schema](https://webstudio.app.n8n.cloud/workflow/mdNfsFIIwnoMsz6N) hook
`${N8N_WEBHOOK_URL}/buy/stripe/com?link=test_dR67uJ0bu3fS2Zi4gh`
```env
N8N_WEBHOOK_URL="https://webstudio.app.n8n.cloud/webhook-test/"
```
Schema after work will respond or with error or with redirect.
Open [n8n dev schema](https://webstudio.app.n8n.cloud/workflow/mdNfsFIIwnoMsz6N)
Execute in Dev Mode (at bottom)
Open URL [https://n8n.prs.webstudio.is/n8n/buy/stripe/com?link=test_dR67uJ0bu3fS2Zi4gh](https://n8n.prs.webstudio.is/n8n/buy/stripe/ …
> feat: N8N support

- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
Fixes https://discord.com/channels/955905230107738152/1174291886878490656
Actions are cleared on copy paste though here we get runtime error because output expects function to be defined.
Here always generate at least empty function.
> fix: generate empty function for cleared actions

- packages/prisma-client/prisma/migrations/20231115205820_client-references/migration.sql
- packages/prisma-client/prisma/schema.prisma
Table "ClientRefernces" allows to hold 3rd party client references per user and service.
Like client_reference_id in stripe
Following constraints
```
@@unique([userId, service])
@@unique([reference, service])
```
As  `@@unique([userId, reference, service)` is not enough
Would need to change existing postgres node in n8n schema https://webstudio.app.n8n.cloud/workflow/mdNfsFIIwnoMsz6N
onto
```
INSERT INTO "ClientReferences"("userId", "service") 
VALUES ($1, 'stripe') 
ON CONFLICT ("userId", "service") DO UPDATE SET "userId"=$1 
RETURNING *;
```
> feat: Add client references table

- apps/builder/app/builder/features/workspace/workspace.tsx
We have experimented quite a bit before and now apparently on windows the canvas is still blurry and removing all the hacks apparently solves it. All of this is according to @itsNintu because he is the only one with windows on the team, I don't see a good way to test it, because the blur is very subtle and you won't clearly see it remote browsers.
1. open builder, resize canvas within workspace (100% scale)
2. resize canvas bigger than workspace, so that scale is lower than 100%
3. see that at no point in time canvas is blurry
> fix: Blurry canvas on windows

- apps/builder/app/routes/n8n.$.tsx
- packages/prisma-client/prisma/migrations/20231116174151_transaction/migration.sql
- packages/prisma-client/prisma/migrations/20231117094001_transaction/migration.sql
- packages/prisma-client/prisma/migrations/20231117095612_transaction/migration.sql
- packages/prisma-client/prisma/schema.prisma
- Prisma way of creating migrations comparing local db with schema model is super error prone
- Adding 'preview' | 'production' or 'local' to n8n webhooks otherway no way to host hooks together
2. expect xyz
> fix: Transaction log, add preview/production/local to hooks

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/canvas/canvas.tsx
- apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/canvas/stores.ts
- apps/builder/app/shared/array-utils.test.ts
- apps/builder/app/shared/array-utils.ts
- apps/builder/app/shared/nano-states/index.ts
- apps/builder/app/shared/nano-states/instances.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/pages.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- packages/react-sdk/src/props.ts
Here refactored props values computing to reuse in both canvas and settings panel and support future collections which need to provide different values for same variables.
Grouped whole logic and covered with tests.
- check image src is working
- check link switch page in preview
> refactor: compute props contextually

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/topbar/share.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/dashboard/dashboard.tsx
- apps/builder/app/dashboard/header.tsx
- apps/builder/app/dashboard/projects/project-card.tsx
- apps/builder/app/dashboard/projects/project-dialogs.tsx
- apps/builder/app/dashboard/projects/projects.tsx
- apps/builder/app/routes/builder.$projectId.tsx
- apps/builder/app/routes/dashboard._index.tsx
- apps/builder/app/shared/context.server.ts
- apps/builder/app/shared/db/user-plan-features.server.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/share-project/share-project-container.tsx
- apps/builder/app/shared/share-project/share-project.stories.tsx
- apps/builder/app/shared/share-project/share-project.tsx
- apps/builder/docker-compose.yaml
- packages/domain/src/trpc/domain.ts
- packages/feature-flags/src/flags.ts
- packages/prisma-client/prisma/migrations/20231119153806_transaction-customer-subscription/migration.sql
- packages/prisma-client/prisma/schema.prisma
- packages/trpc-interface/src/context/context.server.ts
Add additional fields to transaction log, so we can create billing portal for users to unsubscribe/change etc of subscriptions
Plus:
2. expect xyz
> feat: Add fields to transaction log,  add userPlanSettings

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/builder/shared/tree/index.tsx
- packages/design-system/src/components/tree/horizontal-shift.test.ts
- packages/design-system/src/components/tree/horizontal-shift.ts
- packages/design-system/src/components/tree/tree-node.tsx
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
Selectors in tree are necessary to easily access data of ancestors while manipulaating navigator tree.
Required to support collections.
> refactor: use selectors in all tree callbacks

- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
- apps/builder/app/builder/features/style-panel/style-source/style-source-badge.tsx
- apps/builder/app/canvas/collapsed.ts
- apps/builder/app/canvas/instance-selected.ts
- apps/builder/app/shared/nano-states/breakpoints.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
Succeeds https://github.com/webstudio-is/webstudio/pull/2136 in more simple way. Active states are preresolved for everything except local styles. And local styles shown as overwritten when defined state is active.
Fixes https://discord.com/channels/955905230107738152/1177028091227418654
1. create form component
2. choose error state
3. set background red
4. go to error state in style source menu
5. should be "remote" label
6. set background green
7. go to stateless style source
8. reset background color
9. should be "overwritten" label
> fix: show active style states as remote

- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init-flow.ts
- packages/cli/src/config.ts
- packages/cli/src/prebuild.ts
fixes #2538 and #2615
Don't use `vercel` as default template while exporting from cli
> fix: Display error messages when a template is not passed for building a project

- apps/builder/app/routes/n8n.$.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Ref #2661
This allows us to extract posthog (and probably other trackers) cookies distinct_id for the user on the server side
And then using aliasing to use in n8n schemas https://posthog.com/docs/product-analytics/identify#alias-assigning-multiple-distinct-ids-to-the-same-user
See corresponding n8n schemas in saas repo
2. expect xyz
> feat: Pass cookies and requestUrl to n8n

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/breakpoints.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- packages/react-sdk/src/core-components.ts
Part of https://github.com/webstudio-is/webstudio/issues/2516
Here added new copy implementation. There are 2 differences
- it does not change existing instances and not change their children, we will need this to copy pages
- it handles cross-project copy of portals (slots) properly, now each portal content is inserted separately if the root does not exist and skips otherwise
- much better covered with tests
1. try duplicating form and change form state prop
2. try duplicating form error message and change form state prop
> refactor: reimplement duplicating instances

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-content.tsx
- apps/builder/app/builder/features/style-panel/sections/transitions/transition-timing.tsx
fixes #2624 
@taylornowotny i couldn't reproduce the issue with shortcuts in local or either deployed version. But still added acheck to stop events while typing. So, let me know if it's working on your side.
https://github.com/webstudio-is/webstudio/assets/11075561/67d09016-d9be-4bb2-9ff3-552fbc49c461
https://github.com/webstudio-is/webstudio/assets/11075561/9ab3669a-50d3-4c41-92fd-c544d91b55a8
> fix: Handling custom value select from select box in transitions

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.stories.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Fix https://github.com/webstudio-is/webstudio/issues/2516
Here added "duplicate" button to page settings and implemented logic based on recent instances slice utilities.
1. open pages
2. click on page
3. click "copy" button
> feat: support duplicating pages

- apps/builder/app/builder/features/settings-panel/code-editor.tsx
- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/features/settings-panel/controls/color.tsx
- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/shared.tsx
Here added logic to disable props controlled by complex expressions like `formState === 'success'` where we cannot change variable value.
Added icon with tooltip near label to clarify why it is disabled.
1. create form
2. select success message
3. check "show" prop
4. create collection
5. go to html embed and change "code" expression to `collectionItem + " pie"`
6. check code prop
> feat: disable props bound to complex expressions

- packages/cli/src/prebuild.ts
Fixes https://discord.com/channels/955905230107738152/1133337749856989316/1181798549982302329
This fixes linux issue when tmp and cwd are on different mounts or drives.
> fix: create temporary files within assets directory

- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/variables.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/instance-utils.ts
- apps/builder/app/shared/nano-states/props.test.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/core-components.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/sdk/src/schema/data-sources.ts
Here added dataSource.type = 'parameter' without initial value because value is always provided by context. It let us fix a few issues with variables without complicating logic.
- prevent deleting parameter variable (collection item) in variables panel
- allow changing only name of parameter variable
- show only name in the list of variables
- fix removing expression from collection data
- hide item parameter from collection variable list
- prevent editing parameter value from props
- make collection unstylable
2. expect xyz
> refactor: support parameter data source for collection item

- .github/workflows/add-status.yml
github protection rules are based on job names
2. expect xyz
> fix: Fix that status error prevented PR merge

- apps/builder/app/builder/features/blocking-alerts/blocking-alerts.tsx
seems like `// return` was commented for local testing
2. expect xyz
> fix: Broken chrome detection

- apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/url-pattern.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/url-pattern.ts
- packages/sdk/src/schema/pages.ts
Here added description tooltip and additional validation to constrain UrlPattern syntax to fit most framework abilities.
> feat: validate page path

- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/app/__generated__/_index.server.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/__generated__/index.server.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/route-template.tsx
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/remix.test.ts
- packages/react-sdk/src/remix.ts
- packages/react-sdk/src/resources-generator.test.ts
- packages/react-sdk/src/resources-generator.ts
Here added generation of server modules with resource loaders. These loaders are invoked in remix loader and result is passed to page component.
Check fixtures and tests.
> feat: generate resource loaders

- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/variables.stories.tsx
- apps/builder/app/builder/features/settings-panel/variables.tsx
- apps/builder/app/builder/shared/expression-editor.stories.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Here introduce the new expression editor as a replacement to code editor. It is implemented with codemirror and will improve DX of our bindings and cms usage.
- autocomplete now completes nested objects in variables
- javascript syntax is highlighted in expressions
- json values are formatted as multiline text
- autocomplete shows fields value/type
Additionally improved a couple of things
- json objects are wrapped with parentheses `({ param: "value" })` to be treated as object instead of block in highlighter
- objects and arrays are rendered as "object" and "array" in variables list for cleaner UI
Integrated in builder only for variable value and json prop value. Will require additional logic to integrate as expression editor.
1. …
> feat: reimplement expression editor with codemirror

- fixtures/webstudio-custom-template/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.server.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.server.tsx
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/resources-generator.test.ts
- packages/react-sdk/src/resources-generator.ts
- packages/sdk/src/index.ts
- packages/sdk/src/resource-loader.ts
- packages/sdk/src/schema/resources.ts
Refactored resources generator to use universal http resource which cover most cases.
- loadResource is imported from sdk
- accepts url (expression), method, headers (value is expression) and body (expression)
- all variables and page params parameter are available for loader expressions
> refactor: make resources universal

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variables.tsx
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/sync/sync-stores.ts
Here added Value/Resource tabs to "new/edit variable" panel to support creating both value and http request based variables.
Url, headers and body are expressions with support to all available in scope value and page params variables.
Actual loading of resources in builder will be added later.
> feat: add resource variables support in builder

- apps/builder/app/builder/builder.tsx
- apps/builder/app/routes/rest.resources-loader.ts
- apps/builder/app/shared/copy-paste/plugin-instance.test.ts
- apps/builder/app/shared/nano-states/nano-states.ts
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/router-utils/path-utils.ts
- apps/builder/app/shared/sync/sync-stores.ts
Here improved resource management to load defined resources and store in variable values to allow preview data. Builder requests data from proxy route every time resources or their variables are changed.
Data to test is here https://gist.githubusercontent.com/TrySound/56507c301ec85669db5f1541406a9259/raw/a49548730ab592c86b9e7781f5b29beec4765494/collection.json
> feat: load resources in builder

- apps/builder/app/dashboard/projects/project-card.tsx
Reason is we always see spinner, but with delay it feels less responsive
1. click project thumbnail
2. see spinner showing right away
> fix: remove delay when showing spinner for openning projects

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variables.stories.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
Here added new binding popover as a replacement for variables popover. Integrated into resource fields and made button look like suggested by Mark and Taylor.
> feat: add binding popover

- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/expression-editor.stories.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/builder/shared/html-editor.stories.tsx
- apps/builder/app/builder/shared/html-editor.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/2359 https://github.com/webstudio-is/webstudio/issues/2388
Here added codemirror based html editor for html embed component. It supports basic autocomplete and highlights embedded css and js.
Splitted basic codemirror setup into CodeEditor component everything else can be customized around it.
> feat: add html editor

- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
Realized that user can put in a quote that will break the rendering
We also need an actual validation in the UI for class name, because its not just an arbitrary string.
> fix: Escape user-provided class

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/features/settings-panel/controls/combined.tsx
- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select-asset.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
Here changed how bindings are validated
- closing with broken expression will show errors and prevent close
- the next close will not block and keep the old valid expression
- close with valid expression invoked saving
- props no longer can change the type of input
- binding button becomes red and gets tooltip when value has invalid type
- binding popover also shows non-blocking error about type
- each control provides own validation
> feat: improve binding validation

- apps/builder/app/builder/features/breakpoints/width-input.tsx
User was able to delete the value and get a NaN error Ref https://github.com/webstudio-is/webstudio/issues/2734
1. delete the value
2. see the min width rendered
> fix: Ensure user can't enter invalid canvas width value in breakpoints editor

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/app/shared/form-utils/form-utils.ts
- apps/builder/app/shared/form-utils/index.ts
Here changed variable popover UI
- removed save/cancel buttons - save is happening on close
- replaced value/resource tabs with type select
- support additional string, number and boolean values
- add validation to value and resource forms
Also added form utilities to manage and compose field validation.
> feat: improve variable popover

- fixtures/webstudio-custom-template/README.md
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/__generated__/index.css
- fixtures/webstudio-custom-template/package.json
- fixtures/webstudio-remix-netlify-edge-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-edge-functions/README.md
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/package.json
- fixtures/webstudio-remix-netlify-functions/.webstudio/data.json
- fixtures/webstudio-remix-netlify-functions/README.md
- fixtures/webstudio-remix-netlify-functions/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/package.json
- fixtures/webstudio-remix-vercel/.webstudio/data.json
- fixtures/webstudio-remix-vercel/README.md
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[sitemap.xml].ts
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- fixtures/webstudio-remix-vercel/package.json
- packages/cli/src/prebuild.ts
Logic was changed only in `prebuild.ts`. All other changes or README or autogenerated
Integrate atomic CSS support into CLI
The Vercel fixtures project now explicitly sets atomicStyles to true.
Netlify explicitly sets atomicStyles to false.
The custom template doesn't have a default setting, so atomicCss=true is used."
See fixtures.
> feat: Support atomic CSS on build

- packages/sdk-components-react/src/__generated__/vimeo.props.ts
- packages/sdk-components-react/src/vimeo.tsx
- packages/sdk-components-react/src/vimeo.ws.ts
When video is off-screen and needs to be autoplayed, you can now put it to loading=lazy and it won't load until its in viewport.
https://github.com/webstudio-is/webstudio/assets/52824/3fa59ab8-1e19-44b4-969b-3eb99f12fccf
2. expect xyz
> feat: Add loading lazy/eager to vimeo

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- packages/design-system/src/components/text-area.tsx
This prevents users from pointless resetting non-expression bindings.
Also fixed text controls style when binding is bound.
> feat: disable reset button for non-expression binding

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- fixed deleting when delete in variables section
- fixed deleting when delete instance
> feat: delete resources along with variables

- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
Slots will eventually become components. And components cannot have direct access to page variables. Here added constraint to hide all variables outside of slot component.
> feat: hide variables outside of slots

- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
This fixes the issue with "show" is false by default.
> fix: fallback to default value in computed props

- apps/builder/app/builder/features/style-panel/sections/layout/layout.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- packages/design-system/src/components/enhanced-tooltip.tsx
fixes #2733 
Tooltips on FlexGap properties don't have details of `columnGap` or `rowGap`.  Now, on hover on these two properties will show the properties details and  able to reset the values from the tooltip
1. Hover on the flex-gap properties.
2. The property will show the details of the property and allows to reset.
> fix: Add source and reset details in tooltips for flex gap

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- packages/feature-flags/src/flags.ts
We are launching bindings without page params
which will be part of cms launch.
> fix: hide page params with cms flag

- packages/domain/src/db/domain.ts
Just message text
1. add more than 5 domains on a free account
> fix: Better error message when user reaches max domains limit

- packages/prisma-client/prisma/migrations/20240112155724_nullable-user/migration.sql
- packages/prisma-client/prisma/migrations/20240112155725_user_product_view/migration.sql
- packages/prisma-client/prisma/schema.prisma
> feat: Appsumo support

- packages/design-system/src/components/link.stories.tsx
- packages/design-system/src/components/link.tsx
Failed to check after last changes that the default link used most of the time and it should have underline=always by default, only rare cases have underline  hover or none
1. export dialog
2. blocking alert
> fix: Default link always underline

- apps/builder/app/builder/features/sidebar-left/panels/pages/folder-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- packages/sdk/src/schema/pages.ts
Ref  https://github.com/webstudio-is/webstudio/issues/404
- Folders select in pages
- Path rendered in page contains all slugs from all parent folders
1. open page settings
2. select a folder
3. see page was moved to a folder
4. see url preview contains the right folder slugs
> feat: Folders select in pages

- apps/builder/app/builder/features/settings-panel/controls/boolean.tsx
- apps/builder/app/builder/features/settings-panel/controls/check.tsx
- apps/builder/app/builder/features/settings-panel/controls/code.tsx
- apps/builder/app/builder/features/settings-panel/controls/file.tsx
- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/controls/number.tsx
- apps/builder/app/builder/features/settings-panel/controls/radio.tsx
- apps/builder/app/builder/features/settings-panel/controls/select.tsx
- apps/builder/app/builder/features/settings-panel/controls/text-content.tsx
- apps/builder/app/builder/features/settings-panel/controls/text.tsx
- apps/builder/app/builder/features/settings-panel/controls/url.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/props-section/use-props-logic.ts
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- added blue "bound" binding button
- added pink "overwritten" binding button
- added tooltip to reset overwriten binding
> feat: support bound and overwritten binding button variants

- apps/builder/app/builder/features/settings-panel/shared.tsx
Unmount got stale saved value because effect is run without dependencies.
> fix: save latest value when close settings panel

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/canvas/interceptor.ts
- apps/builder/app/shared/db/canvas.server.ts
- apps/builder/app/shared/nano-states/pages.ts
- apps/builder/app/shared/nano-states/props.ts
- apps/builder/app/shared/pages/use-switch-page.ts
- packages/cli/src/prebuild.ts
- packages/project-build/src/shared/pages-utils.test.ts
- packages/project-build/src/shared/pages-utils.ts
- packages/react-sdk/src/props.test.ts
- packages/react-sdk/src/props.ts
- packages/sdk/src/page-utils.ts
- packages/sdk/src/page-utilts.test.ts
Ref https://github.com/webstudio-is/webstudio/issues/404
- can select a nested path for link pages
- can click in preview to get to the page
2. expect xyz
> feat: Allow selecting a nested path for link href

- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.test.ts
- apps/builder/app/shared/copy-paste/plugin-markdown.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
- packages/react-sdk/src/embed-template.test.ts
- packages/react-sdk/src/embed-template.ts
- packages/sdk/src/index.ts
- packages/sdk/src/schema/instances.ts
- packages/sdk/src/schema/webstudio.ts
Here added two new types
WebstudioFragment - reusable fragment of webstudio data which can be generated (markdown, embed template), transferred (copied or stored in marketplace) and inserted.
WebstudioData - all available normalized data to allow composing multiple operations within single transaction like delete instance and then insert into other part of the page.
> refactor: generalize transferrable fragments

- apps/builder/app/builder/features/ai/apply-operations.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/commands.test.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/navigator-tree.tsx
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Here refactored delete instance to accept and mutate webstudio data instead of accessing data stores.
Now we can avoid double transaction when delete pages.
Note: review with hidden whitespaces
2. expect xyz
> refactor: make delete instance composable

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Here refactored insertInstancesSliceCopy to accept webstudio data instead of creating transaction.
This let us avoid hacky callbacks in duplicate instance and duplicate page functionalities.
Note: review with hidden whitespaces
> refactor: make inserting fragments copy composable

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
Fixes https://discord.com/channels/955905230107738152/1198946829778305044/1198946829778305044
Should be behind cms flag
> fix: hide page path tooltip

- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
Just a different icon instead of standard page icon when its a home page
1. open pages
2. see home with home icon, the rest of pages regular icon
> feat: Use home icon on the home page

- apps/builder/app/builder/features/style-panel/parent-style.ts
Here fixed detecting flex child on collection children where collection parent is flexbox.
> fix: compute styles for collection children correctly

- apps/builder/app/builder/features/settings-panel/variables-section.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
> chore: Improve wording for empty state in variables and binding panels

- packages/sdk/src/resource-loader.ts
Here fixed the case with broken published site when invalid url is passed to fetch. The error is passed to user as statusText with 500 status code.
As a result correct everything will continue to render just with empty data.
> fix: handle invalid request errors in resource loader

- apps/builder/app/builder/shared/binding-popover.tsx
- better expresion tooltip wording
- better layout for empty state
2. expect xyz
> chore: Better expression editor tooltip wording

- apps/builder/app/builder/features/style-panel/sections/flex-child/flex-child.tsx
- apps/builder/app/builder/features/style-panel/shared/property-name.tsx
- apps/builder/app/builder/features/style-panel/shared/style-info.test.ts
- apps/builder/app/builder/features/style-panel/shared/style-info.ts
fixes #2799 
The issue is related to picking only one property from the list of `properties` that being sent to `PropertyName` component. The `Sizing` section is sending `flexGrow`, `flexShrink' and `flexBasis`. But the property tooltip is taking only `flexGrow` to show the label.
And in this case, `flexGrow` and `flexShrink` are missing. So, the label doesn't show up. Added a custom logic to show the label by following the order instead. Let me know, your opinions. 
Bug location
https://github.com/webstudio-is/webstudio/blob/main/apps/builder/app/builder/features/style-panel/shared/property-name.tsx#L375
```jsx
}: PropertyNameInternalProps) => {
// When we have multiple properties, they must be originating from the same source, so we can just use one.
const property = properties[0];
``` …
> fix: Use custom logic for showing style source label for property names. 

- apps/builder/app/canvas/canvas.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Here added error boundary to catch user errors and be able to recover from them when broken data is updated.
No longer requires reload.
> fix: recover from canvas errors

- apps/builder/app/builder/features/seo/project-settings.tsx
When clicking on favicon upload label, it shouldn't trigger the upload button click
2. expect xyz
> fix: Label shouldn't be used for section titles

- apps/builder/app/builder/builder.css
Closes https://github.com/webstudio-is/webstudio/issues/1848
Under closer look all fonts were a bit bolder than in figma and this seems to be fixing it
2. expect xyz
> fix: Font smoothing antialised makes all fonts look like in figma

- apps/builder/app/builder/features/inspector/inspector.tsx
- apps/builder/app/builder/features/settings-panel/props-section/props-section.tsx
- apps/builder/app/builder/features/settings-panel/shared.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- packages/design-system/src/components/panel-tabs.tsx
Ref https://github.com/webstudio-is/webstudio/issues/1947
It's getting it closer, but not quite all the things, so not closing the issue yet
Before:
After:
2. expect xyz
> fix: Settings panel spacing

- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/remix.test.ts
- packages/react-sdk/src/remix.ts
- packages/sdk-cli/src/generate-stories.ts
- packages/sdk-components-react-radix/src/__generated__/accordion.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/checkbox.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/collapsible.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/dialog.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/label.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/navigation-menu.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/popover.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/radio-group.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/select.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/sheet.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/switch.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tabs.stories.tsx
- packages/sdk-components-react-radix/src/__generated__/tooltip.stories.tsx
Ref https://github.com/webstudio-is/webstudio/issues/2791
Here renamed generatePageComponent to generateWebstudioComponent and refactored to use it later for slots.
"Page Params" variable is now passed as parameter. Similar way we will support parameters in design components.
> refactor: generalize generating components

- apps/builder/app/builder/features/style-panel/sections/size/size.tsx
- apps/builder/app/builder/features/style-panel/shared/collapsible-section.tsx
closes https://github.com/webstudio-is/webstudio/issues/1847
Just spacing for sizes section
2. expect xyz
> fix: Align spacing for size section with figma

- packages/prisma-client/package.json
- packages/prisma-client/prisma/schema.prisma
- packages/prisma-client/src/prisma.ts
- packages/prisma-client/src/types.ts
- pnpm-lock.yaml
- Removed PGBOUNCER var from vercel
- Renamed DATABASE_URL => DIRECT_URL
- Added DATABASE_URL using this https://www.prisma.io/docs/orm/overview/databases/supabase
SAME MUST BE DONE ON SAAS TOO ON RELEASE!!!!!!!!!!!!!!
2. expect xyz
> build: Connection pool to suport new supabase

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- packages/sdk/src/resource-loader.ts
Fixes https://discord.com/channels/955905230107738152/1199803387005390858/1199803387005390858
Here fixed the issue with leading spaces in resource urls fail when fetch in workers. Trimmed urls and added validation for urls.
> fix: trim url for cloudflare worker

- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
Here missed the case we have to compile our expressions before executing them with optional flag to prevent failing when properties are accessed from undefined.
> fix: compile expressions when compute properties

- apps/builder/app/builder/features/topbar/domains.tsx
- apps/builder/app/builder/features/topbar/publish.tsx
Ref https://github.com/webstudio-is/webstudio/issues/2826
An active domain link icon button causes peopple to click on it when domain/publish is not done and they end up seeing the worker error
1. when domain is not fully connected or at least one publish is not done
2. expect external link button to be deactivated
> feat: Disable domain link button when published site is not ready

- apps/builder/app/builder/features/breakpoints/breakpoints-popover-toolbar-button.tsx
- apps/builder/app/builder/features/breakpoints/breakpoints-popover.tsx
- apps/builder/app/builder/features/topbar/menu/menu-button.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
- packages/design-system/package.json
- packages/design-system/src/components/toolbar.tsx
- pnpm-lock.yaml
Ref https://github.com/webstudio-is/webstudio/issues/2826
Previously active page in the topbar was only text, now its a button that can toggle pages panel
1. click on page name in topbar
2. expect it to toggle pages panel
> feat: Topbar pages button

- packages/prisma-client/prisma/migrations/20240127230238_project-preview/migration.sql
Fixes migration in https://github.com/webstudio-is/webstudio/pull/2836
It turned out updating a view reuires the order of the added fields to be the same, otherwise it may cause weird effects .
2. expect xyz
> chore: Drop view if exists always

- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-custom-template/custom-template/__templates__/route-template.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/__templates__/route-template.tsx
- packages/react-sdk/src/index.ts
- packages/react-sdk/src/page-meta-generator.test.ts
- packages/react-sdk/src/page-meta-generator.ts
Here refactored page meta with simpler type than full page data and moved it into factory which is invoked lazily in loader.
This will let us support variables and resources in page settings later.
> refactor: generate page meta in loader

- apps/builder/app/shared/share-project/share-project.tsx
- packages/design-system/src/components/button.tsx
Publish permission was hidden for non-pro accounts but this makes it  hard to discover.
1. open share dialog
2. see publish permission is disabled for non-pro
3. enabled for pro
4. has a tooltip that explains it
5. has link button that leads to the pricing page
> feat: Make publish permission visible for everyone but enabled for pro

- .github/workflows/cli-test.yml
Macos tests are very flacky and often fail after 20min timeout. In most cases linux tests are enough.
> build: drop macos cli test

- packages/prisma-client/prisma/migrations/20240131200102_page_meta_expressions/migration.ts
Accidentally duplicated description conversion to expression which made all descriptions qouted.
> fix: prevent quoting page description

- apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.stories.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/settings-panel.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/floating-panel.tsx
Here added support for bindings in page meta for following fields
- title
- description
- social image url
- exclude from search
- custom meta content
> feat: support bindings in page meta

- apps/builder/app/builder/features/style-panel/controls/font-family/font-family-control.tsx
- packages/css-engine/src/core/rules.ts
- packages/css-engine/src/core/style-sheet-regular.test.ts
- packages/css-engine/src/core/to-value.test.ts
- packages/css-engine/src/core/to-value.ts
- packages/react-sdk/src/css/global-rules.ts
Now any font that contains a space should render
1. select any font that has a space in the name
2. check it actually renders on canvas
> fix: Font familes with a space were not rendering correctly

- apps/builder/app/builder/features/style-panel/sections/typography/typography.tsx
Show active state of the menu button for advanced typography options
1. typography section > advanced settings menu > click
2. panel opens, button has active state
> fix: Show active state of the menu button for advanced typography options

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/commands-emitter.ts
Both ctrl/cmd + number are used to in browsers to switch between tabs. Webflow is just using a number shortcut without modifier, lets do the same
1. hit numbers to switch breakpoints
2. can still type numbers in inputs
> feat: Use a number as a shortcut for breakpoints without modifiers

- apps/builder/app/builder/shared/expression-editor.stories.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- apps/builder/package.json
- pnpm-lock.yaml
Fixes https://github.com/webstudio-is/webstudio/issues/2790 https://discord.com/channels/955905230107738152/1203115803910873218
Here fixed the issue with completing array indexes or object keys unsupported with dot syntax.
> feat: autocomplete computed member expression

- fixtures/webstudio-remix-vercel/app/__generated__/index.css
- packages/react-sdk/src/css/normalize-type-check.ts
- packages/react-sdk/src/css/normalize.ts
- packages/react-sdk/src/css/presets.ts
- packages/sdk-components-react/src/checkbox.ws.ts
- packages/sdk-components-react/src/radio-button.ws.ts
We don't support inset/outset in the style panel which is the initial for inputs/buttons
New defaults are:
- input, textarea, button - solid
- radio, checkbox - none (already was none, no change,but we didn't reflect that in sp)
1. add those components to canvas
2. see that  input, textarea, button - have solid border style in style panel
3. see that radio, checkbox - show none
> fix: Normalize border style

- apps/builder/app/builder/features/style-panel/sections/transitions/transition-property.tsx
https://discord.com/channels/955905230107738152/1203772575298232412
Fixes, wrong selection of property when a list is being filtered for transition proeprties.
- Add a transition property.
- Then select the `property` and enter some characters for filtering.
- Now, select a value from the newly filtered list.
- [] tested locally and on preview environment (preview dev login: 5de6)
> fix: selecting transition property when filtering

- apps/builder/app/canvas/interceptor.ts
Fixes https://discord.com/channels/955905230107738152/1203979363738193960
> fix: prevent form validation in canvas mode

- packages/eslint-config-custom/index.js
In cases where we need permanent logs, we need to be able to log and commit and there is no point of having that rule. That rule protects against accidentally forgetting console.log
1. write console.warn or console.error and pass the linter
> chore: Allow logging console.info and console.error

- apps/builder/.env.example
- package.json
Connecting to database now needs `DIRECT_URL` too, referene
https://github.com/webstudio-is/webstudio/blob/main/packages/prisma-client/prisma/schema.prisma#L13-L17
```sh
datasource db {
provider  = "postgres"
url       = env("DATABASE_URL")
directUrl = env("DIRECT_URL")
}
```
> chore: Add DIRECT_URL to the .env.example file

- fixtures/webstudio-custom-template/.webstudio/data.json
- fixtures/webstudio-custom-template/app/__generated__/[sitemap.xml].ts
- packages/trpc-interface/src/authorize/project.server.ts
We just removed that check for the wrong reasons, readding it back before we ca find a better solution and avoid having a shortlist check in the permissions check
2. expect xyz
> fix: Return the check for templates permission

- apps/builder/app/dashboard/shared/spinner/spinner.tsx
In the previous attempt to fix React warnings I accidentally deactivated the loading indicator completely, now this fix works.
1. click on any project
2. see loading indicator right away
> fix: Loading indicator was deactivated

- apps/builder/app/builder/features/sidebar-left/panels/pages/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/shared/nano-states/props.test.ts
- apps/builder/app/shared/nano-states/props.ts
- generate path params fields on the fly, even for new page
- fill entered values when path params variable is created
- fixed showing $ws$dataSource$id instead of variable name when no values path params entered
- renamed variable to "Path Params"
> refactor: improve path params

- apps/builder/app/shared/clone-project.tsx
- apps/builder/app/shared/router-utils/path-utils.ts
Clone had no authToken provided via shared url
1. create a shared url with view permission
2. open it from a different account
3. clone from menu should work
> fix: Fix clone from builder when shared link is used

- apps/builder/app/builder/builder.tsx
- apps/builder/app/builder/features/sidebar-left/sidebar-left.tsx
- apps/builder/app/builder/features/topbar/topbar.tsx
Topbar pages button works when in build mode, but in preview it doesn't, this changes it. So one can switch pages when in preview mode
1. switch to preview mode
2. toggle pages button in top bar
> fix: Allow opening pages from topbar when in preview mode

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.ts
Here improved page duplicate logic to support replacing old variables in page meta and path params variable with new references.
Also improved path duplicating to preserve path params by prefixing with `/copy-n` subpath.
- test it on preview (check page params is updated in both title and body id)
> experimental: update variables when duplicate page

- apps/builder/app/builder/features/style-panel/shared/color-picker.tsx
https://github.com/webstudio-is/webstudio/issues/2890
Previous attempt to prevent selection resulted in not updating the value in the picker
When dragging color handle it should be updating the hex value and when dragging outside of the picker it should  not select the entire text
> fix: fix color picker updating value and not selecting text when outside

- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/page-meta-generator.test.ts
- packages/react-sdk/src/page-meta-generator.ts
Here added support for variables in page meta in generated websites. Prevented creating unused variables. We can reuse the same way for other generated parts later.
> experimental: generate variables for page meta website

- apps/builder/app/builder/features/sidebar-left/panels/pages/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/__templates__/route-template.tsx
- packages/react-sdk/src/page-meta-generator.test.ts
- packages/react-sdk/src/page-meta-generator.ts
- packages/sdk/src/schema/pages.ts
Here added new field to page settings ui and page meta schema to redirect page when specified. Having bindings support redirect can be specified conditionally based on cms cata.
Tested locally, works with both urls and paths.
> experimental: add redirect field to page settings

- packages/sdk-components-react/src/image.tsx
When on canvas inside builder we need to always eager load images to avoid this bug in latest chrome with cache turned off
1. turn off cache
2. add image component on canvas
3. see it renders as expected (loading lazy in settings is default, but on canvas it renders as loading eager)
> fix: Image on canvas in latest chrome may not render when loading is lazy

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/templates/defaults/__templates__/route-template.tsx
- packages/react-sdk/src/page-meta-generator.test.ts
- packages/react-sdk/src/page-meta-generator.ts
- packages/sdk/src/schema/pages.ts
Here added support for changing page status in page settings. This works for both redirect and content rendering.
User can render error message based on received cms data and give 404 status code.
> experimental: allow changing page status

- apps/builder/app/canvas/collapsed.ts
> fix: Popover content position change to absolute throw error on canvas

- fixtures/webstudio-custom-template/app/__generated__/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/__generated__/_index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/__generated__/_index.tsx
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
Here improved component generator logic to not generate unused variables. This way later we will be able to avoid requesting unused resources as well.
> refactor: avoid generating unused variables in page components

- apps/builder/app/builder/features/settings-panel/variable-popover.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/nano-states/index.ts
- apps/builder/app/dashboard/dashboard.stories.tsx
- apps/builder/app/shared/db/user-plan-features.server.ts
- packages/trpc-interface/src/context/context.server.ts
Added additional validation for hobby users to forbid dynamic path parameters and disable copy address button.
> experimental: put dynamic path behind feature flag

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- packages/cli/src/prebuild.ts
- packages/react-sdk/src/page-meta-generator.test.ts
- packages/react-sdk/src/page-meta-generator.ts
- packages/react-sdk/src/resources-generator.test.ts
- packages/react-sdk/src/resources-generator.ts
- packages/sdk/src/schema/pages.ts
> refactor: rename page.pathVariableId to pathParamsDataSourceId

- apps/builder/app/builder/features/topbar/topbar.tsx
With the introduction of a button in the top bar we  forgot to truncate when page name is too long
1. create a page with a very long name
2. see it's name being truncated in the top bar
> fix: Fix truncation of a long page name in the top bar button

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
> experimental: add pro banner to page settings

- apps/builder/app/builder/features/sidebar-left/panels/pages/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/url-pattern.test.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/url-pattern.ts
- apps/builder/remix.config.js
- packages/design-system/package.json
- packages/design-system/src/components/input-field.tsx
- packages/design-system/src/components/tooltip.tsx
- pnpm-lock.yaml
Now it looks more like address bar and provides validation for required or non-splat params with slashes. To make it work implemented tokenizer and improved pattern compiler.
> experimental: improve address bar UI

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Here renamed everywhere in the code instances slice to webstudio fragment to keep naming consistent across whole app.
> refactor: rename instances slice to webstudio fragment

- apps/builder/app/builder/features/project-settings/project-settings.tsx
- apps/builder/app/builder/features/project-settings/redirect-section.tsx
We have 2 separators between redirects section in project settings, when Redirects are enabled
> fix: Fix unnecessary separator

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
Here fixing an issue with showing scope of selected page instead of currently opened in editor.
- select page
- add variable to body
- start editing another page settings without selecting
- make sure that variable is not visible on editing page
> fix: use editing page scope instead of selected page

- apps/builder/app/builder/features/address-bar.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/pages.tsx
- apps/builder/app/builder/shared/url-pattern.test.ts
- apps/builder/app/builder/shared/url-pattern.ts
Here added new isPathnamePattern utility to check the path is dynamic. We can use to change the icon in pages list.
> experimental: use dynamic page icon in pages navigator

- apps/builder/app/builder/features/sidebar-left/panels/pages/page-utils.ts
- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/shared/copy-paste/plugin-instance.ts
- apps/builder/app/shared/instance-utils.test.ts
- apps/builder/app/shared/instance-utils.ts
Here refactored to extract fragment or copy from any data not only global stores.
> refactor: allow to extract webstudio fragment from any data

- apps/builder/app/builder/features/ai/ai-fetch-result.ts
- packages/react-sdk/src/component-generator.test.ts
- packages/react-sdk/src/component-generator.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/resources-generator.test.ts
- packages/react-sdk/src/resources-generator.ts
Here improved the resources generator to not produce variables unused in resource fields.
Also enforced unused variables to be always provided to avoid issues with not generated variables.
> fix: prevent generating unused variables in resoures

- apps/builder/app/builder/features/project-settings/redirect-section.tsx
- packages/cli/src/prebuild.ts
- packages/sdk/src/schema/pages.ts
Allow users to configure `301` or `302` status code for redirects.
- Go to project settings
- Add a redirect
- Select a status code from the dropdown at the time of adding a redirect.
- When the project is deployed, and redirects should reflect the status code that is added in project settings.
> feat: allow users to set custom redirect status code

- apps/builder/app/builder/features/sidebar-left/panels/components/components.tsx
Accidentally broke list filtering of the collection component in the components panel
2. expect xyz
> fix: fix collection component filter

- fixtures/webstudio-custom-template/app/routes/[hello]._index.ts
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/__templates__/route-template.tsx
Here switched from remix redirect method to native Response.redirect available in all platforms.
> refactor: use native Response.redirect method

- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/html-editor.tsx
When collection Data renders a large json, its hard to read or edit without a bigger editor. With this full-screen is available on all Code Editors
1. See expanding works in all properties
- Collection: Data
- HTML Embed: Code
- Edit variable type JSON
> feat: Make fullscreen option available to all code editors

- apps/builder/app/builder/shared/expression-editor.tsx
- packages/react-sdk/src/expression.ts
Here fixing the issue with saving expressions with variables not available in the scope which leads to user confusion and compilation errors.
> fix: replace unknown variables on paste

- apps/builder/app/builder/shared/commands.ts
- apps/builder/app/builder/shared/tree/index.tsx
- apps/builder/app/shared/nano-states/instances.ts
Found a bug with renaming because edited instance
is stored as id instead of selector.
1. create collection
2. try to rename its content
> fix: support renaming of instances inside collection

- fixtures/webstudio-custom-template/app/routes/[hello]._index.ts
- fixtures/webstudio-custom-template/app/routes/[script-test]._index.tsx
- fixtures/webstudio-custom-template/app/routes/[world]._index.tsx
- fixtures/webstudio-custom-template/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-edge-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-netlify-functions/app/routes/_index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[_route_with_symbols_]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[form]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[heading-with-id]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[nested].[nested-page]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[radix]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/[resources]._index.tsx
- fixtures/webstudio-remix-vercel/app/routes/_index.tsx
- packages/cli/src/prebuild.ts
- packages/cli/templates/defaults/__templates__/route-template.tsx
This reverts commit fa376d4204bc182ef51be9eb0de31cc344bf6686.
Seems like native redirect does not suppot relative paths which are essential for redirect ui.
> refactor: revert remix redirect method

- apps/builder/app/builder/features/settings-panel/controls/json.tsx
- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/custom-metadata.tsx
- apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx
- apps/builder/app/builder/shared/binding-popover.tsx
- apps/builder/app/builder/shared/code-editor.tsx
- apps/builder/app/builder/shared/expression-editor.tsx
- packages/react-sdk/src/expression.test.ts
- packages/react-sdk/src/expression.ts
- packages/react-sdk/src/index.ts
Here improved detecting literal values in expressions without executing with potentially global variables.
Also fixed expression errors
> refactor: check literals with parser

- apps/builder/app/builder/shared/assets/use-assets.tsx
When uploading 15+ images at once it will be rate limited as they upload in parallel and that looks like DDOS to the rate limiter
1. select many files
2. upload and see no error
> fix: upload images serially to avoid being rate limited

- apps/builder/app/builder/features/settings-panel/resource-panel.tsx
- apps/builder/app/routes/rest.resources-loader.ts
- apps/builder/app/shared/nano-states/props.ts
- packages/sdk/src/resource-loader.ts
- packages/sdk/src/schema/resources.ts
Here optionally added support for json in resource body. This is necessary when use graphql apis or just json based rest api.
Expression editor for entering json value is shown whenever method post and content-type: application/json are specified.
> feat: support json in resource body
